### PR TITLE
Turn warning 31 (Module_linked_twice) into a hard error

### LINKED ISSUE #10564: Link time consistency check is incomplete
The link time consistency check (that errors when linking object files that were compiled against different versions of the same interface) fails to detect inconsistencies between an object's interface and objects that were linked before it.

To reproduce:
```ocaml
(* foo.mli *)
type t = T

val foo : bool

(* foo.ml *)
type t = T

let foo = Bar.bar2

(* bar.mli *)
val bar : Foo.t

val bar2 : bool

(* bar.ml *)
let bar = Foo.T
let bar2 = true

(* baz.mli *)
val baz : int

(* baz.ml *)
let baz =
  match Bar.bar with
  | T -> 0
```
```shell
$ ocamlc -c foo.mli bar.mli baz.mli bar.ml foo.ml baz.ml
```

Now edit `foo.ml`, `foo.mli` and `baz.ml` to replace them with:
```ocaml
(* foo.mli *)
type t = T of int

val foo : bool

(* foo.ml *)
type t = T of int

let foo = Bar.bar2

(* baz.ml *)
let baz =
  match Bar.bar with
  | T i -> i
```
```shell
$ ocamlc -c foo.mli bar.mli baz.mli foo.ml baz.ml # Note the omission of bar.ml
$ ocamlc -o test bar.cmo foo.cmo baz.cmo
$ ./test
Segmentation fault
```

The same bug exists with `ocamlopt`.

This can be fixed by replacing the use of `Consistbl.set` by `Consistbl.check` in `Bytelink.check_consistency` (and similar in `Asmlink`) but I'm not sure why the distinction was there.

I found this while looking at alternatives for #10563.

### PR DESCRIPTION
**Pull request by hhugo**
Fix https://github.com/ocaml/ocaml/issues/5461
Fix https://github.com/ocaml/ocaml/issues/10564

### CODE REVIEW

**Comment by hhugo** [comment]
cc @gasche

File: asmcomp/asmlink.ml [hunk 1]
```diff
@@ -90,7 +87,7 @@ let check_consistency file_name unit crc =
   with Not_found -> ()
```
Comment (v-gb) [inline asmcomp/asmlink.ml]: Based on my test script, I think we should move the `raise (Error(Multiple_definition ...))` above at the top of the function, so the errors are improved.

File: bytecomp/bytelink.ml [hunk 2]
```diff
@@ -780,6 +775,13 @@ let report_error ppf = function
       in
       fprintf ppf "@[<hov 2>Wrong link order: %a@]"
         (pp_print_list ~pp_sep:(fun ppf () -> fprintf ppf ",@ ") depends_on) l
+  | Module_linked_twice (modname, file1, file2) ->
+      fprintf ppf "Files %a and %a both define a module named %s"
+        Location.print_filename file1
+        Location.print_filename file2
+        modname
+
+
```
Comment (v-gb) [inline bytecomp/bytelink.ml]: I think we should use the same code as in asmlink.ml (more format boxes than here), and in fact let's use the same constructor name as well (`Multiple_definition`), for easier comparison between bytelink.ml and asmlink.ml.

File: bytecomp/bytelink.ml [hunk 3]
```diff
@@ -194,10 +192,7 @@ let check_consistency file_name cu =
   end;
   begin try
     let source = List.assoc cu.cu_name !implementations_defined in
-    Location.prerr_warning (Location.in_file file_name)
-      (Warnings.Module_linked_twice(cu.cu_name,
-                                    Location.show_filename file_name,
-                                    Location.show_filename source))
+    raise (Error (Module_linked_twice(cu.cu_name, file_name, source)));
```
Comment (v-gb) [inline bytecomp/bytelink.ml]: Same thing as in asmlink.ml: I think we should move the check to the top of the function, for better error messages.

**Review by v-gb — CHANGES_REQUESTED** [review]
Based on the issues linked, there seems to be consensus for making this change, and I think the code change does what's intended.

I tested the behavior of this change with the script at the bottom of this comment, and it works fine but I observe error messages that are a bit worse:

4.14:
```
native:
File "_none_", line 1:
Error: Files 2/a.cmx and 1/a.cmx both define a module named A

bytecode:
File "2/a.cmo", line 1:
Error (warning 31 [module-linked-twice]): files 2/a.cmo and 1/a.cmo both define a module named A
File "2/b.cmo", line 1:
Error (warning 31 [module-linked-twice]): files 2/b.cmo and 1/b.cmo both define a module named B
```

this PR:
```
native:
File "_none_", line 1:
Error: Files 2/a.cmx and 1/a.cmx
       make inconsistent assumptions over interface A

bytecode:
File "_none_", line 1:
Error: Files 2/a.cmo and 1/a.cmo
       make inconsistent assumptions over interface A
```

Not the end of the world when the build system ensures uniqueness of compilation units, but I think it's trivial to fix (as I indicated in an inline comment), so may as well.

Other than addressing the review comments, please do the usual rebase, adding a Changes entry (and maybe squash the commits? not sure what's expected).



The test script:
```bash
#!/bin/bash
set -e -u -o pipefail
which ocamlopt
which ocamlc
rm -rf /tmp/test
mkdir /tmp/test
cd /tmp/test
mkdir 1 2
echo "type t = int" > 1/a.ml
echo "Printf.printf \"%d\\n\" (1 : A.t)" > 1/b.ml
echo "type t = string" > 2/a.ml
echo "Printf.printf \"%s\\n\" (\"qwerty\" : A.t)" > 2/b.ml
echo "native:"
(cd 1; ocamlopt -c {a,b}.ml)
(cd 2; ocamlopt -c {a,b}.ml)
ocamlopt 1/{a,b}.cmx 2/{a,b}.cmx || true
echo "bytecode:"
(cd 1; ocamlc -c {a,b}.ml)
(cd 2; ocamlc -c {a,b}.ml)
ocamlc 1/{a,b}.cmo 2/{a,b}.cmo
```

File: bytecomp/bytelink.ml (hunk 2 above)
Comment (hhugo) [reply bytecomp/bytelink.ml]: Done

File: bytecomp/bytelink.ml (hunk 3 above)
Comment (hhugo) [reply bytecomp/bytelink.ml]: Done

File: asmcomp/asmlink.ml (hunk 1 above)
Comment (hhugo) [reply asmcomp/asmlink.ml]: Done

**Comment by hhugo** [comment]
Thanks for the review @sliquister. I meant to add a new test in the testsuite but my few attempts weren't successful.
Here is the output of your script with this PR
```
native:
File "_none_", line 1:
Error: Files 2/a.cmx and 1/a.cmx both define a module named A
bytecode:
File "_none_", line 1:
Error: Files 2/a.cmo and 1/a.cmo both define a module named A
```

Running more tests, I noticed that, when linking a library that contain units also present elsewhere on the command line, we don't fail/warn if theses units don't end up being linked. The behavior seems fine but it means that adding `-linkall` would suddenly trigger the error.

File: Changes [hunk 4]
```diff
@@ -219,6 +219,9 @@ Working version
   modules with mismatching -for-pack
   (Pierre Chambart and Vincent Laviron, review by Mark Shinwell)
 
+- #11635: Turn warning 31 (Module_linked_twice) into a hard error
```
Comment (v-gb) [inline Changes]: Please list the issues as well, not just the PR.

**Review by v-gb — APPROVED** [review]
Looks good, modulo the Changes entry.

**Comment by v-gb** [comment]
The appveyor failure looks spurious.

> Running more tests, I noticed that, when linking a library that contain units also present elsewhere on the command line, we don't fail/warn if theses units don't end up being linked. The behavior seems fine but it means that adding `-linkall` would suddenly trigger the error.

Yeah, that behavior seems fine, although a stricter behavior would probably also make sense.

File: utils/warnings.ml [hunk 5]
```diff
@@ -349,10 +349,6 @@ let descriptions = [
       "Two labels or constructors of the same name are defined in two\n\
       \    mutually recursive types.";
     since = None };
-  { number = 31;
-    names = ["module-linked-twice"];
-    description = "A module is linked twice in the same executable.";
-    since = since 4 0 };
```
Comment (gasche) [inline utils/warnings.ml:355]: I would like to understand well what is going on with the warning from a compatibility perspective:

- what happens if a user manually specifies this warning, on the command-line or in an attribute, by number or by name?
- what is shown in `-warn-help`?

My current understanding is as follows:

- Warning modifiers are interpreted by mutating dense flag arrays of all warning numbers.
- Using a number-based modifier `-31` or `+31` will modify the flag array and do nothing else (as the warning is never raised anymore). In practice this is silently ignored, which is probably fine.
- Using `-module-linked-twice` will result in a lookup failure because the `description` entry is removed here, which will eventually result in a confusing `ocaml_deprecated_cli` alert. This is not good.
- The warning will not appear in `-warn-help` anymore, because the description entry is removed.

I think that we should do this instead: keep the description entry, but extend the description to say that the warning is now ignored and replaced by a hard error.

My understanding is that we would then get the following behavior:
- specifying the warning by number or by name is ignored
- the warning shows up in `-warn-help`, with a mention that it is ignored

I think that this new behavior would be reasonable, a better default.

One may think of something even more informative (if users try to *disable* the warning, letting them know that this does not work anymore through... another warning?), but I think that it would not be worth the implementation and conceptual complexity.

Minor note: the definition of `defaults_warn_error` further down still mentions `+31`, it should be removed I think.

File: Changes (hunk 4 above)
Comment (hhugo) [reply Changes]: Done

File: utils/warnings.ml (hunk 5 above)
Comment (hhugo) [reply utils/warnings.ml:355]: I've kept the description entry, updated `defaults_warn_error` and updated manual and man pages.

I'm not super happy with the updated description.
```
31 [module-linked-twice] Ignored: now a hard error (since 5.0).
    A module is linked twice in the same executable.
```
I've tried to follow what was done for number 25
```
25 Ignored: now part of warning 8.
```

Comment (hhugo) [reply utils/warnings.ml:355]: I've changed it to
```
 31 [module-linked-twice] A module is linked twice in the same executable.
    Ignored: now a hard error (since 5.0).
```

Comment (gasche) [reply utils/warnings.ml:355]: Fine with me, thanks!

**Review by gasche — APPROVED** [review]
i agree with @sliquister that this is a good implementation of the proposed change. I am in favor of merging once the commits have been rebased/fixupped by @hhugo as he prefers, and the CI is green.

Thanks a lot @sliquister for your careful review. I don't think that I would have had the energy to look at this by myself without your contribution.

File: utils/warnings.ml (hunk 5 above)
Comment (Octachron) [reply utils/warnings.ml:355]: 5.1 rather than 5.0 ?

Comment (hhugo) [reply utils/warnings.ml:355]: @Octachron, fixed thanks.

**Comment by hhugo** [comment]
> i agree with @sliquister that this is a good implementation of the proposed change. I am in favor of merging once the commits have been rebased/fixupped by @hhugo as he prefers, and the CI is green.
> 
> Thanks a lot @sliquister for your careful review. I don't think that I would have had the energy to look at this by myself without your contribution.

I've squashed the commits and rebased.

**Comment by v-gb** [comment]
Looks like the warning changes are breaking `tests/warnings/mnemonics.mll`.

**Comment by nojb** [comment]
> Looks like the warning changes are breaking `tests/warnings/mnemonics.mll`.

Indeed. This test checks that every constructor of the sum type has a corresponding textual mnemonic, and vice-versa. This fails because the mnemonic for warning 31 does not have a corresponding constructor.

The simplest workaround is to add a hard-coded list of deprecated warnings to this test (for which there is no associated constructor).

**Comment by hhugo** [comment]
I've pushed a fix for the tests/warnings/mnemonics.mll test following @nojb suggestion

**Comment by hhugo** [comment]
The appveyor failure is due to #11853

**Review by v-gb — APPROVED** [review]

**Comment by nojb** [comment]
Merged, thanks!
