### PR TITLE
Fix `Buffer.add_substitute`

### LINKED ISSUE #6732: Buffer.add_substitute is not surjective and its documentation is incomplete.
**Original bug ID:** 6732
**Reporter:** @damiendoligez
**Status:** acknowledged (set by @damiendoligez on 2015-01-09T17:22:48Z)
**Resolution:** open
**Priority:** low
**Severity:** minor
**Version:** 4.02.1
**Category:** standard library
**Monitored by:** @hcarty @dbuenzli

## Bug description

The documentation of Buffer.add_substitute says:
   An escaped [$] character is a [$] that immediately follows a backslash
   character; it then stands for a plain [$].
This is not true if the [$] follows an even number of backslashes.

It also says:
   Raise [Not_found] if the closing character of a parenthesized variable
   cannot be found.
But [Not_found] is also be raised if there is an unescaped [$] at the end of the string.

The documentation also fails to state that, when [Not_found] is raised, some characters are still added to the buffer. It also omits the fact that the adding stops silently when it sees an unescaped [$] followed by anything else than alphanum, '_', '{' or '('.

Finally, the only way to get a single backslash followed by a dollar is by playing with variables, there is no way to get it from a constant string because the quoting conventions are incomplete: backslashes should also be escaped by backslashes.

Some of these problems should be fixed, and the others documented.

## Steps to reproduce

OCaml version 4.02.1

# let b = Buffer.create 0;;
val b : Buffer.t = <abstr>
# Buffer.add_substitute b (fun _ -> "") "\n1. \\$";;
- : unit = ()
# Buffer.add_substitute b (fun _ -> "") "\n2. \\\\$";;
Exception: Not_found.
# Buffer.add_substitute b (fun _ -> "") "\n3. \\\\$ ";;
- : unit = ()
# Buffer.add_substitute b (fun _ -> "") "\n3. \\\\$!";;
- : unit = ()
# Buffer.add_substitute b (fun _ -> "") "\n4. \\\\\\$";;
- : unit = ()
# Buffer.add_substitute b (fun _ -> "") "\n5. $}";;
- : unit = ()
# print_endline (Buffer.contents b);;

1. $
2. \\
3. \\
3. \\
4. \\$
5. 
- : unit = ()
#

### PR DESCRIPTION
**Pull request by damiendoligez**
- clarify documentation
- remove `Not_found` exception
- fix implementation

Fixes #6732

### CODE REVIEW

File: testsuite/tests/lib-buffer/test.ml [hunk 1]
```diff
@@ -255,3 +255,34 @@ let () =
...
+  (* escaped dollar *)
+  Buffer.add_substitute b f {| \$foo|};
+  Buffer.add_substitute b f {| \\$foo|};
+  Buffer.add_substitute b f {| \\\$foo|};
+  (* no variable name *)
+  Buffer.add_substitute b f " $";
+  Buffer.add_substitute b f " $!";
+  Buffer.add_substitute b f " $(abc";
+  assert (Buffer.contents b
+            = {| FOO hash hash nil $foo \$foo \\$foo $ $& $(abc|})
```
Comment (MisterDA) [inline testsuite/tests/lib-buffer/test.ml]:
```suggestion
            = {| FOO hash hash nil $foo \$foo \\$foo $ $! $(abc|})
```
I think that was just a typo.

**Review by MisterDA — CHANGES_REQUESTED** [review]
LGTM. Do we expect breakage with this change?
The commit message should be amended to keep a blank line between the first line and the body.

**Review by MisterDA — APPROVED** [review]

File: stdlib/buffer.mli [hunk 2]
```diff
@@ -167,18 +167,16 @@ val add_subbytes : t -> bytes -> int -> int -> unit
...
    of buffer [b] with substitution.
-   The substitution process looks for variables into
-   the pattern and substitutes each variable name by its value, as
+   The substitution process looks for variable references in
+   the pattern and substitutes each variable reference with its value, as
    obtained by applying the mapping [f] to the variable name. Inside the
-   string pattern, a variable name immediately follows a non-escaped
-   [$] character and is one of the following:
+   string pattern, a variable reference is a non-escaped [$] immediately
+   followed by a variable name, which is one of the following:
```
Comment (Julow) [inline stdlib/buffer.mli:174]: The way the `$` character is escaped is inconsistent with escaping in other places (eg. OCaml strings, format strings) as it's impossible to escape the `` \ `` character.
It's impossible to have this function write `\$` without using a trick but it's possible to write `"\\\""` and `printf "%%s"`.

Comment (damiendoligez) [reply stdlib/buffer.mli:174]: > The way the `$` character is escaped is inconsistent with escaping in other places (eg. OCaml strings, format strings) as it's impossible to escape the `\` character.

That's true, it's this way because I wanted to make minimal changes to the behavior of the function.

> It's impossible to have this function write `\$` without using a trick

That's in fact fixed by this PR. Look at the test file, the function maps:
`\$` to `$`
`\\$` to `\$`
`\\\$` to `\\$`
(and so on). It's a different quoting convention, but it **is** surjective, unlike the current version of `add_substitute`.

Comment (damiendoligez) [reply stdlib/buffer.mli:174]: Actually, what is impossible without tricks is a backslash followed by a variable reference. We could fix this by switching to the usual quoting convention, but I'm afraid this might entail a lot of breakage.

**Review by nojb — APPROVED** [review]
LGTM

This is a mostly-backwards compatible that makes two changes to the function:

- a backslash now always stands for itself, except when it precedes a `$` when the pair stands for a lone `$`. Previously, `\\$foo` would be mapped to `\\<value of foo>`, now it maps to `\$foo`.

- no longer raises `Not_found` when an unterminated variable reference is found (eg `${foo`), instead it simply echoes the characters back. A quick OPAM grep (https://sherlocode.com/?q=Buffer.add_substitute) shows that most (all?) users of this function do not handle `Not_found` anyway. One could argue that, if anything, `Buffer.add_substitute` should have raised `invalid_arg` instead of `Not_found` in this case, but simply returning the untouched characters seems even better.

A second approval by a core dev is needed, as this touches the standard library (note that @MisterDA has approved the PR as well, so a "on-behalf-of" approval could be enough).

**Comment by MisterDA** [comment]
I'm satisfied about the new behavior of the function, and the test cases cover all the patterns that were important to me when we filed the original bug.

**Comment by nojb** [comment]
Friendly ping; we still need a second review of this PR... volunteers appreciated! Thanks.

**Review by gasche — APPROVED** [review]
My impression:
- the spec of this function is somewhat broken, it should not be in Buffer in the first place ( I think everyone agrees, starting with Alain 9 years ago: https://github.com/ocaml/ocaml/issues/6732#issuecomment-473041067 )
- the fix makes some cases that looked very broken behave nicer -- but the result remains unsatisfying in some respects
- in jest I would say, semi-seriously, that the main reason to merge this is the sunk cost fallacy: we have put enough effort in the change to want to see it merged, despite the fact that in practice no one cares and the cost of changing the behavior of the function under the user's feet is probably going to outweigh the benefits of the improvements

I deduce from this glowing review that we should go ahead and merge it, sooner rather than later.

**Comment by nojb** [comment]
> * the main reason to merge this is the sunk cost fallacy:

Thanks for the review @gasche!

Just for future reference, my thought process regarding this PR is as follows: I tend to agree that the API is not ideal, but as pointed out in https://github.com/ocaml/ocaml/issues/6732#issuecomment-626622185, we are stuck with it for the time being, so in general we should try to fix its shortcomings if it can be done without too much trouble. Whether to go ahead with with backwards-incompatible fixes as in this PR is a more delicate question, but my (necessarily subjective) feeling is that it is worth it.
