### PR TITLE
Fix #7636 using expansion for vanishing parameters

### LINKED ISSUE #7636: Constant type can not be generalized ?
**Original bug ID:** 7636
**Reporter:** ChriChri
**Assigned to:** @garrigue
**Status:** confirmed (set by @lpw25 on 2017-10-02T16:40:50Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Target version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** typing
**Monitored by:** ChriChri

## Bug description

It looks like if variables were not values in Ocaml ?

This is not accepted :
```ocaml
type 'a iter = { f : 'b.'a -> unit }

let promote f : 'a -> unit = { f }
```
This works: 
```ocaml
let promote f =
  let f : 'b.'a -> unit = fun x -> f x in
  { f = fun x -> f x }
```

### PR DESCRIPTION
**Pull request by garrigue**
This is a follow up to #1588, fixing #7636 and #5673 by using the expansion method suggested by @lpw25 .

Namely, in `Ctype.update_level`, when a constructor has a vanishing parameter whose level we would have to lower, we rather expand it.

### CODE REVIEW

File: typing/ctype.ml [hunk 1]
```diff
@@ -837,8 +837,18 @@ let rec update_level env level expand ty =
...
           raise Trace.(Unify [escape(Constructor p)])
         end
-    | Tconstr(_, _ :: _, _) when expand ->
+    | Tconstr(p, (_ :: _ as tl), _) ->
+        let variance =
+          try (Env.find_type p env).type_variance
+          with Not_found -> List.map (fun _ -> Variance.may_inv) tl in
+        let needs_expand =
+          expand ||
+          List.exists
```
Comment (lpw25) [inline typing/ctype.ml]: I think you can just use `List.exists2` here.

File: Changes [hunk 2]
```diff
@@ -327,6 +327,9 @@ Working version
 
 ### Bug fixes:
 
+- #5673, #7636: unused type variable causes generalization error
+  (Jacques Garrigue, report by Christophe Raffalli)
```
Comment (lpw25) [inline Changes]: (Ahem)

**Review by lpw25 — APPROVED** [review]
LGTM

File: typing/ctype.ml (hunk 1 above)
Comment (garrigue) [reply typing/ctype.ml]: Didn't know about that one. Nice.

File: Changes (hunk 2 above)
Comment (garrigue) [reply Changes]: ?? Added others involved.

Comment (lpw25) [reply Changes]: Well the code in this PR is almost verbatim from my comment: https://github.com/ocaml/ocaml/pull/1588#issuecomment-361557731. So I was expecting at least some credit in the Changes entry -- I will accept the review credit that you have since added.

Comment (garrigue) [reply Changes]: Right. I gradually converged to your code, removing all the extra bits I had in the beginning.
The only place you can recognize that I didn't copy it is that I was not using `exists2`, but even that has been fixed, so yes, this is your code.

Comment (gasche) [reply Changes]: I just added Leo as an author in the Changes.
