### PR TITLE
Fix dumpobj crash due to naked pointer comparison

### LINKED ISSUE #11061: `dumpobj` tool crashes
As of revision f022f9b9d, the executable `tools/dumpobj` crashes with a segmentation fault when called on a simple bytecode program. The same is true of `tools/dumpobj.opt`.
```
$ cat tmp.ml
let () =
  let x = 42 in
  let x = x + x in
  Printf.printf "%d\n" x
$ ocamlc tmp.ml
$ ~/path/to/compiler/tools/dumpobj a.out
## start of ocaml dump of "a.out"
zsh: segmentation fault (core dumped) ~/path/to/compiler/tools/dumpobj a.out
$ ~/path/to/compiler/tools/dumpobj.opt a.out
## start of ocaml dump of "a.out"
zsh: segmentation fault (core dumped) ~/path/to/compiler/tools/dumpobj.opt a.out
```

GDB backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000822403 in do_compare_val (stk=stk@entry=0x7fffffffbee0, v1=0, v2=0, total=total@entry=0) at compare.c:150
150	      switch (Tag_val(v1)) {
(gdb) bt
#0  0x0000000000822403 in do_compare_val (stk=stk@entry=0x7fffffffbee0, v1=0, v2=0, total=total@entry=0) at compare.c:150
#1  0x00000000008229b7 in compare_val (total=0, v2=<optimized out>, v1=<optimized out>) at compare.c:97
#2  caml_equal (v1=<optimized out>, v2=<optimized out>) at compare.c:316
#3  <signal handler called>
#4  0x000000000052b4d1 in camlDumpobj__same_custom_1113 () at dumpobj.ml:114
#5  0x000000000052b7b5 in camlDumpobj__print_obj_1160 () at dumpobj.ml:135
#6  0x000000000052c53e in camlDumpobj__print_instr_1317 () at dumpobj.ml:440
#7  0x000000000052ca20 in camlDumpobj__print_code_1336 () at dumpobj.ml:482
#8  0x000000000052d23f in camlDumpobj__arg_fun_1536 () at dumpobj.ml:574
#9  0x00000000007f51d2 in camlStdlib__Arg__parse_and_expand_argv_dynamic_aux_601 () at arg.ml:279
#10 0x00000000007f641b in camlStdlib__Arg__parse_expand_830 () at arg.ml:287
#11 0x000000000052d333 in camlDumpobj__main_1540 () at dumpobj.ml:582
#12 0x000000000052da6f in camlDumpobj__entry () at dumpobj.ml:585
#13 0x00000000005273ab in caml_program ()
#14 <signal handler called>
#15 caml_startup (argv=<optimized out>) at startup_nat.c:136
#16 0x000000000083faf5 in caml_main (argv=<optimized out>) at startup_nat.c:142
#17 0x00000000005268bc in main (argc=<optimized out>, argv=<optimized out>) at main.c:37
```

### PR DESCRIPTION
**Pull request by OlivierNicole**
This fixes #11061. `dumpobj` crashes because it calls `(=)` on the first field of two `int64` values, which are pointers to a C `custom_ops` struct (since `int64` values are implemented as custom blocks). This worked when the generic comparison function supported naked pointers, but that is no longer the case since the Multicore merge.
This was found with some help from @jmid, thanks to him!

Replacing `(=)` with `(==)` avoids the crash without changing the result.

I also added a test for `dumpobj` to detect its breakage in the future.

### CODE REVIEW

File: tools/dumpobj.ml [hunk 1]
```diff
@@ -111,7 +111,7 @@ let rec print_struct_const = function
 (* Print an obj *)
 
 let same_custom x y =
-  Obj.field x 0 = Obj.field (Obj.repr y) 0
+  Obj.field x 0 == Obj.field (Obj.repr y) 0
```
Comment (gasche) [inline tools/dumpobj.ml]: This may be correct, but it is a bit dangerous because you need to be a compiler expert to ensure that the code does not load naked pointers as temporary values in an incorrect way. Instead you should use the new-ish `Obj.raw_field` API, which properly boxes the naked/raw data into a `nativeint`. So I would try

```
  Obj.raw_field x 0 = Obj.raw_field (Obj.repr y) 0
```

**Review by gasche — COMMENTED** [review]
Nice find!

**Comment by gasche** [comment]
Also:
- I like that there is a test, thanks!
- Could you include a Changes entry for this changes? (Bug fixes, "make dumpobj compatible with no-naked-pointers" or something.)

File: testsuite/tests/tool-dumpobj/test.run [hunk 2]
```diff
@@ -0,0 +1,4 @@
+set -e -o pipefail
+
+# We remove the first and last lines as they contain user-dependent file paths
+${ocamlsrcdir}/tools/dumpobj.opt ${program} | tail -n +2 | head -n -1 > ${output}
```
Comment (Octachron) [inline testsuite/tests/tool-dumpobj/test.run]: For the header part, you can ask ocamltest to skip header lines with the `skip_header_lines` variable:

```
**** check-program-output
skip_header_lines=1
```
It would probably make sense to update ocamltest with a `skip_footer_lines` variable for the symmetric part.

File: tools/dumpobj.ml (hunk 1 above)
Comment (OlivierNicole) [reply tools/dumpobj.ml]: Ah yes, that's much better. Done in the new version.

**Comment by OlivierNicole** [comment]
I fixed the test by implementing the new ocamltest variable suggested by @Octachron in a separate commit. If needed, I can move it to a separate PR.

**Review by gasche — APPROVED** [review]

**Comment by OlivierNicole** [comment]
The test is a bit annoying in the sense that it will have to be updated every time the bytecode executable generated for `test.ml` changes. I don't quite see how to avoid it, except maybe relaxing the test and only testing the exit code of dumpobj. Let me know.

File: ocamltest/filecompare.ml [hunk 3]
```diff
@@ -104,7 +105,28 @@ let line_seq_of_in_channel ~normalise ic =
...
+      let seq1 = fun () -> node1 in
+      let rec loop seq1 seq2 =
+        match seq1 (), seq2 () with
+        | Nil, node2 -> length (fun () -> node2) = n
+        | Cons _, Nil -> false
+        | Cons (x1, rem1), Cons (x2, rem2) ->
+            if x1 = x2 then loop rem1 rem2 else false
+      in
+      loop seq1 seq2
+
```
Comment (xavierleroy) [inline ocamltest/filecompare.ml]: That's a lot of code...  I'm afraid we need a review by @shindere or someone who is familiar with ocamltest.

**Review by xavierleroy — COMMENTED** [review]
The change to dumpobj is perfect.  But I'm scared by the changes in ocamltest.  Do we really need a test for the one-line change to dumpobj?  I'll gladly sign it off without a test.

**Comment by shindere** [comment]
No strong opinion on whether the test is worth it or not. On the one
hand the reference file is copious, on the other hand, since the tool
gets installed it's probably worth testing it (I assume that, with this
test, the problem with naked pointers would have been caught earlier).

Regarding the implementaiton, though, the current one does indeed seem a
bit overkill to me, especially given that the `skip_header_lines`
variable is not used any longer by any other test.

Since the test already relies on a `.run` script, why not simply pipe
the output of dumpobj through `head -n -1 | tail -n +2` before writing
to the output file?

**Comment by gasche** [comment]
Ok, let's remove the ocamltest change before merging.

(I agree that your version of "remove the n last elements then compare" is too complex.)

**Comment by Octachron** [comment]
Note that the `skip_header_lines` variable is still used by ocamldoc tests (which were the tests for which the variable was introduced).

**Comment by shindere** [comment]
Out of curiosity, why is it necessary to remove the first and last line
of output before comparing it to the reference file? Is there some
variation between runs of `objdump`?

**Comment by shindere** [comment]
Florian Angeletti (2022/03/02 12:22 -0800):
> Note that the `skip_header_lines` variable is still used by ocamldoc
> tests (which were the tests for which the variable was introduced).

Oops sorry, I did a git grep but perhaps I made a mistake...

**Comment by shindere** [comment]
Okay dumpobj prints banners so that one knows which file it dumps, that are
the first and last line of its output.

If one wanted to tset it more massively, one could add a -no-banners
option to remove those lines, as has been done for the toplevelto remove the
prompts and the startup message.

It would also be possible to have an option that makes file names in the
banners relative, or have jsut the base name. That way the banners would be
relocatable, so to speak.

Finally, one could argue that, if dumpobj is run with only one file, then
printing those banners is superfljous and thus remove them.

**Comment by OlivierNicole** [comment]
A problem with piping the output in `head` is that ~~`tail -n -1`~~ (edit: sorry, actually `head -n -1`) is not portable e.g. on macOS.

I removed the ocamltest change. What about simplifying the test by just testing the exit code of `dumpobj`? This would make the test less maintenance-heavy and detect crashes like the one that prompted this PR.

**Comment by gasche** [comment]
> What about simplifying the test by just testing the exit code of dumpobj? This would make the test less maintenance-heavy and detect crashes like the one that prompted this PR.

If you want. I think this is already what the PR does right now?

I'm not too worried about the maintenance-heaviness of the test, in particular because the bytecode compilation strategy rarely changes. Sometimes it's nice to see the effect of changes in in the testsuite, and `promote` makes test maintenance easy. But: I agree that writing a perfect test may not be the primary focus right now, so I guess that testing the exit code is good enough.

**Comment by gasche** [comment]
(I think that if ocamltest explicitly support trimming lines from the head of the output, it would also make perfect sense to support trimming lines from the tail of the output. The general patch looked good, except this weird Seq function in the middle that looked like it would force the same Seq several times. I think this was a reasonable move and could be made into its own PR, but again, do we care enough?)

**Comment by OlivierNicole** [comment]
> If you want. I think this is already what the PR does right now?

Yes, I changed it in that way.

**Comment by gasche** [comment]
Merged, thanks!

**Comment by OlivierNicole** [comment]
For the record, I noticed that the test is not reported as failing, even when it is… it is probably the same cause as https://github.com/ocaml/ocaml/issues/10953.

```
~/compiler/trunk/testsuite/ make one TEST=tests/tool-dumpobj/test.ml
 ... testing 'test.ml' with 1 (setup-ocamlc.byte-build-env) => passed
 ... testing 'test.ml' with 1.1 (ocamlc.byte) => passed
 ... testing 'test.ml' with 1.1.1 (run) => /home/olivier/compiler/trunk/testsuite/tests/tool-dumpobj/test.run : ligne 5 : 447305 Segmentation fault      (core dumped)${ocamlsrcdir}/tools/dumpobj.opt ${program} > ${output}
failed ()
> Specified modules: test.ml
> Source modules: test.ml
> Running test setup-ocamlc.byte-build-env with 1 actions
> 
> Running action 1/1 (setup-ocamlc.byte-build-env)
> Action 1/1 (setup-ocamlc.byte-build-env) passed
> Running test ocamlc.byte with 1 actions
> 
> Running action 1/1 (ocamlc.byte)
> Compiling program /home/olivier/compiler/trunk/testsuite/_ocamltest/tests/tool-dumpobj/test/ocamlc.byte/test.byte from modules  test.ml
> Commandline: /home/olivier/compiler/trunk/runtime/ocamlrun /home/olivier/compiler/trunk/ocamlc -use-runtime /home/olivier/compiler/trunk/runtime/ocamlrun -I /home/olivier/compiler/trunk/runtime -nostdlib -I /home/olivier/compiler/trunk/stdlib -o /home/olivier/compiler/trunk/testsuite/_ocamltest/tests/tool-dumpobj/test/ocamlc.byte/test.byte test.ml
>   Redirecting stdout to /home/olivier/compiler/trunk/testsuite/_ocamltest/tests/tool-dumpobj/test/ocamlc.byte/ocamlc.byte.output 
>   Redirecting stderr to /home/olivier/compiler/trunk/testsuite/_ocamltest/tests/tool-dumpobj/test/ocamlc.byte/ocamlc.byte.output 
> Action 1/1 (ocamlc.byte) passed
> Running test run with 1 actions
> 
> Running action 1/1 (run)
> Entering run_hook for hook /home/olivier/compiler/trunk/testsuite/tests/tool-dumpobj/test.run
> Hook should write its response to /tmp/ocamltest-3f5877.response
> Hook returned 1Action 1/1 (run) failed ()
make[1] : on entre dans le répertoire « /home/olivier/compiler/trunk/testsuite »
make[1] : on quitte le répertoire « /home/olivier/compiler/trunk/testsuite »
make[1] : on entre dans le répertoire « /home/olivier/compiler/trunk/testsuite »


Summary:
    2 tests passed
    0 tests skipped
    0 tests failed
    0 tests not started (parent test skipped or failed)
    0 unexpected errors
    2 tests considered
```

**Comment by shindere** [comment]
The test as proposed by this PR is not fully correct because it runs
the native version of dumpobj, assuming it exists.
This will not be the case if the native compiler is disabled.

PR #11079 fixes this and makes the tset both simpler and more precise
since it includes the comparison to a reference output file.
