### PR TITLE
Fix #10907: Wrong type inferred from existential types

### LINKED ISSUE #10907: Wrong type inferred from existential types
Input the following code into toplevel (both trunk and 4.13.1):

``` ocaml
type 'a t = T : ('a -> 'b) * ('b -> 'a) -> 'a t;;
type 'a t = T : ('a -> 'b) * ('b -> 'a) -> 'a t

let t = T ((fun x -> x), (fun x -> x));;
val t : 'a t = T (<fun>, <fun>)

let T (g, h) = t in h (g 1);;
- : 'a = <poly>

let f x = let T (g, h) = t in h (g x);;
val f : 'a -> 'b = <fun>
```

Seems the typechecker failed to infer the correct type, in comparison with

``` ocaml
type s = S : (int -> 'b) * ('b -> int) -> s;;
type s = S : (int -> 'b) * ('b -> int) -> s

let s = S ((fun x -> x), (fun x -> x));;
val s : s = S (<fun>, <fun>)

let S (g, h) = s in h (g 1);;
- : int = 1
```

### PR DESCRIPTION
**Pull request by garrigue**
Fix the unsoundness by lowering the level of variables in constructors that introduce existentials to `expansion_scope` (#10907)

Based on a first draft by @gasche 

This PR also removes spurious principality warnings coming from generated counter-examples.
As a result, the output of #10189 is a bit shortened.

### CODE REVIEW

**Comment by gasche** [comment]
As far as I can tell, the code corresponds to our discussion. (I agree with @garrigue that @lpw25's refined proposal is harder to implement -- I tried.) Minor comments:

- It's not obvious at first that `lower_contravariant` will not only lower contravariant variables, but all variables that appear under some contravariant position; in Coq terms, we are lowering all "non-strictly-positive" variables. In particular, you rely on the fact that `lower_contravariant ... true` actually means `lower_variables`. It could be nice to define a `lower_variables` (or `lower_all_variables`, etc.) mutually-recursively with `lower_contravariant`, and use it here and in the negative cases of `lower_contravariant` itself).

- I don't know if we need to keep the two versions of the repro case in the testsuite; I would just use whichever you prefer, attributed to the reporter.

- This also has potential for breaking code, for example by suddenly failing with principality warnings/errors in codebases that were previously safe. We should try to do some OPAM-wide testing before merging. (For this keeping the patch minimal is a plus, so nice documentation comments and code cleanups should probably wait.)

**Comment by garrigue** [comment]
@gasche Thanks for looking at this.
Actually, there is a vocabulary problem around variance in ocaml, and it is not limited to here.
I.e. we (I?) use contravariant both to say that a variable is allowed to be subtyped in the opposite direction, and to say that an occurence is at a negative position. Since a variable can have several occurrences, there is already something fishy.
Outside of that, the comment in the mli is supposed to be clear: all variables in contravariant branches (i.e. under nodes at contravariant/negative positions) are lowered, which indeed amounts to the opposite of strict positivity in Coq parlance. Maybe we should call it `lower_non_strictly_positive_variables`, but then there are many other places to fix. Note that, from a parameter variance point of view, this corresponds to `May_weak` in `Types.Variance`.

As for the opam testing, I can only approve. The impact should be small, but it is hard to guarantee that nothing breaks when we change polymorphism. Note that we may end up mostly breaking unsound code :-)

File: testsuite/tests/typing-gadts/pr10189.ml [hunk 1]
```diff
@@ -111,24 +111,6 @@ Warning 8 [partial-match]: this pattern-matching is not exhaustive.
...
-module M :
-  sig
-    type 'a d
-    type i = < m : 'c. 'c -> 'c d >
-    type 'a j = < m : 'c. 'c -> 'a >
-  end
-type _ t = A : M.i t
-File "_none_", line 1:
-Warning 18 [not-principal]: typing this pattern requires considering $0 and 'c M.d as equal.
-But the knowledge of these types is not principal.
```
Comment (gasche) [inline testsuite/tests/typing-gadts/pr10189.ml:124]: Note: this is an example of a principality warning that was raised during exhaustivity analysis, on a sub-case of an "exploded" wildcard pattern. The dummy location (File "_none_", line 1) comes from the dummy location used by parmatch when exploding wildcard partterns.

I believe that the change in this testsuite result does not come from the lowering of levels (the actual type-checking change in the PR), but simply from the fact that we now silence this warning during exhaustivity analysis. (We silenced them because our behavior change would raise those warnings very often in this situation.) It's interesting that it already occurred in the wild.

File: Changes [hunk 2]
```diff
@@ -451,6 +451,9 @@ OCaml 4.14.0
   operation in `NO_SHARING` mode.
   (Xavier Leroy, report by Anil Madhavapeddy, review by Alain Frisch)
 
+- #10907, #10959: Wrong type inferred from existential types
+  (Jacques Garrigue and Gabriel Scherer, report by @dyzsr *)
```
Comment (gasche) [inline Changes]: Nitpick: There is an extra `*` at the end. Is this muscle-memory due to writing too many comments? (I would expect François Pottier to make these typos out of habit, but not Jacques :-D)

**Comment by gasche** [comment]
I think that we should seriously consider having this in 4.14: it fixes a long-standing soundness bug. (The fact that it is long-standing suggests that it would probably also be fine to wait for 5.0 or 4.14.1.)

We need two things to advance further:
- some feedback from @lpw25, ideally a review
- report on opam-repository impact from @Octachron or @kit-ty-kate (what would you need for this? maybe merging in 4.14 would actually be the simplest approach to get feedback :D)

**Review by lpw25 — APPROVED** [review]
LGTM

**Comment by trefis** [comment]
:wave: 

I had missed the bugreport, so I've been catching up on this this morning. I've been looking at the code and I think I have some questions. Fortunately I'm having lunch with @gasche today, so I can probably discuss things with him and come back with a second approval this afternoon.

**Comment by kit-ty-kate** [comment]
> report on opam-repository impact from @Octachron or @kit-ty-kate (what would you need for this? maybe merging in 4.14 would actually be the simplest approach to get feedback :D)

yes, as long as a the next alpha/beta release doesn’t come too soon after that to give me the time to test the ecosystem it is indeed the easiest approach as I’m already testing the `4.14` branch directly. As long as you’re confident it shouldn’t break anything I’m all for it.
If you’re unsure, I can setup a specific test using this branch (given it’s already set up for the 4.14 brach). I would get the results this weekend probably.

File: Changes (hunk 2 above)
Comment (garrigue) [reply Changes]: Well, this PR is pretty short, and it still includes a comment (in a mli, I admit), so this is not so true :-)

File: testsuite/tests/typing-gadts/pr10189.ml (hunk 1 above)
Comment (garrigue) [reply testsuite/tests/typing-gadts/pr10189.ml:124]: Indeed, it purely comes from my turning off the warning on counter-examples.
Whether turning off the warning is correct might be debatable. Namely, the fact the inference is deemed not principal suggests that the exhaustiveness assessment might not be principal. However, at least the current warning was not satisfactory, as it warns on non-existing code. Moreover, the exhaustiveness check runs after everything else, so at that point all types should be already known, even if it is not in a principal way, so the surprise factor seems much lower.

**Comment by garrigue** [comment]
@kit-ty-kate It is important that this is checked before the release, so that we know about the consequences, but I do not expect major breakage, and it should be easy to track problems back, so I think that merging first and testing opam after is fine. Just waiting for @trefis approval.

**Comment by Octachron** [comment]
There is already few changes worthy of a new alpha release in 4.14 (the new `Thread.Exit` exception, the removal of the deprecation warning for (u)int{8,16}). I would propose to release a second alpha with this change once it is merged.
And if this change causes too much troubles in 4.14, we will still have time to revert it before the first beta.

**Comment by gasche** [comment]
Let's merge in 4.14 then :-)

**Review by trefis — APPROVED** [review]
Makes sense to me.

I find some things surprising in this part of the code, but they are unrelated to this issue/PR. So I'll reach out at another time.
