### PR TITLE
Fix #7813 (major GC fails to start)

### LINKED ISSUE #7813: Calling Gc.major_slice stalls gc'ing
**Original bug ID:** 7813
**Reporter:** anders.fugmann
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.06.1
**Category:** runtime system and C interface
**Monitored by:** @nojb

## Bug description

When only allocating data on the major heap, and continuously calling Gc.major_slice, the gc gets into a state where it stops collecting.

The attached test exposes the problem, and results in OOM after a while.

Removing the call to Gc.major_slice, or extending the test to do allocations on the minor heap avoids the gc stall, and memory pressure stabilizes to allow the test to run forever.

## Steps to reproduce

The attached test exposes the problem on 4.06.1 and 4.07-trunk.

## File attachments

- [leak.ml](https://gist.githubusercontent.com/vicuna/1300507f3f0b2e19da29af2e79fd671b/raw/2c92d61348747f060d6b78555c8614365080c056/leak.ml)
- [leak2.ml](https://gist.githubusercontent.com/vicuna/1300507f3f0b2e19da29af2e79fd671b/raw/24525c58b48b00e147b1e8b56fe0a13987ac9931/leak2.ml)

### PR DESCRIPTION
**Pull request by damiendoligez**
The problem in #7813 is that the major GC stays in `Phase_idle` because we do a major slice without first emptying the minor heap.

There are two commits in this fix:
1. change `caml_gc_dispatch` to make sure it always starts the major GC cycle if needed
2. make `caml_gc_major_slice` call `caml_gc_dispatch` (through `caml_do_pending_actions_exn`) if the major GC needs to start a new cycle.

fixes #7813

### CODE REVIEW

File: runtime/gc_ctrl.c [hunk 1]
```diff
@@ -602,10 +602,23 @@ CAMLprim value caml_gc_full_major(value v)
...
+      /* Calls the major GC without passing [v] but the initial slice
+         ignores this parameter anyway. */
+    CAML_EV_END(EV_EXPLICIT_GC_MAJOR_SLICE);
+    caml_raise_if_exception (exn);
+  }else{
+    CAML_EV_BEGIN(EV_EXPLICIT_GC_MAJOR_SLICE);
+    CAMLassert (Is_long (v));
+    caml_major_collection_slice (Long_val (v));
+    CAML_EV_END(EV_EXPLICIT_GC_MAJOR_SLICE);
+  }
```
Comment (jhjourdan) [inline runtime/gc_ctrl.c]: We could factorize a bit:

```suggestion
  value exn = Val_unit;
  CAML_EV_BEGIN(EV_EXPLICIT_GC_MAJOR_SLICE);
  CAMLassert (Is_long (v));
  if (caml_gc_phase == Phase_idle){
    /* We need to start a new major GC cycle. Go through the pending_action
       machinery. */
    caml_request_major_slice ();
    exn = caml_process_pending_actions_exn ();
      /* Calls the major GC without passing [v] but the initial slice
         ignores this parameter anyway. */
  }else caml_major_collection_slice (Long_val (v));
  CAML_EV_END(EV_EXPLICIT_GC_MAJOR_SLICE);
  caml_raise_if_exception (exn);
```

File: runtime/minor_gc.c [hunk 2]
```diff
@@ -464,34 +464,38 @@ extern uintnat caml_instr_alloc_jump;
...
     caml_instr_alloc_jump =  0;
   });
 
-  if (trigger == Caml_state->young_alloc_start
-      || Caml_state->requested_minor_gc) {
+  if (Caml_state->young_trigger == Caml_state->young_alloc_start){
     /* The minor heap is full, we must do a minor collection. */
+    Caml_state->requested_minor_gc = 1;
+  }else{
+    Caml_state->requested_major_slice = 1;
```
Comment (jhjourdan) [inline runtime/minor_gc.c:473]:
```suggestion
    /* The minor heap is half-full, do a major GC slice. */
    Caml_state->requested_major_slice = 1;
```

**Review by jhjourdan — APPROVED** [review]
I have two minor remarks, but the changes looks good to me.

**Comment by damiendoligez** [comment]
I've implemented @jhjourdan's suggestions and rebased. Will merge when CI turns green.

**Comment by Octachron** [comment]
Merged and cherry-picked to 4.12 as 90c5897d5ae5423eb4153f .

**Comment by Octachron** [comment]
This PR seems to somehow trigger an error on the Inria CI in the flambda + 32bit mode: the test `test-misc/ephe_infix.ml` segfaults. Any idea on how to fix the issue? Should I revert the PR while waiting for a fix? (cc @shindere)

**Comment by xavierleroy** [comment]
tests/misc/ephe_infix.ml also fails on PowerPC 32 bits with flambda.

Also, tests/misc/weaklifetime.ml fails on mingw32 without flambda, but maybe this is unrelated.

**Comment by Octachron** [comment]
The weaklifetime.ml failure doesn't seem to trigger on 4.12 according to my precheck tests, whereas the `ephe_infix` failures trigger on 4.12 when this PR is included.

**Comment by lthls** [comment]
I've tried to reproduce the problem (to see if it was caused by flambda) and the segfault occurs if and only if the compiler is configured with `--disable-naked-pointers` (whether it is configured with flambda or not is irrelevant).
This is the configuration line I used (on my linux 64-bit computer) to reproduce the problem without flambda:
```
./configure --disable-naked-pointers CC="gcc -m32" AS="as --32" ASPP="gcc -m32 -c" --host i386-linux PARTIALLD="ld -r -melf_i386"
```
The runtime is out of my domain of expertise, but I hope this can help the people who will do the debugging.

**Comment by xavierleroy** [comment]
Indeed, the CI tests flambda + no-naked-pointers at the same time.  Thanks for figuring it out.  Still, this is a 32-bit-only issue, right?

**Comment by lthls** [comment]
Yes, with `./configure --disable-naked-pointers` as configuration the test passes.

**Comment by xavierleroy** [comment]
Something is wrong either with this PR or with the `ephe_infix.ml` test.  If nobody looks into it in the coming days, we will have to revert.

**Comment by xavierleroy** [comment]
I think this PR is innocent.  There's something very incompatible with no-naked-pointers in the implementation of ephemerons, namely function `copy_value` in `runtime/weak.c`.  On the ocaml-linux32 CI machine it causes a write in the code area...  It's amazing it doesn't bomb on more platforms!

**Comment by gasche** [comment]
If I understand correctly, @bobot's PR #9990 is removing all uses of the OCaml functions that use this primitive within the compiler distribution, and deprecating them from the stdlib.

**Comment by xavierleroy** [comment]
I agree this copying business is bad and should go eventually.  #9990 doesn't remove the faulty primitive, it just deprecates it.  So either we remove it now or we merge the PR I'm about to submit so as to patch this copying.

**Comment by xavierleroy** [comment]
See #10054 .

**Comment by dra27** [comment]
Just to confirm that this PR is definitely triggering the sporadic failures of `misc/weaklifetime.ml` which we're seeing on AppVeyor.

So far it only seems to trigger in bytecode (I haven't actually hammered the test in native code, because it's very slow to build). The failure is the assertion on line 45 - it's encountering `gc1 = 17` but `n = 15`.

**Comment by dra27** [comment]
#10054 (as expected) doesn't fix the mingw32 crashes - it's roughly 10% of runs of that test in bytecode are failing, running the test on a loop on my machine (I don't know why the AppVeyor failure rate is so much higher).
