### PR TITLE
Make #directory add directories to the start/left of the load path rather than the end/right

### LINKED ISSUE #10442: 4.12.0 regression for #cd and #use
I found a regression in 4.12.0 when OCaml in "scripting" mode, so to speak. Example below.

First the "project"
```Con
> tree
└── test
    ├── test.ml
    └── version.ml

> cat test/test.ml 
#cd "test"
#directory "."
#use "version.ml"

> cat test/version.ml 
let _ = print_endline Sys.ocaml_version
```
And now to the actual bug.
```Con
> opam switch 4.11.2
> ocaml test/test.ml
4.11.2
> opam switch 4.12.0
> ocaml test/test.ml
File "./test/test.ml", ine 1:
Error: I/O error: test/version.ml: No such file or directory
[2]> 
```

In case it helps, if I move the `test.ml` to parent folder and run `ocaml test.ml` everything runs fine

Attaching the relevant parts of `strace` output 

[strace-4.11.txt](https://github.com/ocaml/ocaml/files/6600678/strace-4.11.txt)
[strace-4.12.txt](https://github.com/ocaml/ocaml/files/6600679/strace-4.12.txt)

### PR DESCRIPTION
**Pull request by dra27**
Prior to #9611, `#directory` in the toplevel effectively added the new directory to the _start_ of the load path. This was consistent with `Dll.add_path` (I think), but the original load path handling was only accidentally the same.

This PR adds a test (which breaks) and then adds a new function for prepending a directory to the load path.

I'm not sure whether the debugger should be doing this as well.

@nojb and I weren't totally sure that this fix is actually the right way to go, but it's slightly easier to discuss this with the change in hand. I think that this is the intuitive behaviour - that `#directory` in the toplevel overrides what the toplevel knew before (as opposed to appending `-I dir` to a call to `ocamlopt` which doesn't). As long as I've read `Dll.add_path` correctly, it's also presently strange that `#directory` adds the directory to the _end_ of the load path and the _beginning_ of the DLL search path!

### CODE REVIEW

File: utils/load_path.ml [hunk 1]
```diff
@@ -96,8 +96,22 @@ let add dir =
...
+   unconditionally added. *)
+let prepend_dir dir =
+  assert (not Config.merlin || Local_store.is_bound ());
+  List.iter
+    (fun base ->
+       let fn = Filename.concat dir.Dir.path base in
+       STbl.replace !files base fn;
+       STbl.replace !files_uncap (String.uncapitalize_ascii base) fn)
+    dir.Dir.files;
+  dirs := dir :: !dirs
```
Comment (nojb) [inline utils/load_path.ml]: Shouldn't `dir` be added to the end of `dirs`? Otherwise theoretically one could get the wrong result when looking up non-basename files (see `find`).

Comment (dra27) [reply utils/load_path.ml]: Thanks for catching that - that appears to be a rebase/committing artefact!

File: utils/load_path.mli [hunk 2]
```diff
@@ -60,7 +60,16 @@ module Dir : sig
       sub-directories of this directory. *)
 end
 
-val add : Dir.t -> unit
+val[@deprecated] add : Dir.t -> unit
```
Comment (nojb) [inline utils/load_path.mli:63]: Is it worth deprecating a function in compiler-libs ? Why not simply remove it ?

Comment (dra27) [reply utils/load_path.mli:63]: Given all the Merlin stuff and everything else I didn't have the courage to do this! I don't have strong opinions on the names at all - `append_dir` / `prepend_dir` seemed to make for a clearer API than `add` and `add_at_start`, for example. The compiler doesn't use `Load_path.append_dir` anyway.

File: utils/load_path.ml [hunk 3]
```diff
@@ -96,8 +96,22 @@ let add dir =
...
+(* Add the directory at the start of load path - so basenames are
+   unconditionally added. *)
+let prepend_dir dir =
+  assert (not Config.merlin || Local_store.is_bound ());
+  List.iter
+    (fun base ->
+       let fn = Filename.concat dir.Dir.path base in
+       STbl.replace !files base fn;
+       STbl.replace !files_uncap (String.uncapitalize_ascii base) fn)
+    dir.Dir.files;
```
Comment (Octachron) [inline utils/load_path.ml]: This part of the code is the same as the first definition of `add`. I would suggest to rename this first `add` function to `prepend_add` to share code.

Comment (dra27) [reply utils/load_path.ml]: Yes, that's much nicer, thanks!

File: testsuite/tests/load_path/test/driver.ml [hunk 4]
```diff
@@ -0,0 +1,4 @@
+#cd "test"
+#remove_directory ""
```
Comment (Octachron) [inline testsuite/tests/load_path/test/driver.ml]: I am not sure what is the purpose of this line? As far as I can see this is a no-op and the test passes without it.

**Comment by Octachron** [comment]
Overall, I agree that it seems simpler for the user to let the last `#dir` directives takes precedence over the previous ones. Restoring compatibility with the behavior before 4.12 is another good point. It might be even a good idea to propagate the bugfix to 4.12.1 too, in order to keep this behavior homogeneous across versions.

File: testsuite/tests/load_path/test/driver.ml (hunk 4 above)
Comment (dra27) [reply testsuite/tests/load_path/test/driver.ml]: I think that may have been an accidental hangover from an earlier version while I was battling a bit to set the repro up in ocamltest! I've removed it - the test both fails before without it and passes after the bug fix.

**Review by Octachron — APPROVED** [review]

**Comment by dra27** [comment]
Thanks, @Octachron - rebased and history tidied. I'll merge with CI and cherry-pick to 4.12 and 4.13
