### PR TITLE
Fix [@deprecated_mutable], which couldn't be triggered.

### LINKED ISSUE #11516: `[@deprecated_mutable]` is broken
The `deprecated_mutable` attribute is currently broken.  For example, the following program does not result in a warning, but did in OCaml 4.09.1:

```ocaml
module M = struct
  type t = { mutable x : int [@deprecated_mutable] }
end

let foo : M.t = {M.x = 5}

let () = foo.M.x <- 42
```

It looks like the check for the warning was accidentally removed in #2127.

I considered making a new PR to fix the warning, which is simple.  But another option is to just remove the attribute - it's been broken since 2019 and nobody seems to have noticed.

### PR DESCRIPTION
**Pull request by ccasin**
This repairs the `deprecated_mutable` attribute, which is currently broken.  For example, the following program does not result in a warning, but did in OCaml 4.09.1:

```ocaml
type t = {mutable x : int [@deprecated_mutable]}

let y : t = {x = 5}

let () = y.x <- 42
```

It looks like the check for the warning was accidentally removed in #2127.  This PR restores the old behavior and adds a corresponding test case.

Fixes #11516.

### CODE REVIEW

File: typing/env.ml [hunk 1]
```diff
@@ -104,6 +104,10 @@ let add_label_usage lu usage =
     lu.lu_mutation <- true;
     lu.lu_construct <- true
 
+let is_mutable_label_usage = function
+  | Mutation -> true
+  | (Projection | Construct | Exported_private | Exported) -> false
```
Comment (nojb) [inline typing/env.ml:109]: I find the name of this function a bit misleading, as it is not about "mutable" labels but about "mutating" labels. One could also inline the function directly in the use site.

**Review by nojb — APPROVED** [review]
LGTM

A second pair of eyes may be useful, eg @lpw25 or @gasche.

File: typing/env.ml (hunk 1 above)
Comment (lpw25) [reply typing/env.ml:109]: (Amusingly, I actually asked Chris to outline this function in the first place)

**Review by Octachron — APPROVED** [review]
The fix looks good to me. Moreover, since this is a simple bug fix, the change should be fine for 5.0 and 4.14.2 (the main change entry should be in the 5.0 section).

**Comment by nojb** [comment]
I took the liberty of amending `Changes`. Once CI passes, planning to merge and cherry-pick to 5.0 and 4.14.

**Comment by nojb** [comment]
Cherry-picked to 5.0 de0a88398b1aef885e8492db80e80710e3e55928
Cherry-picked to 4.14 adcf2cb2c6bea7701d399e7ec8734b55403584a3
