### PR TITLE
typing: fix the scope of extension constructor declarations

### LINKED ISSUE #9970: Typing regression in OCaml 4.11 (and trunk)
```
type 'a t = ..
type 'a t += X of {x: 'a}
let x: 'a. 'a -> 'a t = fun x -> X {x}
```
gives
```
File "/home/nojebar/foo.ml", line 3, characters 36-37:
3 | let x: 'a. 'a -> 'a t = fun x -> X {x}
                                        ^
Error: The record field x belongs to the type 'b X
       but is mixed here with fields of type 'a X
       The type constructor X would escape its scope
```
The issue is present in 4.11 and trunk (works fine in 4.10).

### PR DESCRIPTION
**Pull request by gasche**
fixes #9970 (hopefully?)

I am not completely sure of what I am doing in this PR. I understand that the previous code was broken (see below), and the new code (1) looks reasonable and (2) gets the code of `transl_type_extension` closer to the code of `transl_declaration`, which I think is desirable.

(Reviewing this is for @garrigue, @trefis, @lpw25.)

Below: here is an example of what gets very wrong before this PR, and works fine after this PR. The example only describes what happens (incorrectly) before the PR. This is copied from https://github.com/ocaml/ocaml/issues/9970#issuecomment-723597231

```
# type _ t = ..;;
# type 'a t += X of {x : 'a};;
# X {x = 1};;
Error: The record field x belongs to the type 'a X
       but is mixed here with fields of type 'b X
       The type constructor X would escape its scope
# X {x = 1};;
- : int t = X {x = <poly>}
```

What happens:
- `Typedecl.transl_extension_constructor` creates a new scope for X.
  (In my debug runs, X has scope 3.)
- Then the following toplevel phrase runs at a level below the scope of X. It therefore builds type that are ill-scoped
  (In my debug runs, a Tconstr(X, ...) at level 2).
- When a phrase fails to type-check in the toplevel, the current level is not reset to its previous level.
  The following phrase thus starts with a higher level, higher than the scope of X, so there is no scope escape anymore.
  (In my debug runs, at level 5)

### CODE REVIEW

**Review by trefis — DISMISSED** [review]
I think what you say in https://github.com/ocaml/ocaml/issues/9970#issuecomment-723606087 is correct:
> the scope should be declared outside the `begin_def..end_def` block.

This fix looks reasonable to me.

**Comment by trefis** [comment]
(The "have you checked" part was me starting to ask a question, then looking for myself, deciding everything's fine, and finally forgetting to remove that part of my message before sending it. Oops!)

**Comment by gasche** [comment]
If we assume that technically this is okay (I'm waiting a bit to see if other knowledgeable people have comment), there is a question of which releases this should go in.

In #9970 it was reported that the bug bites Lexifi's codebase in 4.11, in conjunction with the change to type-checking of type annotations in let-binding. With our new understanding of the problem it is clear that annotations are not related to the issue. But I think that the body of annotated let-bindings is now checked at a lower level than it was in the past, which explains the relation. Finally, we don't have a bugfix release of 4.11 planned.

I think that this suggests having the fix in 4.12 and trunk, but it is not clear that it needs to go in earlier branches. (It is a problem that was present as far as 4.08.) Maybe @nojb can comment if a backport in the upstream 4.11 branch would be useful to Lexifi.

**Comment by yallop** [comment]
It would be useful to have a clear description of exactly what the behaviour is supposed to be, because it's changed several times in recent versions, and this patch appears to change it again.  Here's the code from #9970, plus one extra definition without an annotation:

```ocaml
type 'a t = ..
type 'a t += X of {x: 'a}
let x: 'a. 'a -> 'a t = fun x -> X {x}
let y = fun x -> X {x}
```

In 4.07, both `x` and `y` are accepted and given polymorphic types.

In 4.10.0, `x` is accepted, but `y` is rejected ("The type constructor X would escape its scope"), but `y` is accepted with a polymorphic type on the second attempt in the REPL.

In 4.11.1, both `x` and `y` are rejected ("The type constructor X would escape its scope"), but `y` is accepted with a polymorphic type on the second attempt in the REPL.

With this patch `x` is rejected and `y` is accepted with a weak type.

I don't understand why the syntactic value `y` should have a weak type.

**Comment by trefis** [comment]
This:
> In 4.11.0, both x and y are rejected ("The type constructor X would escape its scope"), but y is accepted with a polymorphic type on the second attempt in the REPL.

is explained by:
> When a phrase fails to type-check in the toplevel, the current level is not reset to its previous level.

And while this could be changed, there isn't any reason to (apart from: "it would be cleaner"). I believe it's perfectly admissible to raise the current level to an arbitrary number, and that it shouldn't have an impact on which things are allowed to typecheck.

**Comment by trefis** [comment]
Note:
- I cannot comment on the other points raised by @yallop at the moment.
- I still believe this PR, which only touches the typing of extension *declarations*, to be correct.

**Comment by yallop** [comment]
@trefis: in case it wasn't clear, I think that the 4.07.0 behaviour for `x` and `y` was correct and all the variations that have followed are incorrect.

While this PR may be correct in some sense, it doesn't completely fix #9970, so we shouldn't autoclose #9970 by merging this PR.

**Comment by nojb** [comment]
> While this PR may be correct in some sense, it doesn't completely fix #9970, so we shouldn't autoclose #9970 by merging this PR.

I confirm this. For the code at the origin of #9970, this PR is not enough because it doesn't give `x`  a fully polymorphic type.

**Comment by gasche** [comment]
I agree with @yallop's analysis, there are further issues to fix here. Hopefully this PR is a good (independent) first step in this direction. (There is little used trying to fix the issue without it, because without the fix the type-checker will build ill-scoped types which may prevent observing other issues by breaking in various ways.)

**Comment by gasche** [comment]
After tinkering with the bug more, I think my previous assessment was not quite right: moving the identifier scope outside the `def` block had a an impact on the level of the declaration type parameters, that ended up non-generic, which prevents the generalization in the `fun x -> X x` example.

I have a pushed a second commit that fixes the issue by moving `reset_type_variables` inside the def block (so at a younger level than the scope creation). I observe that the type parameters are generalized again, and the issue appears to be fixed, but once again I don't really understand what this is doing (for example what `reset_type_variables` is doing in the first place).

The new commit moves `reset_type_variables` one block younger than `create_scope`, but it then creates a new `def` block to create the type parameters and translate the extension constructor. In my testing, this new def block was not necessary (those three examples work fine without), but non-extension constructor declarations are done in this way, so I thought that it was more prudent to reflect this structure.

P.S.: when hunting this bug I have observed types that appear to break very basic invariants of the type system: ill-scoped types passed around, but also type declarations whose (non-constrained) type parameters cannot be generalized. I wonder if we should invest in some basic "debug assert" to write these invariants in code, and make it easier to hunt these bugs by blowing up earlier when in "debug the type-checker" mode.

**Comment by nojb** [comment]
> I think that this suggests having the fix in 4.12 and trunk, but it is not clear that it needs to go in earlier branches. (It is a problem that was present as far as 4.08.) Maybe @nojb can comment if a backport in the upstream 4.11 branch would be useful to Lexifi.

I have tried the latest version of your fix and indeed it seems to resolve the problem in our codebase. As for backporting, it is not an issue for us since we can easily cherry-pick this ourselves to 4.11.

Having said that, what is the argument against backporting this to 4.08, 4.09, 4.10 and 4.11 (apart from the drudgery involved)?

**Comment by gasche** [comment]
Indeed, it would be fine to backport widely -- once we have a fix that we trust to be right. I am less confident in the second part of the fix than in the first, so we really need additional reviews and analysis.

**Comment by gasche** [comment]
@garrigue would you by chance be able to look at this, and give an opinion on the fix?

File: typing/typedecl.ml [hunk 1]
```diff
@@ -1072,7 +1071,7 @@ let is_rebind ext =
   | Text_decl _ -> false
 
 let transl_type_extension extend env loc styext =
-  reset_type_variables();
+  let scope = Ctype.create_scope () in
   Ctype.begin_def();
```
Comment (lpw25) [inline typing/typedecl.ml:1078]: You should remove this `begin_def`

File: typing/typedecl.ml [hunk 2]
```diff
@@ -1118,17 +1117,20 @@ let transl_type_extension extend env loc styext =
...
     type_params;
   let constructors =
-    List.map (transl_extension_constructor env type_path
+    List.map (transl_extension_constructor ~scope env type_path
                type_decl.type_params type_params styext.ptyext_private)
       styext.ptyext_constructors
   in
-  Ctype.end_def();
+  Ctype.end_def ();
+  Ctype.end_def ();
```
Comment (lpw25) [inline typing/typedecl.ml]: You should remove one of these `end_def`s

**Review by lpw25 — CHANGES_REQUESTED** [review]
I think this is nearly right now. You are doing some unnecessary `begin_def`/`end_defs` which you should remove.

The problem with your first attempt was that it inserted the `create_scope` between the `reset_global_variables` and the `begin_def`, which would give type variables a level that could not be generalised. The `reset_global_variables` interface is quite fragile -- it says that type variables should be created at the *next* level opened, so you need to make sure that you call `begin_def` straight after it.

**Comment by gasche** [comment]
@lpw25 many thanks for the review. I took your comments into account, and the result is a simpler patch that still passes the testsuite. However, I'm not sure I understand. The diff between the previous (incorrect) version and the current (more correct) version is the following:

```diff
 let transl_type_extension extend env loc styext =
-  reset_type_variables();
   let scope = Ctype.create_scope () in
-  Ctype.begin_def();
   let type_path, type_decl =
     let lid = styext.ptyext_path in
     Env.lookup_type ~loc:lid.loc lid.txt env
   in
   begin
     match type_decl.type_kind with
     | Type_open -> begin
         match type_decl.type_private with
         | Private when extend -> begin
             match
               List.find
                 (function {pext_kind = Pext_decl _} -> true
                         | {pext_kind = Pext_rebind _} -> false)
                 styext.ptyext_constructors
             with
             | {pext_loc} ->
                 raise (Error(pext_loc, Cannot_extend_private_type type_path))
             | exception Not_found -> ()
           end
         | _ -> ()
       end
     | _ ->
         raise (Error(loc, Not_extensible_type type_path))
   end;
   let type_variance =
     List.map (fun v ->
                 let (co, cn) = Variance.get_upper v in
                   (not cn, not co, false))
              type_decl.type_variance
   in
   let err =
     if type_decl.type_arity <> List.length styext.ptyext_params then
       Some Includecore.Arity
     else
       if List.for_all2
            (fun (c1, n1, _) (c2, n2, _) -> (not c2 || c1) && (not n2 || n1))
            type_variance
            (Typedecl_variance.variance_of_params styext.ptyext_params)
       then None else Some Includecore.Variance
   in
   begin match err with
   | None -> ()
   | Some err -> raise (Error(loc, Extension_mismatch (type_path, err)))
   end;
+  reset_type_variables();
+  Ctype.begin_def();
   let ttype_params = make_params env styext.ptyext_params in
   [...]
```

My assumption is that none of the garbage in the middle is influenced by `create_scope`, `reset_type_variables` or `begin_def`, and that the only difference between the two versions is the respective ordering of `reset_type_variables` and `create_scope` (`begin_def` is in the same position, at the end, in the two versions). You mention that `reset_type_variables` should be called immediately before `begin_def`, so I'm assuming that the error was to call `create_scope` in the middle? (I changed the implementation of `transl_exception` to create the scope before resetting type variables.)

**Comment by lpw25** [comment]
> My assumption is that none of the garbage in the middle is influenced by create_scope, reset_type_variables or begin_def, and that the only difference between the two versions is the respective ordering of reset_type_variables and create_scope (begin_def is in the same position, at the end, in the two versions). You mention that reset_type_variables should be called immediately before begin_def, so I'm assuming that the error was to call create_scope in the middle?

Correct

**Review by lpw25 — APPROVED** [review]

**Comment by gasche** [comment]
I changed the diff slightly to make it more minimal, and added a comment about the fact that the ordering matters.

**Comment by gasche** [comment]
Merged, and cherry-picked in 4.12 as b3f4fc7cb311aa6429a4eb19b6a5711b8a8c6b9d . Thanks @trefis and @lpw25 for your reviews.

**Comment by gasche** [comment]
I was too lazy to cherry-pick in older releases so far, but I just cherry-picked in 4.11 in reaction to the now-widely-popular rumor that a new minor release might occur.

**Comment by Octachron** [comment]
@gasche, it seems that you only have cherry-picked this fix on your 4.11 branch, is that intentional?

**Comment by gasche** [comment]
Thanks! I indeed forgot to push after running the testsuite locally. Done now.
