### PR TITLE
ocamldoc: fix the printing of (::)

### LINKED ISSUE #9421: Ocamldoc is rendering list variant constructors without parentheses
See e.g. https://caml.inria.fr/pub/docs/manual-ocaml/libref/List.html

```ocaml
type 'a t = 'a list =
| []
| :: of 'a * 'a list
```

This is syntactically incorrect, the expected output rendering is:

```ocaml
type 'a t = 'a list =
| ([])
| (::) of 'a * 'a list
```

### PR DESCRIPTION
**Pull request by Octachron**
Currently,
```ocaml
type t = (::)
```
is printed by ocamldoc as
```ocaml
type t = ::
```
This small PR fixes this issue in all ocamldoc backends by using directly `(::)` in the ocamldoc description of variant constructors.

Closes #9421 .

(There is no parentheses needed for the four other non-UIDENT constructors: true, false, [] and () )

### CODE REVIEW

File: ocamldoc/odoc_sig.ml [hunk 1]
```diff
@@ -391,8 +391,13 @@ module Analyser =
               | Cstr_record l ->
                   Cstr_record (List.map (get_field env name_comment_list) l)
             in
+            let vc_name = match constructor_name with
+              | "::" ->
+                  (* The only infix constructor is always printed (::) *)
+                  "(::)"
+              | s -> s in
```
Comment (yawaramin) [inline ocamldoc/odoc_sig.ml]: Slight formatting quibble, it looks like `in` is usually on its own line for multi-line bindings...

**Review by yawaramin — APPROVED** [review]

File: ocamldoc/odoc_sig.ml (hunk 1 above)
Comment (damiendoligez) [reply ocamldoc/odoc_sig.ml]: Indeed, and it's the style used right above this let-binding.
```suggestion
              | s -> s
            in
```

**Review by damiendoligez — APPROVED** [review]
Looks good to me, modulo the formatting nitpick.

File: ocamldoc/odoc_sig.ml (hunk 1 above)
Comment (Octachron) [reply ocamldoc/odoc_sig.ml]: Fixed.
