### PR TITLE
Fix #14200 (without breaking pr7321_ok.ml)

### LINKED ISSUE #14200: Bad variance check with private aliases
Given a module `M` with this signature:
```ocaml
sig
  type 'a t = private string
  type foo = private int
  type bar = private int
  val foo : foo t
end
```
then I think I should not be able to construct an `M.bar M.t`, since I only have an `M.foo M.t` and `M.foo` and `M.bar` are different private types. Indeed, attempting to do so directly with `(M.foo :> M.bar t)` fails.

However, it is possible to do so:
```ocaml
module Coerce : sig
  type +'a pos = private string
  type -'a neg = private string

  val p : 'a M.t -> 'a pos
  val pn : 'a pos -> 'a neg
  val n : 'a neg -> 'a M.t
end = struct
  type 'a pos = 'a M.t
  type 'a neg = 'a M.t

  let p = Fun.id
  let pn = Fun.id
  let n = Fun.id
end

let bar : M.bar M.t =
  M.foo
  |> Coerce.p
  |> (fun t -> (t :> int Coerce.pos))
  |> Coerce.pn
  |> (fun t -> (t :> M.bar Coerce.neg))
  |> Coerce.n
```

I think the module `Coerce` should not be accepted, as it adds dubious variance markers not present in the signature of M. (Notably, the variance markers are rejected if placed in the `struct` instead of the `sig`. I think variance is being checked against the signature right-hand-side only, but should be checked against the structure right-hand-side as well)

### PR DESCRIPTION
**Pull request by garrigue**
This fixes #14200 by checking that types exported as private keep the same variance as their internal definition.

This was supposed to be as simple as switching two lines, handling such types the same way as abstract types, but this actually breaks `typing-module-bugs/pr7321_ok.ml`.
The problem is that the lower bound side of variance is inferred for private types, and it may not match the one obtained as the result of a functor application.
So we should only check the upper-bound side of the variance, and just accept the inferred variance for the lower-bound side.

Note: this should at least go in 5.4, so I put the change log there.
This is not a strict unsoundness, as it only allows to change the variance given by the user, not the one inferred from the definition. But this is still serious, as phantom parameters used to encode some safety property may be ignored.

### CODE REVIEW

File: typing/includecore.ml [hunk 1]
```diff
@@ -1039,21 +1039,35 @@ let type_declarations ?(equality = false) ~loc env ~mark name
...
         let (co1,cn1) = get_upper v1 and (co2,cn2) = get_upper v2 in
-        (if abstr then (imp co1 co2 && imp cn1 cn2)
+        (if abstr' then (imp co1 co2 && imp cn1 cn2)
          else if opn || constrained ty then (co1 = co2 && cn1 = cn2)
          else true) &&
         let (p1,n1,j1) = get_lower v1 and (p2,n2,j2) = get_lower v2 in
+        (* Only check the lower bound for abstract types.
+           For private types, the lower bound can be inferred, and
+           the internal one may be wrong in the result of functors. *)
         imp abstr (imp p2 p1 && imp n2 n1 && imp j2 j1))
```
Comment (garrigue) [inline typing/includecore.ml:1071]: There is no specific need to change this line, but for an abstract type `p2` and `n2` are always false, so that checking `j2` would be sufficient.

**Review by stedolan — APPROVED** [review]
Looks good to me, thanks for the quick fix!

**Comment by garrigue** [comment]
Thank you for the review.

**Comment by garrigue** [comment]
Cherry-picked to 5.4 branch.
