### PR TITLE
Don't apply local function optimisation for Tupled functions (fixes #8705)

### LINKED ISSUE #8705: Native code segfault with 4.08
We've noticed that the [Lem specification tool](https://github.com/rems-project/lem) segfaults with the 4.08.0+rc1 compiler, when the build first tries to run the generated executable on Lem's standard library.  It only appears to happen for native code (testing with 64-bit and 32-bit x86 Linux), and bisecting suggests that commit 9b27a9c75ec4c76a7d9e440de29c203666ea6a28 introduces the problem.  Indeed, if I revert that commit in 4.08.0+rc1 Lem runs without faulting.

The top of the stack trace isn't terribly revealing:
```
#0  0x00005555558454c7 in camlStdlib__map__mapi_284 () at map.ml:306
#1  0x00005555558454d8 in camlStdlib__map__mapi_284 () at map.ml:310
#2  0x00005555557f70af in camlTyped_ast__exp_to_free_2768 () at finite_map.ml:111
#3  0x0000555555784d34 in camlPatterns__mk_opt_let_exp_1686 () at patterns.ml:1044
```
The call to `mapi` in the `exp_to_free` function is [here](https://github.com/rems-project/lem/blob/master/src/typed_ast.ml#L1273).  From experimenting with a large minor heap using `OCAMLRUNPARAM` and reducing the input size a bit it seems that the problem can be triggered without any GC activity.

If you want to try reproducing this, only ocaml, ocamlbuild and lem are needed.  Lem's other dependencies are only used later in the build process.

### PR DESCRIPTION
**Pull request by mshinwell**
The local function optimisation from #2143 appears to contain a bug, as seen in #8705, which causes arguments to be passed incorrectly when the function is of `Tupled` kind.

The symptom in this particular case was the "list" argument to `mapi` containing a code pointer to one of the `caml_curry` functions.

As far as I understand it, `Tupled` functions appear from their `params` to have arity greater than one.  However in fact all of these parameters are passed within a single block; code is generated later in the compiler to project them out before binding the parameter variables themselves.  (This is made explicit on the way into Flambda, in fact, which generates the appropriate wrapper functions.)

I think the optimisation goes wrong when the arity of a function application, of a `Tupled` function, has N arguments where N is two or more.  This should be treated as an over-application, but instead, each of the N arguments get bound to the variables corresponding to the parameters.  This is wrong because those parameters, as above, should instead contain values projected from the first argument.

The following is what the optimisation did to a piece of code in Lem:
```diff
 (let
   (extended_exp_to_exp/1388 =
      (function (param/3996, param/3997, param/3998)
        (let
          (l_org/1391 =
             (apply (field 21 (global Typed_ast!)) param/3998)
           l/1392 =
             (makeblock 0 1a "extended_exp_to_exp"
               (makeblock 0 l_org/1391))
-          new_sub/1393 =
-            (function n/1394 m/1395
-              (makeblock 0 (field 1 (field 7 (global Types!)))
-                (apply (field 5 (field 1 (global Typed_ast!)))
-                  (field 1 (field 1 (global Typed_ast!)))
-                  (makeblock 0 n/1394 (makeblock 1 m/1395)))))
-          sub_fun/1396 =
-            (function (param/4000, param/4001)
-              (apply (field 0 (field 23 (global Patterns!)))
-                (apply new_sub/1393 param/4000 param/4001)))
           modify_fun/1400 =
             (function param/1405 e2/1403
               (let
                 (e/1402 =a (field 1 param/1405)
                  n/1401 =a (field 0 param/1405)
                  *match*/3999 =
                    (apply (field 43 (global Typed_ast_syntax!)) e/1402))
                 (if *match*/3999
-                  (apply sub_fun/1396
+                  (let
+                    (param/5169 =
-                    (makeblock 0 n/1401 (field 0 *match*/3999))
-                    e2/1403)
+                       (makeblock 0 n/1401 (field 0 *match*/3999)))
+                    (apply (field 0 (field 23 (global Patterns!)))
+                      (makeblock 0 (field 1 (field 7 (global Types!)))
+                        (apply (field 5 (field 1 (global Typed_ast!)))
+                          (field 1 (field 1 (global Typed_ast!)))
+                          (makeblock 0 param/5169
+                            (makeblock 1 e2/1403))))))
                   (apply (field 79 (global Typed_ast_syntax!)) l/1392
                     (makeblock 0 n/1401 e/1402) e2/1403)))))
          (apply (field 21 (global Stdlib__list!)) modify_fun/1400
            param/3997 param/3998))))
   (setfield_ptr(root-init) 55 (global Patterns!)
     extended_exp_to_exp/1388))
```
The fix takes the most straightforward approach, namely disabling this optimisation for `Tupled` functions.

I have tested a previous version of this patch (the same except for cosmetic details) on Lem but would be pleased if someone (maybe @bacam) could independently verify.

Marked as no-change-entry needed since this will presumably end up on the same branch (4.08) as the code introducing this feature.

### CODE REVIEW

**Comment by damiendoligez** [comment]
cc @alainfrisch

**Comment by gasche** [comment]
For the record, the [source code](https://github.com/rems-project/lem/blob/d206b93/src/patterns.ml#L330-L342) for @mshinwell's example is as follows:

```ocaml
let extended_exp_to_exp ((_, let_list, exp):pat_matrix_ext_exp) : exp =
  let l_org = exp_to_locn exp in
  let l = Ast.Trans (true, "extended_exp_to_exp", Some l_org) in
  let new_sub n m = (Types.TNfmap.empty, Nfmap.insert Nfmap.empty (n, Sub_rename m)) in
  let sub_fun ((n : Name.t), (en : Name.t)) = (C_no_types.exp_subst (new_sub n en)) in

  let modify_fun (n, e) e2 =
     match dest_var_exp e with
       None -> mk_let_exp l (n, e) e2
     | Some en -> sub_fun (n, en) e2 in

  let r = List.fold_right modify_fun let_list exp in
  r
```

I would like to write a smaller repro case to have in the compiler testsuite, so that future attempts to improve this would fail on the same bug.

**Comment by mshinwell** [comment]
I will try to write a reproduction case.

**Comment by gasche** [comment]
Here is a repro case:

```ocaml
let test x =
  let tupled (x, y) = (); fun () -> [|x; y|] in
  match x with
  | None -> [| |]
  | Some (x, y) -> tupled (x, y) ()

let () = print_endline (test (Some ("Hello ", "World!"))).(0)
```

**Comment by mshinwell** [comment]
I have a more straightforward test case, but I've added (a slightly modified version of) @gasche 's one too.

**Comment by mshinwell** [comment]
This fix is probably appropriate for 4.08 and 4.09 but we should probably fix the handling of `Tupled` functions so the optimisation applies in trunk.

File: bytecomp/simplif.ml [hunk 1]
```diff
@@ -794,7 +795,9 @@ let simplify_local_functions lam =
     | Lvar id ->
         Hashtbl.remove slots id
     | Lfunction lf as lam ->
-        check_static lf;
+        if Lambda.function_is_curried lf then begin
```
Comment (alainfrisch) [inline bytecomp/simplif.ml]: I think this chunk is wrong: it removes the warning telling the user that the optimization doesn't apply even though it was requested (and precisely, if the function is tupled, the optimization does not trigger and this should be reported as such).

**Comment by alainfrisch** [comment]
Thanks @mshinwell for looking at it, and sorry for the oversight.  The fix looks correct (but see my inline comment).

I'm not sure it's worth adding extra logic to adapt the optimization to the tupled case, which is not a common idiom I believe.

**Comment by bacam** [comment]
Thanks, I've been able to build a working copy of Lem with these changes.

File: bytecomp/simplif.ml [hunk 2]
```diff
@@ -754,7 +754,8 @@ let simplify_local_functions lam =
       -> false
   in
   let rec tail = function
-    | Llet (_str, _kind, id, Lfunction lf, cont) when enabled lf.attr ->
+    | Llet (_str, _kind, id, Lfunction lf, cont)
+      when Lambda.function_is_curried lf && enabled lf.attr ->
```
Comment (alainfrisch) [inline bytecomp/simplif.ml:758]: Since that's the only use of  Lambda.function_is_curried that would remain after the other note is taken into account, this could just be:
````ocaml
 | Llet (_str, _kind, id, Lfunction ({kind=Curried} as lf), cont) when enabled lf.attr ->
````
(avoiding the need to define Lambda.function_is_curried)

File: bytecomp/simplif.ml (hunk 1 above)
Comment (mshinwell) [reply bytecomp/simplif.ml]: Fixed

File: bytecomp/simplif.ml (hunk 2 above)
Comment (mshinwell) [reply bytecomp/simplif.ml:758]: True, but I generally favour the "accessor" style here (it would ease any future attempt at adding more abstraction, for example).

**Comment by gasche** [comment]
I just wrote the code to optimize the tupled case to understand how it would go, and I found an optimization issue for constant blocks -- that also prevents other Simplif optimizations, such as elimination of beta-redexes, from firing.

```ocaml
let test_optimized () =
 (fun (x,y) ->x+y) (1+2, 4)

let test_not_optimized () =
 (fun (x,y) ->x+y) (3, 4)
```

See #8707 for a fix that includes recognition of constant blocks.

**Comment by gasche** [comment]
For the record, here is the patch to fix the optimization in the Curried case:

```diff
diff --git a/bytecomp/simplif.ml b/bytecomp/simplif.ml
index 9ac1bf5406..e5bbc4d457 100644
--- a/bytecomp/simplif.ml
+++ b/bytecomp/simplif.ml
@@ -317,6 +317,21 @@ let simplify_exits lam =
    Assumes |args| = |params|.
 *)
 
+let exact_application {kind; params; _} args =
+  match kind with
+  | Curried ->
+      if List.length params <> List.length args
+      then None
+      else Some args
+  | Tupled ->
+      begin match args with
+      | [Lprim(Pmakeblock _, tupled_args, _)] ->
+          if List.length params <> List.length tupled_args
+          then None
+          else Some tupled_args
+      | _ -> None
+      end
+
 let beta_reduce params body args =
   List.fold_left2 (fun l (param, kind) arg -> Llet(Strict, kind, param, arg, l))
                   body params args
@@ -721,7 +742,7 @@ module Hooks = Misc.MakeHooks(struct
 
 type slot =
   {
-    nargs: int;
+    func: lfunction;
     mutable scope: lambda option;
   }
 
@@ -755,7 +776,7 @@ let simplify_local_functions lam =
   in
   let rec tail = function
     | Llet (_str, _kind, id, Lfunction lf, cont) when enabled lf.attr ->
-        let r = {nargs=List.length lf.params; scope=None} in
+        let r = {func = lf; scope = None} in
         Hashtbl.add slots id r;
         tail cont;
         begin match Hashtbl.find_opt slots id with
@@ -778,7 +799,8 @@ let simplify_local_functions lam =
         end
     | Lapply {ap_func = Lvar id; ap_args; _} ->
         begin match Hashtbl.find_opt slots id with
-        | Some {nargs; _} when nargs <> List.length ap_args ->
+        | Some {func; _}
+          when exact_application func ap_args = None ->
             (* Wrong arity *)
             Hashtbl.remove slots id
         | Some {scope = Some scope; _} when scope != !current_scope ->
@@ -813,7 +835,14 @@ let simplify_local_functions lam =
       | Llet (_, _, id, _, cont) when Hashtbl.mem static_id id ->
           rewrite cont
       | Lapply {ap_func = Lvar id; ap_args; _} when Hashtbl.mem static_id id ->
-          Lstaticraise (Hashtbl.find static_id id, List.map rewrite ap_args)
+          begin
+            let st = Hashtbl.find static_id id in
+            let slot = Hashtbl.find slots id in
+            match exact_application slot.func ap_args with
+            | None -> assert false
+            | Some exact_args ->
+                Lstaticraise (st, List.map rewrite exact_args)
+          end
       | lam ->
           Lambda.shallow_map rewrite lam
     in
```

**Comment by alainfrisch** [comment]
> if an argument tuple has only constant members, then it will have been replaced by a constant name

At the Lambda level, that would be a `Const_block`, not a name, right?  It wouldn't be too hard to handle this case in addition to `Pmakeblock`.

**Comment by gasche** [comment]
Good point! I moved the code (enhanced with your proposal) to a new PR for trunk only ( #8707 ), so that we can focus on the safest release-branch fix in the present discussion. (I will edit my comments above to remove the not-for-4.08 bits when that makes sense.)

**Comment by alainfrisch** [comment]
@damiendoligez : What's the protocol fpr cherry-picking to 4.09 and trunk?  Should we open other PRs?  (I don't seem to be able to push directly to either branch.)

**Comment by gasche** [comment]
Pushing cherry-picks directly is fine, and you should have the privileges to do it. Are you sure that you started from an up-to-date version of the branch?

**Comment by alainfrisch** [comment]
Ok, thanks.  (I was using an https:// URL for the repo.  With the git:// URL, I managed to push.)
