### PR TITLE
Dynamically allocate the alternate signal stack

### LINKED ISSUE #10250: 4.11.2: build fails with glibc 2.34
```
[tkloczko@barrel ocaml-4.11.2]$ make
make coldstart
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make -C runtime  all
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/runtime'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/runtime'
cp runtime/ocamlrun boot/ocamlrun
make -C stdlib  \
  CAMLC='$(BOOT_OCAMLC) -use-prims ../runtime/primitives' all
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/stdlib'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/stdlib'
cd stdlib; cp stdlib.cma std_exit.cmo *.cmi camlheader ../boot
cd boot; ln -sf ../runtime/libcamlrun.a .
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make opt.opt
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make checkstack
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
if /usr/bin/gcc -O2 -fno-strict-aliasing -fwrapv -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -Wall -Wdeclaration-after-statement -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE  -Wl,-E -o tools/checkstack tools/checkstack.c; \
  then tools/checkstack; \
fi
rm -f tools/checkstack
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make runtime
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make -C runtime  all
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/runtime'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/runtime'
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make core
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make coldstart
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make -C runtime  all
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/runtime'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/runtime'
cp runtime/ocamlrun boot/ocamlrun
make -C stdlib  \
  CAMLC='$(BOOT_OCAMLC) -use-prims ../runtime/primitives' all
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/stdlib'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/stdlib'
cd stdlib; cp stdlib.cma std_exit.cmo *.cmi camlheader ../boot
cd boot; ln -sf ../runtime/libcamlrun.a .
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make coreall
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make -C runtime  all
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/runtime'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/runtime'
make ocamlc
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make[4]: 'ocamlc' is up to date.
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make ocamllex ocamltools library
make[4]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make -C yacc  all
make[5]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/yacc'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/yacc'
make -C lex all
make[5]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/lex'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/lex'
make -C tools all
make[5]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/tools'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/tools'
make -C stdlib  all
make[5]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/stdlib'
make[5]: Nothing to be done for 'all'.
make[5]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/stdlib'
make[4]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make[3]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make ocaml
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make[2]: 'ocaml' is up to date.
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make opt-core
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2'
make -C runtime  allopt
make[3]: Entering directory '/home/tkloczko/rpmbuild/BUILD/ocaml-4.11.2/runtime'
/usr/bin/gcc -c -O2 -fno-strict-aliasing -fwrapv -O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -Wall -Wdeclaration-after-statement -fno-common -fexcess-precision=standard -fno-tree-vrp -ffunction-sections -g -D_FILE_OFFSET_BITS=64 -D_REENTRANT -DCAML_NAME_SPACE   -DNATIVE_CODE -DTARGET_amd64 -DMODEL_default -DSYS_linux   -o signals_nat_n.o signals_nat.c
signals_nat.c:198:13: error: variably modified ‘sig_alt_stack’ at file scope
  198 | static char sig_alt_stack[SIGSTKSZ];
      |             ^~~~~~~~~~~~~
make[3]: *** [Makefile:344: signals_nat_n.o] Error 1
```

### PR DESCRIPTION
**Pull request by xavierleroy**
In Glibc 2.34 and later, `SIGSTKSZ` may not be a compile-time constant. It is no longer possible to statically allocate the alternate signal stack for the main thread, as we've been doing for the last 25 years.

This PR implements dynamic allocation of the alternate signal stack even for the main thread.  It reuses the code already in place to allocate the alternate signal stack for other threads.

Fixes: #10250.

### CODE REVIEW

**Comment by rwmjones** [comment]
I built this version on Fedora Rawhide (which has the new glibc) and it all looks good:
```
Summary:
  2857 tests passed
   38 tests skipped
    0 tests failed
   97 tests not started (parent test skipped or failed)
    0 unexpected errors
  2992 tests considered
```

File: runtime/signals_nat.c [hunk 1]
```diff
@@ -269,28 +267,33 @@ void caml_init_signals(void)
...
 {
 #ifdef HAS_STACK_OVERFLOW_DETECTION
   stack_t stk;
   stk.ss_sp = malloc(SIGSTKSZ);
+  if (stk.ss_sp == NULL) return -1;
   stk.ss_size = SIGSTKSZ;
   stk.ss_flags = 0;
-  if (stk.ss_sp)
-    sigaltstack(&stk, NULL);
+  return sigaltstack(&stk, NULL);
```
Comment (avsm) [inline runtime/signals_nat.c:295]: This can now return ENOMEM under two circumstances -- either the malloc failing or the sigaltstack call failing (and the latter should never happen since SIGSTKSZ should never be < MINSIGSTKSZ).  That seems right.

Do we need to adjust the invocation of caml_setup_stack_overflow_detection() in otherlibs/systhreads/st_stubs.c:caml_thread_start to do something in the event of it returning -1?

File: runtime/signals_nat.c [hunk 2]
```diff
@@ -269,28 +267,33 @@ void caml_init_signals(void)
...
   }
 #endif
 }
 
-CAMLexport void caml_setup_stack_overflow_detection(void)
+/* Allocate and select an alternate stack for handling signals,
+   especially SIGSEGV signals.
+   Each thread needs its own alternate stack.
+   The alternate stack used to be statically-allocated for the main thread,
+   but this is incompatible with Glibc 2.34 and never, where SIGSTKSZ
```
Comment (Octachron) [inline runtime/signals_nat.c]: `and never,` ⇒ `and newer,`

File: runtime/signals_nat.c (hunk 1 above)
Comment (xavierleroy) [reply runtime/signals_nat.c:295]: > Do we need to adjust the invocation of caml_setup_stack_overflow_detection() in otherlibs/systhreads/st_stubs.c:caml_thread_start to do something in the event of it returning -1?

Perhaps... but I'm not sure what to do!  
1. We could abort the whole program, of course.  That's not very subtle.
2. Or we could disable the handling of SIGSEGV and disable the alternate stack in the new thread, so that it uses its system stack for signal handling, but not the alternate stack of the thread that created it.  Other threads would still use their own alternate stacks.  That's no longer necessary (if we no longer catch SIGSEGV) but safe.

File: runtime/signals_nat.c (hunk 2 above)
Comment (xavierleroy) [reply runtime/signals_nat.c]: Never say newer!  Fixed.

File: runtime/signals_nat.c (hunk 1 above)
Comment (stedolan) [reply runtime/signals_nat.c:295]: How about doing this?
```c
caml_thread_uncaught_exception(caml_exn_Out_of_memory);
```
It prints a message and aborts the thread, but more importantly it does the same thing as any other out-of-memory error happening on that thread.

(If you're feeling particularly keen, you could also allocate the alt stack in the parent thread during `caml_thread_new` where `caml_raise_out_of_memory()` is a reasonable thing to do and pass it down via the `caml_thread_t`. I'm not sure it's worth it, though)

Comment (avsm) [reply runtime/signals_nat.c:295]: If it was just the main thread, I'd advocate for 1. since a malloc failing so early in the runtime initialisation would either indicate a critical lack of resources (many other future mallocs will fail), or some external thing trying to manipulate a specific condition into occurring (e.g. some malware that might be chaining an attack that wants to turn off stack overflow detection). But this is now for all threads begun with caml_thread_start, so aborting the whole program seems extreme.

The problem with 2. is that it's quite non-deterministic -- I'd hope that I could determine at program startup time if stack overflow detection is available or not (if I understand your suggestion correctly that we turn off overflow detection for the particular thread where malloc fails).

Is there an option 3. where we could simply terminate a thread that attempts to turn on stack overflow detection but fails to do so? This would be extremely rare, but at least the failure to start the thread would be observable by the mutator and so could potentially be handled by the application as with any other reason why a system thread might fail to spawn.

Comment (avsm) [reply runtime/signals_nat.c:295]: My comment was sent in parallel with @stedolan. Raising Out_of_memory seems ideal to me!

Comment (xavierleroy) [reply runtime/signals_nat.c:295]: These are nice suggestions, thanks @stedolan!  However, `caml_exn_Out_of_memory` exists only in native code and is not exported...  So, this would need some refactoring.  

I'm going to table this issue for later work.  There are other, more urgent changes in this department, such as freeing the alternate stack when the thread terminates.  I'll address these issues later in a separate PR.

Right now, the code does exactly what it did before, i.e. ignore failures when setting up the alternate signal stack in a new thread.  So there is no regression, and improvements will come later.

**Comment by xavierleroy** [comment]
I'm going to merge this PR so as to unblock the build on Rawhide.  Suggestions for further improvements are duly noted.

**Comment by damiendoligez** [comment]
@xavierleroy: This PR triggers a failure in the "sanitizers" CI job at Inria: https://ci.inria.fr/ocaml/job/sanitizers/315/console

Why are we using `malloc` directly here and not one of the `caml_stat_alloc` functions?

**Comment by xavierleroy** [comment]
> Why are we using malloc directly here and not one of the caml_stat_alloc functions?

This was discussed here: https://github.com/ocaml/ocaml/issues/10250#issuecomment-789108059  A memory leak is better than a crash.  Not sure what to do w.r.t. the CI check, though.

**Comment by rwmjones** [comment]
FYI: https://lists.gnu.org/archive/html/bug-m4/2021-03/msg00004.html

**Comment by hhugo** [comment]
I don't see this backported to 4.12. Should I expect a backport ?
