### PR TITLE
Prohibit using classes through recursive modules (fixes #6491)

### LINKED ISSUE #6491: Recursive modules do not correctly handle class inheritance
**Original bug ID:** 6491
**Reporter:** @lpw25
**Status:** acknowledged (set by @damiendoligez on 2014-07-30T20:39:30Z)
**Resolution:** open
**Priority:** normal
**Severity:** feature
**Target version:** later
**Category:** typing
**Tags:** recmod
**Monitored by:** @gasche

## Bug description

Recursive modules can contain classes or class types which inherit from each other. However, since inheritance is done by copying the methods and values, the information only passes through one layer of inheritance. For example the `x` method is missing from `Baz.c` in the following:

    # module rec Foo : sig class type c = object method x : int end end = Foo
      and Bar : sig class type c = object inherit Foo.c end end = Bar
      and Baz : sig class type c = object inherit Bar.c end end = Baz;;
        module rec Foo : sig class type c = object method x : int end end
    and Bar : sig class type c = object method x : int end end
    and Baz : sig class type c = object  end end

Module types would suffer from the same problem, but instead it gives an error:

    # module rec Foo : sig module type c = sig val x : int end end = Foo
      and Bar : sig module type c = sig include Foo.c end end = Bar
      and Baz : sig module type c = sig include Bar.c end end = Baz;;
        Characters 111-116:
        and Bar : sig module type c = sig include Foo.c end end = Bar
                                                  ^^^^^
    Error: Illegal recursive module reference

The same could be achieved for inheritance by calling `find_class_type` on any inherited class types during `approx_class`.

### PR DESCRIPTION
**Pull request by lpw25**
Prohibits using classes through recursive modules because it doesn't work. From the tests:
```ocaml
module rec Foo : sig class type c = object method x : int end end = Foo
and Bar : sig class type c = object inherit Foo.c end end = Bar
and Baz : sig class type c = object inherit Bar.c end end = Baz;;
[%%expect {|
module rec Foo : sig class type c = object method x : int end end
and Bar : sig class type c = object method x : int end end
and Baz : sig class type c = object  end end
|}]
```
becomes:
```ocaml
module rec Foo : sig class type c = object method x : int end end = Foo
and Bar : sig class type c = object inherit Foo.c end end = Bar
and Baz : sig class type c = object inherit Bar.c end end = Baz;;
[%%expect {|
Line 2, characters 44-49:
2 | and Bar : sig class type c = object inherit Foo.c end end = Bar
                                                ^^^^^
Error: Illegal recursive module reference
|}]
```

### CODE REVIEW

**Comment by gasche** [comment]
Sorry for the naive question, but what does "it doesn't work" mean here?

**Comment by lpw25** [comment]
See the added test. Inheriting from a class or class type, or creating an "alias" to a class type, works by just copying the methods and instance variables from one class to the other. Since recursive modules start by assuming that all classes are empty, such inheritance can unexpectedly act as if the inherited class is empty. Module inclusion would suffer from the same issue and has the same fix as in this PR: it is prohibited.

**Comment by Octachron** [comment]
Another example would be:
```ocaml
module rec A: sig
  class type c = object
    method x:int
    inherit B.c
    method z:float
  end
end = A
and B: sig
  class type c = object
    method y:int
    inherit C.c
    method w:float
  end
end = B
and C: sig
  class type c = object
    method x:float
    inherit D.c
    method z:int
  end
end = C
and D: sig
  class type c = object
    inherit A.c
    method y:float
    method w:int
  end
end = D
```
which currently generate four class types that "inherit" from each over but have conflicting types for the methods `x`,`y`,`z`,and`w`.

I agree that is a good idea to avoid exposing such convergence failure of the typing of recursive modules. I will check the opam repository to see if there are users of this kind of half-broken inheritance.

File: testsuite/tests/typing-recmod/pr6491.ml [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+*)
+
+module rec Foo : sig class type c = object method x : int end end = Foo
+and Bar : sig class type c = object inherit Foo.c end end = Bar
+and Baz : sig class type c = object inherit Bar.c end end = Baz;;
+[%%expect {|
+Line 2, characters 44-49:
+2 | and Bar : sig class type c = object inherit Foo.c end end = Bar
+                                                ^^^^^
+Error: Illegal recursive module reference
```
Comment (DemiMarie) [inline testsuite/tests/typing-recmod/pr6491.ml:12]: This is not a particularly clear error message.  Could the error explain that the problem is specifically due to classes?

**Review by gasche — APPROVED** [review]
The comment of @DemiMarie reminded me of this PR. I agree that it fixes a problem, and the implementation is clearly correct. (I wonder if an existing generic traversal could have been used here, but that's not so important.)

@DemiMarie asks about the error message, but the error-handling and error-reporting mechanism are pre-existing and outside the scope of this PR. It may very well be improved, but I think that it is orthogonal and could be done in a later PR.

**Comment by Octachron** [comment]
Since this is an user visible change, a change entry should be added before merging.

**Comment by gasche** [comment]
I tried to rebase and push a Changes entry to help, but I don't have push rights to @lpw25's repository. My branch is at https://github.com/gasche/ocaml/tree/fix-pr6491 ( [compare](https://github.com/ocaml/ocaml/compare/trunk...gasche:ocaml:fix-pr6491) ).

**Comment by lpw25** [comment]
Thanks @gasche. I've pushed your branch here.

**Comment by DemiMarie** [comment]
Is this a fundamental problem, or a workaround for an implementation deficiency?

**Comment by gasche** [comment]
There is an unrelated issue with the AppVeyor CI:

```
failed:
    tests/lib-dynlink-initializers/'test2_main.ml' with 1.2.1.4 (ocamlopt.byte) 
[...]
> ### begin stdout ###
> ** Fatal error: Cannot run cygpath -m "libmingw32" "libmingw32.lib" "libmingw32.dll.a" "libmingw32.a" "C:\projects\🐫реализация-mingw64\otherlibs\dynlink\native\libmingw32" [...]
> File "caml_startup", line 1:
> Error: Error during linking (exit code 2)
> ### end stdout ###
```

**Comment by gasche** [comment]
@DemiMarie this is a natural restriction arising from the implementation strategy of recursive modules, similar to other restrictions that were already properly enforced. We might be able to remove these restrictions, or some of them, by using a more complex implementation strategy for recursive modules.
