### PR TITLE
Gc.set incorrectly handles the three `custom_*` fields

### LINKED ISSUE #9326: Performance regression in OCaml 4.08
Dear OCaml devs,

@RalfJung has pointed out a non-trivial performance regression in Coq when moving from OCaml 4.07 to OCaml 4.08 https://github.com/coq/coq/issues/11652

See some numbers [here](https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/861/console), for example CompCert does compile more than 7% faster in 4.07

There are a few candidates in the changelog for the slowdown, I think we will try reverting some PRs and seeing what happens with a reduced file. Any ideas? [For example #2144 could be relevant? I doubt it tho]

Benchs:
- 4.07.1 vs 4.10.0 : https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/865/
- 4.07.1 vs 4.09.0: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/864/
- 4.08.1 vs 4.07.1: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/861/
- 4.09.0 vs 4.08.1: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/863/

### PR DESCRIPTION
**Pull request by xavierleroy**
As found by @stedolan in #9326, some `Long_val` conversions were missing.

This was setting the wrong values for the `custom_` parameters, causing the major GC to work too much, slowing down some programs.

Fixes: #9326

### CODE REVIEW

**Comment by xavierleroy** [comment]
A remaining question is how far back we want to backport this fix.

File: testsuite/tests/regression/pr9326/gc_set.ml [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+open Gc
+
+let min_heap_sz = 524288 (* 512k *)
+let maj_heap_inc = 4194304 (* 4M *)
+
+let _ =
+  let g1 = Gc.get() in
+  Gc.set { g1 with minor_heap_size = min_heap_sz;
+                   major_heap_increment = maj_heap_inc };
+  let g2 = Gc.get() in
```
Comment (hhugo) [inline testsuite/tests/regression/pr9326/gc_set.ml:24]: One could make the test to fail next time new fields are added and force people to update it by deconstructing either g1 or g2 and relying on exhaustive pattern in record.
```ocaml
let {minor_heap_size; ...} = Gc.get() in
```

**Comment by gasche** [comment]
We should backport it to 4.11 and 4.12 for sure.

Given how uninvasive the fix is, I might be motivated to backport it to 4.08 and following branches. We don't have releases planned for those, but keeping a maintenance branch is useful for various purposes. (For example: five years from now I want to build some software that works with OCaml 4.08.)

File: testsuite/tests/regression/pr9326/gc_set.ml (hunk 1 above)
Comment (xavierleroy) [reply testsuite/tests/regression/pr9326/gc_set.ml:24]: Good idea.  Done.

File: testsuite/tests/regression/pr9326/gc_set.ml [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+open Gc
+
+let min_heap_sz = 524288 (* 512k *)
+let maj_heap_inc = 4194304 (* 4M *)
+
+let _ =
+  let g1 = Gc.get() in
+  (* Do not use { g1 with ... }, so that the code will break if more fields
+     are added to the Gc.control record type *)
```
Comment (gasche) [inline testsuite/tests/regression/pr9326/gc_set.ml:12]: Nitpick: the comment could go the last mile and explain what to do when the code breaks: add another check below. This is obvious today, but it may not be as obvious to the person in 2023 adding a new field. (Relatedly: there is also no information in this testsuite file that explains what this test is checking / protecting against and why.)

**Review by gasche — APPROVED** [review]
Here is an approval stamp with a perfectionist comment.

Note to others: your Changes entry placed in "4.08 maintenance section" suggests that you are enthusiastic about wide backporting.

File: testsuite/tests/regression/pr9326/gc_set.ml (hunk 2 above)
Comment (xavierleroy) [reply testsuite/tests/regression/pr9326/gc_set.ml:12]: Use your brain?   The test in `testsuite/regression/prXXXX` is a regression test for the issue reported in problem report XXXX.

**Comment by xavierleroy** [comment]
> your Changes entry placed in "4.08 maintenance section" suggest that you are enthusiastic about wide backporting.

s/enthusiastic/resigned/

But yes I'll backport all over as soon as CI is green.
