### PR TITLE
Fix #11101 by making `occur ty ty` succeed

### LINKED ISSUE #11101: A recursive type constraint fails on 4.14
The following definition  fails with  OCaml > `4.14.0~` 
```ocaml
type ('node,'self) extension = < node: 'node; self: 'self > as 'self
type 'ext node = < > constraint 'ext = ('ext node, 'self) extension
```

```
1 |   type 'ext node = < > constraint 'ext = ('ext node, 'self) extension
           ^^^^
Error: Constraints are not satisfied in this type.
       Type ('a node, < node : 'a node; self : 'b > as 'b) extension as 'a
       should be an instance of
         ('c, < node : 'c; self : 'd > as 'd) extension
```
Similarly, using classes it is possible to trigger an internal compiler error with 4.14:

```ocaml
class type ['node] extension =
  object ('self)
    method clone : 'self
    method node : 'node
  end

type 'ext node = < >
  constraint 'ext = 'ext node #extension

module Raise: sig val default_extension: 'a node extension as 'a end = struct
  let default_extension = assert false
end
```
> Fatal error: exception Ctype.Escape(_)

Both examples works with previous versions (from OCaml 4.02.3 to OCaml 4.13.1).

As far as I can see, the regression appeared with #10337, and I am still investigating the root issue.

The issue was discovered by @kit-ty-kate in the [wild](http://check.ocamllabs.io/log/1646478756-0320214bdd317139efb4cd36210bf08e3ae551dd/4.14/bad/pxp.1.2.9).
I am thus hoping to fix the issue before the release of 4.14.0.

### PR DESCRIPTION
**Pull request by garrigue**
PR #11101 uncovers some problematic interaction between the occur check and expansion.
Namely, expansion inside `ty` may be required during the occur check `occur env ty0 ty`, but it can have adverse effects if it ends up modifiying `ty0` itself.

This fix avoids the problem in some cases by having the occur check succeed if `ty0` ends up being `ty` itself.
This also requires a small modification in `Types.link_type`, to ensure that it will not create a loop in that case.

While this change seems semantically correct, it doesn't explain why the problem didn't occur before #10337.
It would be interesting to know why, and this might provide another solution. On the other hand, finding the cause may take a long time.

### CODE REVIEW

**Comment by Octachron** [comment]
Looking at a typechecker trace before and after #10337, on the slightly simplified example
```
type ('a,'s) t = < node: 'a > as 's
type 'ext node = < > constraint 'ext = ('ext node,_) t
```
the two execution starts to diverge when calling `occur_rec` on
```ocaml
occur rec
  ty0=868->{id=860;level=2;scope=0;desc=Tconstr(node,[{id=859;level=2;scope=0;desc=Tconstr(t,[{id=860};{id=861;level=2;scope=0;desc=Tobject({id=862;level=2;scope=0;desc=Tfield(node,Fpresent,{id=864;level=2;scope=0;desc=Tpoly({id=860},[])},{id=863;level=2;scope=0;desc=Tnil})},ref None)}],[t;node])}],[node;node])}
  ty={id=860;level=2;scope=0;desc=Tconstr(node,[{id=859;level=2;scope=0;desc=Tconstr(t,[{id=860};{id=861;level=2;scope=0;desc=Tobject({id=862;level=2;scope=0;desc=Tfield(node,Fpresent,{id=864;level=2;scope=0;desc=Tpoly({id=860},[])},{id=863;level=2;scope=0;desc=Tnil})},ref None)}],[t;node])}],[node;node])}
```
(using a slightly modified type expression printer that prints `Tlink`s).
The execution before #10337 only compare physically the two types (and never follows the `Tlink` on the `ty0`) and thus proceed further and ends up succeeding by expanding the `node` type constructor into `< >`.

File: testsuite/tests/typing-misc/constraints.ml [hunk 1]
```diff
@@ -295,3 +295,37 @@ Error: The class constraints are not consistent.
...
+type 'ext node = < >
+  constraint 'ext = 'ext node #extension ;;
+[%%expect{|
+class type ['node] extension =
+  object ('a) method clone : 'a method node : 'node end
+type 'a node = <  > constraint 'a = < clone : 'a; node : 'a node; .. >
+|}]
+
+module Raise: sig val default_extension: 'a node extension as 'a end = struct
+  let default_extension = assert false
```
Comment (Octachron) [inline testsuite/tests/typing-misc/constraints.ml]: I would propose to replace the `assert false` with a `failwith "Default_extension failure"` to avoid having an expected assert failure in the result. But I can do that in a subsequent PR.

**Review by Octachron — APPROVED** [review]
After pondering for a while, I agree that the change is semantically correct: it corresponds to always accepting `'a as 'a` type without relying on the implementation details of the union-find graph.

For the sake of completeness, I have also checked that `ocaml-pxp` build with this fix.

**Comment by garrigue** [comment]
Thanks for the analysis of what happened. This somehow implies that the behavior before was not really correct either, since as soon as `ty0` would get modified, the occur check was disabled (one would compare the physical `ty0` with its dereferenced version, and they would always differ).
I don't know whether I can actually build a counter-example where the original code would allow creating an invalid recursion, but this looks like an argument for this change.

**Comment by garrigue** [comment]
Also cherry-picked to trunk.
