### PR TITLE
modular explicit: #14719, fix syntactic arity constraints

### LINKED ISSUE #14719: Misleading syntactic arity error message
For the following program

```ocaml
module type t = sig type _ t end
let f (type a) (module X: t) (Equal : (a X.t, int) Type.eq) : string = ""
```

OCaml produces the following error message in `trunk` (11c0cd29):

```
File "/tmp/bug.ml", line 2, characters 6-73:
2 | let f (type a) (module X: t) (Equal : (a X.t, int) Type.eq) : string = ""
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: The syntactic arity of the function doesn't match the type constraint:
       This function has 2 syntactic arguments, but its type is constrained to
         (module X : t) -> ('a X.t, int) Type.eq -> string.
        Hint: consider splitting the function definition into
          fun ... gadt_pat -> fun ...
          where gadt_pat is the pattern with the GADT constructor that
          introduces the local type equation on (module X : t) ->
                                                ('a X.t, int) Type.eq ->
                                                string.
```

As far as I can see, there isn't any kind of syntactic arity mismatch here, so the error message is misleading

### PR DESCRIPTION
**Pull request by Octachron**
This PR fixes the spurious syntactic arity error reported in #14719 by taking in account module-dependent arrow when enforcing that the syntactic arity of a function is not strictly greater that the arity of its type.

Close #14719

### CODE REVIEW

File: typing/ctype.ml [hunk 1]
```diff
@@ -4084,6 +4084,28 @@ let filter_functor env t l =
...
+          in
+          link_type t t';
+          Ok (env, ty_ret)
+      | Tarrow(_, _, ty_ret, _) -> Ok (env, ty_ret)
+      | Tfunctor (_, id, pack, ct) ->
+            let env, ret = open_tfunctor ~loc:Location.none env id pack ct in
+            Ok (env, ret)
+      | _ -> Error Not_a_function
+
 let is_really_poly env ty =
```
Comment (smuenzel) [inline typing/ctype.ml]: `filter_arrow`, `filter_functor` and `filter_arity` have a very similar structure.
Maybe the common logic could be factored out?
e.g.

```ocaml
let filter_desc ~f ~reverse_diff env t l =
    match expand_head_trace env t with
   | exception Unify_trace trace ->
       let t', _, _ = function_type l ~param_hole:false (get_level t) in
      let diff =
        if reverse_diff then
          Diff { got = t; expected = t' }
        else
          Diff { got = t'; expected = t }
      in
      Error (Unification_error
              (expand_to_unification_error
                  env
                  (diff :: trace)))
   | t -> f env t l
```

File: typing/typecore.ml [hunk 2]
```diff
@@ -4343,77 +4412,8 @@ and type_expect_
...
-              result_params
-          in
-          match body with
-          | Tfunction_body _ -> ()
-          | Tfunction_cases _ ->
-              ignore
-                (filter_ty_ret_exn ret_ty Nolabel ~param_hole:false : type_expr)
-      end;
+      if contains_gadt = Contains_gadt then
+        enforce_syntactic_arity ~loc env exp_type result_params body;
```
Comment (smuenzel) [inline typing/typecore.ml]: Possibly better to have a match rather than equality check, to show all cases have been considered? (and maybe other cases may be added in the future)

File: typing/ctype.ml (hunk 1 above)
Comment (Octachron) [reply typing/ctype.ml]: I have factorized the common part of the error path and type variable unification. For now, I have left aside the common skeleton of the pattern matching because moving pieces of this skeleton to an higher-order function felt more ambiguous in term of readability.

File: typing/typecore.ml (hunk 2 above)
Comment (Octachron) [reply typing/typecore.ml]: I have switched to a pattern matching, but I am a bit on the edge in this case since  the `contain_gadt` type is essentially a named boolean, for which using `x = Contains_gadt`  also feels like a good choice.

**Comment by Octachron** [comment]
@gasche : gentle ping? This is a genuine bug fix that needs to be fixed for 5.5 rather than a quality of life improvement like other fixes in the same family.

**Comment by gasche** [comment]
I would be happy to approve on @smuenzel's behalf if he actually approves the PR (typically by using the github UI; this means that you vouch for the quality of the PR and believe it should be merged). I can also do a review of my own, but probably not today.

File: typing/ctype.ml [hunk 3]
```diff
@@ -4029,60 +4042,50 @@ let filter_arrow env ~in_apply t l ~param_hole =
...
-      in
-      Error (Unification_error
-              (expand_to_unification_error
-                  env
-                  (diff :: trace)))
+              let ty_param = newmono_package ~level:(get_level t) pack in
+              let t' = newty2 ~level:(get_level t)
+                  (Tarrow (l, ty_param, ty_ret, commu_ok))
+              in
+              link_type t t';
```
Comment (smuenzel) [inline typing/ctype.ml:4053]: The documentation of `link_type` says that it can only be used if the desc of `t` is `Tvar` or if `t` and `t'` have the same type description constructor. But I think in this case `t'` is `Tarrow` and `t` is `Tfunctor`

Comment (Octachron) [reply typing/ctype.ml:4053]: This is the implicit conversion between non-dependent `Tfunctor` to `Tarrow` (which should be documented but is not changed by this PR).

**Review by smuenzel — APPROVED** [review]
I think this looks correct and does what's advertised.

**Review by gasche — APPROVED** [review]
Green-stamped on @smuenzel's behalf. Thanks!
