### PR TITLE
Fix async exception handling inside Domain.spawn

### LINKED ISSUE #12269: possible memory-leak on failed domain backup thread installation
From #12263 there's a possible rare memory leak in `runtime/domain.c` if `install_backup_thread` fails to spawn the thread.  

@kayceesrk suggests that instead of `install_backup_thread` raising a Failure exception directly, it should return the failure and the callers of `install_backup_thread` (of which there are two, since domain 0 is a special case) need to call the domain termination functions (which will clean up the allocated resources and also raise the Failure exception).

### PR DESCRIPTION
**Pull request by gadmm**
This PR fixes unsafety and deadlocks, should an asynchronous exception arise at specific locations during domain creation and shutdown.

Explanation: some OCaml code is reimplemented in C for better control over asynchronous exceptions.

A simpler implementation could use masks (#8961) to have the needed control, but the present change is also useful as a preliminary work to fix #12269.

Note: this is based over #12408 for convenience.

cc @kayceesrk

### CODE REVIEW

File: stdlib/domain.ml [hunk 1]
```diff
@@ -19,7 +19,21 @@
...
+
+  (* The layouts of [state] and [term_sync] are hard-coded in
+     [runtime/domain.c] *)
+
+  type 'a state =
+    | Running
+    | Finished of ('a, exn) result
+
+  type 'a term_sync = {
+    mutable state : 'a state [@warning "-69"] ; (* protected by [mut] *)
```
Comment (gasche) [inline stdlib/domain.ml]: - I'm not sure why you need this warning attribute as `state` looks used in `join` below
- I would prefer to disable the warning by name `[@warning "-unused-field"]`, it is not so nice to have to call `ocamlc -warn-help` when reading the code

File: runtime/domain.c [hunk 2]
```diff
@@ -1070,6 +1076,38 @@ CAMLexport _Atomic caml_timing_hook caml_domain_terminated_hook =
...
 
+static void domain_sync_result(value term_sync, value res_or_exn)
+{
+  CAMLparam1(term_sync);
+  CAMLlocal1(res);
+  if (Is_exception_result(res_or_exn)) {
+    res = Extract_exception(res_or_exn);
+    /* [Finished (Error res)] from stdlib/domain.ml */
+    res = caml_alloc_1(1, res);
+    res = caml_alloc_1(0, res);
```
Comment (gasche) [inline runtime/domain.c]: Should we consider mlvalues.h macros for `result`, just like we have for options?

File: runtime/domain.c [hunk 3]
```diff
@@ -1070,6 +1076,38 @@ CAMLexport _Atomic caml_timing_hook caml_domain_terminated_hook =
...
+  } else {
+    res = res_or_exn;
+  }
```
Comment (gasche) [inline runtime/domain.c:1090]: Could we have a helper function that takes a "value or error" value, returns the corresponding `('a, exn) result` value, as is guaranteed to not run any callback?

File: runtime/domain.c [hunk 4]
```diff
@@ -1070,6 +1076,38 @@ CAMLexport _Atomic caml_timing_hook caml_domain_terminated_hook =
...
+{
+  CAMLparam1(term_sync);
+  CAMLlocal1(res);
+  if (Is_exception_result(res_or_exn)) {
+    res = Extract_exception(res_or_exn);
+    /* [Finished (Error res)] from stdlib/domain.ml */
+    res = caml_alloc_1(1, res);
+    res = caml_alloc_1(0, res);
+  } else {
+    res = res_or_exn;
```
Comment (gasche) [inline runtime/domain.c]: I would have expected an allocation of `Ok res_or_exn` here. Unless I am missing something, (1) the code is wrong and (2) our testsuite needs beefing up on `Domain.join`.

File: runtime/domain.c [hunk 5]
```diff
@@ -1070,6 +1076,38 @@ CAMLexport _Atomic caml_timing_hook caml_domain_terminated_hook =
...
+
+  /* Synchronize with joining domains. We call [caml_ml_mutex_lock]
+     because the systhreads are still running on this domain. We
+     assume this does not fail the exception it would raise at this
+     point would be bad for us. */
+  caml_ml_mutex_lock(*Term_mutex(term_sync));
+
+  /* Store result */
+  volatile value *state = Term_state(term_sync);
+  CAMLassert(!Is_block(*state));
```
Comment (gasche) [inline runtime/domain.c:1107]: Why not assert directly that `*state` is `Running`?

**Review by gasche — COMMENTED** [review]
I looked at this PR and made various comment, including one where I suspect a bug.

My summary of the work:
- Before this PR, the OCaml code was in charge of handling the synchronization between `spawn` and `join`: spawn "produces a result" by broadcasting that its domain is done and writing its result to shared memory, and join "waits on a result" by waiting on this condition and reading the result.
- This is not async-exception-safe because the `spawn` logic could be interrupted by an asynchronous exception in the middle of this synchronization logic.
- The fix is in this PR is to move the "producing a result" code to C. Now the OCaml part of `spawn` returns its result without any synchronization logic, and the runtime logic around it is in charge of the synchronization. This is async-safe because the runtime has functions to allocate without running callbacks.
- The "waiting on a result" side for Join remains in OCaml, so the synchronization logic is spread across C and OCaml and the type structures have to be kept synchronized.

After reading this PR I was left wondering why we don't move all the synchronization logic on the C side. We could have an FFI-implemented abstract type `'a promise` for what is currently `'a Raw.term_sync`, define `type 'a Domain.t = Raw.t * 'a Raw.promise`, and implement `join` on the C side. (We could even keep the return value in its encoded `value_or_exn` form and avoid the intermediary `result` wrapping, simplifying the code.)

**Comment by xavierleroy** [comment]
> (We could even keep the return value in its encoded value_or_exn form and avoid the intermediary result wrapping, simplifying the code.)

Here are dragons.  Unlike `('a, exn) Result.t`, the "value or exn" encoding is GC-unsafe and cannot survive any allocation.  I'd rather keep as much code as possible in OCaml with nice algebraic datatypes than debug those kind of GC hazards.

File: stdlib/domain.ml (hunk 1 above)
Comment (gadmm) [reply stdlib/domain.ml]: I am not sure why I get this warning either. Note that it complains about the `mutable` part.

This looks like a false positive to me as `term_sync` is an input to an `external` which can very well (and does) mutate `state`.

File: runtime/domain.c (hunk 2 above)
Comment (gadmm) [reply runtime/domain.c]: I do not have any particular opinion about this.

File: runtime/domain.c (hunk 3 above)
Comment (gadmm) [reply runtime/domain.c:1090]: I think the usefulness would be limited as the "value or exn" type is for C consumption but `('a, exn) result` is cumbersome for C consumption. In this rare instance the conversion is made for OCaml consumption.

File: runtime/domain.c (hunk 4 above)
Comment (gadmm) [reply runtime/domain.c]: ~Ouch, well spotted! Besides my obvious oversight, I'll look into why the testsuite did not catch this.~

File: runtime/domain.c (hunk 5 above)
Comment (gadmm) [reply runtime/domain.c:1107]: I simply adapted the test that was made before.

**Comment by gadmm** [comment]
I agree that it is better to reduce the C runtime to a minimum and implement in OCaml as much as possible. For instance the implementation of join is nice and there is no good reason to translate it into C (now if we did not have the async-safe Mutex.protect this would have been a different story). In fact it would be nice if we could move it all back to `stdlib/domain.ml` at some point.

File: runtime/domain.c (hunk 4 above)
Comment (gadmm) [reply runtime/domain.c]: You convinced me that I made a mistake but it turns out that it is correct. `Domain.spawn` already returns `Finished (Ok res)` on the OCaml side. The testsuite would have caught the error, as well.

I'll add a comment.

File: stdlib/domain.ml (hunk 1 above)
Comment (gasche) [reply stdlib/domain.ml]: I wonder if we should make the code more regular by changing `spawn` to return the result directly. Changing it to return an `('a, exn) result` value would be very simple, but we could go further by returning an `'a` and raising the corresponding exceptions -- I think there would be opportunities for simplifying the code there.

```ocaml
      match
        DLS.create_dls ();
        DLS.set_initial_keys pk;
        let res = f () in
        res
      with
      | res ->
        do_at_exit ();
        res
      | exception exn ->
        let bt = Printexc.get_raw_backtrace () in
        (try do_at_exit () with _ -> ());
        Printexc.raise_with_backtrace bt exn
```

Comment (gasche) [reply stdlib/domain.ml]: Ah, I didn't know that the warning was about the lack of mutation in the code.

I agree that the warning is a false positive and that it is fine to silence it. (Maybe a comment that explains what warning arises and why we silence it could be nice.)

File: runtime/domain.c (hunk 4 above)
Comment (gasche) [reply runtime/domain.c]: Ah, indeed!

I wonder if we should make the code more regular by changing `spawn` to return the result directly. Changing it to return an `('a, exn) result` value would be very simple, but we could go further by returning an `'a` and raising the corresponding exceptions -- I think there would be opportunities for simplifying the code there.

```ocaml
      match
        DLS.create_dls ();
        DLS.set_initial_keys pk;
        let res = f () in
        res
      with
      | res ->
        do_at_exit ();
        res
      | exception exn ->
        let bt = Printexc.get_raw_backtrace () in
        (try do_at_exit () with _ -> ());
        Printexc.raise_with_backtrace bt exn
```

Comment (gadmm) [reply runtime/domain.c]: You mean `body`, right?
```
Error: Wrong link order: Stdlib__Domain depends on Stdlib__Printexc
```

Comment (gadmm) [reply runtime/domain.c]: > let bt = Printexc.get_raw_backtrace () in

I left this out as I could not fix the dependency issues. I'll let anyone looking to fix #12362 deal with this!

File: runtime/domain.c (hunk 3 above)
Comment (gasche) [reply runtime/domain.c:1090]: Having a helper function for this makes the code easier and nicer to read, even if we are not sure that we will reuse the helper very often.

File: runtime/domain.c [hunk 6]
```diff
@@ -1111,29 +1151,34 @@ static void* domain_thread_func(void* v)
...
+       and/or can deadlock. */
     caml_domain_initialize_hook();
 
     /* release callback early;
        see the [note about callbacks and GC] in callback.c */
     value unrooted_callback = ml_values->callback;
     caml_modify_generational_global_root(&ml_values->callback, Val_unit);
-    caml_callback_exn(unrooted_callback, Val_unit);
+    value res_or_exn = caml_callback_exn(unrooted_callback, Val_unit);
+    domain_sync_result(ml_values->term_sync, res_or_exn);
```
Comment (gasche) [inline runtime/domain.c]: Now that the handling of `res_or_exn` is more regular, it would be easy to convert `res_or_exn` into an OCaml value here, caller-side, instead of doing the work in `domain_sync_result`. (This also avoids the awkwardness of passing `domain_sync_result` a `value` parameter that cannot validly be rooted.)

**Review by gasche — COMMENTED** [review]
The simplification looks nice, thanks! (Too bad for the backtrace, but I agree that giving up on a perfect backtrace is reasonable.)

File: runtime/domain.c (hunk 6 above)
Comment (gadmm) [reply runtime/domain.c]: No thanks, this makes `domain_thread_func` even bigger (and if you introduce a helper function you are back to the awkardness of passing an irregular value).

Comment (gasche) [reply runtime/domain.c]:
```c
value result = caml_extract_result(caml_callback_exn(unrooted_callback, Val_unit));
```

> if you introduce a helper function you are back to the awkardness of passing an irregular value

It is easier to be careful about a short helper function that is specifically dedicated to a subtle input type than about a larger function that takes one weird arguments among other things.

**Review by gasche — APPROVED** [review]

**Comment by gadmm** [comment]
History is now clean.
