### PR TITLE
Clambda: do not substitute mutable variables in function bodies

### LINKED ISSUE #7683: Mutable variables read shouldn't be substituted
**Original bug ID:** 7683
**Reporter:** @chambart
**Status:** confirmed (set by @mshinwell on 2017-12-06T17:08:41Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.0+dev/beta2/rc1/rc2
**Category:** middle end (typedtree to clambda)
**Monitored by:** @nojb @gasche @alainfrisch

## Bug description

In closure.ml the Uvar constructor is supposed to be pure by 'is_simple_argument', but when the variable is mutable this
can be wrong.

## Steps to reproduce

This program exhibit the problem, it returns 1 in bytecode and flambda and 2 with closure.

let f () n () =
  n

let g () =
  let r = ref 0 in
  f (incr r) !r (incr r)

let () = print_int (g ())

### PR DESCRIPTION
**Pull request by nojb**
Fixes #7683

The proposed solution uses a global `Hashtbl.t` to keep track of mutable variables, which is simple but not very nice. The translation functions in `Closure` already have two "env" arguments which are passed everywhere. One possibility could be to introduce a record type for the "env" arguments and add a field to keep track of the set of mutable variables. Opinions?

### CODE REVIEW

**Comment by gasche** [comment]
I'm not excited by having yet another piece of global mutable state to avoid passing arguments, and would welcome a richer environment structure to handle this instead. That said, it could come as a later PR, and we could already merge this if there was approval that the fix is correct.

I tried to review this patch but I was blocked by the fact that nowhere is a specification of `is_simple_argument` spelled out. After reading the code of how it is used, I think that I understand the issue and what you change (and that it is, indeed, purely about the order of evaluation of arguments), but I think that we should take this opportunity to specify what people mean with `is_simple_arguments` and `no_effects`. I suspect that the Flambda people have already built a good vocabulary to deal with this, namely the `effects` and `coeffects` types in `bytecomp/semantics_of_primitives.mli`.

**Comment by gasche** [comment]
Also, the CI needs to pass, so you need a Changes entry. (The x64 failure looked very mysterious to me and probably a transient issue with the CI environment, so I just restarted the build.)

**Comment by alainfrisch** [comment]
Would it be crazy to use a specific construction (already at the lambda level) to materialize reads from mutable variables (e.g. Lread instead of Lvar)?  I haven't looked at the impact of this approach, but it might be at the end as simple as passing the information in an environment, and perhaps more robust.

**Comment by mshinwell** [comment]
@alainfrisch Yes, that is exactly what you want to do, preferably using another type for mutable variables.  This is what we do in Flambda.

**Comment by mshinwell** [comment]
(Following on from the discussion on the Mantis issue.)  I would argue that we should fix cases where the evaluation order differs between bytecode/Closure/Flambda -- we should have dealt with the hard part of this now (in `Selectgen`).

However ignoring evaluation order, here's a bug, which I think is due to this issue:
```
# let f () n () = n;;
val f : unit -> 'a -> unit -> 'a = <fun>

# let [@inline always] h1 x = x;;
val h1 : 'a -> 'a = <fun>
# let [@inline never] h2 x = x;;
val h2 : 'a -> 'a = <fun>

# let g1 () = let r = ref 0 in f (incr r) (h1 !r) (incr r);;
val g1 : unit -> int = <fun>
# g1 ();;
- : int = 2

# let g2 () = let r = ref 0 in f (incr r) (h2 !r) (incr r);;
val g2 : unit -> int = <fun>
# g2 ();;
- : int = 1
```
"g1" and "g2" should give the same result; the only difference is inlining annotations.

**Comment by gasche** [comment]
If the semantics of a program is the set of behaviors (I/O trace and result) resulting of specification-respecting evaluations of it, then there is no bug in your example: the two programs with differing annotations are correctly given the same semantics, it just happens that the reference implementation does not select the same element of the set in both cases. (Note that the specification never says that an implementation should always return the same element of the semantics of a given program, as non-deterministic evaluation order choices are valid.)

**Comment by damiendoligez** [comment]
>However ignoring evaluation order, here's a bug

Why "ignoring evaluation order"? Your bug is precisely about evaluation order.

I mostly agree with Gabriel here, although I think it was a mistake in the language design to leave evaluation order unspecified.

**Comment by mshinwell** [comment]
I consider it a bug, even if the program depends on unspecified evaluation order, for a source code modification that only affects inlining annotations to change the result of the program.  I think that is going to be the reasonable expectation of most users.

**Comment by gasche** [comment]
There are many ways in which inlining more or less can change the behavior of a program: stack overflow, a collection running at function-call point running finalizers, inspecting the stack trace of a program, etc.

In any case, I think that we all agree that we should do this change on the compiler, but @nojb should maybe consider some changes to the PR before it is merged.

**Comment by nojb** [comment]
Yes, absolutely; however I have not been able to follow the discussion closely.  Are we thinking of getting rid of the global state by enriching the environment, or the much more heavier change of changing `lambda` to make reads from mutable variables explicit?

**Comment by gasche** [comment]
What I personally would like to see as a minimum for merging (for reviewing, really) is a clear specification, in comments, of what those functions are doing/checking.

I think that the two other changes proposed would be nice-to-have, in this PR or a next one.

**Comment by damiendoligez** [comment]
>I consider it a bug, even if the program depends on unspecified evaluation order, for a source code modification that only affects inlining annotations to change the result of the program. I think that is going to be the reasonable expectation of most users.

Then it's just a question of point of view. In my eye, the bug is that the evaluation order is changed by the inlining annotation.

**Comment by nojb** [comment]
It would be nice to reach a consensus on whether this is a bug that needs fixing or not before putting in more work on this PR.

**Comment by gasche** [comment]
The behavior exhibited by the compiler in this case is not the one we wish, and there is strong consensus that we should change it to match expectations.

The debate about whether this is a bug or not is nitpicking about whether this respects or not the language's specification regarding evaluation order. Implementing something stronger and better (than the evaluation order specification) is the right move here.

Edit: to clarify, yes this is a bug that needs fixing, but it is a bug with respect to a specification that is stronger than the OCaml language specification. There is consensus on the fact that this stronger specification is desired in this particular case.

**Comment by nojb** [comment]
@gasche I added some comments to the code, let me know if they help. Thanks!

**Comment by nojb** [comment]
Ping @gasche.

**Comment by gasche** [comment]
I'm sorry to be the grating one, but I don't find your specifications very satisfying. They explain how the code came to be (and what were the beliefs of the people that wrote it), but they are very imprecise. The specification of `binds_param` mostly repeats the implementation (so in that sense it is a bit superfluous), but leaves me with some questions:

- what does "pure according to no_effects" actually mean? Is there a way to understand what that is without reading the code of no_effects? (Which is actually not enlightening as it refers to another function somewhere else)
- what is the difference between "is 'simple' according to is_simple_argument" and "is pure"? Are the two notions of purity different, and why?

Maybe the specification that is_simple_argument try to approximate is that `let x = s in t` is equivalent to `t[s/x]` whenever `is_simple s` holds. (Or maybe there are additional concerns related to duplicating the computation of `s` if `x` occurs several time in t?). Intuitively this looks like a fairly reasonable notion of purity, is `no_effects` actually different?

`bytecomp/semantics_of_primitives.mli` defines notions of purity that I understand because they are independent from the details of the language -- they are not defined by implementation only, or by properties only. In particular I think that the definition between effects (that change the state of the world) and co-effects (that depend on the state of the world) is a useful one to think about when encountering a mutable-variable-related bug (although that doesn't mean it should be mentioned explicitly in a specification). They also explain that some expressions have no effect that is observable in their output, but still should not be duplicated, which might be a start of distinction between `no_effects` and `is_simple_argument`.

I'm not saying that these definitions or this code should be used exactly as is, but I think that they give a good example of setting a conceptual framework to think about these things precisely, and that we should reuse those tools for the mind.

**Comment by nojb** [comment]
Thanks @gasche for the detailed comments; I will work to improve the specification of the code along the lines you suggest.

**Comment by gasche** [comment]
Note: I don't understand the relative importance, for you, of merging the patch now vs. having a better version. I think that the current proposal is certainly an improvement over the current state, so you could do a two-stage process. But it's one of these cases where I have the hunch that it's worth trying to solve the problem carefully, because it will catch bugs today or prevent them in the future.

**Comment by nojb** [comment]
> But it's one of these cases where I have the hunch that it's worth trying to solve the problem carefully, because it will catch bugs today or prevent them in the future.

I agree.

**Comment by damiendoligez** [comment]
Then let's postpone this PR to after 4.07.

**Comment by xavierleroy** [comment]
One year and a few months later, can we reach an agreement on this PR?

**Comment by nojb** [comment]
I rebased the PR, and added a comment with my understanding of the situation along the lines suggested by @gasche. Hopefully it will pass muster :)

~~More seriously, writing this comment helped me found a bug in the PR: `let p = a in body` can be replaced by `body` when `p` does not occur in `body` even if `a` is a mutable variable.~~

File: middle_end/closure/closure.ml [hunk 1]
```diff
@@ -697,15 +697,39 @@ let rec substitute loc ((backend, fpc) as st) sb rn ulam =
...
+     only generative effects. As an approximation we only do this when [a] is
+     either a variable or a constant or a closure allocation.
+
+   - In general [f a] is equivalent to [a; body] if [p] does not occur in [body].
+*)
+
+let mutable_ids = Hashtbl.create 17
+
+(* Approximates "no effects and no coeffects" *)
 let is_simple_argument = function
```
Comment (gasche) [inline middle_end/closure/closure.ml]: Could this function be maybe renamed `is_substituable`?

File: middle_end/closure/closure.ml [hunk 2]
```diff
@@ -697,15 +697,39 @@ let rec substitute loc ((backend, fpc) as st) sb rn ulam =
...
-  | Uvar _  | Uconst _ -> true
+  | Uvar v -> not (Hashtbl.mem mutable_ids v)
+  | Uconst _ -> true
   | _ -> false
 
+(* Approximates "only generative effects" *)
 let no_effects = function
```
Comment (gasche) [inline middle_end/closure/closure.ml]: Could this function maybe be renamed `is_erasable`?

File: middle_end/closure/closure.ml [hunk 3]
```diff
@@ -697,15 +697,39 @@ let rec substitute loc ((backend, fpc) as st) sb rn ulam =
...
-  | Uclosure _ -> true
-  | u -> is_pure u
+  | Uclosure _ | Uvar _ | Uconst _ -> true
+  | _ -> false
```
Comment (gasche) [inline middle_end/closure/closure.ml]: In several cases your patch replaces `is_pure u` by `false` (for example, "pure" primitives, offset instructions, etc., will now be rejected while they were previously accepted). This looks like a regression in optimizations, am I missing something? If I understand your comment correctly, this function is used to decide whether a subexpression can be dropped completely, so we shouldn't need to ensure that accepted expressions are "small".

**Review by gasche — COMMENTED** [review]
The new versions is fairly easy to review, thanks! I left a few comments.

File: middle_end/closure/closure.ml (hunk 3 above)
Comment (nojb) [reply middle_end/closure/closure.ml]: Oops, indeed, I got confused here. I reverted this change.

File: middle_end/closure/closure.ml (hunk 2 above)
Comment (nojb) [reply middle_end/closure/closure.ml]: Done.

File: middle_end/closure/closure.ml (hunk 1 above)
Comment (nojb) [reply middle_end/closure/closure.ml]: Done.

**Comment by gasche** [comment]
I might be pushing my luck a bit too far here, but: now that I'm perfectly satisfied with the comments and the behavior of the implementation, could we maybe revisit this question of adding another piece of global mutable state to the module? There is an environment structure that is passed around by the `close*` functions, wouldn't it work (and be fairly easy) to add a new `mutability_env` field to that structure, of type `Asttypes.mutable_flag V.Map.t`, instead of a module-global hashtable?

**Comment by gasche** [comment]
(Or `mutable_vars : V.Set.t`, or whatever.)

**Comment by nojb** [comment]
> I might be pushing my luck a bit too far here, but: now that I'm perfectly satisfied with the comments and the behavior of the implementation, could we maybe revisit this question of adding another piece of global mutable state to the module? There is an environment structure that is passed around by the `close*` functions, wouldn't it work (and be fairly easy) to add a new `mutability_env` field to that structure, of type `Asttypes.mutable_flag V.Map.t`, instead of a module-global hashtable?

I will give it a try, thanks.

**Comment by nojb** [comment]
I pushed a commit getting rid of the global hashtbl and threading the information in the environment instead.

File: middle_end/closure/closure.ml [hunk 4]
```diff
@@ -772,7 +767,7 @@ let warning_if_forced_inline ~loc ~attribute warning =
 
 (* Generate a direct application *)
 
-let direct_apply ~backend fundesc ufunct uargs ~loc ~attribute =
+let direct_apply ~backend fundesc ufunct uargs ~loc ~attribute ~mutable_vars =
```
Comment (gasche) [inline middle_end/closure/closure.ml]: Have you considered changing `direct_apply` to take the `env` parameter as a whole, instead of `~backend ~mutable_vars` separately? (I guess we need to move the `env` definition above here as a result, which is fine.)

File: middle_end/closure/closure.ml [hunk 5]
```diff
@@ -730,37 +728,34 @@ let is_erasable = function
...
-            pl al body in
-        if occurs_var (VP.var p1) body then
-          Ulet(Immutable, Pgenval, p1', u1, body')
-        else if is_erasable a1 then body'
-        else Usequence(a1, body')
-      end
-  | (_, _) -> assert false
-
-let bind_params loc fpc params args body =
+let bind_params ~mutable_vars loc fpc params args body =
```
Comment (gasche) [inline middle_end/closure/closure.ml]: I think that `bind_params` could take the whole environment as well. This is more regular than cherry-picking the part(s) that are required, and easier to upgrade with more environment metadata in the future.

**Review by gasche — APPROVED** [review]
Thanks a lot for going along. I'm satisfied with the change, and here is a preliminary seal of approval. I left a few nitpick-level remarks that you should feel free to follow or not. This should be fine to merge if/when the CI approves.

File: middle_end/closure/closure.ml (hunk 4 above)
Comment (nojb) [reply middle_end/closure/closure.ml]: Makes sense, I amended as suggested.

**Comment by gasche** [comment]
I'm out of nitpicks, except that maybe the commit history is a bit long. Are you planning to rebase all of this into a handful of commits only?

**Comment by nojb** [comment]
> I'm out of nitpicks, except that maybe the commit history is a bit long. Are you planning to rebase all of this into a handful of commits only?

Yes, but will wait for the CI to complete to avoid having to wait twice :)

**Comment by nojb** [comment]
Thanks for the review @gasche !
