### PR TITLE
#12061 fix: avoid adding inconsistent equations in functor error messages

### LINKED ISSUE #12061: Invalid_argument("List.iter2") under moregen with ill-aritied type in functor argument
When ocaml sees

```
module F
    (A : sig type 'a t end)
    (B : sig
       type 'a t
       val f : 'a A.t -> 'a t
     end) =
struct end

include
  F
    (struct
      type t = unit   (* this is bogus! *)
    end)
    (struct
      type 'a t = unit

      let f x = x
    end)
```

it says

```
Fatal error: exception Invalid_argument("List.iter2")
Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
Called from Ctype.occur_univar.occur_desc in file "typing/ctype.ml", line 1951, characters 12-694
Re-raised at Ctype.occur_univar.occur_desc in file "typing/ctype.ml", line 1947, characters 30-32
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Ctype.occur_univar_for in file "typing/ctype.ml", line 1980, characters 4-23
Called from Ctype.moregen_occur in file "typing/ctype.ml", line 3658, characters 2-33
Called from Ctype.moregen in file "typing/ctype.ml", line 3672, characters 8-43
Called from Ctype.moregen in file "typing/ctype.ml", line 3692, characters 14-54
Called from Ctype.moregeneral.(fun) in file "typing/ctype.ml", line 3911, characters 9-64
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Includecore.value_descriptions in file "typing/includecore.ml", line 82, characters 8-60
Called from Includemod.value_descriptions in file "typing/includemod.ml", line 165, characters 7-72
Re-raised at Includemod.mark_positive in file "typing/includemod.ml", line 149, characters 20-108
Called from Includemod.signature_components in file "typing/includemod.ml", line 730, characters 14-75
Called from Includemod.signature_components in file "typing/includemod.ml", line 835, characters 10-103
Called from Includemod.signatures.pair_components in file "typing/includemod.ml", line 656, characters 10-134
Called from Includemod.try_modtypes in file "typing/includemod.ml", line 489, characters 8-67
Called from Includemod.modtypes in file "typing/includemod.ml", line 426, characters 8-64
Called from Includemod.Functor_app_diff.diff.Compute.test in file "typing/includemod.ml", line 1172, characters 18-135
Called from Diffing.Define.Generic.compute_inner_cell in file "utils/diffing.ml", line 342, characters 12-40
Called from Diffing.Define.Generic.compute_inner_cell in file "utils/diffing.ml", line 339, characters 6-301
Called from Diffing.Define.Generic.compute_matrix.loop in file "utils/diffing.ml", line 379, characters 10-28
Called from Diffing.Define.Right_variadic.diff in file "utils/diffing.ml", line 443, characters 6-39
Called from Includemod_errorprinter.Functor_suberror.App.patch in file "typing/includemod_errorprinter.ml", line 462, characters 6-51
Called from Includemod_errorprinter.report_apply_error in file "typing/includemod_errorprinter.ml", line 904, characters 10-55
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Stdlib__Fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__Fun.protect in file "fun.ml", line 38, characters 6-52
Called from Persistent_env.without_cmis in file "typing/persistent_env.ml", line 142, characters 10-109
Called from Includemod_errorprinter.register.(fun) in file "typing/includemod_errorprinter.ml", line 936, characters 15-149
Called from Location.error_of_exn.loop in file "parsing/location.ml", line 967, characters 16-21
Called from Location.report_exception.loop in file "parsing/location.ml", line 985, characters 10-26
Re-raised at Location.report_exception.loop in file "parsing/location.ml", line 986, characters 14-25
Called from Maindriver.main in file "driver/maindriver.ml", line 118, characters 2-33
Called from Main in file "driver/main.ml", line 2, characters 7-54
```

The output above is from the tip of `trunk`, but similar errors are reported in 4.14.0 and 5.0.0 (the only other ones I tested). The program should be rejected, but perhaps with a friendlier error message. :)

### PR DESCRIPTION
**Pull request by Octachron**
This PR fixes by #12061 by making sure that the diffing algorithm for functor errors doesn't add inconsistent equations to the typing environment when exploring potential patches.

More precisely, this PR ensures that whenever the type of the concrete functor argument and the type of the abstract parameter disagree, we don't add any equations between the two.

It might be possible to be more finer-grained and keep consistent equations but that's probably better done at a later point. Note that the second commit in this PR removes a test which is no longer relevant without such addition of consistent equations.

Along the way, this PR fixes a small fixes when the diffing algorithm was not adding enough equations when inserting a missing argument.

Fix #12061

### CODE REVIEW

**Comment by gasche** [comment]
I tried to jump at the diff and read the code, but I need more context to understand what is going on, and I am too lazy to look it up myself so let's just ask here.

1. What is the specification of `update` again? My guess is that it takes a "diff", that is a move inside the edit matrix (it is a move from a pair of states to compare (S1, S2) to a "larger" pair (S1', S2'))), and it has to update some "state" that made sense in (S1, S2) and now has to make sense in (S1', S2').

2. In the case of functors, the state contains a typing environment. What is the assumption on the relation between the typing environment and the pair of (S1, S2)? (How do we call S1,S2 if not "states"? positions?) My vague guess is that, depending on the move, it tries to maintain an environment that makes sense for both S1 and S2, and sometimes it gives up. From your PR description it sounds like you are moving more cases to the "give up" category, but in trying to match this intuition to the patch I... gave up.

3. What does `expand_params` do? Eyeballing its implementation, and also `lookup_expansion`, did not answer this question immediately. Are they documented somewhere?

**Comment by Octachron** [comment]
1. The `update` function  computes the new state (here the environment and substitutions) at the tip of the current patch after a move in the edit matrix.
  There are no pair of equivalent states, we have
   - a common environment to add abstract functor parameters that are bound only inside the functor
   - a substitution that represent equations between the expected and actual argument
  
2.  We need to add an equation between the two sides whenever they are compatible, in other words in the `Keep` case. Previously, the `update` function was adding the same equation even in the `Change` case when we know that there are some incompatibilities. That might lead to better errors in some case because the incompatibilities might be harmless for the diffing algorithm (e.g. one value with incompatible type). But in general, this breaks some invariant in the typechecker. For instance #12061 is due to the fact that the current code is breaking the precondition that the arity of type constructors would be always the same on the two side of the comparison.
The current patch is thus "giving" up on keeping the possibly consistent equations in the `Change` case and it is moving the `Change` case to the `Insert _` group that may still need to add the abstract parameter to the typing environment, but doesn't add equations between the argument and the parameter.

4. At the end of the update, we may have discovered equalities that may change the concrete arity of the functor, the `expand_params` function recompute this concrete arity

**Comment by gasche** [comment]
> There are no pair of equivalent states

I wasn't meaning to suggest that states in a pair are equivalent. I view the edit matrix for the words W1 and W2 as formed of pairs of prefixes of W1 and W2, with (empty, empty) on one end and (W1, W2) on the other end, and any other point is (P1, P2) for two prefixes. I assume, in the case of "functor diffing", words/prefixes are sequences of module ~~applications~~ abstractions. (Sometimes we call "telescopes" such sequences of abstractions.)

> we have
>
> - a common environment to add abstract functor parameters that are bound only inside the functor
> - a substitution that represent equations between the expected and actual argument

This is too abstract for me and I would need an example (or to think hard about it, but who wants to do that?). Would you introduce some documentation for `Functor_inclusion_diff.Defs.state`, with an example?

**Comment by Octachron** [comment]
> Would you introduce some documentation for Functor_inclusion_diff.Defs.state,

This would not be the right place for such documentation, since your questions concern the typing of functor applications or functor inclusion in general and are not related to the diffing algorithm.

**Comment by Octachron** [comment]
I added some more comments (and one fix for an error detected while writing the comments). More generally, the higher level specification of `update` in function of the move in the edit matrix is that:

- `Keep` update the typing environment as usual (it is the only case which updates the set of equalities between modules).

- `Delete` and `Insert` add their consumed module to the environment if it was an abstract parameter (always for `Insert`, and while typing functor inclusion in the `Delete` case). This is useful because those abstract modules may contain equations between exterior component:

Consider for instance:
```ocaml
module _: sig
    module F: functor (X: sig type 'a t = 'a * 'a end)(Y: sig type 'a t = 'a X.t * 'a list end) -> sig end
end = struct
    module F(X: sig type 'a s = 'a list end)(Y: sig type 'a t = ('a * 'a) * 'a X.s end) = struct end
end
```
The second parameters ought to be considered as matching because they both extend to
```ocaml
sig type 'a t = ('a * 'a) * 'a list
```
however this equality rely on the type abbreviations defined in the diverging first arguments `X`.

- `Change` is `Delete` + `Insert`.

File: typing/includemod.ml [hunk 1]
```diff
@@ -1038,23 +1038,38 @@ module Functor_inclusion_diff = struct
...
+    | Change (Named (Some id, arg), (Unit|Named(None,_)), _) ->
+        (* One named parameter that doesn't match it anonymous counterpart,
+           we add it to the typing environment because it may
+           contain useful abbreviations. *)
         let arg' = Subst.modtype Keep st.subst arg in
         let env = Env.add_module id Mp_present arg' st.env in
         expand_params { st with env }
-    | Keep (Named (name1, _), Named (name2, arg2), _)
-    | Change (Named (name1, _), Named (name2, arg2), _) -> begin
+    | Change (Named (Some id, arg), Named(Some id2, arg2), _) ->
```
Comment (gasche) [inline typing/includemod.ml]: Nitpick: I would find `id1, arg1` more regular (as you had before).

**Review by gasche — COMMENTED** [review]
I looked at the Functor_inclusion_diff part (not the Function_app_diff part), it looks okay. The new comments are really helpful for me to make sense of what is going on.

File: typing/includemod.ml [hunk 2]
```diff
@@ -566,24 +566,25 @@ and functor_param ~in_eq ~loc env ~mark subst param1 param2 =
...
-        | None, Some id2 ->
-            let id1 = Ident.rename id2 in
-            Env.add_module id1 Mp_present arg2' env,
-            Subst.add_module id2 (Path.Pident id1) subst
-        | Some id1, None ->
-            Env.add_module id1 Mp_present arg2' env, subst
-        | None, None ->
-            env, subst
-      in
+      let env, subst = equate_one_functor_param subst env arg2' name1 name2 in
```
Comment (gasche) [inline typing/includemod.ml:569]: Nit: I would have `env` before `subst` in the parameter list, because `subst` lives "over" `env` (its well-formedness depends on the value of `env`).

File: typing/includemod.ml [hunk 3]
```diff
@@ -1059,25 +1060,12 @@ module Functor_inclusion_diff = struct
         let arg2 = Subst.modtype Keep st.subst arg2 in
         let env = Env.add_module id2 Mp_present arg2 env in
         expand_params { st with env }
-    | Keep (Named (name1, _), Named (name2, arg2), _) -> begin
-        let arg' = Subst.modtype Keep st.subst arg2 in
-        match name1, name2 with
-        | Some id1, Some id2 ->
-            (* two matching abstract parameters: we add one identifier to the
-               environment and record the equality between the two identifiers
-               in the substitution *)
```
Comment (gasche) [inline typing/includemod.ml]: Could we preserve this comment? I found it helpful.

File: typing/includemod.ml [hunk 4]
```diff
@@ -566,24 +566,25 @@ and functor_param ~in_eq ~loc env ~mark subst param1 param2 =
...
-        match name1, name2 with
-        | Some id1, Some id2 ->
-            Env.add_module id1 Mp_present arg2' env,
-            Subst.add_module id2 (Path.Pident id1) subst
-        | None, Some id2 ->
-            let id1 = Ident.rename id2 in
-            Env.add_module id1 Mp_present arg2' env,
-            Subst.add_module id2 (Path.Pident id1) subst
-        | Some id1, None ->
-            Env.add_module id1 Mp_present arg2' env, subst
```
Comment (gasche) [inline typing/includemod.ml:579]: Question: in the error code there was a nice symmetry between the `None, Some` and the `Some, None` case, this is not the case here -- there is a rename in one case and not in the other. Why the difference?

**Review by gasche — COMMENTED** [review]
(looking just at the new commit)

File: typing/includemod.ml (hunk 3 above)
Comment (Octachron) [reply typing/includemod.ml]: Good point, I will add the comment to the new shared function.

File: typing/includemod.ml (hunk 1 above)
Comment (gasche) [reply typing/includemod.ml]: Along with @Octachron I wondered if `Change` could be implemented by just calling the function recursively twice on `Delete` then `Insert`.

File: typing/includemod.ml [hunk 5]
```diff
@@ -1119,43 +1122,38 @@ module Functor_app_diff = struct
...
+            st.res
+        in
+        let subst = Subst.add_module param arg st.subst in
+        I.expand_params { st with subst; res }
+    | Keep (((Anonymous|Empty_struct), mty),
+            Named (Some param, _param), _) ->
+        let mty' = Subst.modtype Keep st.subst mty in
+        let env = Env.add_module ~arg:true param Mp_present mty' st.env in
+        let res = Option.map (Mtype.nondep_supertype env [param]) st.res in
+        I.expand_params { st with env; res}
```
Comment (gasche) [inline typing/includemod.ml:1157]: I reviewed this part with @Octachron's help and I agree that it does what it says it does.

File: typing/includemod.ml [hunk 6]
```diff
@@ -1038,31 +1039,33 @@ module Functor_inclusion_diff = struct
...
+        let env = Env.add_module id Mp_present arg st.env in
+        let arg2 = Subst.modtype Keep st.subst arg2 in
+        let env = Env.add_module id2 Mp_present arg2 env in
+        expand_params { st with env }
+    | Keep (Named (name1, _), Named (name2, arg2), _) ->
+        let arg = Subst.modtype Keep st.subst arg2 in
+        let env, subst =
+          equate_one_functor_param st.subst st.env arg name1 name2
+        in
+        expand_params { st with env; subst }
```
Comment (gasche) [inline typing/includemod.ml:1069]: The nice refactoring has the slight downside of having heterogeneous abstraction levels across the different cases here, a minor issue which could be solved by moving the Subst+Env logic to their own auxiliary functions as well.

**Review by gasche — APPROVED** [review]
Approved, with minor nitpicks to be taken into account or not depending on the author's whims.

File: typing/includemod.ml (hunk 4 above)
Comment (Octachron) [reply typing/includemod.ml:579]: This is a bugfix from #10693 to avoid potential identifier collisions in the non-error path.

File: typing/includemod.ml (hunk 1 above)
Comment (Octachron) [reply typing/includemod.ml]: I went with the recursive call in the last version.

File: typing/includemod.ml (hunk 2 above)
Comment (Octachron) [reply typing/includemod.ml:569]: I would rather keep the same order as the one in the non-error path.

File: typing/includemod.ml (hunk 6 above)
Comment (Octachron) [reply typing/includemod.ml:1069]: I have added a small auxiliary function for binding abstractions in the environment.

**Review by gasche — APPROVED** [review]
I am happy with the new state of the code, and the extra documentation. Approved.

**Comment by Octachron** [comment]
Since this is a localized bug fix, I am thinking of cherry-picking it to 4.14 . Any objections?

**Comment by gasche** [comment]
Sounds fine to me.
