### PR TITLE
Fix regression in #12403: quote source code also for marshalled ASTs

### LINKED ISSUE #12697: Errors for marshalled ASTs no longer print relevant source code
I'm pretty sure this is caused by #12403.  I believe it's a regression because I don't see it acknowledged as a consequence in the discussion there, but it's possible it was intended, in which case just close this.

Here is an incorrect program:
```ocaml
let x : int = true
```

On `trunk`, we print the error differently depending on whether the source file itself is passed to the compiler, or we pass a marshalled AST.  Here is the error for the former:
```
File "foo.ml", line 1, characters 14-18:
1 | let x : int = true
                  ^^^^
Error: This expression has type bool but an expression was expected of type
         int
```
And here is the latter:
```
File "foo.ml", line 1, characters 14-18:
Error: This expression has type bool but an expression was expected of type
         int
```
To produce the latter, put the bad program in a file named `foo.ml`, and then run this script in the toplevel:
```ocaml
#directory "+compiler-libs";;
#load "ocamlcommon.cma";;
let ast = Pparse.parse_implementation ~tool_name:"test" "foo.ml";;
Pparse.write_ast Pparse.Structure "foo.marshalled.ml" ast;;
```
(And then run the compiler on the resulting `foo.marshaled.ml`)

I haven't read the code of #12403, but based on the description I suspect the issue is that when compiling marshalled asts, we relied entirely on the "fallback" path of re-reading the source file to give nice errors, and that fallback has been removed.

(I noticed this while rebasing #12451, which adds a test that the reworked warning 53 works appropriately for marshalled asts.  I only have that test there because I got it wrong initially, but probably we should have more such tests.)

cc @gasche

### PR DESCRIPTION
**Pull request by nojb**
As mentioend in #12697, it appears that #12403 introduced a regression: when reading marshalled ASTs the compiler no longer quotes any source code in error messages. This is because the compiler no longer reads in the source file corresponding to the marshalled AST.

This PR proposes a fix by reading (if possible) the source file when unmarshalling the AST and making it available to later error printers.

Assigning to @gasche who authored #12403.

Fixes #12697

### CODE REVIEW

**Review by gasche — COMMENTED** [review]
I believe that the change is correct and I find it somewhat ingenious (it is interesting that our infrastructure, despite being a bit ad-hoc and full of mutable state, allows us to do this easily). But I don't like the duplication of "read the whole file at once" logic, that is, the pair of `In_channel.input_all` and the explanatory comment, which is reproduced here in a slightly less informative version than it appears below.

This could be fixed by having an auxiliary function that has the logic and the comment, and is called in both cases -- parsing a source file or consuming a serialized ast. This could be a local function `set_input_lebxuf : in_channel -> unit` that is in charge of reading the whole source file and storing it in `Location.input_lexbuf`. (The caller in the parse-a-source-file case is still responsible for `seek_in`.)

**Comment by nojb** [comment]
> This could be fixed by having an auxiliary function that has the logic and the comment, and is called in both cases -- parsing a source file or consuming a serialized ast.

Thanks for the suggestion. Pushed a commit in this direction: ddd84f8f14105b57cd253d21497d0a49ab38307d.

File: driver/pparse.ml [hunk 1]
```diff
@@ -175,14 +187,9 @@ let file_aux ~tool_name ~sourcefile inputfile (type a) parse_fun invariant_fun
...
-        begin match In_channel.with_open_bin !Location.input_name In_channel.input_all with
-        | source ->
-            (* If the source file for the marshalled AST is found, then read it
-               fully into a lexing buffer to make it available to error printers
-               to quote source code at specific locations. *)
-            Location.input_lexbuf := Some (Lexing.from_string source)
-        | exception Sys_error _ ->
-            ()
+        begin match In_channel.with_open_bin !Location.input_name set_input_lexbuf with
+        | (_ : Lexing.lexbuf) -> ()
```
Comment (gasche) [inline driver/pparse.ml:193]: It's nice that your own warning forced you to add an annotation :-)

**Review by gasche — APPROVED** [review]
