### PR TITLE
Make Ephemeron compatible with infix pointers.

### LINKED ISSUE #9485: Segfault in Weak.get_copy with Infix_tag
The implementation of `Weak.get_copy` is missing the special case necessary to handle `Infix_tag`, so it can corrupt memory:
```
        OCaml version 4.10.0

# let w = Weak.create 1 in
  let rec f () = g () and g () = f () in
  Weak.set w 0 (Some g);
  match Weak.get_copy w 0 with Some h -> h () | _ -> ();;
Segmentation fault
```
I don't think this is particularly urgent to fix, because it's been there a long time without anyone noticing:
```
        Objective Caml version 3.10.2

# let w = Weak.create 1 in
  let rec f () = g () and g () = f () in
  Weak.set w 0 (Some g);
  match Weak.get_copy w 0 with Some h -> h () | _ -> ();;        
Segmentation fault
```

### PR DESCRIPTION
**Pull request by jhjourdan**
This fixes #9485 and #7810.

Cc @bobot, @damiendoligez.

### CODE REVIEW

**Comment by jhjourdan** [comment]
I am not completely sure I did not miss any patch, perhaps, @bobot, you could check a bit more.

**Comment by jhjourdan** [comment]
Since this is a bugfix, this could be back ported to 4.11. That said, given that this bug exists for a long time for weak pointers and nobody was really annoyed, this may not be necessary.

**Comment by xavierleroy** [comment]
@bobot, @damiendoligez : this is a bug fix for an area of the run-time system that you are responsible for.  Please review.

File: runtime/minor_gc.c [hunk 1]
```diff
@@ -343,7 +348,7 @@ void caml_oldify_mopup (void)
     }
   }
 
-  if (redo) caml_oldify_mopup ();
```
Comment (bobot) [inline runtime/minor_gc.c:346]: Just to clarify, I understand that this modification is independent of the bugfix, yes?

File: runtime/caml/weak.h [hunk 2]
```diff
@@ -191,6 +191,7 @@ Caml_inline void caml_ephe_clean_partial (value v,
           }
         }
       }
+      if (Tag_val (child) == Infix_tag) child -= Infix_offset_val (child);
       if (Is_white_val (child) && !Is_young (child)){
         release_data = 1;
         Field (v, i) = caml_ephe_none;
```
Comment (bobot) [inline runtime/caml/weak.h:197]: For the data case (below, I can't comment the line),  child should also get the infix treatment for the assert?

**Review by bobot — CHANGES_REQUESTED** [review]
Thank you for the heads up. I think one case remains to be done. However in #9424 I will need to add this infix handling in many places.

File: runtime/minor_gc.c (hunk 1 above)
Comment (jhjourdan) [reply runtime/minor_gc.c:346]: Indeed. But this is arguably also a bug since tail call optimization is not guaranteed in C.

File: runtime/caml/weak.h (hunk 2 above)
Comment (jhjourdan) [reply runtime/caml/weak.h:197]: I could, yes. But note that the assertion is true even in the current state (an infix header is always white). Also, in order to make sure the "infix treatment" is only performed in debug mode, and not when child is not a block, the code need to be a little involved.

Comment (jhjourdan) [reply runtime/caml/weak.h:197]: Just tell me what you prefer, I'll do the change.

Comment (bobot) [reply runtime/caml/weak.h:197]: I prefer the convoluted code, it already appears in other cases and this assert was very handy for checking #9424. Thank you for doing the change and for the whole PR, I understand better now in which case this tag must be handled.

Comment (jhjourdan) [reply runtime/caml/weak.h:197]: Wish granted.

**Comment by xavierleroy** [comment]
@bobot are you happy with the revised PR?  @damiendoligez would you care to comment?

**Review by bobot — APPROVED** [review]
I approve

**Comment by xavierleroy** [comment]
Thank you gentlemen, I'll merge now.  It's too late for a backport to 4.11, this will wait until 4.12.
