### PR TITLE
Fix #10189: Universal variables leaking through GADT equations

### LINKED ISSUE #10189: Universal variables leaking through GADT equations
There is a missing call to `occur_univar` somewhere in the GADT machinery. The following code should clearly be a type error:

```ocaml
# type i = <m : 'c. 'c -> 'c >
  type ('a, 'b) j = <m : 'c. 'a -> 'b >
  type _ t = A : i t;;
type i = < m : 'c. 'c -> 'c >
type ('a, 'b) j = < m : 'a -> 'b >
type _ t = A : i t

#  let f (type a b) (y : (a, b) j t) : a -> b =
      match y with
      | A -> fun x -> x;;
val f : ('a, 'b) j t -> 'a -> 'b = <fun>
```

The univar from inside `i` is leaking out into the equations for `a` and `b` allowing them to be made unexpectedly equal. I believe this bug cannot cause any soundness issues as the cases where it happens must be dead. However, we still shouldn't allow unbound universal variables to wonder around unattended.

### PR DESCRIPTION
**Pull request by garrigue**
Fix #10189 by checking for leaking univars before adding an equation to the environment.

### CODE REVIEW

**Review by trefis — APPROVED** [review]
LGTM.

**Comment by garrigue** [comment]
I'll wait for @lpw25 to have a look at it, to be sure we agree.

**Review by lpw25 — COMMENTED** [review]
The fix looks good to me.

I think it would be good to also catch this case in `mcomp` too, to
keep its behaviour in sync with the cases of `unify3` that add gadt
equations.

My mental model of the GADT unification is that it will only fail
if `mcomp` would fail. Whilst the cases in `unify3` that add
equations do not explicitly call `mcomp`, they will only apply in
cases where `mcomp` would have succeeded. I think they should
also only fail in cases where `mcomp` would have failed.

Here is an example that would be affected by changing `mcomp`:

```ocaml
# module M = struct
    type a
    type i = C of <m : 'c. 'c -> 'c >
    type j = C of <m : 'c. 'c -> a >
  end
  type _ t = A : M.i t;;
module M :
  sig
    type a
    type i = C of < m : 'c. 'c -> 'c >
    type j = C of < m : 'c. 'c -> a >
  end
type _ t = A : M.i t

# let f (y : j t) = match y with _ -> .;;
Line 1, characters 31-32:
1 | let f (y : j t) = match y with _ -> .;;
                                   ^
Error: This match case could not be refuted.
       Here is an example of a value that would reach it: A
```

and to be on the safe side, here is an example that should
not change:

```ocaml
# module M = struct
    type 'a a
    type i = C of <m : 'c. 'c -> 'c >
    type j = C of <m : 'c. 'c -> 'c a >
  end
  type _ t = A : M.i t;;
module M :
  sig
    type 'a a
    type i = C of < m : 'c. 'c -> 'c >
    type j = C of < m : 'c. 'c -> 'c a >
  end
type _ t = A : M.i t

# let f (y : j t) = match y with _ -> .;;
Line 1, characters 31-32:
1 | let f (y : j t) = match y with _ -> .;;
                                   ^
Error: This match case could not be refuted.
       Here is an example of a value that would reach it: A
```

**Comment by garrigue** [comment]
@lpw25 Actually, the specification of `mcomp` is just that it must succeed if unification might succeed for some definition of the abstract types in the environment.
Due to incompleteness, the converse is not true.
Of course, it should be as close as possible to unification, but since it does not instantiate type variables, it cannot be very precise.

It is possible to obtain the behavior you suggest on these examples by prohibiting unifiying univars with non-parametric type constructors (I enclose the diff below), but this is ad hoc.
In particular, this wouldn't work if we use
```
type i = C of < m : 'c. 'c -> 'c -> 'c >
type j = C of < m : 'c. 'c -> a >
```
for instance. For this we would need to have `occur_univar` work in two modes, the second one ensuring that the univar cannot disappear through expansion of (possibly unknown) types.
I'm not sure this is worth the effort.

```diff
--- a/typing/ctype.ml
+++ b/typing/ctype.ml
@@ -2264,10 +2264,14 @@ let rec mcomp type_pairs env t1 t2 =
             mcomp_list type_pairs env tl1 tl2
         | (Tconstr (p1, tl1, _), Tconstr (p2, tl2, _)) ->
             mcomp_type_decl type_pairs env p1 p2 tl1 tl2
-        | (Tconstr (p, _, _), _) | (_, Tconstr (p, _, _)) ->
+        | (Tconstr (p, tl, _), td) | (td, Tconstr (p, tl, _)) ->
             begin try
-              let decl = Env.find_type p env in
-              if non_aliasable p decl || is_datatype decl then raise (Unify [])
+              if match td with
+                Tunivar _ when tl = [] -> true
+              | _ ->
+                  let decl = Env.find_type p env in
+                  non_aliasable p decl || is_datatype decl
+              then raise (Unify [])
             with Not_found -> ()
             end
         (*
```

**Comment by garrigue** [comment]
After some hesitation I have committed the real thing, which uses `occur_univar ~must_occur:true` to detect guaranteed occurrences. Please have a look. I can easily remove the last commit if it looks dubious.

**Comment by garrigue** [comment]
Actually, extending `occur_univar` is really needed, as we should only fail when adding gadt equations in the `must_occur:true` case, otherwise exhaustiveness may be unsound.
As a result, extending `mcomp` too seems reasonable, even if this is just a corner case. (Note that it reflects a case in the rules I gave for modular implicit unification.)

File: typing/ctype.ml [hunk 1]
```diff
@@ -2264,10 +2265,14 @@ let rec mcomp type_pairs env t1 t2 =
...
             begin try
-              let decl = Env.find_type p env in
-              if non_aliasable p decl || is_datatype decl then raise (Unify [])
+              if tl = [] &&
+                (try occur_univar ~must_occur:true env (newgenty td); false
+                  with Unify _ -> true)
+              || (let decl = Env.find_type p env in
+                  non_aliasable p decl || is_datatype decl)
+              then raise (Unify [])
             with Not_found -> ()
```
Comment (lpw25) [inline typing/ctype.ml]: This code looks correct, but might I suggest something like:
```ocaml
        | (Tconstr (_, [], _), _) when must_occur_univar t2' -> raise (Unify [])
        | (_, Tconstr (_, [], _)) when must_occur_univar t1' -> raise (Unify [])
        | (Tconstr (p, _, _), _) | (_, Tconstr (p, _, _)) ->
            begin try 
              let decl = Env.find_type p env in 
              if non_aliasable p decl || is_datatype decl then raise (Unify []) 
            with Not_found -> ()
```
where `must_occur_univar` is defined as:
```ocaml
let must_occur_univar env t =
  match occur_univar ~must_occur:true env t with
  | () -> false
  | exception Unify _ -> true
```

File: typing/ctype.ml [hunk 2]
```diff
@@ -2441,6 +2446,9 @@ let find_expansion_scope env path =
 let add_gadt_equation env source destination =
   (* Format.eprintf "@[add_gadt_equation %s %a@]@."
     (Path.name source) !Btype.print_raw destination; *)
+  let univar_leaks =
+    try occur_univar !env destination; false with Unify _ -> true in
+  if univar_leaks then occur_univar ~must_occur:true !env destination else
   if local_non_recursive_abbrev !env source destination then begin
```
Comment (lpw25) [inline typing/ctype.ml]: Good catch. This does indeed look correct and the previous version was unsafe.

This code would benefit from a function like:
```ocaml
let can_occur_univar env t =
  match occur_univar ~must_occur:false env t with
  | () -> false
  | exception Unify _ -> true
```

File: typing/ctype.ml [hunk 3]
```diff
@@ -1937,7 +1937,7 @@ let rec unify_univar t1 t2 = function
 
 (* Test the occurrence of free univars in a type *)
 (* that's way too expensive. Must do some kind of caching *)
-let occur_univar env ty =
```
Comment (lpw25) [inline typing/ctype.ml:1940]: This will sound familiar: I'm not keen on using an optional parameter here. All occurences of `occur_univar` are local to this file, we might as well add the argument to them all and avoid any risk of using the wrong version by accident.

**Review by lpw25 — APPROVED** [review]
LGTM

**Comment by garrigue** [comment]
Notre that this PR uncovered a soundness bug, I suppose that this should be fixed in 4.12 too.
I'm thinking a making a smaller PR for that, with just the extension of `occur_univar` and `unify3_var`. Thoughts?

**Comment by Octachron** [comment]
This is too late for 4.12.0, you should consider that it has been released last week.

Moreover, if I read your example correctly, the soundness bug is the result of a three-body interaction between:

- polymorphic methods
- non-injective type
- GADTs

That degree of complexity to trigger the issue does not seem to warrant an emergency 4.12.1 release.

**Comment by gasche** [comment]
Let's take the time to look at the smaller/simpler PR and have you explain the issue, and see what is the state of release branches at this point. (4.12.0 will have shipped, but maybe not the next 4.11, nor the next 4.12.)

**Comment by garrigue** [comment]
Note that the (fixed) unsoundness example exhibits a spurious principality warning about a generated counter-example.
This is not directly related with the current bug, but this should also be fixed, in a separate PR.

File: testsuite/tests/typing-gadts/pr10189.ml [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+    type e
+    type 'a d
+    type i = < m : 'c. 'c -> 'c d >
+    type j = < m : 'c. 'c -> e >
+  end
+type _ t = A : M.i t
+Line 9, characters 2-20:
+9 |   let None = y in () ;;
+      ^^^^^^^^^^^^^^^^^^
+Warning 8 [partial-match]: this pattern-matching is not exhaustive.
```
Comment (mrmr1993) [inline testsuite/tests/typing-gadts/pr10189.ml:84]: Shouldn't the `Some A` case here be ruled out? I think you'll need to add an `occur_univar` check to instantiable `Tconstr`s in `unify3`.

Comment (garrigue) [reply testsuite/tests/typing-gadts/pr10189.ml:84]: Just add `type 'a d = e` in the above piece of code, and you can see that the `Some A` may really happen. We have to be extremely careful with those (and conservative when we don't know for sure).
