### PR TITLE
Fix #11869: weak variance for package types

### LINKED ISSUE #11869: Injectivity checker: change in behaviour since 5.0.0
#11018 has changed the behaviour of injectivity checking, so that it rejects definitions that were previously accepted.  I'm not sure whether the change was deliberate, but it doesn't appear to be documented.

In OCaml 5.0.0 (and in `trunk` before #11018 was merged):
```ocaml
# module type s = sig type t end;;
module type s = sig type t end
# type !'a t = (module s with type t = 'a);;
type 'a t = (module s with type t = 'a)
```

After #11018: 
```ocaml
# module type s = sig type t end;;
module type s = sig type t end
# type !'a t = (module s with type t = 'a);;
Line 1, characters 0-40:
1 | type !'a t = (module s with type t = 'a);;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: In this definition, expected parameter variances are not satisfied.
       The 1st type parameter was expected to be injective invariant,
       but it is invariant.
```
(Discovered here: https://github.com/ocaml/ocaml/pull/11830#pullrequestreview-1237097898)

### PR DESCRIPTION
**Pull request by garrigue**
#11018 wrongly weakened the variance of package types aka first class modules.
This fixes that: their parameters should indeed be invariant.

### CODE REVIEW

File: typing/typedecl_variance.ml [hunk 1]
```diff
@@ -88,9 +88,7 @@ let compute_variance env visited vari ty =
         compute_same ty
     | Tvar _ | Tnil | Tlink _ | Tunivar _ -> ()
     | Tpackage (_, fl) ->
-        let v =
-          Variance.(if mem Inv vari then full else unknown)
```
Comment (gasche) [inline typing/typedecl_variance.ml:92]: In #11018 you changed the code from (1)

```ocaml
let v = Variance.(if mem Pos vari || mem Neg vari then full else unknown)
```

to (2)

```ocaml
let v = Variance.(if mem Inv vari then full else unknown)
```

and now you propose a third version (3):

```ocaml
let v = Variance.(compose vari full)
```

Why not go back to the previous version (1), is this version (3) better? If I understand correctly, it is stronger than (1), it will return a stronger variance, while (2) was weaker than (1). Why is the new, stronger check correct?

Does the testsuite also contain negative examples checking that the variable inferred is not stronger than it should be?

Comment (garrigue) [reply typing/typedecl_variance.ml:92]: Because we now have a proper variance composition operator.
If the variance of the context is `vari` and the relative variance of a parameter is `v`, then the variance inside the parameter becomes `compose vari v`.
The previous variances were decided manually case by case, which was much more error prone.

There are tests in the testsuite in both directions (soundness and completeness), but I don't think they are exhaustive.

**Comment by garrigue** [comment]
If I understand correctly, #11018 is only in trunk (5.1) so there is no need to fix 5.0 in this case.

**Review by gasche — APPROVED** [review]

**Comment by gasche** [comment]
This is also my understanding.
