### PR TITLE
Fix #11865 by detecting deletion of a root during root scanning.

### LINKED ISSUE #11865: caml_remove_global_root in finalizer spins on roots_mutex
I'm testing the Sundials/ML library against OCaml 5.0.0. One of the examples spins forever after the following sequence:
1. The GC is triggered and `caml_scan_global_young_roots` locks `roots_mutex`.
2. During the subsequent scan, one of my finalizers in C is called and it invokes `caml_remove_global_root`.
3. The resulting call to `caml_delete_global_root` requests `roots_mutex` and spins until ^C.

The smallest failing example that I have been able to produce is as follows. Sorry it's not simpler.

`block_ml.c`:
```
#include <caml/alloc.h>
#include <caml/memory.h>

typedef struct cdata { value backlink; } *pcdata;
#define PCDATA(v) (*(pcdata *)Data_custom_val(v))

void mlfinalize(value val)
{
    pcdata v = PCDATA (val);
    caml_remove_global_root(&(v->backlink));
    free(v);
}

CAMLprim value mlwrap(value payload)
{
    CAMLparam1(payload);
    CAMLlocal1(vcptr);

    pcdata v = calloc(1, sizeof(struct cdata));
    v->backlink = payload;
    caml_register_global_root(&(v->backlink));

    vcptr = caml_alloc_final(1, mlfinalize, 1, 30);
    PCDATA(vcptr) = v;

    CAMLreturn(vcptr);
}
```

`block.ml`:
```
type ptr
type 'data t = { payload: 'data; cptr: ptr }

external c_wrap : 'a -> ptr = "mlwrap"
let make v = { payload = v; cptr = c_wrap v }

type gdata = ..
type gdata += RA of int
type gdata += VV of gdata t

let rec make_ra v = make (RA v)
and make_vv v = make (VV v)
and clone { payload; _ } =
  match payload with
  | RA v -> make_ra v
  | VV nv -> make_vv (clone nv)
  | _ -> assert false

let _ =
  let y = make_ra 7 in
  let x = make_vv y in
  let _ = clone x in
  Gc.major ();
  Gc.full_major ();
  let _ = clone y in
  Gc.minor ()
```
To reproduce, compile with `ocamlopt -o block block_ml.c block.ml`, run `block`, and terminate it with Ctrl-C. The description above summarizes the back trace generated by valgrind or gdb.

It's always possible that the C interface code is not correct, but I can't see the problem...

### PR DESCRIPTION
**Pull request by stedolan**
If a C finaliser for a custom object tries to unregister a root with `caml_remove_global_root` or `caml_remove_generational_global_root`, then the runtime currently deadlocks (or otherwise goes wrong, platform-dependent) by trying to recursively acquire a nonrecursive mutex.

Changing this to a recursive mutex would not help: even if we got past the locking code, deleting a root while iterating would then corrupt the skiplist. The problem is that a data structure (the roots skiplist) is being modified during iteration.

The fix is straightforward: instead of removing roots during iteration, mark them to be deleted lazily. There's also a test, which deadlocks before this patch and succeeds after.

**FAQ** (foreseeably asked questions):

  - **Why use a thread-local variable to detect iteration?**
    If a root is deleted while _another thread_ is iterating, there is no problem: it simply waits for the lock as usual, and the iteration will be complete before the root is deleted. The problem only arises when the current thread is the one iterating.

  - **Why not always use lazy deletion, instead of detecting when an iteration is occurring?**
    It is possible for a large number of roots to be created and removed within the same GC cycle. Lazy deletion while no root scan is in progress would cause the size of the skiplist to grow without bound.

  - **Doesn't lazy deletion make the skiplist bigger in any case?**
    Yes, but by a bounded amount. The maximum length of the skiplist with this patch is at most double the length before it, since lazily deleted nodes are (a) only created during root scanning and (b) deleted during either the same root scanning cycle or the next one.

  - **What if a new root is added with the same address as one being lazily deleted?**
    This works fine: `caml_skiplist_insert` overwrites the current entry if the key is already present, so the lazy deletion node will be overwritten with a normal root.

### CODE REVIEW

**Comment by jberdine** [comment]
Thanks, it would be great to see the return of the ability to unregister roots from finalizers. Minor nit, it would be good to partially roll back the manual change from https://github.com/ocaml/ocaml/pull/11876 that states that global roots must not be (un)registered from finalizers.

File: runtime/globroots.c [hunk 1]
```diff
@@ -52,15 +60,22 @@ struct skiplist caml_global_roots_old = SKIPLIST_STATIC_INITIALIZER;
...
 
 Caml_inline void caml_delete_global_root(struct skiplist * list, value * r)
 {
-  caml_plat_lock_blocking(&roots_mutex);
-  caml_skiplist_remove(list, (uintnat) r);
-  caml_plat_unlock(&roots_mutex);
+  if (iterating_roots > 0) {
+    uintnat* p = caml_skiplist_find_ptr(list, (uintnat) r);
+    if (p != NULL) {
+      *p = ROOT_DELETED;
```
Comment (mshinwell) [inline runtime/globroots.c:73]: I think it might be worth adding a comment that this write cannot race (if I understand correctly, that is) with a write (from another thread) corresponding to re-use of an existing skiplist cell in `caml_skiplist_insert` because on this line 72, we always hold the lock, so any caller to that function (from this file, where all such calls are protected by the lock) is going to have to wait.

File: runtime/globroots.c [hunk 2]
```diff
@@ -27,9 +27,17 @@
 
 static caml_plat_mutex roots_mutex = CAML_PLAT_MUTEX_INITIALIZER;
 
+/* Greater than zero when the current thread is scanning the roots */
+static CAMLthread_local int iterating_roots = 0;
```
Comment (mshinwell) [inline runtime/globroots.c:31]: Was there a particular reason this takes values other than 0 and 1?

**Comment by mshinwell** [comment]
A couple of comments, but this looks correct to me.

File: runtime/globroots.c (hunk 2 above)
Comment (stedolan) [reply runtime/globroots.c:31]: No, I'm fairly sure it's only ever 0 or 1, but it was easier to be robust to the possibility of higher numbers than to verify that they definitely never occur.

File: runtime/globroots.c [hunk 3]
```diff
@@ -241,16 +263,22 @@ void caml_scan_global_roots(scanning_action f, void* fdata) {
...
 
   caml_iterate_global_roots(f, &caml_global_roots, fdata);
   caml_iterate_global_roots(f, &caml_global_roots_young, fdata);
 
   /* Move young roots to old roots */
   FOREACH_SKIPLIST_ELEMENT(e, &caml_global_roots_young, {
-      value * r = (value *) (e->key);
-      caml_skiplist_insert(&caml_global_roots_old, (uintnat) r, 0);
+      if (e->data == ROOT_DELETED) {
+        caml_skiplist_remove(&caml_global_roots_young, e->key);
```
Comment (damiendoligez) [inline runtime/globroots.c]: You don't need to do this, the whole skip list will be erased on line 280.

File: testsuite/tests/regression/pr11865/mkroot_stubs.c [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+static void box_finalize(value v)
+{
+  struct box** r = Data_custom_val(v);
+  caml_remove_global_root(&(*r)->nongen_root);
+  caml_remove_generational_global_root(&(*r)->gen_root);
+  free(*r);
+}
+
+static struct custom_operations box_ops = {
+  "_box",
```
Comment (damiendoligez) [inline testsuite/tests/regression/pr11865/mkroot_stubs.c]: Identifiers starting with "_" are (informally) reserved to the OCaml runtime.
```suggestion
  "box",
```

**Review by damiendoligez — APPROVED** [review]
Looks good modulo two small remarks. Thanks for finding a simple solution to this hairy problem. Don't forget to update the manual (line 2034 of `manual/src/cmds/intf-c.etex`).

File: testsuite/tests/regression/pr11865/mkroot_stubs.c (hunk 4 above)
Comment (stedolan) [reply testsuite/tests/regression/pr11865/mkroot_stubs.c]: Fixed

File: runtime/globroots.c (hunk 3 above)
Comment (stedolan) [reply runtime/globroots.c]: Good point! (I was overeager in copypasting the logic of `caml_iterate_global_roots`). Fixed.

File: runtime/globroots.c (hunk 1 above)
Comment (stedolan) [reply runtime/globroots.c:73]: Done.

**Comment by stedolan** [comment]
I've updated the manual accordingly.

**Review by mshinwell — APPROVED** [review]

**Comment by gasche** [comment]
I was looking at this change again in the context of #13732 and was confused: it's not clear what exactly leads to a deadlock between skiplist traversal and skiplist element removal in the handling of custom block finalizers. In particular I expected the issue to come from finalizing a custom block on the minor heap (because those are typically more trouble), but minor custom blocks are not finalized during any kind of root traversal, as far as I can see, they are finalized in `custom_finalize_minor` which a distinct phase of the minor GC.

My current guess as to what is happening is that the finalizers causing trouble are those in the major heap. We are traversing the set of global generational young roots during a minor GC, we call `oldify_*` on the values reachable from those, which allocates into the major heap; the major heap works to find a place for the promoted value, and in the process it decide to do some sweeping work. At this point it can call a custom block finalizer, when sweeping the value.

This class of issues could possibly be avoided by storing custom blocks separately in the major heap, to be swept during major GC work only. The goal is not to increase the expressivity of custom block finalizers (they are still called during a minor GC, so fairly restricted in what is safe), but to relax the constraint that root-registration implementations must support reentrant removal in the middle of scanning. (Or is there another general reason why we should assume that root registration, modification, deletion can happen during root scanning?)

**Comment by stedolan** [comment]
> My current guess as to what is happening is that the finalizers causing trouble are those in the major heap. We are traversing the set of global generational young roots during a minor GC, we call `oldify_*` on the values reachable from those, which allocates into the major heap; the major heap works to find a place for the promoted value, and in the process it decide to do some sweeping work. At this point it can call a custom block finalizer, when sweeping the value.

Yes, that sounds right to me.

> This class of issues could possibly be avoided by storing custom blocks separately in the major heap, to be swept during major GC work only. The goal is not to increase the expressivity of custom block finalizers (they are still called during a minor GC, so fairly restricted in what is safe), but to relax the constraint that root-registration implementations must support reentrant removal in the middle of scanning. (Or is there another general reason why we should assume that root registration, modification, deletion can happen during root scanning?)

I don't understand the motivation here - lazy deletion is easy to implement (see this patch, but I struggle to imagine a root-registration scheme where it would be hard), and the constraint that root removal must never happen during scanning is tricky to enforce (see the bug this patch fixes, and its various other attempted fixes). Could you explain your goal here a bit more? (Also, when you say "class of issues", what are you thinking of beyond #11865?)
