### PR TITLE
Fix #7902: Type-checker infers a recursive type, even though -rectype…

### LINKED ISSUE #7902: Type-checker infers a recursive type, even though -rectypes is off
**Original bug ID:** 7902
**Reporter:** @fpottier
**Assigned to:** @garrigue
**Status:** acknowledged (set by @garrigue on 2019-01-29T00:53:04Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.07.1
**Category:** typing
**Monitored by:** @nojb @yallop

## Bug description

I have come across a code snippet where OCaml 4.07.1 infers a recursive type, even though -rectypes is off.

The code is as follows:
```ocaml
type ('a, 'b) segment =
  | SegNil  : ('a, 'a) segment
  | SegCons : ('a * 'a, 'b) segment -> ('a, 'b) segment

let color (* : type a b . (a, b) segment -> int *) =
  fun s ->
    match s with
    | SegNil ->
        0
    | SegCons SegNil ->
        0
    | SegCons _ ->
        0
```
Here is the inferred type:
```
val color : ('a * 'a as 'a, 'a) segment -> int = <fun>
```
If I uncomment the type annotation, the code is accepted (as it should be).

If I turn on -principal, the code is rejected (as it should be).

Still, I find it strange that a recursive type is allowed to appear when -rectypes is off.

### PR DESCRIPTION
**Pull request by garrigue**
Fixes #7902.
Turn on lax typing of recursion only in check mode of `type_pat`.

### CODE REVIEW

File: testsuite/tests/typing-gadts/pr7374.ml [hunk 1]
```diff
@@ -29,16 +29,22 @@ Error: This expression has type (a, a) eq
...
+let magic : type a b. a -> b =
+  fun x ->
+    let Refl = (Bad.uniq Refl : (a,Bad.t) eq) in
+    let Refl = (Bad.uniq Refl : (b,Bad.t) eq) in x
+[%%expect{|
+module Id : sig type 'a t = 'b constraint 'a = [ `Rec of 'b ] end
+Line 4, characters 13-16:
+4 | module Bad = Fix(Id)
+                 ^^^
+Error: Unbound module Fix
```
Comment (Octachron) [inline testsuite/tests/typing-gadts/pr7374.ml:46]: Is this test really supposed to check the nonexistence of `Fix`?

Comment (garrigue) [reply testsuite/tests/typing-gadts/pr7374.ml:46]: Originally, there was a comment saying "if I can define `Fix` then I can prove unsoundness". It was accompanied with some commented out code, that was unfortunately incomplete.
I prefer leaving the complete code around, even if it will just generates an extra error.
It makes easier to see what's wrong when Fix becomes definable.

Comment (Octachron) [reply testsuite/tests/typing-gadts/pr7374.ml:46]: Thanks for the explanation. Maybe the comment

>  (* Trigger the unsoundness *)

could be updated to

>  (* Trigger the unsoundness if Fix were definable*)

**Comment by xavierleroy** [comment]
This is a bug fix.  Please finish the review.

**Comment by Octachron** [comment]
Should use cases like
```ocaml
type (_,_) def = W:  ('a, 'a list) def
let three (type t) (W: (t,t) def) (x:t): t = [ x ; [ x ] ; [[x]] ]
```
be classified as bugs?
The GADT witness is used to manipulate values with a recursive type without `-rectypes`, but the type of `three` itself is not recursive.

**Comment by garrigue** [comment]
> ```ocaml
> type (_,_) def = W:  ('a, 'a list) def
> let three (type t) (W: (t,t) def) (x:t): t = [ x ; [ x ] ; [[x]] ]
> ```

The PR refuses this example. The opposite would be confusing, as one does not expect such a seemingly heterogeneous list to be typable.

**Comment by garrigue** [comment]
Note that your statement is always true before this PR: the recursive types we can construct currently are only local, and you can only see them in error messages.

**Comment by Octachron** [comment]
My example was more an illustration of a function that is currently accepted and rejected with after this PR. Rejecting it seems perfectly fine to me, but I think it is useful to state explitly that such intentional use of GADT to locally enable recursive types ought to be rejected.

**Comment by garrigue** [comment]
The rationale to disallow it is the same as for usual recursive types: most often this is a programming error. You can of course enable it by using `-rectypes` if you want.

But you have a point that we may want to check that this _feature_ is not used in the wild.
How do I run this check on opam?

**Comment by Octachron** [comment]
I don't expect this "feature" to be used, but I will run opamcheck with this pr.

**Comment by gasche** [comment]
@Octachron were you by chance able to run opamcheck?

**Comment by Octachron** [comment]
There is an opamcheck run in progress that should be finished by the end of the week (refreshing the opamcheck image took some time).

**Review by lpw25 — APPROVED** [review]
The code looks good to me and I think it behaves as described. Once the opam check is done this is good to merge.

**Comment by Octachron** [comment]
Some time after the battle, it seems that unsurprisingly no one is using GADTs to avoid using "-rectypes" in the opam repository: https://opamcheck.polychoron.fr/2020_06_15_4.10.0%2Bpr9556/fullindex.html .

**Comment by Octachron** [comment]
@garrigue , the change entry for this PR (no recursive types in GADTs without `-rectypes`) is in the 4.11 section but the PR was not cherry-picked to 4.11 . Is it fine if I fix the Change entry?

**Comment by garrigue** [comment]
Yes, it's fine.

**Comment by Octachron** [comment]
Ok, I have moved the change entry.
