### PR TITLE
Fix miscompilation of method delegation

### LINKED ISSUE #10763: Miscompilation of method delegation
````ocaml
module W = struct
  let r = ref (object method m x = Printf.printf "BAD %i\n%!" x end)
end

let proxy = object method m = (!W.r) # m end

let () =
  W.r := object method m x = Printf.printf "OK %i\n%!" x end;
  proxy # m 3
````

On 4.12.1 and on trunk, both with ocamlc and ocamlopt, this program prints "BAD 3" instead of "OK 3".  A first look at the output of -dlambda suggests that the method `m` on proxy is compiled using CamlinternalOO's `SendConst`, reading from the `W.r` reference when the proxy object is created.  This is not correct, because this read is impure.

### PR DESCRIPTION
**Pull request by alainfrisch**
Fix #10763

The first commit is quite conservative.  The second commit restores the original optimization when accessing an object directly bound in a toplevel compilation unit, or accessible by a trivial path module path (a module identifier), as in
````ocaml
module W = struct  let c = object method m x = Printf.printf "%i\n%!" x end end
let proxy = object method m = W.c # m end
````

But this wouldn't work with a nested module, so perhaps it's best to keep the second commit out (I don't think it's super useful).

I don't think one can do much better without keeping some mutability information on the `Pfield` primitive.

### CODE REVIEW

**Comment by lthls** [comment]
I've tried to think of cases where the second commit introduces the bug back.
I haven't managed to find one, but I think I'm quite close:
- Support for `[@@unboxed]` annotations on module types with only one physical component would allow compiling `!(M.r)` to a single `Pfield`
- If the `Rec_check` mode computation used `Delay` (as it should, in theory) for method bodies instead of `Dereference` then I would be able to build a problematic case using recursive values and first class modules.

My preferred fix would be to disable builtin methods (or at least the ones involved in this particular bug), but I would be willing to approve this PR restricted to its first commit too.

Regarding mutability information on `Pfield`, Flambda 2 includes such a patch but it would not be completely safe to use that because of recursive values (an immutable field load might only be valid if it's inside a function body, and this optimisation would lift it).

File: lambda/translclass.ml [hunk 1]
```diff
@@ -542,7 +541,8 @@ let const_path local = function
   | Lfunction {kind = Curried; body} ->
       let fv = free_variables body in
       List.for_all (fun x -> not (Ident.Set.mem x fv)) local
-  | p -> module_path p
+  | Lprim(Pfield _, [p], _) -> module_path p
```
Comment (garrigue) [inline lambda/translclass.ml]: Don't you also need a case for `Lprim(Pgetglobal _, [], _)` ?
Couldn't it happen if you pass a first class module wrapping a compilation unit ?

**Review by garrigue — APPROVED** [review]
LGTM

The original (broken) criterion was hacky, and it would certainly be better to use something more information than variable names to know what is a modules, but this looks conservative enough.

**Comment by gasche** [comment]
@lthls I'm not sure why the body of method definitions is marked Dereference in rec_check (in `class_field_kind`) -- it would be nice to have a comment explaining why in the code. The choice comes from @yallop's original PR #556 (`Use.inspect` in `class_field_kind`), and I think we just reused it when we reworked the mode system -- it's always safer to be conservative with these weirdly-compiled language features.

**Comment by alainfrisch** [comment]
@garrigue : I'd fell more confident with keeping the first commit only, as @lthls suggests.  Would you agree with this version as well, or do you think keeping the extra optimization in some cases is important enough?

**Comment by garrigue** [comment]
I have no strong opinion on that.
Considering the overhead in the object system, it is possible that this optimization does not make a big difference.
And you are one of the main users.
I would still suggest that you try this on your code base, to have an idea of whether it changes the code size significantly.
The goal of these optimizations was more to avoid the huge code size required by wrapper classes than to improve performance.

File: lambda/translclass.ml (hunk 1 above)
Comment (alainfrisch) [reply lambda/translclass.ml]: That's right, but it's a super-rare idiom, esp. because this requires that no coercion is needed between the compilation unit and the expected module type.

**Comment by alainfrisch** [comment]
> I would still suggest that you try this on your code base, to have an idea of whether it changes the code size significantly.

Our main executable goes from 74_474_496 to 74_501_632 bytes after the first commit (0.03% increase), and to 74_482_176 after the second commit (0.01% increase from base).

**Comment by garrigue** [comment]
I'll let you decide.
While 0.03% may seem small, this is still a 27KB difference, so if the second commit allows you to get back all of it, this may be worth it (or not).

**Comment by alainfrisch** [comment]
> so if the second commit allows you to get back all of it, this may be worth it (or not).

I've updated the note above.  With the second commit, I regain 2/3 of the loss.

As an extra data point, disabling all "builtin_methods", the size becomes 74_642_944 (0.22% increase from base).

**Comment by alainfrisch** [comment]
With these numbers, and considering @lthls remark that we are quite close to getting the bug back if we keep the second commit, I propose to keep only the first one.

@garrigue : aren't you concerned by the impact on LablGTK, which is another big user of OO features?

**Comment by alainfrisch** [comment]
Added a non-regression test and changelog entry (I've put it in 'Working version' -- perhaps it should go somewhere else if this is cherry-picked for a bug-fix release).

**Comment by Octachron** [comment]
As a miscompilation bug fix, you can move the change entry to the 4.14 section (and cherry-pick the PR to 4.14).

**Comment by alainfrisch** [comment]
> As a miscompilation bug fix, you can move the change entry to the 4.14 section (and cherry-pick the PR to 4.14).

Should this be a new section called 4.14.1?  (Also, wouldn't it make sense to base the PR against the 4.14 branch, and merge that one into master after the PR is merged?)

**Comment by Octachron** [comment]
The 4.14.0 section is the right one: we are still in the bug fix phase for 4.14.0/5.00 , only new features are frozen on the 4.14 branch.

**Comment by alainfrisch** [comment]
> The 4.14.0 section is the right one: we are still in the bug fix phase for 4.14.0/5.00 , only new features are frozen on the 4.14 branch.

Thanks, I've move the entry to 4.14.0. I though the next bug fix release on 4.14 would be 4.14.1, not 4.14.0+something, but you know better!

**Comment by gasche** [comment]
4.14.0 is not released yet

**Comment by alainfrisch** [comment]
> 4.14.0 is not released yet

Ah, that's the info I missed 😊    (To my defense, the first Google result for "ocaml 4.14.0" was https://opam.ocaml.org/packages/ocaml/ocaml.4.14.0/, which claimed 4.14.0 was released on June 3rd.)

**Comment by gasche** [comment]
> (To my defense, the first Google result for "ocaml 4.14.0" was https://opam.ocaml.org/packages/ocaml/ocaml.4.14.0/, which claimed 4.14.0 was released on June 3rd.)

This is confusing indeed, where does this come from? (cc @Octachron @kit-ty-kate @dra27 )

**Comment by lthls** [comment]
The package `ocaml.4.14.0` is released as soon as the version of trunk is switched to `4.14.0+...`, so in this case when the 4.13 branch was created. It's necessary for the people who build opam switches out of the trunk branch.

I believe that you can't create switches out of the `ocaml` packages directly though, so `opam switch list-available` should only contain `4.14.0+trunk` at this point, which is (probably? I haven't checked) based on the git 4.14 branch.

You'll note that there is already a package `ocaml.5.00.0` too, for similar reasons.

**Comment by Octachron** [comment]
The ocaml package is a virtual meta-package that is a dependency for the real ocaml packages. Unfortunately, this means that the ocaml package for version $N is a dependency for the trunk opam package (aka ocaml-variants.$N+trunk) which is created as soon as the version $(N-1) of ocaml is branched. The fact that this meta-package ends up being that visible on google sounds like an issue however.
