### PR TITLE
st_stubs.c: fix initialization of thread ID when a thread starts

### LINKED ISSUE #10477: Segmentation fault on Windows with OCaml 4.12
The [Ctypes library](https://github.com/ocamllabs/ocaml-ctypes/) has a [test](https://github.com/ocamllabs/ocaml-ctypes/blob/master/tests/test-lifetime/test_lifetime.ml) that checks that code generated by the library keeps objects alive while the runtime lock is released.  The test consistently passes with all combinations of OCaml versions and operating systems, except one: [OCaml 4.12 on Windows](https://github.com/ocamllabs/ocaml-ctypes/issues/677), where it fails with a segmentation fault.

Some investigation suggests that the bug is due to a problem in OCaml, introduced between 4.11 and 4.12.  The following cut-down program (also available [here](https://github.com/yallop/ocaml-windows-segfault)) doesn't use ctypes, but does trigger segmentation faults fairly reliably:

```ocaml
let alloc () =
  for i = 0 to 20000 do
    for i = 0 to 200; do ignore (Array.make 10 ()) done;
    ignore (Array.make 1000 ());
    if i mod 1000 = 0 then (Gc.compact ());
  done

let churn () =
  let allocators = List.init 10 (fun _ -> Thread.create alloc ()) in
  List.iter Thread.join allocators

let () = churn ()
```

As the CI logs for the program show, [on 4.11 the test runs reliably](https://github.com/yallop/ocaml-windows-segfault/runs/2915044196?check_suite_focus=true#step:5:21), while [on 4.12 it segfaults every few runs](https://github.com/yallop/ocaml-windows-segfault/runs/2915044243?check_suite_focus=true#step:5:25).

### PR DESCRIPTION
**Pull request by nojb**
Fixes #10477 

The crashing example given in #10477 runs "forever" with this fix, which is also [suggested](https://github.com/ocaml/ocaml/issues/10477#issuecomment-868638872) by @dra27.

### CODE REVIEW

**Comment by nojb** [comment]
(Fix needs to be cherry-picked to 4.12 and 4.13)

**Comment by dra27** [comment]
How long does @yallop’s repro case take to run? Is it worth adding to the PR?

**Comment by nojb** [comment]
> How long does @yallop’s repro case take to run? Is it worth adding to the PR?

image

But the failure is not deterministic; I had to run it ~10 times to get it to fail. Not sure how it would behave in the CI machines.

**Comment by dra27** [comment]
To me that’s fine - we’ve had a few of these recently where we get suspicious at the sporadic failure and so (belligerently!) investigate further. What do you think?

**Comment by dra27** [comment]
I may have just referred to a “decade” as “recently”, but there we are!

File: otherlibs/systhreads/st_stubs.c [hunk 1]
```diff
@@ -532,9 +532,9 @@ static ST_THREAD_FUNCTION caml_thread_start(void * arg)
 
   /* Associate the thread descriptor with the thread */
   st_tls_set(thread_descriptor_key, (void *) th);
-  st_thread_set_id(Ident(th->descr));
   /* Acquire the global mutex */
   caml_leave_blocking_section();
+  st_thread_set_id(Ident(th->descr));
```
Comment (xavierleroy) [inline otherlibs/systhreads/st_stubs.c:537]: If anyone is wondering about what's wrong in the original code: `th->descr` points to a block allocated in the OCaml heap.  So, if we don't hold the master lock, the block may be in the process of being moved by the GC or the compactor, and accessing it is a race condition.

**Review by xavierleroy — APPROVED** [review]
LGTM.

This should be backported  to the 4.12 and 4.13 branches, so please add a Changes entry in a new "OCaml 4.12 maintenance branch" section.

**Comment by xavierleroy** [comment]
I'm not a big fan of tests that fail only once in a while.

**Comment by xavierleroy** [comment]
@nojb or whoever will merge this PR: please amend the commit message.  It's not "fix acquisition of runtime lock", rather "Fix initialization of thread ID when a thread starts".  Then you can add my explanation in the commit message.

File: otherlibs/systhreads/st_stubs.c (hunk 1 above)
Comment (nojb) [reply otherlibs/systhreads/st_stubs.c:537]: Thanks, added the explanation to the commit message.

**Comment by nojb** [comment]
> @nojb or whoever will merge this PR: please amend the commit message. It's not "fix acquisition of runtime lock", rather "Fix initialization of thread ID when a thread starts". Then you can add my explanation in the commit message.

Amended.

**Comment by nojb** [comment]
`4.12` https://github.com/ocaml/ocaml/commit/60ae64584e5530edc587e8bab5f54ee4d320d5e9
`4.13` https://github.com/ocaml/ocaml/commit/91ec866ec6916d45d3cae325f22edc07780cda2c
