### PR TITLE
#10836: recognize unrecoverable errors in the signature inclusion check

### LINKED ISSUE #10836: Internal type-checker exception on mismatched type arity
The following invalid OCaml program causes the 4.13.1 type-checker to fail with an internal exception:

```ocaml
$ cat test.ml

module M : sig
  type (_, _) t

  val f : (_, _) t -> unit
end = struct
  type _ t

  let f _ = ()
end
```

```text
$ ocamlc test.ml
Fatal error: exception Invalid_argument("List.iter2")
Raised at Stdlib.invalid_arg in file "stdlib.ml" (inlined), line 30, characters 20-45
Called from Stdlib__List.iter2 in file "list.ml", line 148, characters 14-38
Called from Ctype.occur_univar.occur_desc in file "typing/ctype.ml", line 1952, characters 12-694
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Ctype.occur_univar_for in file "typing/ctype.ml", line 1981, characters 4-23
Called from Ctype.moregen_occur in file "typing/ctype.ml", line 3327, characters 2-33
Called from Ctype.moregen in file "typing/ctype.ml", line 3342, characters 8-37
Called from Ctype.moregen in file "typing/ctype.ml", line 3365, characters 14-54
...
```
<details>
<summary>
Click to see full stack trace
</summary>

```
Fatal error: exception Invalid_argument("List.iter2")
Raised at Stdlib.invalid_arg in file "stdlib.ml" (inlined), line 30, characters 20-45
Called from Stdlib__List.iter2 in file "list.ml", line 148, characters 14-38
Called from Ctype.occur_univar.occur_desc in file "typing/ctype.ml", line 1952, characters 12-694
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Ctype.occur_univar_for in file "typing/ctype.ml", line 1981, characters 4-23
Called from Ctype.moregen_occur in file "typing/ctype.ml", line 3327, characters 2-33
Called from Ctype.moregen in file "typing/ctype.ml", line 3342, characters 8-37
Called from Ctype.moregen in file "typing/ctype.ml", line 3365, characters 14-54
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Includecore.value_descriptions in file "typing/includecore.ml", line 82, characters 8-60
Called from Includemod.value_descriptions in file "typing/includemod.ml", line 161, characters 7-72
Called from Includemod.signature_components in file "typing/includemod.ml", line 668, characters 8-61
Called from Includemod.signatures.pair_components in file "typing/includemod.ml", line 556, characters 10-77
Called from Includemod.signatures.pair_components in file "typing/includemod.ml", line 592, characters 10-93
Called from Includemod.signatures.pair_components in file "typing/includemod.ml", line 592, characters 10-93
Called from Includemod.try_modtypes in file "typing/includemod.ml", line 424, characters 18-59
Called from Includemod.modtypes in file "typing/includemod.ml", line 362, characters 8-51
Called from Includemod.modtypes in file "typing/includemod.ml", line 990, characters 8-56
Called from Typemod.wrap_constraint in file "typing/typemod.ml", line 2062, characters 6-69
Called from Typemod.type_module_aux in file "typing/typemod.ml", line 2180, characters 8-73
Called from Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 239, characters 14-18
Re-raised at Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 244, characters 4-13
Called from Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 239, characters 14-18
Re-raised at Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 244, characters 4-13
Called from Typemod.type_structure.type_str_item in file "typing/typemod.ml", line 2464, characters 10-202
Called from Typemod.type_structure.run in file "typing/typemod.ml", line 2679, characters 33-53
Called from Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 239, characters 14-18
Re-raised at Builtin_attributes.warning_scope in file "parsing/builtin_attributes.ml", line 244, characters 4-13
Called from Typemod.type_structure in file "typing/typemod.ml" (inlined), line 2696, characters 21-46
Called from Typemod.type_implementation.(fun) in file "typing/typemod.ml", line 2869, characters 8-38
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Profile.record in file "utils/profile.ml" (inlined), line 100, characters 34-78
Called from Compile_common.typecheck_impl in file "driver/compile_common.ml", line 103, characters 2-131
Called from Compile_common.implementation.(fun) in file "driver/compile_common.ml", line 119, characters 18-44
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Misc.try_finally in file "utils/misc.ml", line 31, characters 8-15
Re-raised at Misc.try_finally in file "utils/misc.ml", line 45, characters 10-56
Called from Compenv.process_action.impl in file "driver/compenv.ml", line 630, characters 4-69
Called from Compenv.process_deferred_actions in file "driver/compenv.ml" (inlined), line 717, characters 12-32
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Stdlib__List.iter in file "list.ml" (inlined), line 108, characters 13-64
Called from Compenv.process_deferred_actions in file "driver/compenv.ml", line 717, characters 2-61
Called from Maindriver.main in file "driver/maindriver.ml", line 34, characters 6-147
Re-raised at Location.report_exception.loop in file "parsing/location.ml", line 932, characters 14-25
Called from Maindriver.main in file "driver/maindriver.ml", line 110, characters 4-35
Called from Main in file "driver/main.ml", line 2, characters 7-54
```
</details>

Switching to ocaml.4.12.0 (or removing `f` from the signature) restores the correct error:

```
❭ opam exec --switch=4.12.0 ocamlc ./test.ml
File "./test.ml", lines 4-7, characters 6-3:
4 | ......struct
5 |   type _ t
6 |   let f _ = ()
7 | end
Error: Signature mismatch:
       Modules do not match:
         sig type _ t val f : 'a -> unit end
       is not included in
         sig type (_, _) t val f : ('a, 'b) t -> unit end
       Type declarations do not match:
         type _ t
       is not included in
         type (_, _) t
       They have different arities.
       File "./test.ml", line 2, characters 2-15: Expected declaration
       File "./test.ml", line 5, characters 2-10: Actual declaration
```

### PR DESCRIPTION
**Pull request by Octachron**
This PR stops the computation of signatures difference as soon as types start to diverge in order to avoid trying to typecheck items in incoherent environments. This avoid raising internal type errors due to, for instance, having type constructors with incoherent arity.

close #10836

### CODE REVIEW

File: typing/includemod.ml [hunk 1]
```diff
@@ -606,13 +618,13 @@ and signatures  ~in_eq ~loc env ~mark subst sig1 sig2 mod_shape =
      and the coercion to be applied to it. *)
   let rec pair_components subst paired unpaired = function
       [] ->
-        let oks, (shape_map, deep_modifications), errors =
+        let oks, (shape_map, deep_modifications), errors, unknowns =
```
Comment (gasche) [inline typing/includemod.ml]: What you mean by "unknowns" was unclear to me, but I think this in fact means `rem(ainder)` or `leftovers`, which I would find clearer.

File: typing/includemod.ml [hunk 2]
```diff
@@ -682,17 +700,20 @@ and signature_components  ~in_eq ~loc old_env ~mark env subst
               | _ -> true
             in
             let shape_map = Shape.Map.add_value_proj shape_map id1 orig_shape in
+            let item = recoverable_error item in
```
Comment (gasche) [inline typing/includemod.ml]: Reading the code, I thought that `item` was error information, and I was confused as I didn't know how you could tell from this code that `id1`, `id2` don't match or something. In fact `recoverable_error` means "if this item is an error, then mark that error as recoverable". I think `with_recoverable_error` or `mark_errors_recoverable` would be clearer.

```ocaml
let item = mark_errors_recoverable @@ 
  value_descriptions ...
```

File: typing/includemod.ml [hunk 3]
```diff
@@ -736,6 +758,7 @@ and signature_components  ~in_eq ~loc old_env ~mark env subst
             let shape_map =
               Shape.Map.add_module_type_proj shape_map id1 orig_shape
             in
+            let item = unrecoverable_error item in
```
Comment (gasche) [inline typing/includemod.ml]: This is fishy. We can match `val x : t1` against `val x : t2`, recover and continue, but we cannot recover from `module type S : sig val x : t1 end` against `module type S : sig val x : t2 end`?

**Review by gasche — COMMENTED** [review]
If I understand correctly, the problem is as follows:
- some parts of a module signature depend on what came earlier
- to check the inclusion of what follows, we enrich the "comparison environment" with the earlier part
- this makes no sense when the earlier parts disagree, as we don't know how to enrich the "comparison environment" to check the later parts, that live in incompatible environments

Your proposal is to accept divergences only in signature items that don't change the typing environment / don't introduce dependencies. So we maintain the property that there exists a common environment in which to compare later parts.

Thinking out loud: would it make sense to perform an heterogeneous inclusion check, where we carry two environments, one for each signature? Then we could always extend the environments to check for inclusion of the rest, but the notion of signature-item inclusion becomes a bit weirder.

File: typing/includemod.ml (hunk 1 above)
Comment (Octachron) [reply typing/includemod.ml]: I meant that the remaining elements cannot be categorized clearly into the `oks` or `errors` set. `leftovers` is fine with me.

File: typing/includemod.ml (hunk 2 above)
Comment (Octachron) [reply typing/includemod.ml]: Let's go with `mark_error_as_recoverable`.

**Comment by Octachron** [comment]
First, an important context point: currently the signature difference is not exposed in error messages. It is meant as ground work for improving error messages at a later time. Thus, this fix is intended to be minimal and only marks as recoverable value-level error because this is the simplest and obvious case.
It might make sense to recover from early errors in more situations, but only once we start really using the difference.

File: typing/includemod.ml (hunk 3 above)
Comment (Octachron) [reply typing/includemod.ml]: The current fix makes no effort to identify all recoverable errors, since recoverable errors will only be useful in a future error message improvements.

**Comment by gasche** [comment]
Thanks for the context. With that in mind (plus the fact that heterogeneous comparison is a minefield anyway, we don't want to go there) I'm happy to okay the change. I feel slightly grumpy about the proliferation of N+1-uples with N>1, maybe we should move to records at some point?

**Comment by Octachron** [comment]
I tend to agree that we should move to a record at some point (it was hard to resist to the temptation to introduce yet another new record type in this fix).

**Comment by gasche** [comment]
> it was hard to resist to the temptation to introduce yet another new record type in this fix

Run for it! Usually people go the other way, they avoid introducing a record each time and we end up with 12-uples. Fly!

File: typing/includemod.ml [hunk 4]
```diff
@@ -767,36 +781,41 @@ and signature_components  ~in_eq ~loc old_env ~mark env subst
...
       | Ok x when present_at_runtime ->
-          (pos,x) :: oks, final_map, errors, unknowns
-      | Ok _ -> oks, final_map, errors, unknowns
+          let runtime_coercions = (pos,x) :: r.runtime_coercions in
+          { r with runtime_coercions; deep_modifications }
+      | Ok _ -> { r with deep_modifications }
       | Error {error; recoverable = true }  ->
-          oks, final_map, (id,error) :: errors, unknowns
+          { r with errors = (id,error) :: r.errors; deep_modifications }
       | Error {recoverable=false; _ }  -> r
```
Comment (gasche) [inline typing/includemod.ml]: The code flow is weird here, in particular the flow of `deep_modifications`. A proposal:

```ocaml
let first = (* signature difference for the first item *)
  match item with
  | Ok -> ...
  | Error -> ...
in
let continue =
  match item with
  | Ok _ -> true
  | Error e -> e.recoverable
in
let rest = (* signature difference for the remainder *)
  if not continue then ...
  else signature_items ...
in
{
  runtime_coercions = first.runtime_coercions @ rest.runtime_coercions;
  shape_map =
    (* shape maps are threaded through the computation, the last one has all information *)
    rest.shape_map;
  deep_modifications = first.deep_modifications || rest.deep_modifications;
  errors = first.errors @ rest.errors;
  leftovers = first.leftovers @ rest.leftovers;
}
```

**Review by gasche — APPROVED** [review]

File: typing/includemod.ml (hunk 4 above)
Comment (Octachron) [reply typing/includemod.ml]: Going in this direction, I would propose to move helper functions in a submodule and go for something like:
```ocaml
let deep_modifications = !shape_modified in
let first =
  match item with
  | Ok x ->
    let runtime_coercions = if present_at_runtime then [pos,x] else [] in
    Sign_diff.make ~deep_modifications ~runtime_coercions shape_map
  | Error { recoverable = true; error } ->
    Sign_diff.make ~errors:[id,error] ~deep_modifications shape_map
  | Error { recoverable = false; error } ->
    Sign_diff.make ~deep_modifications ~errors:[id,error] ~leftovers:rem
      shape_map
   in
   let continue = match item with
   | Ok _ -> true
   | Error x -> x.recoverable
   in
   let rest =
     if continue then
       signature_components ~in_eq ~loc old_env ~mark env subst
         orig_shape shape_map rem
     else Sign_diff.empty
   in
   Sign_diff.merge first rest
  ```

Comment (gasche) [reply typing/includemod.ml]: This looks fine. (I'm not fond of turning records into functions with labelled and optional parameters. I would expose the records directly, possibly with `{ empty with ...}` for initialization. But this is just me.)

Comment (Octachron) [reply typing/includemod.ml]: @gasche : last check before squashing and merging, are you fine with the last commit?

File: typing/includemod.ml [hunk 5]
```diff
@@ -795,28 +812,31 @@ and signature_components  ~in_eq ~loc old_env ~mark env subst
...
-              shape_map;
-              deep_modifications= !shape_modified;
-              errors=[id,error];
-              leftovers=rem
-            }
-        | Error { recoverable = true; _ } | Ok _ ->
-            signature_components ~in_eq ~loc old_env ~mark env subst
-              orig_shape shape_map rem
+            let errors =[id,error] in
+            Sign_diff.{ empty with deep_modifications; errors; leftovers=rem }
```
Comment (gasche) [inline typing/includemod.ml]: if you allow me a minor nitpick: I think that `leftovers=rem` should come from `rest`, not `first`. (Nothing here, and `{ empty with leftovers=rem }` in the `if not continue` case of `rest`.)

**Review by gasche — APPROVED** [review]
A thing of beauty. Thanks!

File: typing/includemod.ml (hunk 5 above)
Comment (Octachron) [reply typing/includemod.ml]: That's slightly clearer indeed. I will keep that in mind in subsequent updates.

Comment (Octachron) [reply typing/includemod.ml]: Well, since the change entry needed to be synced with trunk anyway, here is the last minute change.
