### PR TITLE
#14629:  update is_inferred to traverse `local open`s

### LINKED ISSUE #14629: [5.5] Local open changes the typechecker behaviour regarding optional argument elimination
I've noticed a change in OCaml 5.5 where a local open will make the type-checker change its behaviour.
Before 5.5, the type-checker had the same behaviour regardless of the local open: optional arguments were eliminated when the function is used with the pipe operator:
```
$ ocaml
OCaml version 5.5.0+dev4-2026-02-25

# let f ?x ?y ~z () = z;;
val f : ?x:'a -> ?y:'b -> z:'c -> unit -> 'c = <fun>
# let a = () |> Stdlib.(f ~z:2);;
Error: This expression has type ?x:'a -> ?y:'b -> unit -> int
       but an expression was expected of type unit -> 'c
       The first argument is labeled ?x,
       but an unlabeled argument was expected
Hint: This function application is partial, maybe some arguments are missing.
# let a = () |> f ~z:2;;
val a : int = 2
```
```
$ opam exec --sw=5.4 -- ocaml
OCaml version 5.4.0

# let f ?x ?y ~z () = z;;
val f : ?x:'a -> ?y:'b -> z:'c -> unit -> 'c = <fun>
# let a = () |> Stdlib.(f ~z:2);;
val a : int = 2
# let a = () |> f ~z:2;;
val a : int = 2
```

### PR DESCRIPTION
**Pull request by Octachron**
This PR restores the inlining of `|>` in `x |> M.(f y)` by preserving the previous behaviour of the `is_inferred` function in this specific case. 

I had considered making this function traverses all `Pexp_structure_item _` but the function feels quite adhoc to me, and thus preserving the previous behaviour seems like a good first step.

Fixes #14629 
cc @nojb

### CODE REVIEW

File: typing/typecore.ml [hunk 1]
```diff
@@ -3967,6 +3987,7 @@ let rec is_inferred sexp =
   | Pexp_coerce _ | Pexp_send _ | Pexp_new _ | Pexp_pack (_, Some _) -> true
   | Pexp_sequence (_, e) -> is_inferred e
   | Pexp_ifthenelse (_, e1, Some e2) -> is_inferred e1 && is_inferred e2
+  | Pexp_struct_item( { pstr_desc= Pstr_open _; _ }, e ) -> is_inferred e
```
Comment (nojb) [inline typing/typecore.ml]: A comment may be useful to a future reader to underestand why we only treat this case here.
```suggestion
  | Pexp_struct_item( { pstr_desc= Pstr_open _; _ }, e ) -> is_inferred e (* PR #14638 *)
```

**Review by nojb — APPROVED** [review]
LGTM

Thanks @Octachron for the speedy fix!

File: typing/typecore.ml (hunk 1 above)
Comment (Octachron) [reply typing/typecore.ml]: Added a comment with a link to the issue which seemed more informative than this PR.

**Comment by nojb** [comment]
Cherry-picked to 5.5 86331362d4da7c948091a98909a1e0014a334aeb
