### PR TITLE
Functions from weak are breaking all marking invariants on ephemerons

### LINKED ISSUE #9391: Ephemeron segfault with missing write barrier
Ephemerons don't use the normal write barrier, and because they're marked incrementally this can lead to the lost object problem, where an object becomes reachable only from an ephemeron that's already marked and never ends up getting marked.

It's difficult to trigger because it relies on the timing of incremental GC, but here's an example that hits the bug on trunk.

```ocaml
module E = Ephemeron.K1

let key = ref 1
let mk_ephe () =
  let e = E.create () in
  E.set_key e key;
  e

let eph = mk_ephe ()
let other = ref "beep"

let () =
  for stop = 100 to 2000 do
    E.set_data eph (ref "hello");
    Gc.major ();
    Gc.minor (); Gc.major_slice 1 |> ignore; Gc.major_slice 1 |> ignore;
    (* let _ = Array.init 1 (fun _ -> mk_ephe ()) in *)
    let e = mk_ephe () in
    (* let _ = Array.init 3 (fun _ -> mk_ephe ()) in *)
    for i = 1 to 2000 do
      Gc.major_slice 1 |> ignore;
      if i = stop then begin
          E.blit_data eph e;
          E.set_data eph other;
        end;
    done;
    let r = match E.get_data e with None -> assert false | Some r -> r in
    Printf.printf "[%03d] %s\n%!" stop !r;
    Gc.full_major ();
  done
```

I'm not sure what the fix is. It may be as simple as adding darkening in `blit_data` (and maybe `set_data`?), but I don't understand what the marking invariants are for ephemerons.

### PR DESCRIPTION
**Pull request by bobot**
The marking of ephemerons follow the invariants describe in `major_gc.c`:

```
   Ephemerons:
   During mark phase the list caml_ephe_list_head of ephemerons
   is iterated by different pointers that follow the invariants:
   caml_ephe_list_head ->* ephes_checked_if_pure ->* ephes_to_check ->* null
                        |                         |                  |
                       (1)                       (2)                (3)

    At the start of mark phase, (1) and (2) are empty.

    In mark phase:
      - An ephemeron in (1) have a data alive (grey/black if in the heap)
        or none (nb: new ephemerons are added in this part by weak.c)
      - An ephemeron in (2):
         - is in any state if ephe_list_pure is false
         - otherwise has at least a white key or is white or its data is black or none.
           The third case can happen only using a set_* of weak.c
      - the ephemerons in (3) are in an unknown state and must be checked

    At the end of mark phase, (3) is empty and ephe_list_pure is true.
    The ephemeron in (1) and (2) will be cleaned (white keys and data
    replaced by none or the ephemeron is removed from the list if it is white)
    in clean phase.
```

During the addition of the cleaning phase, which fixes some behavior inconsistencies in weak pointers, I started to think the clean phase as a magical bullet which avoided the `set_*` functions from weak to take care of the `mark` phase. It is clearly wrong as #9391 shows.

This MR fixes that by:
  - ensuring that functions that modify the data of ephemerons doesn't break the property that ephemerons in the set `(1)` should follow
 - ensuring that functions that modify the keys of ephemerons doesn't break the property that ephemerons in the set `(2)` should follow

There are different possible fixes:
 - put back the ephemerons in the set `(3)` when modified, but it makes the marking possibly non terminating;
- always blacken the data, but it could defeat the purpose of ephemerons;
- detect in which set the ephemerons is, in order to do nothing in 2 of the 3 cases, but it is complicated to keep track of this information and it is just an optimization;
- detect by looking at all the keys, if the ephemerons can be in set (2) or (3), but it could lead to bad performance as #9259 shown.

The intermediary choice in this implementation is to blacken the data except when:
- in case of data modification:
   - it is sure it is not before the modification in set `(1)`: the old data was white.
- in case of key modification:
   - after the modification it verifies the property of the set `(2)`, the ephemeron is white or one of the setted keys is white (EDIT: now additionnally, "or the data is marked")

TODO:
 - [x]  add tests that are consistently failing before the fix, and check the fix.
 - [x] handle infix tag

### CODE REVIEW

**Comment by xavierleroy** [comment]
Any progress on this PR?

File: runtime/weak.c [hunk 1]
```diff
@@ -89,7 +94,29 @@ Caml_inline int Must_be_Marked_during_mark(value x)
...
+
+/* True if ar could be in the set (1) (Cf. major_gc.c) */
+static int already_marked (value ar)
+{
+  value old_data;
+  CAMLassert (caml_gc_phase == Phase_mark);
+
+  old_data = Field (ar, CAML_EPHE_DATA_OFFSET);
+  return ( old_data == caml_ephe_none ||
+           (Is_block(old_data) &&
```
Comment (damiendoligez) [inline runtime/weak.c]: Either I'm confused or you are missing a negation here.

In any case, you should define an inline function that returns
```
#if defined(NATIVE_CODE) && defined(NO_NAKED_POINTERS)
x == Is_block(x) && !Is_young(x) && Is_white_val(x)
#else
x == Is_block(x) && Is__in_heap(x) && Is_white_val(x)
#endif
```
and then use it to define `Is_white_during_mark` and `Is_dead_during_clean` (as well as this function) without the need for ugly `#ifdef`s.

File: runtime/weak.c [hunk 2]
```diff
@@ -221,7 +256,15 @@ CAMLexport void caml_ephemeron_unset_key(value ar, mlsize_t offset)
 
   offset += CAML_EPHE_FIRST_KEY;
 
-  do_check_key_clean(ar, offset);
+  if( caml_gc_phase == Phase_mark
+      && ephe_list_pure
+      && Field(ar, CAML_EPHE_DATA_OFFSET) != caml_ephe_none
```
Comment (damiendoligez) [inline runtime/weak.c:254]: You could use `Is_white_during_mark` here, because if it's not white then `caml_darken` will do nothing.

File: runtime/weak.c [hunk 3]
```diff
@@ -529,6 +574,23 @@ CAMLexport void caml_ephemeron_blit_key(value ars, mlsize_t offset_s,
...
   offset_d += CAML_EPHE_FIRST_KEY;
 
+  if ( caml_gc_phase == Phase_mark
+       && ephe_list_pure
+       && Field(ard, CAML_EPHE_DATA_OFFSET) != caml_ephe_none ){
+
+    dest_has_white_value = 0;
+
+    for(i = 0; i < length; i++){
+      dest_has_white_value &= Is_White_During_Mark(Field(ard, offset_d + i));
```
Comment (damiendoligez) [inline runtime/weak.c]:
```suggestion
      dest_has_white_value |= Is_White_During_Mark(Field(ard, offset_d + i));
```
otherwise `dest_has_white_value` is always 0.

**Review by damiendoligez — COMMENTED** [review]
A few questions on the current state of the PR.

**Comment by damiendoligez** [comment]
CI is failing because you need to rename `ephe_list_pure` into `caml_ephe_list_pure` now that it's become a global.

File: runtime/weak.c (hunk 1 above)
Comment (bobot) [reply runtime/weak.c]: Indeed a negation was needed. I removed the function because it is not just that it is in the set (1) that must be tested. Now the code mark the new data when the old is marked. The factorization can be done in another PR.

File: runtime/weak.c (hunk 2 above)
Comment (bobot) [reply runtime/weak.c:254]: I don't understand the comment, `Is_white_during_mark` is used and on something different than what is darken.

File: runtime/weak.c (hunk 3 above)
Comment (bobot) [reply runtime/weak.c]: Indeed thank you. Some comments are added.

**Comment by jhjourdan** [comment]
@bobot You're right, well spotted, there is a bug. I'm preparing a PR to fix that.

**Comment by jhjourdan** [comment]
As for the test: wht about making it more robust by making it try several values of the parameters?

**Comment by jhjourdan** [comment]
> In 95400d7 (I reviewed the PR #9742 flushed) @jhjourdan, is it normal in naked pointer to access the value before checking it is in the heap?

I proposed a fix in #9989. Note, however, that your `Is_White_During_Mark` function seems to suffer from the same defect.

File: runtime/weak.c (hunk 2 above)
Comment (damiendoligez) [reply runtime/weak.c:254]: I meant using `Is_white_during_mark` instead of the `Field(...) != caml_ephe_none` test. But it doesn't seem important anyway.

File: Changes [hunk 4]
```diff
@@ -45,6 +45,9 @@ Working version
 
 ### Bug fixes:
 
+* #9391, #9424: Fix failed assertion in runtime due to ephemerons *set_* function during
+   Mark phase (François Bobot, reported by Stephen Dolan, review by Damien Doligez)
```
Comment (damiendoligez) [inline Changes]:
```suggestion
* #9391, #9424: Fix failed assertion in runtime due to ephemerons *set_*
  function during Mark phase
  (François Bobot, reported by Stephen Dolan, review by Damien Doligez)
```

File: runtime/major_gc.c [hunk 5]
```diff
@@ -88,14 +88,15 @@ int caml_gc_subphase;     /* Subphase_{mark_roots,mark_main,mark_final} */
...
-      - the ephemerons in (1) have a data alive or none
-        (nb: new ephemerons are added in this part by weak.c)
-      - the ephemerons in (2) have at least a white key or are white
-        if ephe_list_pure is true, otherwise they are in an unknown state and
-        must be checked again.
+      - An ephemeron in (1) have a data alive (grey/black if in the heap)
+        or none (nb: new ephemerons are added in this part by weak.c)
+      - An ephemeron in (2):
+         - is in any state if caml_ephe_list_pure is false
+         - otherwise has at least a white key or is white or its data is black or none.
```
Comment (damiendoligez) [inline runtime/major_gc.c]:
```suggestion
         - otherwise has at least a white key or is white or its data is
           black or none.
```

File: runtime/weak.c [hunk 6]
```diff
@@ -537,10 +574,33 @@ CAMLexport void caml_ephemeron_blit_key(value ars, mlsize_t offset_s,
   offset_s += CAML_EPHE_FIRST_KEY;
   offset_d += CAML_EPHE_FIRST_KEY;
 
+  if ( caml_gc_phase == Phase_mark
+       && caml_ephe_list_pure
+       && Field(ard, CAML_EPHE_DATA_OFFSET) != caml_ephe_none
+       && !Is_white_val(ard)
+       ){
+    /* If the destination is in set (2) it is because of a white key */
```
Comment (damiendoligez) [inline runtime/weak.c]: I don't understand this comment. Couldn't it be in set (2) because its data is black?

File: runtime/weak.c [hunk 7]
```diff
@@ -537,10 +574,33 @@ CAMLexport void caml_ephemeron_blit_key(value ars, mlsize_t offset_s,
...
+
+    dest_has_white_value = 0;
+
+    for(i = 0; i < length; i++){
+      dest_has_white_value |= Is_White_During_Mark(Field(ard, offset_d + i));
+    };
+    /* test if the destination can't be in set (2) because of the keys that are going to be set */
```
Comment (damiendoligez) [inline runtime/weak.c]:
```suggestion
    /* test if the destination can't be in set (2) because of the keys that are
       going to be set */
```

File: runtime/weak.c [hunk 8]
```diff
@@ -537,10 +574,33 @@ CAMLexport void caml_ephemeron_blit_key(value ars, mlsize_t offset_s,
...
+    if(!dest_has_white_value) goto No_darkening;
+    for(i = 0; i < length; i++){
+      /* test if the source is going to bring a white key to replace the one set */
+      if(Is_White_During_Mark(Field(ars, offset_s + i))) goto No_darkening;
+    };
+    /* the destination ephemeron could be in the set (2) because of a white key replaced and not have one anymore after. */
```
Comment (damiendoligez) [inline runtime/weak.c]:
```suggestion
    /* the destination ephemeron could be in the set (2) because of a white key
        replaced and not have one anymore after. */
```

**Review by damiendoligez — COMMENTED** [review]
Looks good except for the long lines and one comment that seems wrong.

**Comment by xavierleroy** [comment]
Any news about this PR?  It's not clear whether @damiendoligez is waiting for @bobot to revise the code again, or we are waiting for @damiendoligez to accept as is.

File: runtime/weak.c (hunk 6 above)
Comment (bobot) [reply runtime/weak.c]: Indeed the comment is misleading. Two possible modification:

* Just change the comment to

```
We check here if darkening of the data of the destination is needed because
the destination could be in (2). Indeed a white key could disappear from the
destination after blitting and being in (2) requires if the ephemeron is alive without 
white key to have a black or none data.
```

* Just add the condition `&& !Is_White_During_Mark(Field(ard, CAML_EPHE_DATA_OFFSET)))`

**Comment by damiendoligez** [comment]
Thanks @bobot
