### PR TITLE
fix #7829: pointer comparisons in assertions

### LINKED ISSUE #7829: Assertion failed in freelist.c
**Original bug ID:** 7829
**Reporter:** @db4
**Status:** acknowledged (set by @dra27 on 2018-07-24T11:17:41Z)
**Resolution:** open
**Priority:** high
**Severity:** crash
**Platform:** i386
**OS:** Linux
**Version:** 4.07.0
**Target version:** 4.08.0+dev/beta1/beta2
**Category:** runtime system and C interface
**Related to:** #7831
**Monitored by:** @nojb @gasche

## Bug description

When running the testsuite with the debug runtime inside docker container I'm getting many errors like this:

Running tests from 'tests/runtime-errors' ...
file freelist.c; line 463 ### Assertion failed: prev < bp || prev == Fl_head
Aborted (core dumped)

I tried to debug the problem and added

  if (!(prev < bp || prev == Fl_head)) {
    fprintf (stderr, "%lx %lx %lx\n", prev, bp, Fl_head);
  }

before line 463. That gave me

58476004 f731b4cc 56dfd5a4

So the bug is obvious now. prev and bp are values (i.e. signed ints) so compiler uses signed compare here. But we would like to compare prev and bp as pointers that are unsigned addresses.

The fix for this problem is trivial but I'm afraid it's not the only place where signed compare is incorrectly used for pointers.

### PR DESCRIPTION
**Pull request by damiendoligez**
This is a replacement for #1311 and a fix for #7829. When comparing values in debug assertions, cast them to pointers to make sure we don't get into trouble with the sign bit.

Note, this is only relevant on some 32-bit machines, the most important being our Travis CI x86 worker.

### CODE REVIEW

**Comment by dra27** [comment]
I remember trying this with #1311 - it doesn't fix it, sadly.

**Comment by damiendoligez** [comment]
@dra27 Do you have a machine where you can reproduce this? Debugging through Travis is not the easiest thing...

**Comment by dra27** [comment]
@damiendoligez - yes, my Ubuntu 16.04 VM (set up to match Travis) seems to be behaving the same way

**Comment by dra27** [comment]
@damiendoligez - I think I may have it:

```diff
diff --git a/runtime/freelist.c b/runtime/freelist.c
index 4d16b99..fb129bd 100644
--- a/runtime/freelist.c
+++ b/runtime/freelist.c
@@ -551,7 +551,7 @@ void caml_fl_add_blocks (value bp)
     cur = Field(cur, 0);
   } while (cur != Val_NULL);
 
-  if (bp > fl_last){
+  if (Bp_val(bp) > Bp_val(fl_last)){
     Next (fl_last) = bp;
     if (fl_last == caml_fl_merge && (char *) bp < caml_gc_sweep_hp){
       caml_fl_merge = Field (bp, 1);
@@ -564,7 +564,7 @@ void caml_fl_add_blocks (value bp)
 
     prev = Fl_head;
     cur = Next (prev);
-    while (cur != Val_NULL && cur < bp){
+    while (cur != Val_NULL && Bp_val(cur) < Bp_val(bp)){
       CAMLassert (Bp_val (prev) < Bp_val (bp) || prev == Fl_head);
       /* XXX TODO: extend flp on the fly */
       prev = cur;
```

File: runtime/freelist.c [hunk 1]
```diff
@@ -460,13 +461,13 @@ header_t *caml_fl_merge_block (value bp)
...
-  CAMLassert (prev < bp || prev == Fl_head);
-  CAMLassert (cur > bp || cur == Val_NULL);
+  CAMLassert (Bp_val (prev) < Bp_val (bp) || prev == Fl_head);
+  CAMLassert (Bp_val (cur) > Bp_val (bp) || cur == Val_NULL);
 
   if (policy == Policy_first_fit) truncate_flp (prev);
 
   /* If [last_fragment] and [bp] are adjacent, merge them. */
-  if (last_fragment == Hp_bp (bp)){
+  if (last_fragment == Hp_val (bp)){
```
Comment (dra27) [inline runtime/freelist.c:471]: I think this is just a philosophical change reflecting that you want a pointer to the header rather than a pointer to the first byte specifically?

**Review by dra27 — COMMENTED** [review]
I've run https://github.com/dra27/ocaml/commit/824ef656755e84d16700d9753a5dfde122224eb0 through Travis on [top of this PR](https://travis-ci.org/dra27/ocaml/builds/516155365) and that seems finally to have nailed it.

**Comment by dra27** [comment]
I think `truncate_flp` may need a change too?

File: runtime/freelist.c (hunk 1 above)
Comment (damiendoligez) [reply runtime/freelist.c:471]: You're right that it's philosophical, but `bp` is declared as a value and all the other macros applied to it are `_val`, so why not this one?

Comment (dra27) [reply runtime/freelist.c:471]: Oh, I see - that was kind of where my question was coming from. So the idea is `Hp_bp` should be being given a pointer, not a `value`. Gotcha! The other reason for noting it was because it's a change which isn't in an assertion.

**Comment by damiendoligez** [comment]
@dra27 you're perfectly right, thanks for debugging this. I've added a commit with your fixes.

**Comment by dra27** [comment]
Squashed to 4.08 in 8be0b878031479066e0fa0f60c582920f69cd8d6

**Comment by gasche** [comment]
(My favorite command for this is `git cherry-pick -m 1 -x <trunk-merge-commit>`, which includes a reference to the trunk commit hash in the commit message of the cherry-picked version.)

**Comment by dra27** [comment]
Ah, ok - that'd be a case for merging (I rebased this one, since I wanted to keep the fix to the assertions and the fix to the comparisons in separate commits on trunk, but was less bothered about that on 4.08)
