### PR TITLE
#11314: do not elide the whole module type error message

### LINKED ISSUE #11314: Uninformative error message for signature mismatch since OCaml 4.13
Since OCaml 4.13 up to the current trunk, error messages for signature mismatch appear to be hidden behind ellipsis as soon as they exceed a certain length, and can become uninformative. For instance, given the following file:
```ocaml
module A = struct
  type a and b and c and d
end

module type S = sig
  module B = A
end

module C : S = struct
  module B = struct
    type a and b and c and d and e and f and g and h
  end
end
```
the compiler gives the following error:
```ocaml
File "bug_alias.ml", lines 9-13, characters 15-3:
 9 | ...............struct
10 |   module B = struct
11 |     type a and b and c and d and e and f and g and h
12 |   end
13 | end
Error: Signature mismatch:
       ...
       ...
```
whereas with OCaml 4.12, we had the following message, which shows what mismatches:
```ocaml
File "bug_alias.ml", lines 9-13, characters 15-3:
 9 | ...............struct
10 |   module B = struct
11 |     type a and b and c and d and e and f and g and h
12 |   end
13 | end
Error: Signature mismatch:
       ...
       In module B:
       Modules do not match:
         sig
           type a = B.a
           and b = B.b
           and c = B.c
           and d = B.d
           and e = B.e
           and f = B.f
           and g = B.g
           and h = B.h
         end
       is not included in
         (module A)
```

### PR DESCRIPTION
**Pull request by Octachron**
Since OCaml 4.13 when printing error message for module type inclusion, it was possible that the whole error message ended up elided, for instance:
```ocaml
Error: Signature mismatch:
       ...
       ...
```
This PR fixes this issue by making sure that the last difference between module types in an inclusion error trace is always printed when there are no more meaningful refinement available in the error trace.

Close #11314

### CODE REVIEW

File: typing/includemod_errorprinter.ml [hunk 1]
```diff
@@ -709,7 +709,16 @@ let rec module_type ~expansion_token ~eqmode ~env ~before ~ctx diff =
       functor_params ~expansion_token ~env ~before ~ctx d
   | _ ->
```
Comment (gasche) [inline typing/includemod_errorprinter.ml:710]: Could this pattern here be made exhaustive / non-fragile? It would help understand what is going on, in particular by making it easy to reason about which cases go to `dwith_context_and_elision` below.

**Review by gasche — COMMENTED** [review]
I looked at the code.

Here is what I understand.
- The type-checking code produces a datatype that explains the "symptom" as an error, which may in general look like a nested list of explanations: this module is incompatible with that module because this component is incompatible with that component because ...
- The error-explaining code walks that nested list, producing one explanation at each level, from the toplevel to the more precise.
- But often there is a lot of redundancy among the explanations and we try to "elide" the coarser-grained / more global explanations to keep mostly the final / more precise explanation.
- The bug reported is a case where the printer elided everything.
- This happens in the specific case of the `module_type` explainer that takes a "module type diff", in some cases produces a "leaf explanation" and in some other cases defers to a more precise `module_type_symptom` explainer... which sometimes prints nothing at all.
- The fix is to ensure that, in the case where `module_type_symptom` might say nothing at all, `module_type` never elides its own explanation.

Questions:
- Why is it possible that the "symptom" is `Mt_core of core_module_type_symptom` and yet have `core_module_type_symptom` not produce an explanation at all? (Why does this function return `None`?)
- The fix un-elides the `module_type` explanation in all `Mt_core` type, does this also matter in the case where `core_module_type_symptom` would in fact produce an explanation? (Or are you just worsening the message in this case?) Could we have testsuite support for this combination?
- Doesn't the code of `module_type` look fishy? It supposedly takes a `diff` as input that contains more information than just a symptom, but in fact it only checks the symptom and decides based on that... and in many case defers to the `module_type_symptom` that itself reasons on the symptom in turn. What's the reason for `module_type` to not defer to `module_type_symptom` in all cases if it's only reasoning based on the symptom? (Could this reason be explained in a comment? Are the cases where the two functions do not go to the same paths, namely the cases where `module_type` does not call `module_type_symptom`, exercised by the testsuite?)

**Comment by gasche** [comment]
Ah, I forgot a question. If the problem is that we should never elide all explanations, then maybe the decision to elide should be based on the context, rather than being taken independently by each explanation-producer? Would it not be reasonable to store the full explanation in the `before` parameters (with maybe information on whether it is elidable/how), and then perform the elisions as a post-processing pass that knows to preserve the last explanation?

**Comment by Octachron** [comment]
* The `Mt_core` case is essentially a new class of error explanation that has been added when I refactored the error tree for the inclusion error message in the work on functor application. In order to not change unrelated error messages in the functor work, most of those explanations have not yet been surfaced to the error message. 
* I tend to think that it improves the error messages: all `Mt_core _`  cases mostly adds a comments on why the two module types are incompatible (one of them is abstract, one is an alias which cannot be expanded, only one of them is an alias or an identifier). Printing the main difference seems fine in those case.
* The coupling between the `module_type` and `module_type_symptom` looks ugly indeed. From my memory, it happened in order to keep the same printed error message while the changing the error representation. It should be cleaned up later. The functor case is exercised by the testsuite.
* My preference would be to have an error message builder module that knows when to elide or not a suberrror message in function of the context:  https://github.com/Octachron/ocaml/tree/dont_elide_the_whole_error_trace . However, I also wanted to have a fix small enough for 4.14, thus this smaller PR.

**Review by gasche — APPROVED** [review]
Thanks! My questions have been answered, and I agree this is okay for a minimal backportable fix, even if long-term we wish the code structure was better.

**Comment by Octachron** [comment]
Cherry-picked on 4.14 (a691ba7f7893ad) and 5.0 (f1fc8521de6be171c11).
