### PR TITLE
symtab.c: make_bucket: fully initialize to zero

### LINKED ISSUE #14747: ocamlyacc wrong line directive generated
```
$ cat q.mly 
%type <int> EOF
%token EOF
%type <unit> start
%start start
%%
start: EOF { () }
%%

$ env MALLOC_PERTURB_=66 ocamlyacc q.mly

$ ocamlc -c q.ml
File "q.ml", line 3, characters 2-3:
3 | # -1111638595 "q.mly"
      ^
Error: Syntax error

$ head -6 q.ml
type token =
  | EOF of (
# -1111638595 "q.mly"
int
# 6 "q.ml"
)
```
the reason is in https://github.com/ocaml/ocaml/blob/e1e9a7797c020a05397f52b3493688c8c7c5a4eb/yacc/symtab.c#L44
`bp->lineno` is not initialized and implicitly relies on malloc to zero-initialize.

### PR DESCRIPTION
**Pull request by nojb**
Make sure to fully initialize the `bucket` data structure to zero after allocating it with `malloc`. Also, remove a duplicated check.

Fixes #14747

### CODE REVIEW

File: yacc/symtab.c
Comment (gasche) [inline yacc/symtab.c:49]: defs.h offers a CALLOC macro. Could you use it for extra safety? (It would zero-initialize the bucket.) We could leave the explicit zero-initialization here, but at the same time feel confident that future omissions of this kind are not going to result in uninitialized reads.

Comment (nojb) [reply yacc/symtab.c:49]: Sure, but why only here? There are other uses of `MALLOC` in the code. We could simply redefine `MALLOC` as a wrapper of `CALLOC` and get the benefit of zero-initialization everywhere.

Comment (gasche) [reply yacc/symtab.c:49]: That would also be fine.

Comment (nojb) [reply yacc/symtab.c:49]: Done in 40b8f731a0b09a6130b89d3dfce45d21f2930fc9

File: yacc/defs.h [hunk 1]
```diff
@@ -125,7 +125,7 @@
 
 #define CALLOC(k,n)      (calloc((unsigned)(k),(unsigned)(n)))
 #define FREE(x)          (free((char*)(x)))
-#define MALLOC(n)        (malloc((unsigned)(n)))
+#define MALLOC(n)        (CALLOC(n, 1))
```
Comment (gasche) [inline yacc/defs.h]: could you include a comment here that documents the choice of always zero-initializing to avoid undefined reads?

**Review by gasche — APPROVED** [review]

File: yacc/defs.h (hunk 1 above)
Comment (nojb) [reply yacc/defs.h]: Done in 829e4f6a249348707764e74d8dabade37a5ae6fb

**Comment by xavierleroy** [comment]
Zero initialization often hides programming mistakes but doesn't really fix them.  What if the correct initial value for the lineno field was not 0 ?  What matters is that all fields are properly initialized, not that calloc magically sets everything to 0.

File: yacc/symtab.c [hunk 2]
```diff
@@ -56,10 +56,12 @@ make_bucket(const char *name)
     bp->value = UNDEFINED;
     bp->index = 0;
     bp->prec = 0;
-    bp-> class = UNKNOWN;
+    bp->class = UNKNOWN;
     bp->assoc = TOKEN;
     bp->entry = 0;
     bp->true_token = 0;
+    bp->lineno = 0;
+    bp->column = 0;
```
Comment (xavierleroy) [inline yacc/symtab.c:64]: That's the correct fix.  No need for additional calloc magic.

**Comment by gasche** [comment]
> Zero initialization often hides programming mistakes but doesn't really fix them.

The current PR is evidence that *some* programming mistakes were still hiding in this legacy codebase. If this was actively-maintained software, we would find someone motivated to review the implementation to ensure that there are no more mistakes of this kind, and/or compile the software with a sanitizer, etc. Given that this is more like legacy software, I find it reassuring to know that any remaining mistake (hopefully none) will read 0 instead of an undefined value. This can also reduces our workload by avoiding to worry about CVEs, and reducing the number of vulnerability report slop that we receive on that part of the codebase.

File: yacc/symtab.c (hunk 2 above)
Comment (nojb) [reply yacc/symtab.c:64]: This minimal fix was my original intention. Can we reach a consensus?

**Comment by xavierleroy** [comment]
ocamlyacc is not actively developed, but is very well maintained.  For example, there's only one open issue about it, and @nojb proposed a fix the day after it was reported (this PR)...

I stand by my claim that zero initialization by default just to hide a possible use-uninitialized bug is a terrible idea.  For one thing, "missing initialization" bugs are easy to track with valgrind or other dynamic or static analysis tools, while "using a zero value instead of the correct initial value" bugs are not.

**Comment by xavierleroy** [comment]
Also, I prefer PRs that address one issue and address it perfectly than PRs that mix a bug fix with questionable changes.  So, @nojb please merge the original two-line PR and we'll fight over `calloc` elsewhere.

**Comment by nojb** [comment]
> Also, I prefer PRs that address one issue and address it perfectly than PRs that mix a bug fix with questionable changes. So, @nojb please merge the original two-line PR and we'll fight over `calloc` elsewhere.

Makes sense. Merged!
