### PR TITLE
#6985 extended: ghost row types should stay hidden

### LINKED ISSUE #9774: Exception File "typing/ctype.ml", line 4735
```sh
Fatal error: exception File "typing/ctype.ml", line 4735, characters 2-8: Assertion failed
```

Happens when trying to hide a type of a class

```
module A = struct class t = object method getWeight = 0.5 end end
module B = struct include A
                  type t end
```

### PR DESCRIPTION
**Pull request by Octachron**
This PR fixes a lapse in `Mtype.strengthen_sig` that makes it possible to observe a ghost row type (e.g. `t#row`) with the following sequence of events:

```ocaml
module Root = struct
  (* type t#row *)
  type u
  and t = private < .. >
end

module Trunk = struct
  include Root (* type t#row = Root.t#row *)
  type t = A
  type u
end

module M: module type of Trunk = struct
    type t = A
    type u
end
```
>```
> Error: Signature mismatch:
>       Modules do not match:
>         sig type t = A type u end
>       is not included in
>         sig type t = A type u end
>       The type `t#row' is required but not provided
>```

The problem stems from the strengthening of signatures in `Mtype.strenghtenen_sig` that was only conditionally removing ghost row types when they were immediately followed by their core type.
However, ghost and core types are not immediate neighbor in a recursive definition (like the one in `Root`).

This PR fixes this issue by removing all ghost row items from a strengthened signature unconditionally.
(This is extracted from a in-progress work with @gasche to fix #9774)

### CODE REVIEW

File: typing/mtype.ml [hunk 1]
```diff
@@ -54,9 +54,8 @@ and strengthen_sig ~aliasable env sg p =
     [] -> []
   | (Sig_value(_, _, _) as sigelt) :: rem ->
       sigelt :: strengthen_sig ~aliasable env rem p
-  | Sig_type(id, {type_kind=Type_abstract}, _, _) ::
-    (Sig_type(id', {type_private=Private}, _, _) :: _ as rem)
-    when Ident.name id = Ident.name id' ^ "#row" ->
+  | Sig_type(id, {type_kind=Type_abstract}, _, _) :: rem
+    when Btype.is_row_name (Ident.name id) ->
```
Comment (gasche) [inline typing/mtype.ml:58]: Code-review remark for myself: the trunk code would only drop row types when the corresponding type was Private, while the PR code does not check this anymore (it could drop the "row type of a Public type"). But row types are only creates for private types anyhow, so there is no actual change of behavior here.

To check this: Look for `#row` in typedecl.ml for the two places that introduce these ghost type declarations. See that they only run when `is_fixed_type sdecl` holds. This check only passes for Private type declartions.

**Review by gasche — COMMENTED** [review]
I believe that the change is correct. (You kindly mentioned that this is related to our shared work, but this PR is entirely new code from you.)

I still have a question though: is this fix at the right level? If I understand correctly, you use `include` to build a signature that has a row type (a ghost declaration) without the corresponding "main" declaration, and the current check in the strengthening function does not handle this. But is right to have such "dangling" row types in the first place, or do we eventually plan for getting rid of them in the `include` typing and other places? (I would maybe expect the invariant that "sigitem groups" are always well-formed in signatures, which does not hold here.) And if we are going to soon enforce stronger well-formedness properties on signature item groups, will that subsume this fix, and do we still want it in that future world? (Certainly we want the test.)

**Comment by Octachron** [comment]
The module type of an included module is already strengthened. What happens without this PR is that the strengthening takes care of removing the ghost row type in the common case:
```ocaml
type t = private < .. >
```
since this case translates to
```ocaml
type t#row
type t = private < .. >
```
But with a recursive type definition like
```ocaml
type t = private < .. >
and u = U
and s = private < .. >
```
the ghost row items are laid out as
```ocaml
type t#row
type s#row
type t = private < .. >
and u = U
and s = private < .. >
```
which is not captured by the current code in `Mtype`.

Thus in this case after strengthening, the ghost row types are still there (... and strengthened).
Capturing those with `module type of` is already problematic:
```ocaml
module M = struct
  type u and t = private < .. >
end
module X: module type of struct include M end = struct
  type t = M.t
  type u = M.u end
end
```
>```
 >      Modules do not match:
>         sig type t = M.t type u = M.u end
>       is not included in
>         sig type u = M.u and t = M.t end
>       The type `t#row' is required but not provided
>```

Shadowing the type `t` and `u` with an include mostly makes the pre-existing dangling ghost row type more visible.

**Review by gasche — APPROVED** [review]
Thanks! This is clearer with the extra explanation of the complex-recursive-group case, which could be added to the commit message.

File: Changes [hunk 2]
```diff
@@ -348,6 +348,9 @@ Working version
 
 ### Bug fixes:
 
+- #6985, #????: ghost types should stay hidden
+  (Florian Angetti, review by ???)
```
Comment (anmonteiro) [inline Changes]: @Octachron I think you typed your own name wrong 😂
