### PR TITLE
x86: Force result of Icomp to be in a register

### LINKED ISSUE #11803: Error: operand size mismatch for `movzb' for 32+bit compiler
Dear OCaml devs,

when compiling coq-serapi in 32bit OCaml we are seeing this:
```
$ dune build -p coq-serapi
File "serlib/.serlib.objs/native/_unknown_", line 1, characters 0-0:
(cd _build/default && /home/egallego/.opam/jscoq+32bit/bin/ocamlopt.opt -w -40 -rectypes -g -ppx '.ppx/341932708445810a638020e478ebc4f1/ppx.exe --as-ppx --cookie '\''library-name="serlib"'\''' -I serlib/.serlib.objs/byte -I serlib/.serlib.objs/native -I /home/egallego/.opam/jscoq+32bit/lib/base -I /home/egallego/.opam/jscoq+32bit/lib/base/base_internalhash_types -I /home/egallego/.opam/jscoq+32bit/lib/base/caml -I /home/egallego/.opam/jscoq+32bit/lib/base/shadow_stdlib -I /home/egallego/.opam/jscoq+32bit/lib/findlib -I /home/egallego/.opam/jscoq+32bit/lib/ocaml/threads -I /home/egallego/.opam/jscoq+32bit/lib/parsexp -I /home/egallego/.opam/jscoq+32bit/lib/ppx_compare/runtime-lib -I /home/egallego/.opam/jscoq+32bit/lib/ppx_deriving/runtime -I /home/egallego/.opam/jscoq+32bit/lib/ppx_deriving_yojson/runtime -I /home/egallego/.opam/jscoq+32bit/lib/ppx_hash/runtime-lib -I /home/egallego/.opam/jscoq+32bit/lib/ppx_sexp_conv/runtime-lib -I /home/egallego/.opam/jscoq+32bit/lib/result -I /home/egallego/.opam/jscoq+32bit/lib/seq -I /home/egallego/.opam/jscoq+32bit/lib/sexplib -I /home/egallego/.opam/jscoq+32bit/lib/sexplib0 -I /home/egallego/.opam/jscoq+32bit/lib/yojson -I /home/egallego/.opam/jscoq+32bit/lib/zarith -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/boot -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/clib -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/config -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/coqworkmgrapi -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/engine -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/gramlib -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/interp -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/kernel -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/lib -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/library -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/parsing -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/pretyping -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/printing -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/proofs -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/stm -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/sysinit -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/tactics -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/vernac -I /home/egallego/external/coq-master/_build/install/default/lib/coq-core/vm -intf-suffix .ml -no-alias-deps -open Serlib -o serlib/.serlib.objs/native/serlib__Ser_glob_term.cmx -c -impl serlib/ser_glob_term.ml)
/tmp/build_15c8bd_dune/camlasmcddc6e.s: Assembler messages:
/tmp/build_15c8bd_dune/camlasmcddc6e.s:10336: Error: operand size mismatch for `movzb'
File "serlib/ser_glob_term.ml", line 1:
Error: Assembler error, input left in file /tmp/build_15c8bd_dune/camlasmcddc6e.s
```

this was first detected by opam CI system. To reproduce try to build coq-serapi as above. Note that a dune build with the `dev` profile doesn't trigger this error. I can reproduce in 4.12 and 4.14

cc #10626 cc @kit-ty-kate

### PR DESCRIPTION
**Pull request by lthls**
Fixes #11803.
I've made the PR against 4.14, as the bug report only mentioned 32-bit native code which is not supported on trunk, but I think this should be considered for trunk too.
I've checked that the issue reported in #11803 disappears with this patch.

### CODE REVIEW

File: asmcomp/amd64/reload.ml [hunk 1]
```diff
@@ -66,7 +67,18 @@ inherit Reloadgen.reload_generic as super
...
+      if stackp arg.(0) && stackp arg.(1)
+      then ([|arg.(0); self#makereg arg.(1)|], res)
+      else (arg, res)
+  | Iintop(Icomp _) ->
+      (* The result must be a register *)
+      let res =
+        if stackp res.(0)
+        then [|self#makereg res.(0)|]
+        else res
+      in
```
Comment (xavierleroy) [inline asmcomp/amd64/reload.ml]: `makereg` is a no-op if the argument is already a register, and there's `makeregs` to handle arrays of regs.  Proposed simplification:
```suggestion
      (* The result must be a register (PR#11083) *)
      let res = self#makeregs res in
```

File: asmcomp/amd64/reload.ml [hunk 2]
```diff
@@ -80,6 +92,11 @@ method! reload_operation op arg res =
       if stackp arg.(0)
       then (let r = self#makereg arg.(0) in ([|r|], [|r|]))
       else (arg, res)
+  | Iintop_imm(Icomp _, _) ->
+      (* The result must be in a register *)
+      if stackp res.(0)
+      then (arg, [|self#makereg res.(0)|])
+      else (arg, res)
```
Comment (xavierleroy) [inline asmcomp/amd64/reload.ml]: Similar suggestion:
```suggestion
  | Iintop_imm(Icomp _, _) ->
      (* The result must be in a register (PR#11083) *)
      (arg, self#makeregs res)
```

**Review by xavierleroy — COMMENTED** [review]
Looks good to me.  A suggestion for shorter code below.  To be copy-pasted to i386 if you adopt it.

An alternative that I considered is to force the result of `Icomp` to be in the RAX register, and emit code like this:
```
  xor rax, rax
  cmp ...
  setxx al
```
This avoids a partial register stall on writing to AL, which could be good for performance.  However, if the result cannot be held in RAX, an extra move will be generated by the register allocator.

File: asmcomp/amd64/reload.ml (hunk 1 above)
Comment (lthls) [reply asmcomp/amd64/reload.ml]: I didn't think of calling `makereg` even in the register case, but I didn't use `makeregs` because it wasn't exported. I assume that there's no harm in exporting it though, so I've pushed a patch with your suggestion.

**Comment by stedolan** [comment]
> An alternative that I considered is to force the result of Icomp to be in the RAX register, and emit code like this:

That code sequence looks like it's probably better (as you say, avoiding the partial reg stall is good). But the xor should be after the `cmp`, because one of the arguments can arrive in RAX.

**Comment by xavierleroy** [comment]
> But the xor should be after the cmp, because one of the arguments can arrive in RAX.

Good point.  But the xor changes the condition codes :-)  A move should do, however:
```
  cmp ...
  movl $0, eax
  setxx al
```

**Comment by smuenzel** [comment]
> 
> ```
>   cmp ...
>   movl $0, eax
>   setxx al
> ```
I believe that `movl 0` is not one of the zeroing idioms recognized by most processors, meaning that the instruction has to be executed by the processor. `xor` is eliminated by rename, so it does not consume execution resources

**Comment by stedolan** [comment]
> But the xor changes the condition codes :-)

Hah, true! Perhaps we should have `Emit` choose `xor; cmp; setcc` when the result does not alias the input, and `cmp; mov; setcc` when it does?

Incidentally, on amd64 there's no need to have a `mov` at the end, since `setcc` can reach the low 8 bits of every integer register. (This is not true on i386 where the 8-bit registers are weird)

**Comment by smuenzel** [comment]
There is some useful discussion here: https://stackoverflow.com/questions/33666617/what-is-the-best-way-to-set-a-register-to-zero-in-x86-assembly-xor-mov-or-and (see the section "Things are more complicated when you don't want to xor before a flag-setting instruction. ")

**Review by xavierleroy — APPROVED** [review]
Looks good to me.  Thanks!

**Comment by xavierleroy** [comment]
OK, this is merged on 4.14.  Once CI is happy we'll backport to trunk.

**Comment by xavierleroy** [comment]
Cherry-picked to trunk: c314da5c74

**Comment by xavierleroy** [comment]
@stedolan @smuenzel : I pushed the quick fix for issue #11803, but you're welcome to try  and improve the x86-64 code generated for `Icomp` instructions.  In my opinion, it's not performance-critical, but it's a good reminder of how awful the x86 ISA is :-)
