### PR TITLE
Attempt at a thread-safe implementation of DLS

### LINKED ISSUE #12677: `Domain.DLS` is not thread-safe
The current `Domain.DLS` implementation is not (sys)thread-safe, because the implementations of the various state updating operations include safe points during which the runtime may switch between threads.  I'll briefly highlight some specific scenarios of what can go wrong.

Consider the implementation of `Domain.DLS.get`: https://github.com/ocaml/ocaml/blob/e397ed28bcef85fdc1f0f007af481ef201fb1fd7/stdlib/domain.ml#L120-L127

Two threads on a single domain that concurrently `get` with the same key before `init` has been called may both end up calling `init` (so `init` would be called twice for a single key).  That can happen because `maybe_grow` (which potentially allocates) includes a safe point and because `init` (which often allocates) itself may include a safe point.  What can happen then is that the two calls of `get` return two different results (e.g. two different mutable records), one of which is stored in DLS.

Consider the implementation of the internal `Domain.DLS.maybe_grow`: https://github.com/ocaml/ocaml/blob/e397ed28bcef85fdc1f0f007af481ef201fb1fd7/stdlib/domain.ml#L98-L111

Two threads on a single domain that concurrently `get` with two different keys both call `maybe_grow` and may both end up allocating a new array for the DLS.  This is possible because `maybe_grow` includes a safe point.  Only one of the two arrays eventually ends up being stored as the DLS and one of the `get` operations ends up being undone.  Furthermore if the two threads also perform `set` operations, some of those may end up being undone.

Here is an example interleaving (variation of the above) where the effects of `DLS` operations performed by Thread B vanish:

```
  Thread A                 Thread B
  get x starts

    <--- switch at a safe point --->
  
                           get y starts
                           get y ends
                           set y starts
                           set y ends  

    <--- switch at a safe point --->
  
  set_dls_state
  get x ends
```

The effects of both `get y` and `set y` vanish.  Even just having `get y` vanish is a problem, because `get` may call `init`, which may return a mutable object, which might be mutated or stored outside of the DLS.

### PR DESCRIPTION
**Pull request by gasche**
This is a proposal to fix #12677, making Domain.DLS thread-safe -- or rather, understanding, improving and specifying its behavior in presence of multiple threads on the same domain.

~~This is marked as a Draft because I have *not* tested the code, only that it compiles. Writing tests for thread-safety issue is less tempting to me than writing thread-safe code, so I am hoping that some other people (perhaps @polytypic or @jmid ) would be willing to lend a hand to test this / write a test.~~

Seeing the code now (before it is ready for upstreaming) can still be informative to see whether we can hope for a low-invasiveness fix for 5.2, independently of the complete-design-change proposal in #12724.

There are three changes in the PR:

1. The array-resizing logic is made thread-safe by checking whether another thread already resized the array, and giving up / retrying in that case. This relies on a new `compare_and_set`-like primitive for the dls root.

2. We accept that the `init : unit -> 'a` function provided by the user to initialize the key on first `get` may be called several times if several threads call `get` at the same time. We ensure and specify that only the first such value gets used, redundant initialization computations that finish later are discarded.
   This is worth discussing. In particular we could decide to instead fail in this case. But I don't see how users would write programs if we failed by default in this case. The recommendation in the PR is for users to protect their initialization function if they do not support redundant initializations.

3. I refactored the handling of `unique_value` to be hidden in an internal module (this is inspired by my work on unboxed dynarrays: #12885 ). I did this in the context of a first iteration of (2) that stored lazy thunks in the `st` arrays. I gave up on this approach (it fails on concurrent initialization, which I think is the wrong behavior), but I kept the refactoring because I think it clarifies the code, at least it helps me write and think about this code.

### CODE REVIEW

**Comment by SGrondin** [comment]
I already have a test for this in another project, I think. However it's not a test we'd be able to put into the `testsuite/` directory. I'll run it on this PR next weekend and report back.

**Comment by gasche** [comment]
> However it's not a test we'd be able to put into the testsuite/ directory.

This is fine with me, but it would be nice if there is a version that I can run myself if I need to iterate on the PR. Thanks!

**Comment by gasche** [comment]
I think that we need someone to contribute soon, in reviewer position, if we want to get this in 5.2.

**Comment by gasche** [comment]
I wrote a test and marked the PR as "ready for review".

The test was useful as it caught a bug with the previous version of the PR, which accounted for resize/resize races and init/init races, but not resize/init races. Now the test passes and the code is more robust.

File: runtime/domain.c [hunk 1]
```diff
@@ -1996,6 +1996,18 @@ CAMLprim value caml_domain_dls_get(value unused)
...
+  CAMLnoalloc;
+  value current = Caml_state->dls_root;
+  if (current == old) {
+    caml_modify_generational_global_root(&Caml_state->dls_root, new);
+    return Val_true;
+  } else {
+    return Val_false;
+  }
+}
+
```
Comment (OlivierNicole) [inline runtime/domain.c:2019]: While OCaml code cannot run in parallel on the same domain, C code has no such restriction. Therefore extra care must be taken here to ensure that this function can never run concurrently with itself, otherwise we have a C-level data race. That makes me a bit uneasy in terms of robustness to changes.

**Comment by OlivierNicole** [comment]
I am reviewing this.

File: stdlib/domain.ml [hunk 2]
```diff
@@ -104,40 +125,67 @@ module DLS = struct
...
+
+
+  let[@inline never] array_compare_and_set a i oldval newval =
+    (* Note: we cannot use [@poll error] due to the
+       allocations on a.(i) in the Double_array case. *)
+    let curval = a.(i) in
+    if curval == oldval then (
+      Array.unsafe_set a i newval;
+      true
+    ) else false
```
Comment (OlivierNicole) [inline stdlib/domain.ml:156]: Minor: all lines except the first could be put into a function `aux` marked with `[@poll error]`.

File: stdlib/domain.mli [hunk 3]
```diff
@@ -105,6 +105,14 @@ module DLS : sig
         domain will be computed on-demand by the new domain: the first
         [get] call will call the initializer [f] and store that value.
 
+        {b Warning.} [f] may be called several times if several
+        threads on the same domain try to access the key
+        concurrently. Only the 'first' value computed will be used,
+        the other now-useless values will be discarded. If you have
+        a function [f] that cannot be safely called several times, you
+        should protect it by using a boolean flag to detect this and
+        fail, or a mutex, etc.
```
Comment (OlivierNicole) [inline stdlib/domain.mli]:
```suggestion
        should protect it by using an atomic boolean flag to detect this and
        fail, or a mutex, etc.
```
Minor: maybe we shouldn’t let beginners think they can get away with a non-atomic flag.

**Review by OlivierNicole — APPROVED** [review]
This change is a net improvement and I believe it does make DLS thread-safe. I like the `Obj_opt` module, and it fixes a potential bug (missing `opaque_identity` in `DLS.set_initial_key`).

That being said, overall the choice not to use atomic values forces the code to rely on a large set of fragile assumptions: about safe points, about allowed compiler reorderings, about C primitives not releasing the domain lock… I think it would be more future-proof to use atomics and implement locking algorithms that scale well even in contended scenarios (I am not experienced enough to confidently propose some myself, unfortunately, but I believe they exist). The current code can work as an intermediary state but I would feel better if we planned to eventually move toward something else.

More minor, but it is a shame IMO to shift the responsibility of protecting the `init : unit -> 'a` function to the DLS user, instead of enforcing it ourselves with an atomic. It can avoid some contention when `init` requires no protection, but that must be put into balance with the fact that: 1. user-written protection will still cause contention; 2. it will likely be less efficient than a protection written by us, or even incorrect.

However, this can be also done later as a backward-compatible change.

**Comment by OlivierNicole** [comment]
It looks like the test creates too many threads on i386. Maybe the number could be a bit lower?

File: stdlib/domain.mli (hunk 3 above)
Comment (gasche) [reply stdlib/domain.mli]: I'm confused, they can absolutely get away with a non-atomic flag.

```ocaml
let once f =
  let already_called = ref false in
  fun () ->
    if !already_called then invalid_arg "this function may only be called once";
    already_called := true;
    f ()
```

File: runtime/domain.c (hunk 1 above)
Comment (gasche) [reply runtime/domain.c:2019]: `Caml_state` can only be used when the runtime lock is held, so I don't think that we have to worry about races occurring due to this function, it has the same only-one-thread-at-once restriction as OCaml mutator code.

File: stdlib/domain.ml (hunk 2 above)
Comment (gasche) [reply stdlib/domain.ml:156]: What I would rather do is to have a version of "uniform arrays" with a simpler implementation, to make `@poll error` more precise. The problem with your proposal is that you are introducing intermediary function calls, which could in turn introduce poll points. (I think that function calls are poll points in bytecode for example.)

**Comment by gasche** [comment]
> That being said, overall the choice not to use atomic values forces the code to rely on a large set of fragile assumptions: about safe points, about allowed compiler reorderings, about C primitives not releasing the domain lock… I think it would be more future-proof to use atomics and implement locking algorithms that scale well even in contended scenarios (I am not experienced enough to confidently propose some myself, unfortunately, but I believe they exist)

What we are implementing here is Domain.DLS, which is supposed to provide domain-local state, that is, basically, a reference cell per domain, and which is *designed* to avoid synchronization across domains. I am wary of trying to reason about the performance overhead of introducing an atomic read in the fast path of `DLS.get`; this is not my area of expertise, but I would worry about creating scalability bottlenecks on relaxed architectures where barriers are more costly. The PR as proposed does not change the performance profile of the fast path at all (when the value is already initialized), so it is very easy to tell that it should not create performance regressions.

If you have an idea in mind that use atomics only in the slow path (where initialization is required), that would probably be fine. But I don't know what it is that you would suggest doing with atomics there.

> More minor, but it is a shame IMO to shift the responsibility of protecting the init : unit -> 'a function to the DLS user, instead of enforcing it ourselves with an atomic.

What sort of protection do you actually have in mind?
- If you mean "failing when concurrent initialization is detected", I believe that this is the wrong default -- how can users write programs that use both Thread and Domain.DLS in this context, if it is invalid to ever have two threads call `DLS.get` at the same time? 
- If you mean "take a mutex to block other threads from initializing the value", this might be a better default, but it risks blowing up in the user face in the case of reentrancy scenarios (if DLS.get is called from a signal handler or a memprof callback, from the same thread that is already holding the lock to call the `init ()` function). Being able to call `DLS.get` from a memprof callback in particular sounds rather convenient.

My intuition is that most key-initialization functions can in fact tolerate redundant calls just fine and do not need any sort of protection -- this is at least the case of all the uses of `DLS.new_key` in the standard library.

> It looks like the test creates too many threads on i386. Maybe the number could be a bit lower?

Thanks, I will lower the thread count -- I will look for which constants still reliably trigger the bug on my machine.

File: stdlib/domain.mli (hunk 3 above)
Comment (gasche) [reply stdlib/domain.mli]: Thinking about this more, `once` does not quite work as it prevents calling the function from several domains. We could use a DLS cell to remember if the initialization function was called, but it looks a bit weird.

```ocaml
let once_per_domain init =
  let already_called = Domain.DLS.new_key (fun () -> false) in
  fun () ->
    let called = Domain.DLS.get already_called in
    if called then failwith "...";
    Domain.DLS.set already_called true;
    init ()
```

**Comment by gasche** [comment]
I toned down the test considerably, instead of 10 threads per key for 100 DLS keys, it now runs 3 threads per key for 10 DLS keys. (We can still observe rebase/init races on my machine, but they seem to not happen for every run, maybe 1/5 runs. This means that if we were to introduce a regression only in that case, the test would become flaky.)

File: runtime/domain.c (hunk 1 above)
Comment (OlivierNicole) [reply runtime/domain.c:2019]: I didn’t know that! Thanks.

File: stdlib/domain.ml (hunk 2 above)
Comment (OlivierNicole) [reply stdlib/domain.ml:156]: Right, I hadn’t thought of that. Never mind my comment then.

File: stdlib/domain.mli (hunk 3 above)
Comment (OlivierNicole) [reply stdlib/domain.mli]: My bad, it had slipped my mind that the two executions of `f` do not happen truly in parallel. in that case, would it make sense to add a sentence like “Note that the calls to `f` may be concurrent (although only one thread will run OCaml code at a time)”, or something along these lines?

**Comment by OlivierNicole** [comment]
> What sort of protection do you actually have in mind?
> 
>   * If you mean "failing when concurrent initialization is detected", I believe that this is the wrong default -- how can users write programs that use both Thread and Domain.DLS in this context, if it is invalid to ever have two threads call `DLS.get` at the same time?
> 
>   * If you mean "take a mutex to block other threads from initializing the value", this might be a better default, but it risks blowing up in the user face in the case of reentrancy scenarios (if DLS.get is called from a signal handler or a memprof callback, from the same thread that is already holding the lock to call the `init ()` function). Being able to call `DLS.get` from a memprof callback in particular sounds rather convenient.
> 
> 
> My intuition is that most key-initialization functions can in fact tolerate redundant calls just fine and do not need any sort of protection -- this is at least the case of all the uses of `DLS.new_key` in the standard library.

I was thinking about the second type of protection, but your arguments convinced me that it might not be such a good idea.

File: stdlib/domain.ml [hunk 4]
```diff
@@ -104,40 +125,75 @@ module DLS = struct
...
+      let st = get_dls_state () in
+      if array_compare_and_set st idx obj new_obj
+      then v
+      else begin
+        (* if st.(idx) changed, someone must have initialized
+           the key in the meantime. *)
+        let updated_obj = st.(idx) in
+        if Obj_opt.is_some updated_obj
+        then (Obj_opt.unsafe_get updated_obj : a)
+        else assert false
```
Comment (OlivierNicole) [inline stdlib/domain.ml:184]: Nit: saves one line.
```suggestion
        assert (Obj_opt.is_some updated_obj);
        (Obj_opt.unsafe_get updated_obj : a)
```

Comment (gasche) [reply stdlib/domain.ml:184]: I used the current version to remain statically safe under the `-noassert` flag, which disables all `assert` expressions except `assert false`.

**Comment by gasche** [comment]
@OlivierNicole we have had detailed discussions of the code and your review comments since after you made your review. Does your initial "approval" still stands?

This PR needs an approval from a maintainer, on their own or on behalf of @OlivierNicole.

**Comment by gasche** [comment]
Note: this PR is a subtle, non-trivial change to the DLS implementation, so it would be great if we could manage to get this merged before the wider 5.2 testing starts, to maximize our chances of catching potential regressions. This means that the target for merging really is "in a couple weeks".

File: stdlib/domain.ml (hunk 4 above)
Comment (OlivierNicole) [reply stdlib/domain.ml:184]: Oh, I didn’t know about this.

**Comment by OlivierNicole** [comment]
> @OlivierNicole we have had detailed discussions of the code and your review comments since after you made your review. Does your initial "approval" still stands?

I was about to answer yes, but then I came across [a Discuss post by @gadmm](https://discuss.ocaml.org/t/using-poll-error-attribute-to-implement-systhread-safe-data-structures/12804/2) where he says:

> `[@poll error]` is also inoperant in bytecode (which is trickier because it has more polling locations).

So the polling locations in bytecode should be checked (I’ll try to do that soon…). Then I’ll approve the bugfix, while still saying that to me this code should be improved in the future to not rely on many subtle invariants. In a discussion with @sadiqj he said that an `Atomic.get` instead of a plain read on the fast path would probably make no noticeable difference on all reasonable architectures. @polytypic also noted that this is a case where TLS would make the implementation trivially easy and performant.

**Comment by gasche** [comment]
>  @polytypic also noted that this is a case where TLS would make the implementation trivially easy and performant.

Of course, the present PR is meant to fix a bug ( reported by @polytypic ) in 5.2, before a behavior change from DLS to TLS that we hope to happen in 5.3 -- and clearly is out of scope for 5.2.

**Comment by gasche** [comment]
>  to me this code should be improved in the future to not rely on many subtle invariants

Do we have a practical way to do this in mind? The only ones I can think of are as follows:

1. Implement all this in C instead of OCaml, to easily control where poll points occur. (At the cost of a bleh programming language.)
2. Substantially improve the language-level support for poll-safe programming in OCaml, for example with a language construct for masking of asynchronous callbacks. (Spec: delay all callbacks that can be delayed, for example on all allocations, fail if code within may have non-delayable callbacks, for example function calls).

Neither of those approach seem preferable to the current one, to me, in the desired time target of 5.2.

**Comment by gasche** [comment]
Note: I also discussed this problem (how the heck can we write thread-safe programs?) with @gadmm this week. One suggestion he made is to implement a "single-threaded atomics" module in stdlib/camlinternal* or utils/, similar to the implementation of Atomic that we had in 4.x: https://github.com/ocaml/ocaml/blob/4.14/stdlib/camlinternalAtomic.ml (but: for DLS we need atomic operations on Array, in addition to references).

I think that this is a good suggestion, and it aligns well with the current implementation which basically includes such a helper function in the middle of Domain.DLS instead of a dedicated module. However I am *not* suggesting to do this in the general way (a new module and all) in the context of the present PR, because I am tired of working on it and I would like the bugfix to be merged in a reasonable time frame.

**Comment by OlivierNicole** [comment]
> However I am not suggesting to do this in the general way (a new module and all) in the context of the present PR, because I am tired of working on it and I would like the bugfix to be merged in a reasonable time frame.

I don’t have a problem with that. However, I wouldn’t take my task of reviewer seriously if I approved this PR without checking that the code is correct in bytecode by checking the set of possible poll points (the big interpreter loop takes a bit of time to audit, as well as the emission of the `CHECK_SIGNALS` opcode). If you do it and say that it makes no difference, I will take your word for it. Otherwise, I will check it myself. I am doing my best to do this quickly! :slightly_smiling_face: but I am sure that you will understand that I have to juggle it with other time constraints.

**Comment by gasche** [comment]
No problem with that. I *think* that the code is correct in bytecode as well, but I'm happy to let you check as well.

**Review by OlivierNicole — APPROVED** [review]
It turns out that checking bytecode poll points was quicker than I thought.

From what I can see, in addition to polling everywhere the native program would also poll, the bytecode interpreter polls right before uninstalling an exception handler, and after switching fibers (i.e., after installing an effect handler, or performing an effect, or resuming a continuation). Nothing that threatens the correctness of this PR, so I re-iterate my approval.

**Comment by gasche** [comment]
Thanks!

For the record, I think that another difference is that all function applications (that result in an `APP*` bytecode instruction) are poll points due the fallthrough from `check_stacks:` to `CHECK_SIGNALS` in interp.c.

**Comment by OlivierNicole** [comment]
Ah, yes. In native code only recursive functions contain poll points, right?

**Comment by OlivierNicole** [comment]
> Note: I also discussed this problem (how the heck can we write thread-safe programs?) with @gadmm this week. One suggestion he made is to implement a "single-threaded atomics" module in stdlib/camlinternal* or utils/, similar to the implementation of Atomic that we had in 4.x: https://github.com/ocaml/ocaml/blob/4.14/stdlib/camlinternalAtomic.ml (but: for DLS we need atomic operations on Array, in addition to references).

That could be an idea. I would still be interested to know if there is a way to use atomics there in an almost-free way (on the fast path) to have the equivalent at a negligible cost, in a way that is more robust to compiler optimizations: the discussion in #12900 has shown that reasoning about this is non-trivial and requires deep knowledge of the compiler (and relies on invariants that may not be true forever). I personally lack knowledge regarding multicore performance.

Alternatively, ideally your proposal would integrate guarantees against some reorderings.

File: stdlib/domain.ml [hunk 5]
```diff
@@ -55,17 +55,38 @@ type 'a t = {
...
 
-  type dls_state = Obj.t array
+  module Obj_opt : sig
+    type t
+    val none : t
+    val some : 'a -> t
+    val is_some : t -> bool
+
+    (** [unsafe_obj obj] may only be called safely
+        if [is_some] is true.
```
Comment (damiendoligez) [inline stdlib/domain.ml]:
```suggestion
    (** [unsafe_get obj] may only be called safely
        if [is_some obj] is true.
```

File: stdlib/domain.ml [hunk 6]
```diff
@@ -104,40 +125,75 @@ module DLS = struct
...
      * We do not want OCaml's float array optimisation kicking in here. *)
-    st.(idx) <- Obj.repr (Sys.opaque_identity x)
+    st.(idx) <- Obj_opt.some (Sys.opaque_identity x)
+
 
-  let get (idx, init) =
+  let[@inline never] array_compare_and_set a i oldval newval =
+    (* Note: we cannot use [@poll error] due to the
+       allocations on a.(i) in the Double_array case. *)
+    let curval = a.(i) in
```
Comment (damiendoligez) [inline stdlib/domain.ml:152]: You could get around this problem by using `Obj.(obj (field (repr a) i))` instead of `a.(i)`.
This amounts to using `Obj.t` as your "uniform array" type.

File: stdlib/domain.ml (hunk 4 above)
Comment (damiendoligez) [reply stdlib/domain.ml:184]: You can still save one line:
```suggestion
        if not (Obj_opt.is_some updated_obj) then assert false;
        (Obj_opt.unsafe_get updated_obj : a)
```
Don't you love double negations?

File: stdlib/domain.mli [hunk 7]
```diff
@@ -105,6 +105,14 @@ module DLS : sig
         domain will be computed on-demand by the new domain: the first
         [get] call will call the initializer [f] and store that value.
 
+        {b Warning.} [f] may be called several times if several
+        threads on the same domain try to access the key
+        concurrently. Only the 'first' value computed will be used,
```
Comment (damiendoligez) [inline stdlib/domain.mli]: Isn't that overly specific? What about signal handlers, finalizers, etc? What if `f` itself is using DLS?

**Review by damiendoligez — COMMENTED** [review]
Looks almost good. I think the doc comment for `new_key` needs work.

File: stdlib/domain.ml (hunk 6 above)
Comment (gasche) [reply stdlib/domain.ml:152]: Actually this trick does not work, `Obj.field` gets compiled in the same way as `Array.unsafe_get`, it generates a conditional on the block tag and an allocation in the float path. I could suppress this code path with a well-placed `let a = (Obj.magic a : int array)`, but this feels too evil to me -- I don't know that it is safe.

File: stdlib/domain.mli (hunk 7 above)
Comment (gasche) [reply stdlib/domain.mli]: New wording, what do you think?

        {b Warning.} [f] may be called several times if another call
        to [get] occurs during initialization on the same domain. Only
        the 'first' value computed will be used, the other now-useless
        values will be discarded. Your initialization function should
        support this situation, or contain logic to detect this case
        and fail.

**Comment by gasche** [comment]
I took @damiendoligez's comments into account and rebased the PR.

**Comment by gasche** [comment]
(This still needs the approval of a maintainer to be merged.)

**Comment by Octachron** [comment]
@gasche , there is now a maintainer approval.

**Comment by gasche** [comment]
I don't see any maintainer approval through the Github UI, but I am willing to trust your slightly cryptic message as implying that you or some other maintainer approves of this PR. I will rebase right now to re-run the CI, and I would be happy to merge if that passes.

**Comment by Octachron** [comment]
Sorry for the implicitness, I was pointing to the fact that @OlivierNicole's approval is now a maintainer's approval.

**Comment by gasche** [comment]
Duh, right, thanks!

**Comment by gasche** [comment]
(So *this* is what I need to do to get my PRs merged :-)

**Comment by gasche** [comment]
@OlivierNicole would you do the honors of clicking the "Merge pull request" button?

File: stdlib/domain.mli [hunk 8]
```diff
@@ -105,6 +105,13 @@ module DLS : sig
         domain will be computed on-demand by the new domain: the first
         [get] call will call the initializer [f] and store that value.
 
+        {b Warning.} [f] may be called several times if another call
+        to [get] occurs during initialization on the same domain. Only
+        the 'first' value computed will be used, the other now-useless
+        values will be discarded. Your initialization function should
+        support this situation, or contain logic to detect this case
+        and fail.
```
Comment (gadmm) [inline stdlib/domain.mli:113]: A late caveat to the guarantee of using the first value: in case an asynchronous exception occurs between computation and assignment, the first computed value will be discarded. Similarly, if an asynchronous exception occurs during computation, then there is no guarantee that the first execution of the initialization function will give the value used eventually, so the logic mentioned can be difficult to implement.

Comment (gasche) [reply stdlib/domain.mli:113]: Maybe a reasonable view would be to say that the "first thread to compute the value" is defined by the first thread who manages to *set* the value? (This is what we would do in a concurrent setting anyway, where the synchronziation on this final writes and further reads would define the precedence order.)
