### PR TITLE
Fix missing check of illegal recursive module when using module type substitutions

### LINKED ISSUE #13172: Module type substitutions in signature of recursive modules are not checked for cyclicity
When defining a recursive module with a signature that contains a module type substitution, the substituted module type is not properly checked. This leads to cyclic definitions that makes the typechecker loop : 

```ocaml
module rec X : (sig module type A end with module type A = X.A) 
  = struct module type A end (* infinite loop *)
```

If instead, the substitution is inlined, the typechecker correctly refuses it:
```ocaml
module rec X : (sig module type A = X.A end)
  = struct module type A end (* Error: Illegal recursive module reference *)
```
With *type* substitutions, the typechecker is not fooled and find the cyclic definition : 
```ocaml
module rec X : (sig type t end with type t = X.t) 
  = struct type t end (* Error: The type abbreviation X.t is cyclic *)
```

I think the problem might be solved by tweaking those [two lines](https://github.com/ocaml/ocaml/blob/trunk/typing/typemod.ml#L830), I will try to investigate.

### PR DESCRIPTION
**Pull request by clementblaudeau**
This PR fixes #13172 by resolving module type substitutions, approximating the result and merging them with the main signature. It prevent accepting invalid cyclic signature that previously threw the typechecker into an infinite loop later on.

This used to create an infinite loop:
```ocaml
module rec X : (sig module type A end with module type A = X.A) 
  = struct module type A end
```
Now, it correctly fails with:
```
Error: Illegal recursive module reference
```

### CODE REVIEW

**Comment by smuenzel** [comment]
If you target trunk with this, you'll get nicer error messages (https://github.com/ocaml/ocaml/pull/13646)

**Comment by clementblaudeau** [comment]
Context
-----------
To give a bit more context, this PR addresses the module-type substitutions (`with module type T = ...`, `with module type T := ...`) in the signatures of recursive modules. Before, those were ignored during the approximation phase of the typing of recursive modules. It lead to accepting cyclic definition that threw the typechecker into an infinite loop (https://github.com/ocaml/ocaml/issues/13172). It was also making such code fail to typecheck:

```ocaml
module rec X : sig module type A module X' : A end  
  with module type A = sig type t end
= ...
and Y : sig type u = X.X'.t end = ...
(* Error: The module X.X' is abstract, it cannot have any components *)
```

This PR 
-----------

1. When dealing with a definition of the form `module rec X : S with module type A = S'`, this PR approximates `S`, then `S'`, then merge the results (replace occurrences of `A` by the approximation of `S'`). We assume that approximating and merging commute, ie that it is equivalent to merging `S` and `S'` and approximating the result afterwards (which is not easy to implement for technical reasons).

2. Besides, this PR refactor the `merge_constraint` function, as it is used in three different contexts : (1) for merging during typechecking, (2) for merging of package types, (3) for merging during approximation, and the last two cases do not require the building of a typed tree. The previous function is renamed into `merge_constraint_aux`, and now returns a `merge_result`. Three functions `merge_constraint`, `merge_package_constraint` and `merge_constraint_approx` are provided to serve as interface. They enclose the pattern match on the `merge_result`, which should contain a typed tree in normal mode and none in other cases -- they fail (fatal error) if the result is not as expected.

Remaining issue 
-----------
While it fixes the cyclicity bug and (marginally) improve the expressivity, it can lead to accepting invalid substitutions during the approximation phase that are then caught when typechecking the signatures:

```ocaml
module rec X : sig module type A = sig type t end end 
  with module type A = sig type t = int end 
```
During approximation, we merge : ` sig module type A = sig type t end` with `sig type t end`, which will succeed. Therefore, the typechecking phase of the recursive signatures is reached, and the environment contains a module `X` with the signature `sig module type A = sig type t end`.  However, at this point, the invalid substitution is caught (`type t = int` is not equivalent to `type t`) and the example is rejected. I don't know if it could be exploited further into a serious bug.

**Comment by gasche** [comment]
From a distance it is not clear why `Approx_with_modtype{,subst}` are added to the existing type of `with` constraints (`with_info` in trunk), instead of forming a separate type just for them (`with_approx_info`?). This would make the change less invasive (and possibly a bit simpler). Maybe it would force you to duplicate code, which could be moved to auxiliary functions. Have you tried that approach?

**Comment by clementblaudeau** [comment]
I've rebased the pr on trunk.
As a compromise, I've factor out the common code between the `with_modtype` cases and `approx_with_modtype`. The next step is to do a cleaner refactoring of `merge_constraint`, splitting it into separate functions for each kind of constraint, as they only share the recursive case (when going into submodules). It believe that it might be better to put such refactoring a separate PR ?

File: typing/typemod.ml [hunk 1]
```diff
@@ -802,24 +867,12 @@ let rec approx_modtype env smty =
...
-              ignore (Env.lookup_module_path ~use:false ~load:false
-                        ~loc:lid'.loc lid'.txt env))
-        constraints;
-      body
+      (* the module type body is approximated and resolved to a signature *)
+      let approx_body = approx_modtype env sbody in
+      let initial_sig = extract_sig env sbody.pmty_loc approx_body in
+      (* then, the constraints are approximated and merged *)
+      Mty_signature (List.fold_left
+                       (approx_constraint env) initial_sig constraints)
```
Comment (Octachron) [inline typing/typemod.ml:899]: I think you can document that this is equivalent for well-typed substitution to merging the constraint then approximating since inlining the declaration then approximating the body is equivalent to approximating the declaration body then inlining it in all contexts (`module type t = < >`, `include < >`, `me : < >`) in which a module type path may appear.

File: testsuite/tests/typing-modules/module_type_substitution.ml [hunk 2]
```diff
@@ -367,3 +367,54 @@ Error: The module type "t" is not a valid type for a packed module:
...
+module rec X : (sig module type A module X' : A end)
+               with module type A := sig type t end =
+struct
+  module X' = struct type t = int end
+end
+and Y : sig type u = X.X'.t end = struct type u = X.X'.t end
+[%%expect {|
+module rec X : sig module X' : sig type t end end
+and Y : sig type u = X.X'.t end
+|}]
```
Comment (Octachron) [inline testsuite/tests/typing-modules/module_type_substitution.ml:591]: You are missing a case for a signature replacement

```ocaml
module type S = sig
  module type T = sig
    val x: int
    val y: int
  end
  module X:T
end

module rec M: S with module type T := sig val x: int val y:int end =
struct
  module X= struct let x = 0 let y = 1 end
end
```
(which currently fails)

and you should add a test for the corner case where we have a ill-typed substitution but with a well-typed approximated substitution.

**Comment by clementblaudeau** [comment]
I've added the missing tests:
1. concrete signatures replaced by concrete signatures (both destructive and non-destructive)
2. deep constraints (in submodules)
3. corner-case where approximation makes a ill-formed constraint temporary valid (but is then caught by the re-typecheck)

Writing the latter lead me to uncover a regression introduced by this PR (which I believe is benign): merging *concrete* (non-abstract) module types induce an equivalence check which might fail when the original definition in the body was not approximated (but the constraint was). It is the case when using named module types, which are not approximated. The following code (added as a test) fails: 
```ocaml
module type Test = sig
  module type S = sig module type A = sig type t = int end end
  module rec X : S with module type A = sig type t = int end
end
```
The constraint is approximated into `sig type t end`, not a valid replacement of the original definition `sig type t = int end` which was not approximated. This example is however somewhat contrived: it only occurs when substituting an original signature that was well-formed outside of the recursive knot. Note that merging and then approximating (the inverse order of this PR) is not doable here (besides technical difficulties): the equivalence check is not defined on ill-formed signatures, and there is not way to check wellformedness of constraints before the end of the approximation phase.

I have the following questions : 
1. This regression could be (a) fixed by ignoring the constraint if the merging fails (fallback on previous behavior), (b) fixed by ignoring module type constraints on concrete module types (as they should not allow for more typechecking, nor throw the typechecker into infinite loops), (c) fixed by forcing the approximation of the body even when it is a named module type (which is technically painful) or (d) not fixed.
2. Should the interaction of constraints and approximation be documented in the manual ?

File: typing/typemod.ml (hunk 1 above)
Comment (clementblaudeau) [reply typing/typemod.ml:899]: Added as comments

File: testsuite/tests/typing-modules/module_type_substitution.ml (hunk 2 above)
Comment (clementblaudeau) [reply testsuite/tests/typing-modules/module_type_substitution.ml:591]: Added the corresponding test (and destructive/deep variants)

**Comment by Octachron** [comment]
I would propose option `e`: 
- ignore the inclusion check in the approximation mode

Indeed, when the bootstrapping the recursive module signature we care about constructing a skeleton that contain all types, module types and modules declaration and doesn't contain cross-references to other modules. When constraining a module type, this is achieved with both the LHS and RHS. And if the two module type approximations were in fact not equivalent, the inclusion check at the next round will fail.

File: testsuite/tests/typing-modules/module_type_substitution.ml [hunk 3]
```diff
@@ -367,3 +367,292 @@ Error: The module type "t" is not a valid type for a packed module:
...
+       Type declarations do not match:
+         type t = bool
+       is not included in
+         type t = int
+       The type "bool" is not equal to the type "int"
+|}]
+
+
+(* Defining module types before the recursive module prevents them from being
+   approximated and can (erroneously) make the constraint ill-formed *)
```
Comment (Octachron) [inline testsuite/tests/typing-modules/module_type_substitution.ml]: The comment needs to be updated.

File: typing/typemod.ml [hunk 4]
```diff
@@ -802,24 +871,29 @@ let rec approx_modtype env smty =
...
+         with the equivalence check that is done between the constraint and the
+         original definition:
+
+         1. It can erroneously succeed because the approximation made the module
+         types equivalent. It is believed to be harmless, because the
+         ill-formedness is caught when re-typechecking the module types (with
+         the approximation in the environment).
+
+         2. It can erroneously fail because the constraint has been approximated
+         but the body has not (named module types escape approximation).
```
Comment (Octachron) [inline typing/typemod.ml]: The new comment above disabling the equivalence check should probably be merged here.

Comment (clementblaudeau) [reply typing/typemod.ml]: I merged the two comments

File: testsuite/tests/typing-modules/module_type_substitution.ml (hunk 3 above)
Comment (clementblaudeau) [reply testsuite/tests/typing-modules/module_type_substitution.ml]: Updated the comment and the test to show that approximation allows for ill-formed merging of constraints, before the ill-formedness is caught by the typechecking phase

File: testsuite/tests/typing-modules/module_type_substitution.ml [hunk 5]
```diff
@@ -367,3 +367,288 @@ Error: The module type "t" is not a valid type for a packed module:
...
+(* Invalid substitutions might be accepted during the approximation phase, but
+   should be rejected during typechecking of signatures (before typechecking of
+   module bodies) *)
+module type Test = sig
+  module rec X : (sig
+      module type A = sig type t = bool end
+      module X' : A
+    end with module type A = sig type t = int end)
+  and Y : sig type u = X.X'.t end
+end
```
Comment (Octachron) [inline testsuite/tests/typing-modules/module_type_substitution.ml:571]: This is the same test as the one above?

File: typing/typemod.ml [hunk 6]
```diff
@@ -802,24 +875,27 @@ let rec approx_modtype env smty =
...
+         should be equivalent.
+
+         However, for module type constraints replacing a concrete module type,
+         approximating the constraint and the body before merging can interact
+         with the equivalence check that is done between the constraint and the
+         original definition. As approximation only tries to build a skeleton of
+         non-recursive module types that can be used as an under-approximation
+         of the name-spaces for the typechecking phase, the equivalence check is
+         disabled, allowing for ill-formed constraints to be merged. It is
+         believed to be harmless, because the ill-formedness is caught when
```
Comment (Octachron) [inline typing/typemod.ml]: The code is ready in my opinion, but the comments should be less overly cautious.

File: testsuite/tests/typing-modules/module_type_substitution.ml (hunk 5 above)
Comment (clementblaudeau) [reply testsuite/tests/typing-modules/module_type_substitution.ml:571]: Indeed, it's removed now

File: typing/typemod.ml (hunk 6 above)
Comment (clementblaudeau) [reply typing/typemod.ml]: Updated to "should be harmless"

**Comment by Octachron** [comment]
One test need to be updated due to a recent improvement of the error location for subcomponent of Longident paths.

File: Changes [hunk 7]
```diff
@@ -510,6 +510,9 @@ Working version
 - #13880: Make object stat counters atomic
   (Dimitris Mostrous, review by Gabriel Scherer and Nicolás Ojeda Bär)
 
+- #13172, #13829: Fix a missing check of illegal recursive module type
+   definitions (Clement Blaudeau, review by Florian Angeletti)
```
Comment (Octachron) [inline Changes]: There is a missing newline:
```
- #13172, #13829: Fix a missing check of illegal recursive module type
   definitions
  (Clement Blaudeau, review by Florian Angeletti)
```
