### PR TITLE
Fix tools/check-parser-uptodate-or-warn.sh

### LINKED ISSUE #8965: 4.09: # stat: can't read file system information for '%m': No such file or directory
I have the Alpine-based Dockerfile, with these lines:
```Dockerfile
FROM alpine:edge AS builder
RUN apk add --no-cache make m4 which patch sudo wget git pkgconfig \
	gcc g++ musl-dev linux-headers libffi libffi-dev pcre perl python3 \
	gmp-dev libressl-dev pcre-dev zlib-dev xz-dev \
	ocaml ocaml-compiler-libs ocaml-ocamldoc opam ocaml-findlib \
	unzip gmp xz

RUN chmod +s `which bwrap`

RUN addgroup -g 1000 -S user && adduser -u 1000 -D -S user -G user
RUN sed -i.bkp -e \
	's/%wheel\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%wheel ALL=NOPASSWD:ALL/g' \
	/etc/sudoers
COPY ocamlinit /home/user/.ocamlinit
USER user
WORKDIR /home/user

ENV OCAML_TOPLEVEL_PATH /home/user/.opam/default/lib/toplevel
RUN opam init --auto-setup --disable-sandboxing --yes && \
	# FIXME: Ugly hack
	ln -s /home/user/.opam/default/lib/toplevel /home/user/.opam/default/lib/topfind && \
	eval `opam env` && opam install --yes ocamlfind && \
	opam update --yes && export CHECK_IF_PREINSTALLED=false; \
	opam install --yes opam-devel

RUN eval `opam env` && \
	opam switch create 4.09.0 && \
	opam switch 4.09.0
```
And during the build it returns the following error
```
[ocaml-base-compiler.4.09.0] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
[ERROR] The compilation of ocaml-base-compiler failed at "/usr/bin/make -j7 world".

#=== ERROR while compiling ocaml-base-compiler.4.09.0 =========================#
# context              2.0.3 | linux/x86_64 |  | https://opam.ocaml.org#f335c4dc
# path                 ~/.opam/4.09.0/.opam-switch/build/ocaml-base-compiler.4.09.0
# command              /usr/bin/make -j7 world
# exit-code            2
# env-file             ~/.opam/log/ocaml-base-compiler-7-a00279.env
# output-file          ~/.opam/log/ocaml-base-compiler-7-a00279.out
### output ###
# [...]
# ./boot/ocamlrun ./boot/ocamlc -g -nostdlib -I boot -use-prims runtime/primitives -strict-sequence -principal -absname -w +a-4-9-40-41-42-44-45-48-66 -warn-error A -bin-annot -safe-string -strict-formats -I utils -I parsing -I typing -I bytecomp -I file_formats -I lambda -I middle_end -I middle_end/closure -I middle_end/flambda -I middle_end/flambda/base_types -I asmcomp -I asmcomp/debug -I dr[...]
# ./boot/ocamlrun ./boot/ocamlc -g -nostdlib -I boot -use-prims runtime/primitives -strict-sequence -principal -absname -w +a-4-9-40-41-42-44-45-48-66 -warn-error A -bin-annot -safe-string -strict-formats -I utils -I parsing -I typing -I bytecomp -I file_formats -I lambda -I middle_end -I middle_end/closure -I middle_end/flambda -I middle_end/flambda/base_types -I asmcomp -I asmcomp/debug -I dr[...]
# ./boot/ocamlrun ./boot/ocamlc -g -nostdlib -I boot -use-prims runtime/primitives -strict-sequence -principal -absname -w +a-4-9-40-41-42-44-45-48-66 -warn-error A -bin-annot -safe-string -strict-formats -I utils -I parsing -I typing -I bytecomp -I file_formats -I lambda -I middle_end -I middle_end/closure -I middle_end/flambda -I middle_end/flambda/base_types -I asmcomp -I asmcomp/debug -I dr[...]
# stat: can't read file system information for '%m': No such file or directory
# stat: can't read file system information for '%m': No such file or directory
# tools/check-parser-uptodate-or-warn.sh: line 48: arithmetic syntax error
# make[2]: *** [Makefile:1079: parsing/parser.ml] Error 2
# make[2]: *** Waiting for unfinished jobs....
# make[2]: Leaving directory '/home/user/.opam/4.09.0/.opam-switch/build/ocaml-base-compiler.4.09.0'
# make[1]: *** [Makefile:355: coreall] Error 2
# make[1]: Leaving directory '/home/user/.opam/4.09.0/.opam-switch/build/ocaml-base-compiler.4.09.0'
# make: *** [Makefile:463: world] Error 2

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ocaml-base-compiler 4.09.0
+- 
+- The following changes have been performed (the rest was aborted)
| - install base-bigarray base
| - install base-threads  base
| - install base-unix     base
+- 

<><> ocaml-base-compiler.4.09.0 troubleshooting <><><><><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] n
The command '/bin/sh -c eval `opam env` &&      opam switch create 4.09.0 &&    opam switch 4.09.0' returned a non-zero code: 31
```

### PR DESCRIPTION
**Pull request by gasche**
This PR fixes #8965 (a build failure caused by a warning script) by:
- adding support for Busybox' `stat` to the script
- making the script more robust to unexpected failures
- disabling the script on non-development versions (as suggested by @Octachron)

### CODE REVIEW

**Comment by dra27** [comment]
Rather than peppering the diff with `suggestions`, I've pushed commits any of which you should feel free to blow away - the only thing which has to be fixed is the overly long line (which I fixed by adding an extra error message)

File: tools/check-parser-uptodate-or-warn.sh [hunk 1]
```diff
@@ -16,10 +16,7 @@
 #**************************************************************************
 
 # stop early if we are not on a development version
-if test -z "$(cat VERSION | grep '+dev')"
-then
-    exit 0
-fi
+grep -Fq '+dev' VERSION || exit 0
```
Comment (gasche) [inline tools/check-parser-uptodate-or-warn.sh:19]: How portable is this change to different `grep` implementations? I'm worried about using anything more than the simplest `grep` command.

Comment (dra27) [reply tools/check-parser-uptodate-or-warn.sh:19]: I already checked - `-F` and `-q` are both POSIX, as is the combination of them to `-Fq`!

Comment (dra27) [reply tools/check-parser-uptodate-or-warn.sh:19]: (for the others, the `-F` is overkill, for this one it seems sensible in case some naughty `grep` treats `+` as magic without enabling EREs)

**Comment by XVilka** [comment]
By the way, I recommend to use [`shellcheck`](https://github.com/koalaman/shellcheck) tool (and it [integrates nicely](https://github.com/koalaman/shellcheck#in-your-editor) with both Vim and Emacs) for checking the shell scripts on portability issues and such, they even have an [online interface](https://www.shellcheck.net/).

**Comment by XVilka** [comment]
May I ask, when this landed in the trunk, will it be a part of the future 4.09.1 release, or only for 4.10.0 one?

**Comment by dra27** [comment]
There's no reason not to push it to the 4.09 branch, but there's no guarantee that there will be a 4.09.1 release.

**Comment by gasche** [comment]
(I decided to wait for the INRIA CI reports before backporting into 4.09.)
