### PR TITLE
typecore.ml on Pexp_struct_item: fix #14554

### LINKED ISSUE #14554: `let module` value restriction regression in 5.5?
I'm wondering whether https://github.com/ocaml/ocaml/pull/13839 meant to introduce this change in how the following program gets type checked (cc @nojb).Take this minimal example:

```ocaml
type 'a t

let dog : 'this =
  let module Dog = struct
    external make
      : bark:('self -> unit)
      -> < bark : ('self -> unit) > t = "" ""
  end
  in
  Dog.make ~bark:(fun (o : 'this) -> ())
```

Before https://github.com/ocaml/ocaml/pull/13839:

```sh
$ ocamlc -stop-after typing x.ml
$ echo $?
0
```

After https://github.com/ocaml/ocaml/pull/13839:

```ocaml
$ ./ocamlc.opt -I stdlib -stop-after typing x.ml
File "x.ml", line 4, characters 4-7:
4 | let dog : 'this =
        ^^^
Error: The type of this expression, < bark : '_this -> unit > t,
       contains the non-generalizable type variable(s): '_this.
       (see manual section 6.1.2)
```

### PR DESCRIPTION
**Pull request by gasche**
This PR, co-authored with @samsa1, fixes a temporary regression reported by @anmonteiro, introduced in trunk by #13839  (and also a related bug that was already there before).

fixes #14554

### CODE REVIEW

File: testsuite/tests/typing-misc/letitem.ml [hunk 1]
```diff
@@ -58,11 +58,71 @@ let _ =
...
+      -> < bark : ('self -> unit) > t = "%identity"
+  end
+  in
+  Dog.make ~bark:(fun (o : 'this) -> ())
+[%%expect{|
+val dog : < bark : 'a -> unit > t as 'a = <abstr>
+|}]
+
+(* This variant from Samuel Vivien was correct in OCaml 5.4,
+   and was temporarily broken by #13839. *)
```
Comment (samsa1) [inline testsuite/tests/typing-misc/letitem.ml]: This variant was never accepted in 5.4 because `let external` was not supported

Comment (gasche) [reply testsuite/tests/typing-misc/letitem.ml]: good point, I tweaked the description

**Review by Octachron — APPROVED** [review]
I agree with this fix, since `Pexp_struct_item` introduces a new separate scope for global type variables, and we want to generalize the free type variables after leaving the scope.

**Comment by gasche** [comment]
Thanks! I merged and will cherry-pick into the 5.5 release branch.

**Comment by nojb** [comment]
Thanks @samsa1, @gasche for the speedy fix!
