### PR TITLE
#14474, shape occurrences: fix uid lookup for labels

### LINKED ISSUE #14474: Fatal error: exception File "typing/env.ml", line 1155, characters 9-15: Assertion failed
While testing trunk (df3b8352bfecdbc59948bd74eee4bb066583b13a + https://github.com/ocaml/ocaml/pull/14365), some opam packages failed to build with the following error message:
```
#=== ERROR while compiling menhirLib.20250912 =================================#
# context     2.5.0 | linux/arm64 | ocaml-variants.5.5.0+trunk | git+file:///home/kit_ty_kate/work/opam-repository
# path        ~/.opam/5.5/.opam-switch/build/menhirLib.20250912
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p menhirLib -j 9
# exit-code   1
# env-file    ~/.opam/log/menhirLib-36015-c1ba5b.env
# output-file ~/.opam/log/menhirLib-36015-c1ba5b.out
### output ###
# (cd _build/default/lib/pack && ./pack.exe)
# Creating menhirLib.ml...
# Creating menhirLib.mli...
# File "lib/pack/.menhirLib.objs/byte/_unknown_", line 1, characters 0-0:
# (cd _build/default && /home/kit_ty_kate/.opam/5.5/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I lib/pack/.menhirLib.objs/byte -cmi-file lib/pack/.menhirLib.objs/byte/menhirLib.cmi -no-alias-deps -o lib/pack/.menhirLib.objs/byte/menhirLib.cmo -c -impl lib/pack/menhirLib.ml)
# Fatal error: exception File "typing/env.ml", line 1155, characters 9-15: Assertion failed
```
```
#=== ERROR while compiling csexp.1.5.2 ========================================#
# context     2.5.0 | linux/arm64 | ocaml-variants.5.5.0+trunk | git+file:///home/kit_ty_kate/work/opam-repository
# path        ~/.opam/5.5/.opam-switch/build/csexp.1.5.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p csexp -j 9 @install
# exit-code   1
# env-file    ~/.opam/log/csexp-36015-240f78.env
# output-file ~/.opam/log/csexp-36015-240f78.out
### output ###
# File "src/.csexp.objs/byte/_unknown_", line 1, characters 0-0:
# (cd _build/default && /home/kit_ty_kate/.opam/5.5/bin/ocamlc.opt -w -40 -g -bin-annot -bin-annot-occurrences -I src/.csexp.objs/byte -cmi-file src/.csexp.objs/byte/csexp.cmi -no-alias-deps -o src/.csexp.objs/byte/csexp.cmo -c -impl src/csexp.ml)
# Fatal error: exception File "typing/env.ml", line 1155, characters 9-15: Assertion failed
# (cd _build/default && /home/kit_ty_kate/.opam/5.5/bin/ocamlopt.opt -w -40 -g -I src/.csexp.objs/byte -I src/.csexp.objs/native -cmi-file src/.csexp.objs/byte/csexp.cmi -no-alias-deps -o src/.csexp.objs/native/csexp.cmx -c -impl src/csexp.ml)
# File "src/csexp.ml", line 236, characters 7-14:
# 236 |     [@@inlined always]
#              ^^^^^^^
# Warning 53 [misplaced-attribute]: the inlined attribute cannot appear in this context
```

### PR DESCRIPTION
**Pull request by Octachron**
This PR fixes #14474 by refining the `Env.find_uid` function introduced in #14120 to resolve correctly constructor and field uids for the occurrence index. 

The assertion failure reported in #14474 was due to `find_uid` querying on `shape`-only paths to constructor and fields which reuse `Pextra_ty _` path to encode path to record field and constructor in shape. Those kind of paths are not allowed outside of shapes and thus the `find_type` query in `find_uid` ended reaching an `assert false` in the `type_of_cstr` function  when called on those  non-standard paths.

This PR  extends `Env.find_uid` to handle specifically those extended paths for extension constructors, constructors, and labels avoiding the `assert false` but also making it possible to rename local use of constructor and labels in merlin.

cc @voodoos

### CODE REVIEW

File: testsuite/tests/shape-index/index_functor.ml [hunk 1]
```diff
@@ -35,3 +35,11 @@ module G (X : sig type t = int val x : t module M : S end) = struct
 
   type u = Id (X).t
 end
+
+type e = ..
+module I (X: sig type s = A | B of { r:unit } type r = { x:unit } type e += E  end) = struct
```
Comment (gasche) [inline testsuite/tests/shape-index/index_functor.ml]: nitpick: I would find the example more readable if you would break line between signature items.

File: typing/env.ml [hunk 2]
```diff
@@ -1416,7 +1428,13 @@ let find_uid namespace path env =
         let path = normalize_value_path None env path in
         let vd = find_value path env in
         vd.val_uid
-      | Type | Extension_constructor | Constructor | Label ->
+      | Extension_constructor ->
+         let cda = find_extension_full path env in
```
Comment (gasche) [inline typing/env.ml:1437]: Why is there no `normalize_type_path` in this case? (Maybe we could share this `let path` normalization outside the `match namespace with` part, instead of having it in each case?)

File: typing/env.ml [hunk 3]
```diff
@@ -1416,7 +1428,13 @@ let find_uid namespace path env =
...
+         cda.cda_description.cstr_uid
+      | Constructor | Label ->
+         let path = normalize_type_path None env path in
+         find_type_component_uid path env
```
Comment (gasche) [inline typing/env.ml]: I don't like that this case looks different from all the others, while it could be made to look similar if you wrote it like this (which requires changing the auxiliary definitions, new and existing):

```ocaml
| Constructor ->
  let path = normalize_type_path None env path in
  let cstr = find_cstr path env in
  cstr.cstr_uid
| Label ->
  let path = normalize_type_path None env path in
  let label = find_label path env in
  label.lbl_uid
```

File: typing/env.ml (hunk 2 above)
Comment (Octachron) [reply typing/env.ml:1437]: That was an oversight on my side. Factoring the normalization sounded like a good idea.

File: typing/env.ml (hunk 3 above)
Comment (Octachron) [reply typing/env.ml]: I think there is some value on having a different looking code path here. After all, this case is relying on the non-standard interpretation of `Path.t` only used in shape. Having a very limited function make it harder to confuse this shape-specific function with the other `find_*` functions in `Env.t`.

Comment (gasche) [reply typing/env.ml]: I may be missing something, but my impression is that this interpretation is not non-standard, it is the reasonable/canonical interpretation of these extended paths (as used in `find_type_data` in particular), but because those have only been introduced recently there is not much structure in existing type-checker code.

Comment (Octachron) [reply typing/env.ml]: Outside of the occurrence index, the type `Path.t` is used for resolved type or module paths. Constructors and fields are not given a `Path.t` by the typechecker. 
The normal use of `Pextra_ty _` is to refer to the type of inlined records, for instance in
```ocaml
type t = A of { x : int }| B of { x : float } | C
```
the type of the first record is `t.A`. 

Currently, only the occurrence index is building paths like `t.A.x` to refer to the constructor/fields and using them to do shape projection resolution. 

I can agree that the interpretation is not surprising, but there is a conflict of interpretation for t.C which represents the constructor `C` inside the occurrence index, and a non-existing inline record type `t.C` in a type expression.

Comment (gasche) [reply typing/env.ml]: Is this actually ambiguous? I find it reasonable that `t.C`, in a context where we expect a constructor, means the constructor `C` of the algebraic datatype `t`, and in a context where we expect a type, means the input type of `C`. (But maybe the syntax `t.C` is specifically meant to be a record type and not a general type)

Maybe a compromise would be to have the code look as follows:

```ocaml
| Constructor ->
  let path = normalize_type_path None env path in
  let tpath, name = match find_path_extra path with
  | path, Pcstr_ty name -> path, name
  | _ -> raise ...
  in
  let cstr = find_cstr path name env in
  cstr.cstr_uid
| Label ->
  let path = normalize_type_path None env path in
  let tpath, name = match find_path_extra path with
  | path, Pcstr_ty name -> path, name
  | _ -> raise ...
  in
  let label = find_label path name env in
  label.lbl_uid
```

Comment (Octachron) [reply typing/env.ml]: I find the intent slightly less readable in this form; nevertheless the code is still readable, so I switched to it.

File: typing/env.ml [hunk 4]
```diff
@@ -1409,31 +1420,43 @@ let find_module path env =
...
 
-let find_uid namespace path env =
+let find_uid (namespace: Shape.Sig_component_kind.t) path env =
+  let path = match namespace with
+    | Value | Class -> normalize_value_path None env path
+    | Type | Constructor | Label | Extension_constructor | Class_type ->
+       normalize_type_path None env path
+    | Module -> normalize_module_path None env path
+    | Module_type -> normalize_modtype_path env path
+  in
```
Comment (gasche) [inline typing/env.ml:1430]: Sigh, I wish we had a `normalize_path` function that is namespace-agnostic (or maybe namespace-parametrized?), but this is another nitpick that can wait for a later PR. (I *think* that I'm going to send one just to add a label on the `lax` argument, though.)

**Review by gasche — APPROVED** [review]
I like the new version, thanks! (will you squash the commit history?)

**Comment by Octachron** [comment]
I am planning to squash the commits when merging indeed (probably the day after tomorrow?).

**Review by voodoos — APPROVED** [review]
I just had a look at the implementation and the discussions, and the final results looks fine to me, thanks!
