### PR TITLE
Wrong unmarshaling of function pointers in debugger mode

### LINKED ISSUE #9214: Segfault with installed custom printer in ocamldebug
Dear all,
I am currently unable to use a custom installed printer with ocamldebug in my project because of this segfault.

``mytype.ml``
```ocaml
type mytype = unit -> unit
```
``a.ml``
```ocaml
let () =
  let f : Mytype.mytype = fun _ -> () in
  ()
```
``p.ml``
```ocaml
let print_mytype fmt (f : Mytype.mytype) =
  let _ = f () in (* let _ = f () makes ocamldebug segfault ? *)
  Format.fprintf fmt "(installed printer) !"
```
Ocamldebug ``script``
```
set program a
br @ a 3
run
print f
load_printer p.cmo
install_printer P.print_mytype
print f
```
Commands
```bash
ocamlc -g -bin-annot -o mytype.cmo -c mytype.ml
ocamlc -g -bin-annot -o a.cmo -c a.ml
ocamlc -g -bin-annot -o p.cmo -c p.ml
ocamlc -g -bin-annot -o a mytype.cmo a.cmo
ocamldebug ./a << EOF
so script
EOF
```
Wanted behaviour (if you remove ```let _ = f ()``` for example) :
```bash
(ocd) Loading program... done.
Breakpoint 1 at 0:10532: file a.ml, line 3, characters 3-5
Time: 12 - pc: 0:10532 - module A
Breakpoint: 1
3   <|b|>()
f: Mytype.mytype = <fun>
File p.cmo loaded
f: Mytype.mytype = (installed printer) !
(ocd) Removed breakpoint 1 at 0:10532: file a.ml, line 3, characters 3-5
```
Actual behaviour with trunk c5e875d0 or 4.09.0
```bash
(ocd) Loading program... done.
Breakpoint 1 at 0:10532: file a.ml, line 3, characters 3-5
Time: 12 - pc: 0:10532 - module A
Breakpoint: 1
3   <|b|>()
f: Mytype.mytype = <fun>
File p.cmo loaded
Fatal error: exception End_of_file
Segmentation fault
```

Any idea ?

### PR DESCRIPTION
**Pull request by xavierleroy**
In debugger mode, function closures sent by the debuggee have their code pointer modified so that it points to the `function_placeholder` code in debugger/main.ml.  The idea is that the non-closure parts of the value sent by the debuggee can still be inspected and printed, but if a custom printer invokes the closure, `function_placeholder` is called and raises an exception.

However, this has never worked because this modification was performed incorrectly: the whole closure for `function_placeholder` was used as the code pointer for the unmarshalled closure.  This PR fixes this error by using the code pointer from `function_placeholder` is used as code pointer for the unmarshaled closure.
    
Fixes: #9214

### CODE REVIEW

**Comment by xavierleroy** [comment]
This bug has been with us since 4.00 I believe.  Maybe the fix should be backported to 4.13 and perhaps 4.12 ?

**Review by gasche — APPROVED** [review]
I agree that the fix looks very plausible (thanks for the clear error message) and user testing from #9214 seems to indicate that indeed it fixes the segmentation fault. Approved.

File: runtime/intern.c [hunk 1]
```diff
@@ -511,7 +511,8 @@ static void intern_rec(value *dest)
           const value * function_placeholder =
             caml_named_value ("Debugger.function_placeholder");
           if (function_placeholder != NULL) {
-            v = *function_placeholder;
+            /* Use the code pointer from the "placeholder" function */
+            v = Field(*function_placeholder, 0);
```
Comment (lthls) [inline runtime/intern.c]: Small question: I would have expected the `Code_val` macro instead of `Field`. If I read the code correctly this would require an additional cast to `value`, but it would make it clear that we're reading the code pointer.
Does that make sense ?

Comment (xavierleroy) [reply runtime/intern.c]: Yes, the intent is clearer with `(value) Code_val(*function_placeholder)`.  Done in aab79fd .

**Comment by gasche** [comment]
> Maybe the fix should be backported to 4.13 and perhaps 4.12 ?

Anyone (in particular @Octachron) should feel free to backport, but I think it would be perfectly fine not to: this is a fairly obscure bug, and as far as I know we are not planning to have new bugfix releases of 4.12 or 4.13.

**Comment by xavierleroy** [comment]
I'm not pushing for a backport of this bug fix, as it is an old and obscure bug indeed, and will let @Octachron decide.

**Comment by Octachron** [comment]
We could have a bugfix release of 4.13 at the same time as 4.14.0, but that doesn't sound that useful with the shorter release cycle for 4.14.0.
