### PR TITLE
Bigarray.Genarray.init: fix case of 0-dimensional array

### LINKED ISSUE #11570: Unintuitive behavior with Bigarray.Genarray.init for 0d arrays
Hello,

The following code results in `0.` instead of `5.` as the user might expect; the underlying reason is that when passing an empty array to `Bigarray.Genarray.init`, it does not call the passed function at all. Is changing the behavior here so that the passed function is called once with the argument `[||]` reasonable?

```ocaml
let x = Bigarray.(Genarray.init float64 c_layout [||] (fun _ -> 5.)) in Bigarray.Genarray.get x [||]
```

### PR DESCRIPTION
**Pull request by nojb**
Fixes #11570

### CODE REVIEW

**Comment by nojb** [comment]
Note: I am not yet sure this is the right fix; it seems to work, but am still deciphering the index calculations in `bigarray.c`.

**Comment by nojb** [comment]
> Note: I am not yet sure this is the right fix; it seems to work, but am still deciphering the index calculations in `bigarray.c`.

Right, I think this is correct after all. Review welcome!

File: stdlib/bigarray.ml [hunk 1]
```diff
@@ -115,7 +115,6 @@ module Genarray = struct
   let init (type t) kind (layout : t layout) dims f =
     let arr = create kind layout dims in
     match Array.length dims, layout with
-    | 0, _ -> arr
     | dlen, C_layout -> cloop arr (Array.make dlen 0) f 0 dims; arr
     | dlen, Fortran_layout -> floop arr (Array.make dlen 1) f (pred dlen) dims;
                               arr
```
Comment (yallop) [inline stdlib/bigarray.ml]: Now that there's no branch on `dlen`, it could be pulled out of the `match`:

```ocaml
  let init (type t) kind (layout : t layout) dims f =
    let arr = create kind layout dims in
    let dlen = Array.length dims in
    match layout with
    | C_layout       -> cloop arr (Array.make dlen 0) f          0  dims; arr
    | Fortran_layout -> floop arr (Array.make dlen 1) f (pred dlen) dims; arr
```

Comment (yallop) [inline stdlib/bigarray.ml]: Now that there's no branch on `dlen`, it could be pulled out of the `match`:

```ocaml
  let init (type t) kind (layout : t layout) dims f =
    let arr = create kind layout dims in
    let dlen = Array.length dims in
    match layout with
    | C_layout       -> cloop arr (Array.make dlen 0) f          0  dims; arr
    | Fortran_layout -> floop arr (Array.make dlen 1) f (pred dlen) dims; arr
```

**Review by yallop — APPROVED** [review]
The fix is clearly correct.  There's a small opportunity to make the code more succinct, and we could also consider adding a test for the corrected behaviour (https://github.com/nojb/ocaml/pull/10).

File: stdlib/bigarray.ml (hunk 1 above)
Comment (nojb) [reply stdlib/bigarray.ml]: Right; fixed. Thanks.

**Comment by nojb** [comment]
> The fix is clearly correct. There's a small opportunity to make the code more succinct, and we could also consider adding a test for the corrected behaviour ([nojb#10](https://github.com/nojb/ocaml/pull/10)).

Thanks for the review & the tests, both have been integrated to this PR.

**Comment by nojb** [comment]
(As this touches the standard library, a second review is needed.)

**Review by Octachron — APPROVED** [review]
I also agree that this is the right bug fix; and since this is a bug fix, you can move the change entry to the 5.0 section.

**Comment by nojb** [comment]
> I also agree that this is the right bug fix; and since this is a bug fix, you can move the change entry to the 5.0 section.

Thanks, I forgot to update the Changes entry so I did it in a different commit: https://github.com/ocaml/ocaml/commit/3ac4643e7863ecadbd4f3eaa17a162bafa733a3c

Cherry-picked to 5.0 in https://github.com/ocaml/ocaml/commit/4e4f28e8634da7f6bf0e15cb30d4397194d5311c
