### PR TITLE
The Pattern-Matching Bug: propagate mutability of argument positions

### LINKED ISSUE #7241: Pattern matching with mutable and lazy patterns is unsound
**Original bug ID:** 7241
**Reporter:** @stedolan
**Assigned to:** @maranget
**Status:** assigned (set by @mshinwell on 2017-03-09T12:39:53Z)
**Resolution:** open
**Priority:** normal
**Severity:** crash
**Category:** typing
**Related to:** #5992
**Monitored by:** junsli braibant @gasche @hcarty

## Bug description

Optimised pattern matching skips checking conditions that seem redundant. However, since OCaml supports pattern-matching mutable fields, and code execution during matching via "lazy" patterns, the truth of some conditions can vary during matching.

This can cause seemingly-impossible cases to be taken, if forcing lazy values causes mutations that confuse the optimised matching logic. Due to the presence of GADTs, taking an impossible case is a soundness issue.

For example, this program segfaults:

    type (_, _) eq = Refl : ('a, 'a) eq
    type (_, _) deq = Deq : ('a, 'x) eq option * ('x, 'b) eq option -> ('a, 'b) deq
    
    let deq1 = Deq (Some Refl, None)
    let deq2 = Deq (None, Some Refl)
    
    type ('a, 'b) t = { 
      a : bool; 
      mutable b : ('a, 'b) deq;
      mutable c : int Lazy.t
    }
    
    let g (type a) (type b) : (a, b) t -> (a, b) eq = function
    | { a = true; b = Deq (None, _) }
    | { a = true; b = Deq (Some _, _); c = lazy 1 }
    | { a = false }
    | { b = Deq (_, None) } -> 
       assert false
    | { b = Deq (Some Refl, Some Refl) } ->
       Refl
    
    let bad =
      let r = { a = true; b = deq1; c = lazy 1 } in
      r.c <- lazy (r.b <- deq2; 2);
      g r
    
    let castint (type a) (Refl : (int, a) eq) (x : int) : a = x
    let _ = print_string (castint bad 42)

This program uses mutation to change a field from "deq1" to "deq2" during matching, making it seem like the impossible "Deq (Some Refl, Some Refl)". (The behaviour is very dependent on the exact sequence of cases in "g", and seemingly-equivalent programs will often give different behaviour).

### PR DESCRIPTION
**Pull request by gasche**
This is the next PR in the stack to fix #7241. To fix the bug, we need to pessimize the totality information coming from the type-checker when we switch on arguments/positions that may have been mutated. As suggested by the testcase [match-side-effects/partiality.ml:deep](https://github.com/ocaml/ocaml/blob/63ec086cef237c23aa0120eadc80dfaf2ab7f89c/testsuite/tests/match-side-effects/partiality.ml#L206-L242), positions affected are not just those immediately below a mutable field, but also those that are *transitively* mutable -- there is a mutable field somewhere between the root of the value and the current position.

The present PR does not change the compilation behavior, it just adds a `mut` field to argument records to track whether the argument is in transitively-mutable position. (Currently this information is not tracked at all, unlike the information "immediately mutable" that can be reconstructed from the binding kind of the argument expression.)

(cc @ncik-roberts, @Octachron, @lthls )

### CODE REVIEW

File: lambda/matching.ml [hunk 1]
```diff
@@ -2319,6 +2348,7 @@ let get_expr_args_array ~scopes kind head arg rem =
       {
         arg;
         binding_kind = StrictOpt;
+        mut = compose_mut mut Mutable;
```
Comment (Octachron) [inline lambda/matching.ml:2355]: I am not sure how I feel having constant multiplications by `0` or `1` in the source code, but why not.

Comment (gasche) [reply lambda/matching.ml:2355]: With this code organization I find it much easier to check how mutability information evolves during compilation. (Also: if I wanted to track both the "transitive mutability" and the "immediate mutability" of the argument position, this would be easy to do by changing `mut` here to be a pair, without changing much of the rest of the code. This would let us get rid of `mut_of_binding_kind`. I decided not to do it because there is bigger fish to fry, but it suggests that `compose_mut` is a nice abstraction to have.)

File: lambda/matching.ml [hunk 2]
```diff
@@ -1961,19 +1983,20 @@ let get_expr_args_constr ~scopes head arg rem =
       else
         {
           arg = Lprim (Pfield (pos, Pointer, Immutable), [ arg ], loc);
+          mut;
```
Comment (ncik-roberts) [inline lambda/matching.ml]: Should we also multiply by 1 here to document that the read of this field is immutable? (There are also the inlined record / unboxed variant cases below, but I would say that we shouldn't multiply by 1 there, as there's not actually a "read" happening at runtime.)

File: lambda/matching.ml [hunk 3]
```diff
@@ -3875,9 +3905,15 @@ let toplevel_handler ~scopes loc ~failer partial args cases compile_fun =
                       failure_handler ~scopes loc ~failer ())
   end
 
+let root_arg arg binding_kind =
+  (* The mutability information denotes the mutability of a *position*
+     inside the value, whether looking inside the value of the
+     scrutinee is a pure operation. At the root we are immutable. *)
```
Comment (ncik-roberts) [inline lambda/matching.ml]:
```suggestion
  (* The mutability information denotes the mutability of a *position*
     inside the value, which indicates whether looking inside the
     value of the scrutinee is a pure operation. At the root we are
     immutable. *)
```
"whether" can mean "regardless whether"; this rewording makes it clear that it doesn't mean that here.

File: lambda/matching.ml [hunk 4]
```diff
@@ -1088,6 +1097,21 @@ type ('args, 'head_pat, 'matrix) pm_or_compiled = {
...
 
+
+(* The composed mutability of two argument positions:
+   is x.f.g a mutable position of x, depending whether f and g are mutable?
+
+   Note that the following equations hold:
+   - compose_mut mut Immutable = mut
+   - compose_mut mut Mutable = Mutable
+   but we do *not* use them in the code of get_expr_args_* below. We prefer
+   to keep an explicit composition to make the logic more regular.
```
Comment (ncik-roberts) [inline lambda/matching.ml]:
```suggestion
   to call `compose_mut` explicitly to make the logic more regular.
```

**Review by ncik-roberts — APPROVED** [review]
The code is correct, and it makes sense to me why this will be needed for your ensuing PRs.

File: lambda/matching.ml (hunk 2 above)
Comment (gasche) [reply lambda/matching.ml]: Indeed, this was an omission on my part, thanks! I also tweaked the code of `get_expr_args_record` to make it more visually similar to the other.

**Comment by gasche** [comment]
Thanks! I took the review comments into account.

**Comment by ncik-roberts** [comment]
The diff looks to have picked up some unrelated changes in `Changes` and `middle_end/flambda`. Otherwise, it looks good to me.

**Comment by gasche** [comment]
Note: this needs a maintainer approval if we want to merge and rebase the follow-up PRs.

**Review by lthls — APPROVED** [review]
Approving on behalf of @ncik-roberts (after a quick look through the code)

**Comment by gasche** [comment]
Thanks! I merged, and rebased the follow-up PRs -- #13152, #13153, #13154.
