### PR TITLE
Fix source highlighting for long toplevel phrases (#7925)

### LINKED ISSUE #7925: In error messages, source highlighting does not work for long toplevel phrases
**Original bug ID:** 7925
**Reporter:** @Armael
**Status:** confirmed (set by @gasche on 2019-02-20T15:37:04Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.09.0+dev
**Category:** toplevel
**Tags:** junior_job
**Monitored by:** @nojb

## Bug description

When reporting an error, the toplevel (and since 4.08 also the compiler) highlights the line(s) of the source corresponding to the error:

```
# let x = 1 + "abc" in ();;
Line 1, characters 12-17:
1 | let x = 1 + "abc" in ();;
                ^^^^^
Error: This expression has type string but an expression was expected of type
         int
```

However, in the toplevel, if the toplevel phrase is long enough (and the error is near the beginning), the code highlight feature stops working:

```
# let x = 1 + "abc" in
let x = 1 in
[...] (same x75 times)
let x = 1 in ();;
Line 1, characters 12-17:
Error: This expression has type string but an expression was expected of type
         int
```

I have seen this issue in a teaching situation (in combination with other issues that have now been fixed in 4.08/trunk), 
here students were using emacs+tuareg and using M-x tuareg-eval-buffer to evaluate their 1000-lines long code.

How to fix
----------

The "code highlight" feature for the toplevel is implemented by directly peeking into the lexer's buffer. This stops working if the lexbuf has been refilled in the meantime, which happens if the input is long enough.
A fix would probably to instead have the toplevel store the complete current toplevel phrase in a Buffer.t, and have the error reporting function read into that instead of the lexing buffer.

## Steps to reproduce

Paste the attached source snippet into the toplevel.

## File attachments

- [longphrase.ml](https://gist.githubusercontent.com/vicuna/0e2afe31337c203d275502aafbe4c41e/raw/b7031d2856d70b8e833593308e014d1929e2733e/longphrase.ml)

### PR DESCRIPTION
**Pull request by mylekiller**
# Overview
This is a fix of issue #7925 

The issue was that long inputs to the toplevel would result in any errors toward the beginning of the phrase not being underlined as the lexbuf would be refilled and the complete original phrase would no longer be in the lexbuf. 

The fix I am proposing is the same fix that @Armael proposed: create a new Buffer.t called phrase_buffer in `loplevel/toploop.ml` as a global, then in `parsing/location.ml` use this new buffer instead of the lexbuffer when the input_name is "//toplevel//". 

# Implementation
In order to implement this I first created a new Buffer.t called phrase_buffer in `toplevel/toploop.ml`. I initally create this with 1024 bytes but it should grow as necessary if the input is longer. Then I add characters to the buffer as they are extracted in `toplevel.ml:read_input_default` and I reset the buffer in `toplevel.ml:loop` right after Lexing.flush_input is called.

Next in `parsing/location.ml` I created a new `Buffer.t option ref` called input_phrase_buffer and in `toploop.ml:loop` I set this variable equal to phrase_buffer. Finally in `parsing/location.ml` I created a new function `lines_around_from_phrasebuf` which sets up the `location.ml:lines_around` function to read from the phrase buffer instead of the lexing buffer. This functuion is called whenever the input_name is equal to "//toplevel//" as can be seen by the pattern matching code I added in `location.ml:lines_around_from_current_input`.

# Testing
In order to test this new function I added one test case to the `tool-toplevel/error_highlighting.ml` test which tests for error highlighting on a particularly long input. I also updated the correspoinding refernce file to match this new test. 

Finally since my code edited `toplevel/toploop.ml` the test pr6468.ml broke due to the test being dependent on a line in the code being on a certain line, I updated the line number in the .reference file and this fixed the broken test. 

Closes #7925

### CODE REVIEW

File: Changes [hunk 1]
```diff
@@ -184,6 +184,9 @@ Working version
 
 - #3249: ocamlmklib should reject .cmxa files
   (Xavier Leroy)
+- #7925, #8611: fix error highlighting for execptionally
```
Comment (Armael) [inline Changes]: execptionally -> exceptionally

File: parsing/location.ml [hunk 2]
```diff
@@ -546,6 +547,22 @@ let lines_around_from_lexbuf
     lines_around ~start_pos ~end_pos ~seek ~read_char
   end
 
+(* Try to get lines from a phrase buffer fix error #7925 *)
```
Comment (Armael) [inline parsing/location.ml]: I don't think you should refer to the error that this code fixes. 
Just describe what the new code does -- the rest can be read from the git history and the Changes file.

File: parsing/location.ml [hunk 3]
```diff
@@ -546,6 +547,22 @@ let lines_around_from_lexbuf
...
+let lines_around_from_phrasebuf
+    ~(start_pos: position) ~(end_pos: position)
+    (pb: Buffer.t):
+  input_line list
+  =
+  let pos = ref 0 in (* relative position (always starts at 0)*)
```
Comment (Armael) [inline parsing/location.ml]: This comment is uninformative, you can remove it.

File: parsing/location.ml [hunk 4]
```diff
@@ -546,6 +547,22 @@ let lines_around_from_lexbuf
...
+  let seek n = pos := n in
+  let read_char () =
+    if !pos >= Buffer.length pb then (* end of buffer *) None
```
Comment (Armael) [inline parsing/location.ml]: Same here, handling `Buffer`s is straightforward enough that you can remove the comment.

File: parsing/location.ml [hunk 5]
```diff
@@ -583,15 +600,24 @@ let lines_around_from_current_input ~start_pos ~end_pos =
     else
       []
   in
-  match !input_lexbuf with
-  | Some lb ->
+  (*Fix error #7925 added matches for //toplevel// to be able to use
+  the phrase buffer instead of the lexbuffer*)
```
Comment (Armael) [inline parsing/location.ml]: Idem, I don't think it's useful to paraphrase the git history in the comments.

File: parsing/location.ml [hunk 6]
```diff
@@ -583,15 +600,24 @@ let lines_around_from_current_input ~start_pos ~end_pos =
...
+  match !input_lexbuf, !input_phrase_buffer, !input_name with
+  | _, Some pb, "//toplevel//" ->
+      begin match lines_around_from_phrasebuf pb ~start_pos ~end_pos with
+      | [] -> (* Couldn't get input from phrase buffer fall back to file *)
+          from_file ()
```
Comment (Armael) [inline parsing/location.ml]: I wonder if we could have `assert false` here instead. Could you try this?

File: parsing/location.mli [hunk 7]
```diff
@@ -73,6 +73,7 @@ val mkloc : 'a -> t -> 'a loc
 
 val input_name: string ref
 val input_lexbuf: Lexing.lexbuf option ref
+val input_phrase_buffer: Buffer.t option ref
```
Comment (Armael) [inline parsing/location.mli:80]: It would be nice to have a comment indicating that this is used by the error reporting code, and documenting that:

- if `!input_name` is `//toplevel//`, `!input_phrase_buffer` is `Some buf` where `buf` contains of the last toplevel phrase
- otherwise, `!input_phrase_buffer` is `None`.

File: toplevel/toploop.ml [hunk 8]
```diff
@@ -36,6 +36,9 @@ type directive_info = {
   doc: string;
 }
 
+(* Phrase Buffer for Fix error #7925 *)
```
Comment (Armael) [inline toplevel/toploop.ml]: Could you instead document what this buffer contains (for example "stores the last toplevel phrase")

File: toplevel/toploop.ml [hunk 9]
```diff
@@ -447,6 +450,8 @@ let read_input_default prompt buffer len =
       if !i >= len then raise Exit;
       let c = input_char stdin in
       Bytes.set buffer !i c;
+      (*Populate Phrase Buffer as new characters are added *)
```
Comment (Armael) [inline toplevel/toploop.ml]: Spacing: `(*Populate` -> `(* Populate`

File: toplevel/toploop.ml [hunk 10]
```diff
@@ -544,13 +549,16 @@ let loop ppf =
...
   Location.input_lexbuf := Some lb;
+  Location.input_phrase_buffer := Some phrase_buffer;
   Sys.catch_break true;
   run_hooks After_setup;
   load_ocamlinit ppf;
   while true do
     let snap = Btype.snapshot () in
     try
       Lexing.flush_input lb;
+      (*Reset the phrase buffer when we flush the lexing buffer*)
```
Comment (Armael) [inline toplevel/toploop.ml]: Please put one space after `(*` and before `*)`.

**Review by Armael — COMMENTED** [review]
Great, thanks!

See below for small comments on the code. 
Additionally, I think the code that reads from the lexbuf is not needed anymore, since we can always read from the input file, or from the input phrase buffer. Could you try to get rid of  `lines_around_from_lexbuf`?

File: parsing/location.ml [hunk 11]
```diff
@@ -546,6 +547,22 @@ let lines_around_from_lexbuf
...
+    (pb: Buffer.t):
+  input_line list
+  =
+  let pos = ref 0 in (* relative position (always starts at 0)*)
+  let seek n = pos := n in
+  let read_char () =
+    if !pos >= Buffer.length pb then (* end of buffer *) None
+    else
+      let c = Buffer.nth pb !pos in
+      incr pos; Some c
```
Comment (nojb) [inline parsing/location.ml:562]: I would guard the `else` case between `begin ... end`.

**Comment by gasche** [comment]
@Armael wrote:
> Additionally, I think the code that reads from the lexbuf is not needed anymore, since we can always read from the input file, or from the input phrase buffer.

I'm a bit hesitant to go there. Can we actually rely on our ability to locate the input file? I'm thinking of cases where the source is preprocessed, or contains lexer directives, or has been moved around by the build system, and then what the compiler knows about the input file location may not be correct anymore.

My gut feeling is that this aspect of the compiler interface is not very well structured today (it has involved incrementally), relies on global mutable state whose lifecycle I don't understand very well, and is not in a good enough shape to be considered reliable. I may be overly pessimistic or worry about problems that don't come up in practice, but I would wonder about how to test that assumption -- and maybe suggest this as a separate piece of work.

**Comment by Armael** [comment]
That's a fair objection. However:

> Can we actually rely on our ability to locate the input file? I'm thinking of cases where the source is preprocessed, or contains lexer directives, or has been moved around by the build system, and then what the compiler knows about the input file location may not be correct anymore.

In full generality indeed we cannot assume to be able to locate the input file. However, for all the reasonable cases I could think of, it should be the case. Preprocessed files, files with lexer directives should work (if you look in pparse, AFAIR the `input_name` for a preprocessed file points to the file *before* preprocessing, not the one produced by the preprocessor). I doubt there are cases where the build system would move the source file after preprocessing it but before compiling it.

> My gut feeling is that this aspect of the compiler interface is not very well structured today (it has involved incrementally), relies on global mutable state whose lifecycle I don't understand very well, and is not in a good enough shape to be considered reliable.

I agree, but I think we should mitigate this by getting rid of code paths that we expect to be mostly dead -- instead of complicating the code by implementing various best-effort/fallback strategies.

----

Also, note that if we get rid of the lexbuf code as I suggest, it does not mean that the compiler would crash if it does not manage to read from the input file. Instead it will simply not quote the source file in the error message (the user will still get a location).

I think it is fine, and worth getting rid of a few tricky code-paths.

**Comment by Armael** [comment]
> I doubt there are cases where the build system would move the source file after preprocessing it but before compiling it.

And, to be honest, is it too extreme to say that if you do that, not getting fancy source quoting is well deserved? Looking up the lexing buffer to fetch the input code is really a crude hack that I would be quite happy to see disappear.

**Comment by gasche** [comment]
> Looking up the lexing buffer to fetch the input code is really a crude hack that I would be quite happy to see disappear.

That's a good point, the buffer should be purely internal.

I still have mixed feelings about relying on `!input_name` in this way, but you convinced me that this is no worse than what we are currently doing, and that it makes the code simpler. Let's go with what you propose.

**Comment by mylekiller** [comment]
All of the formatting issues have been fixed. Also, I added an assert false statement in place of the from_file () when !input_name is "//toplevel//". 

As for removing the function `lines_around_from_lexbuf` removing this code path seems to break many of the tests related to warnings and errors. A very quick look into this indicated that this would be a non-trival fix and would require some tinkering with code in other parts of the compiler. For this reason it might be better to open that problem as a sperate issue, which I would also be happy to work on.

**Comment by damiendoligez** [comment]
@gasche @Armael will you approve this PR?

**Comment by Armael** [comment]
Unfortunately I think it needs an other round of review (and I have little time right now). I remember that we realized with @gasche that utop is implementing its own toplevel-setup code, and I didn't take that into account in my earlier review. So in fact we should be more conservative than what I was saying, to make sure we don't break userland programs such as utop.

**Comment by Armael** [comment]
I'll try to do this extra round of review during the week end... :).

**Review by Armael — APPROVED** [review]
OK, actually, the code looks good as it is now! Approving.
Sorry about the confusion and the delay.
