### PR TITLE
#3959, #7202: in script mode, handle directive errors

### LINKED ISSUE #3959: no exit on bad #use in ocaml scripts
**Original bug ID:** 3959
**Reporter:** @mjambon
**Assigned to:** @gasche
**Status:** assigned (set by @damiendoligez on 2017-02-27T13:56:11Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 3.09.0
**Category:** toplevel

## Bug description

The ocaml command or a custom toplevel, when used in non-interactive mode, does not stop when it encounters a directive with a valid name but an invalid argument:

1) Valid directive name, wrong argument (should exit):

[droopy] ~/tmp % cat blop.ml
#use "abc";;
print_endline "hello";;
[droopy] ~/tmp % ocaml blop.ml && echo success
Cannot find file abc.
hello
success

2) Wrong directive name (works as expected):

[droopy] ~/tmp % cat blop2.ml
#abcde "abc";;
print_endline "hello";;
[droopy] ~/tmp % ocaml blop2.ml && echo success
Unknown directive `abcde'.

## Additional information

This problem is present at least in OCaml 3.08.4 and OCaml 3.09.1 (x86 Linux).

### LINKED ISSUE #7202: ocaml script mode, some errors are reported on stdout and do not lead to non-zero exit
**Original bug ID:** 7202
**Reporter:** @dbuenzli
**Status:** confirmed (set by @damiendoligez on 2016-04-05T14:34:13Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.02.3
**Category:** toplevel
**Monitored by:** @hcarty @dbuenzli

## Bug description

This seems right:
```
> cat script.ml 
#!/usr/bin/env ocaml

let (
> ocaml script.ml > /tmp/bla
File "script.ml", line 4, characters 0-0:
Error: Syntax error: operator expected.

> echo $?
2
```
However if I have:
```
> cat script.ml
#!/usr/bin/env ocaml

#mod_use "bli.ml"

> ocaml script.ml > /tmp/bla
> echo $?
0
> cat /tmp/bla
Cannot find file bli.ml.
```

### PR DESCRIPTION
**Pull request by Octachron**
In script mode (`ocaml script.ml`), directives error messages are still printed on `stdout` and those errors are not reported on the exit status of the script.  Consequently, the following script
```bash
ocaml -e '#use "a";;' > output; echo $?
``` 
outputs only

> 0

This PR adds an error handler to the toplevel directive which is overridden in script mode to redirect the error message to `stderr` and exit with an error status of `125` as suggested in #7202 .
Witht this change, the output of
```bash
ocaml -e '#use "a";;' > output; echo $?
``` 
becomes
>  Cannot find file a.
> 125

### CODE REVIEW

File: toplevel/byte/topmain.ml [hunk 1]
```diff
@@ -178,7 +178,11 @@ let input_argument name =
       in
       Compenv.readenv ppf Before_link;
       Compmisc.read_clflags_from_env ();
-      if prepare ppf && Toploop.run_script ppf name newargs
+      if prepare ppf && (
+          let exit x = raise (Compenv.Exit_with_status x) in
+          Topdirs.set_error_handler { exit; ppf };
+          Toploop.run_script ppf name newargs
```
Comment (gasche) [inline toplevel/byte/topmain.ml]: This logic is not reentrant, in the sense that the error handler remains set after the script has run. I would expect that you reset it to its previous value after running the script. (Doing this with your API is surprisingly tricky; if you exposed a `ref` directly you could use `Misc.protect_refs`, or you could expose `with_error_handler` using it internally.)

What happens if I use `#use "a.ml";;` from an interactive toplevel, which succeeds correctly, and then I run another directive that fails?

**Review by gasche — COMMENTED** [review]
The code/API is a bit mysterious to me:
- What does "error" mean here? Often in the compiler this means an element of a well-defined "error" type; I wondered if it meant "uncaught exception". If I understand correctly, the protocol instead is that toplevel directives return a boolean that indicates if they succeeded and failed, and "error" means "a directive failed".
- Why is the notion of "error handling" represented by an `exit : int -> unit` function (in OCaml, using `exit` directly is very rare), bundled with a formatter? What is the formatter used for?

Then the actual changes to the code are using a lot of clever wrapper logic.

I would find it simpler to have a bit of mutable state that tells us if we are running interactively or not (is this not already the case?), and have the directive evaluation loop run `exit 125` in non-interactive mode. What am I missing?

File: toplevel/byte/topmain.ml (hunk 1 above)
Comment (dra27) [reply toplevel/byte/topmain.ml]: This code path isn't hit if you're in an interactive toplevel, I think?

**Comment by dra27** [comment]
It's definitely worth adding tests for these cases - when I was last doing this in 2018, the tests were a bit awkward (e.g. https://github.com/ocaml/ocaml/pull/2155/commits/4bb27d2a5219f6258c114a4466b069aed7017fe4, https://github.com/ocaml/ocaml/pull/2155/commits/d079c5162554dd2813948475a7561022a16e7241 and https://github.com/ocaml/ocaml/pull/2155/commits/989224450c49b0abc45aa0e997366180391a00f1) but I think there's newer machinery in ocamltest now to aid this kind of toplevel testing.

File: toplevel/byte/topmain.ml (hunk 1 above)
Comment (Octachron) [reply toplevel/byte/topmain.ml]: Indeed, in scripting mode, we never go back to interactive mode. In fact, we are only running the first script given as argument.

**Comment by Octachron** [comment]
By error, I mean: a directive failed and printed a error message on a formatter.
In an interactive toplevel, this is a recoverable error, and the error message should be displayed on the the standard output.
Contrarily, in scripting mode, it makes sense to make such error fatal to avoid running the rest of the script in a error state. Similarly, the directive's error message should not be interleaved with the script's main output, thus we need to redirect it towards `stderr`.

Inversing the control with a boolean flag would work too. If you find that simpler, let do that.

File: testsuite/tools/expect_test.ml [hunk 2]
```diff
@@ -336,7 +336,8 @@ let main fname =
   end;
   Compmisc.init_path ();
   Toploop.initialize_toplevel_env ();
-  Sys.interactive := false;
+  (* We are in interactive mode and should record directive error on stdout *)
+  Sys.interactive := true;
```
Comment (gasche) [inline testsuite/tools/expect_test.ml:340]: This is making me nervous. Why was it explicitly set to `false` before? Are we breaking something with this change? (cc @jeremiedimino ?)

File: toplevel/topdirs.ml [hunk 3]
```diff
@@ -21,8 +21,16 @@ open Longident
...
-let std_out = std_formatter
+let error_status = 125
+let error_fmt () =
+  if !Sys.interactive then
+    Format.std_formatter
+  else
+    Format.err_formatter
+
+let fail () =
+  if not !Sys.interactive then raise (Compenv.Exit_with_status error_status)
```
Comment (gasche) [inline toplevel/topdirs.ml]: I'm not fond of `fail ()` as an abstraction. Half the time it does nothing, which suggests that its name is a bit confusing. Could we merge this logic inside `action_on_suberror`? (You also use it directly in `parse_warnings`, but this is a breach of protocol and I think we would be better off without.)

File: toplevel/topdirs.ml [hunk 4]
```diff
@@ -122,18 +130,24 @@ let _ = add_directive "cd" (Directive_string dir_cd)
       doc = "Change the current working directory.";
     }
 
-let dir_load ppf name = ignore (Topeval.load_file false ppf name)
 
-let _ = add_directive "load" (Directive_string (dir_load std_out))
+let with_error f x = f (error_fmt ()) x
```
Comment (gasche) [inline toplevel/topdirs.ml]: Higher-order functionals are the functional equivalent of jargon: they should be reserved to the rare case where they bring strong value. Here I'm skeptical that `with_error` does, its meaning at the callsite is not clear, and it cannot be consistently used (or at least you didn't dare using it consistently) for higher-arity directive functions. Could we maybe write slightly longer but simpler code at each callsite to do without this function?

File: toplevel/topdirs.ml [hunk 5]
```diff
@@ -122,18 +130,24 @@ let _ = add_directive "cd" (Directive_string dir_cd)
...
       doc = "Load in memory a bytecode object, produced by ocamlc.";
     }
 
-let dir_load_rec ppf name = ignore (Topeval.load_file true ppf name)
+let dir_load_rec ppf name =
+  action_on_suberror (Topeval.load_file true ppf name)
 
 let _ = add_directive "load_rec"
-    (Directive_string (dir_load_rec std_out))
+    (Directive_string (with_error dir_load_rec))
```
Comment (gasche) [inline toplevel/topdirs.ml]: Note: there is something subtly wrong with the fact that directives take a single formatter, on which they only print errors. This is the property that you use in this refactoring, but it does not hold for all directives, which is why your PR needs special treatment of `#help` and `#show`. (What is the expected behavior of `#show_val fubar;;` in non-interactive mode?)

I think that there would be various ways to improve on this:
1. We could pass two different formatters to our directives, an output formatter and an error formatter.
2. We could make the code simpler, instead of more complex, by changing the `directive_fun` types to add `oppf:Format.formatter -> eppf:Format.formatter ->`, and let Toploop pass the formatters.
3. Alternatively, the directives could be in charge of deciding which formatter to use, and call `error_formatter ()` directly. (But this makes it harder to redirect directive output to a completely different place.)

I'm not so fond of (3). (2) sounds nice, but it may have unpleasant backward-compatibility implications for utop and down. It may be that the best compromise is to remain "subtly wrong" and not change the interface at all, as this PR is doing, but this is worth a discussion.

**Review by gasche — COMMENTED** [review]
More musings. Apologies for making this feature-implementation review surprisingly sophisticated.

File: testsuite/tools/expect_test.ml (hunk 2 above)
Comment (Octachron) [reply testsuite/tools/expect_test.ml:340]: I don't think that there was any deep reason for this (rather than `expect_test` looks like it is non interactive). When the code was written, the only effect of setting `Sys.interactive` to `false` was to disable an error if someone tried to load `ocamltoplevel.cma` from within the `expect_test` REPL. 

Currently, this change also makes  `expect_test` looks at the file system rather than to the cache (see `utlils/load_path.ml`) in case  of file system access. However, this behavior was added in 4.13 .

Comment (ghost) [reply testsuite/tools/expect_test.ml:340]: `expect_test` is a non-interactive tool, so it makes sense to me that `Sys.interactive` is set to `false`.

I wrote this code a long time ago and I can't remember if this line was important. However, getting nice warnings and error messages that don't change all the time was the main difficulty of setting up expectation tests using the toplevel. So if setting `Sys.interactive` to `false` was important and setting it to `true` would break something, I would expect the breakage to be apparent in the testsuite.

> Currently, this change also makes expect_test looks at the file system rather than to the cache (see utlils/load_path.ml) in case of file system access. However, this behavior was added in 4.13 .

This might make the testsuite slower then. Seems worth benching.

File: toplevel/topdirs.ml (hunk 3 above)
Comment (Octachron) [reply toplevel/topdirs.ml]: Why not?

File: toplevel/topdirs.ml (hunk 4 above)
Comment (Octachron) [reply toplevel/topdirs.ml]: Contrarily, I don't thing that expanding most definition of directives to `fun s -> dir (error_fmt()) s` brings much clarity. I would rather factorize this common pattern. Maybe the function could be improved: `with_current_error_fmt`? (Also there is no higher-arity directives, just an out-of-place parameter)

Comment (gasche) [reply toplevel/topdirs.ml]: If you insist, you can keep your wrapper. (I think that the expanded directive is longer but also clearer, but oh well; it's all about finding a compromise.)

File: toplevel/topdirs.ml (hunk 5 above)
Comment (Octachron) [reply toplevel/topdirs.ml]: I tend to agree that morally directives should take both an error and output formatters as argument, and the current set of directives accidentally only use one of them.

> (What is the expected behavior of #show_val fubar;; in non-interactive mode?)

I would expect the result of `show` to be print on `stdout` as part of the script result.

Comment (gasche) [reply toplevel/topdirs.ml]: In this example, `fubar` is missing from the environment, I wondered if it should be counted as a directive failure or not. (Currently it is not, I guess?)

Comment (Octachron) [reply toplevel/topdirs.ml]: Currently, it is not. And keeping it that way seems somewhat sensible (if certainly a bit arbitrary): sucesses or failures of `#show` do not alter the state of the script. Or looking from another perspective, a failure to find an identifier is still a valid answer to the user's query "show me some information about `fubar`".

**Review by gasche — APPROVED** [review]

File: Changes [hunk 6]
```diff
@@ -16,6 +16,10 @@ Working version
 
 ### Tools:
 
+- #3959, #7202: ocaml, directive errors (`#use "";;`) in script mode use stderr
+  and exit with an error
+  (Florian Angeletti, review by ??)
```
Comment (gasche) [inline Changes]: needs an update

File: testsuite/tools/expect_test.ml (hunk 2 above)
Comment (gasche) [reply testsuite/tools/expect_test.ml:340]: I suppose the impact would be larger on Windows, but I don´t observe any AppVeyor timing differences [on this PR](https://ci.appveyor.com/project/avsm/ocaml/builds/39905824) and [on another PR](https://ci.appveyor.com/project/avsm/ocaml/builds/39896593), so it looks like there is no observable performance impact.

(I think this makes sense given that many the eexpect_test in our testsuite don't rely much on external modules.)

Comment (Octachron) [reply testsuite/tools/expect_test.ml:340]: Yes, since the few runs of the testsuite are still within the usual range, the performance impact seems small enough.
