### PR TITLE
Fix #13579 by removing equations_generation

### LINKED ISSUE #13579: Unsoundness involving non-injective types + gadts
The following program is wrongly accepted by the typechecker, which can be turned into a segfault:

```ocaml
module F(X : sig type 'a t end) = struct
  type (_, _) gadt = T : ('a X.t, 'a) gadt
  
  (*
    let __ (type a b) (Equal : (a X.t, b X.t) Type.eq) =
      (Equal : (a, b) Type.eq)
   *)

  let equate_param2_based_on_param1 (type tt m1 m2)
        (T : (tt, m1) gadt) (T : (tt, m2) gadt) : (m1, m2) Type.eq =
     Equal
  ;;
end

module Z = F(struct type 'a t = unit end)

let () =
  let t1 = (Z.T : (unit, int) Z.gadt) in
  let t2 = (Z.T : (unit, string) Z.gadt) in
  let eq : (int, string) Type.eq = Z.equate_param2_based_on_param1 t1 t2 in
  let cast (type a b) (Equal : (a, b) Type.eq) (a : a) : b = a in
  print_string (cast eq 1)
;;
```

The problem is that the function `equate_param2_based_on_param1` is considered well-typed by the typechecker, but in reality it's well-typed iff X.t is injective in 'a. By contrast, the commented-out `injectivity` function is correctly accepted iff X.t is injective in 'a.

(this came up while @mbarbin and I were thinking about the type safety in https://github.com/mbarbin/provider/).

### PR DESCRIPTION
**Pull request by garrigue**
Issue #13579 discovered a soundness issue in unification.
This is a side-effect of using the `equations_generation = Forbidden` mode in `unify3`.
Namely, this mode was used when unifying non-injective types parameters in `Pattern` mode.
The assumption was that, since those unifications were not allowed to instantiate abstract types, non-injective types could not cause the introduction of equations.
#13759 shows that this assumption was wrong: if we allow instantiations in non-injective type parameters, those instantiations can later on cause the introduction of equations while unifying injective one.

The reasonable thing to do is just to scrape the `equations_generation = Forbidden` mode (it was only used in a single place), and only reify in that case, like we do everywhere else.

There is no failure in the testsuite. I wonder whether this unsoundness was unwittingly used in the wild.

### CODE REVIEW

**Review by goldfirere — APPROVED** [review]
I'm not deeply expert here, but this looks like a simplification -- removing a special case that is deemed now unwise. That's generally a safe thing to do, and I'm encouraged that the testsuite passes.

File: typing/ctype.ml [hunk 1]
```diff
@@ -408,15 +404,15 @@ let in_subst_mode = function
   | Pattern _ -> false
 
 let can_generate_equations = function
-  | Expression _ | Pattern { equations_generation = Forbidden } -> false
-  | Pattern { equations_generation = Allowed _ } -> true
+  | Expression _ -> false
+  | Pattern _  -> true
```
Comment (Octachron) [inline typing/ctype.ml]: The `can_generate_equations` function is now an alias for `in_pattern_mode`. I think it might be clearer to remove the function. 
At the very least, the redundant checks on `if in_pattern_mode uenv then (... if can_generate_equations then ...)` should be removed in `unify3_var` and `unify3`.

**Review by Octachron — APPROVED** [review]
Except for the minor nitpicking above, I agree that the changes not only fixes the soundness of issue of creating channels to leak equality but also make the code simpler.

**Comment by garrigue** [comment]
Thanks for spotting the duplication. The code can be further simplified as a result.

**Comment by Octachron** [comment]
A change of behavior with this PR is that:
```ocaml
module M = struct type 'a p end
type _ t = W: int M.p t
let f (W: _ M.p t) = ()
```
now fails with
```ocaml
Error: This pattern matches values of type int M.p t
       but a pattern was expected which matches values of type $0 M.p t
       The type constructor $0 would escape its scope
```
whereas
```ocaml
module M = struct type 'a p end
type _ t = W: int M.p t
let f (W: _ t) = ()
```
is allowed and inferred to be `f: int M.p t -> unit`.

**Comment by garrigue** [comment]
Indeed, this behavior is to be expected, since we do not allow unification under non-injective type constructors.
IIRC, the goal of the current code was precisely to avoid this.
A way to handle such cases would be to try again unification in expression mode (not locally, but globally, i.e. before entering `unify`), or to check the presence of instantiable types before the unification (if there are none, there is no need to use pattern mode).
It would be good to know how much this happens in the wild.

**Comment by Octachron** [comment]
I would propose to add this example of a not-so-obvious behavior to the test in the PR, and merge this soundness fix in 5.3. If somehow the change of behavior is too unwieldy, we will have time to ponder on alternative solution.

**Comment by garrigue** [comment]
OK, I will do it. Soundness is paramount.

For the possible workaround, I am thinking of the following steps in `unify_gadt`:
* first check whether the types contain free variables
* if they don't, do unification in pattern mode
* if they do, first attempt unification in expression mode
* if it fails, backtrack and do unification in patten mode

The only case were the behavior would be changed is if both there are free variables and pattern mode is required, which is already a very fragile situation.

**Comment by Octachron** [comment]
Cherry-picked to 5.3 in 72440859c7e446f42199df in time for the first beta of 5.3.0.

I am planning to review the two remaining type system bug fix before the second beta (planned around the 15th November).

**Comment by garrigue** [comment]
I have written a fix for your example in #13585 , while I have it in mind.
I think that the error message is sufficiently confusing that it is better to avoid it.
