### PR TITLE
Fix type mismatch between definition and declaration

### LINKED ISSUE #9825: Trivial fix for compiling OCaml with Link-Time Optimization (LTO)
Fedora and OpenSUSE package build systems now compile everything with Link-Time Optimization enabled by default.  This allows optimizations to cross compilation unit boundaries which gives more opportunities for inlining in particular.  Unfortunately OCaml didn't build:
```
    major_gc.c:66:14: warning: type of 'caml_fl_merge' does not match original declaration [-Wlto-type-mismatch]
       66 | extern char *caml_fl_merge;  /* Defined in freelist.c. */
          |              ^
    freelist.c:47:7: note: 'caml_fl_merge' was previously declared here
       47 | value caml_fl_merge = Val_NULL;  /* Current insertion pointer.  Managed
          |       ^
    freelist.c:47:7: note: code may be misoptimized unless '-fno-strict-aliasing' is used
```

Fedora is now carrying this trivial fix which you may want to consider:
https://pagure.io/fedora-ocaml/c/7364f5081851fe306802883d9a8069da559d4973?branch=fedora-33-4.11.0-dev2

### PR DESCRIPTION
**Pull request by xavierleroy**
The global variable `caml_fl_merge` and the function `caml_spacetime_my_profinfo` (bytecode version) are defined with one type, but declared `extern` and used with an incompatible type elsewhere.

Closes: #9825

### CODE REVIEW

File: runtime/spacetime_byt.c [hunk 1]
```diff
@@ -12,8 +12,12 @@
 /*                                                                        */
 /**************************************************************************/
 
+#define CAML_INTERNALS
+
 #include "caml/fail.h"
 #include "caml/mlvalues.h"
+#include "caml/io.h"
```
Comment (nojb) [inline runtime/spacetime_byt.c:19]: Just out of curiosity, why is `io.h` required here?

**Review by nojb — APPROVED** [review]
LGTM

File: runtime/spacetime_byt.c (hunk 1 above)
Comment (xavierleroy) [reply runtime/spacetime_byt.c:19]: Because `caml/spacetime.h` uses `struct channel`.  I could have changed `caml/spacetime.h` to include `caml/io.h` itself, but I'm shooting for minimal changes.
