### PR TITLE
Fix #8550: Soundness issue with class generalization

### LINKED ISSUE #8550: Soundness issue with class generalization
There's a soundness issue with generalization of type variables in class definitions:

```ocaml
    # class ['a] r = let r : 'a = ref [] in object method get = r end;;
    class ['a] r : object constraint 'a = 'b list ref method get : 'a end
    # (new r)#get := [3];;
    - : unit = ()
    # List.hd !((new r)#get) ^ "two";;
    Segmentation fault
```

Bisecting shows that this has been around for a while: it was introduced in OCaml `4.00.0` along with GADTs (6c78f42d) for programs checked with `-principal` and more recently spread to programs without `-principal`, too (802945009).  Before these commits the program was rejected:

```
    Characters 0-63:
      class ['a] r = let r : 'a = ref [] in object method get = r end;;
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    Error: The type of this class,
           class ['a] r : object constraint 'a = '_b list ref method get : 'a end,
           contains type variables that cannot be generalized
```

### PR DESCRIPTION
**Pull request by garrigue**
Fix #8550 by replacing use of `generalize_structure` by modal iteration in `generalize_expansive`.

### CODE REVIEW

File: typing/ctype.ml [hunk 1]
```diff
@@ -878,15 +878,17 @@ let update_level env level ty =
...
+(* Lower level of type variables inside contravariant branches *)
 
-let rec generalize_expansive env var_level visited ty =
+let rec generalize_expansive env var_level visited contra ty =
   let ty = repr ty in
   if ty.level = generic_level || ty.level <= var_level then () else
-  if not (Hashtbl.mem visited ty.id) then begin
-    Hashtbl.add visited ty.id ();
+  if try Hashtbl.find visited ty.id < contra with Not_found -> true then begin
+    Hashtbl.add visited ty.id contra;
```
Comment (lpw25) [inline typing/ctype.ml:892]: Could I suggest something like:

```ocaml
let visit =
  match Hashtbl.find visited ty.id with
  | previous_contra -> not previous_contra && contra
  | exception Not_found -> true
in
if visit then begin
...
```
I find the current code a bit hard to read.

Comment (garrigue) [reply typing/ctype.ml:892]: It adds 4 lines, but I agree it's more readable.

File: typing/ctype.ml [hunk 2]
```diff
@@ -878,15 +878,21 @@ let update_level env level ty =
       update_level env level true ty
   end
 
-(* Generalize and lower levels of contravariant branches simultaneously *)
+(* Lower level of type variables inside contravariant branches *)
 
-let rec generalize_expansive env var_level visited ty =
+let rec generalize_expansive env var_level visited contra ty =
```
Comment (trefis) [inline typing/ctype.ml]: Perhaps it would make sense to rename this function (and the one that is exposed in the mli). Something like `lower_contravariant_variables`?

File: typing/ctype.ml [hunk 3]
```diff
@@ -878,15 +878,21 @@ let update_level env level ty =
...
   let ty = repr ty in
-  if ty.level = generic_level || ty.level <= var_level then () else
-  if not (Hashtbl.mem visited ty.id) then begin
-    Hashtbl.add visited ty.id ();
+  let must_visit =
+    ty.level > var_level &&
+    match Hashtbl.find visited ty.id with
+    | done_contra -> contra && not done_contra
+    | exception Not_found -> true
+  in if must_visit then begin
```
Comment (trefis) [inline typing/ctype.ml]: Nitpick: but I think it would be slightly nicer if the `if` was at the beginning of the line.

**Review by trefis — APPROVED** [review]
Some minor stylistic comments, but otherwise this seems correct.

PS: given the state of the history, the commits should be squashed before/when merging.

File: typing/ctype.ml (hunk 2 above)
Comment (garrigue) [reply typing/ctype.ml]: Done (renamed to `lower_contravariant`, to avoid being overly specific).

File: typing/ctype.ml (hunk 3 above)
Comment (garrigue) [reply typing/ctype.ml]: Done.

**Comment by garrigue** [comment]
Cherry-picked in 4.08 as 409ba43.
