### PR TITLE
Fix bytecode compilation of Lsend(Cached, _)

### LINKED ISSUE #10324: Segfault under bytecode in method call that directly calls another method
Originally reported in Discuss https://discuss.ocaml.org/t/code-segfaulting-in-bytecode-compiler-but-running-in-native-compiler/7622

```ocaml
(* foo.ml *)

let x =
  object
    method g = ""
  end

let _ =
  (object method f = x#g end)#f
```

The code segfaults when compiled to bytecode, but **not** when compiled to native code under 4.10.1, 4.11.1 and 4.12.0. It segfaults in the toplevel if ran with `ocaml foo.ml`, but not when using `#use "foo.ml"`.

### PR DESCRIPTION
**Pull request by lthls**
I don't really understand much of what I'm doing here (thanks to the extensive lack of documentation on the object-related code), but apparently `Cached` versions of `Lsend` have two more arguments, and bytecode doesn't seem to use caches, so it makes sense to remove two arguments instead of only one.

This seems to fix #10324.

### CODE REVIEW

**Comment by gasche** [comment]
cc @garrigue I guess? (Who knows about the object-oriented runtime semantics?)

**Comment by nojb** [comment]
cc @garrigue who seems to have introduced the line your are modifying in 6a940ef65d7b70f94e221f4b6731b4ed7a9c410e

**Comment by garrigue** [comment]
What is this supposed to fix?
Is there a bug in the object system?
It would certainly cause crashes in all programs using objects.

IIRC, the compiler introduces cacheing information for both bytecode and native code.
And since I see a `#define CAML_METHOD_CACHE` in `interp.c`, the bytecode interpreter does cacheing.

The location of the cache is different.
* For native code, it is explicitly allocated, so that an extra argument pointing to the cache location is needed.
* For bytecode, the cache is inside the bytecode, just after the instruction (this is why there is a `pc += 2` when cacheing is disabled). So one discards the pointer to the cache during code generation.

At least, this is what I recollect from reading this code 20 years after writing it.

**Comment by lthls** [comment]
I didn't know about the bytecode cache, but in the case I've seen the problematic call was using `Kgetdynmet` anyway, which doesn't seem to use a cache.
Anyway, the problem is that there is not one but two extra arguments for the native cache (named `cache` and `pos` in `translprim.ml`), so we need to remove two of them in bytecode compilation.
The actual segfault is coherent with this behaviour: after a return instruction, the interpreter still has one extra argument left so it assumes that its accumulator must be a closure, but it's not (it's the string returned by `g`).

Note that to reproduce the bug from #10324, you have to compile without `-g`, otherwise the builtin methods aren't used and a regular function is emitted instead. (This is why #10324 triggers with `ocaml foo.ml` but not inside an interactive toplevel).

**Comment by garrigue** [comment]
Looking again, there indeed seems to be no need for to keep the index.
However, this does not explain why the segmentation fault only occurs since 4.07.
In 4.06 and before, this seems to work.

**Comment by lthls** [comment]
Before 656aa426774266ce9ceb38f47ad037a657824f5b, there was some code in `translcore.ml` that detected the `%sendcache` primitive and translated it as a regular `%send` in bytecode. The refactoring seems to have removed this special case.

**Comment by garrigue** [comment]
Ok, then that's the real problem. I.e., `kind = Cached` should never happen in bytecode, so this should rather be an assert false.

**Comment by garrigue** [comment]
And of course we need a test case, such as
```ocaml
let x = object  method g = "abc" end
let s =  (object method f = x#g end)#f
let () = prerr_endline s
```

**Comment by gasche** [comment]
I'm not sure about the "refactoring of primitives" PR being the culprit here (I looked at it earlier today as well out of curiosity; can you point at where the sendcache primitive gets rewritten?). On my machine:

```
$ opam exec --switch=4.06.1 -- ocaml test.ml
$ opam exec --switch=4.07.1 -- ocaml test.ml
$ opam exec --switch=4.08.0 -- ocaml test.ml
Segmentation fault (core dumped)
```

which seems to suggest that the segfault started appearing in 4.08, not 4.07, and the primitive-rework was already in 4.07.

**Comment by lthls** [comment]
Here is the line that does the rewriting:
https://github.com/ocaml/ocaml/blob/037287fe81c21290f6c9d2e1d58219fd0de2a3a7/bytecomp/translcore.ml#L761
This line disappears in the refactoring of primitives PR, and I don't think there is any equivalent in `translprim.ml`.
(I used git bisect to find the commit, so I'm quite confident that this is the culprit).

I use the bytecode compiler, not the toplevel, to check for the bug..

**Comment by garrigue** [comment]
And the problem perfectly makes sense.
`Translobj.meth` does not introduce a cache for bytecode, but the method table compilation in `camlinternalOO.ml` introduces calls to `%sendcache`. In bytecode, `%sendcache` should be interpreted as `%send`, which results in discarding the cache. Your fix in `bytegen.ml` also works, but it is cleaner to enforce the invariant that `kind = Cached` does not appear in bytecode compilation.

File: bytecomp/bytegen.ml [hunk 1]
```diff
@@ -560,7 +560,7 @@ let rec comp_expr env exp sz cont =
         end
       end
   | Lsend(kind, met, obj, args, _) ->
-      let args = if kind = Cached then List.tl args else args in
+      let args = if kind = Cached then List.tl (List.tl args) else args in
```
Comment (garrigue) [inline bytecomp/bytegen.ml]: This should rather be
```ocaml
assert (kind <> Cached);
```

**Comment by lthls** [comment]
I've pushed a new version with the assertion, and the fix in `translprim.ml` to the translation of `%sendcache`.

**Review by garrigue — APPROVED** [review]
Thanks for the fix

**Comment by garrigue** [comment]
Wondering what is the problem with i386-static.

Looking back at `camlinternalOO.ml`, I'm actually wondering too whether it is a good idea to use `sendcache` there anyway. I.e., it would probably be cleaner to just use the standard compilation in those cases. But this is for the future.

File: bytecomp/bytegen.ml [hunk 2]
```diff
@@ -560,7 +560,7 @@ let rec comp_expr env exp sz cont =
         end
       end
   | Lsend(kind, met, obj, args, _) ->
-      let args = if kind = Cached then List.tl args else args in
+      assert (kind <> Cached);
```
Comment (yawaramin) [inline bytecomp/bytegen.ml:563]: Is it the usual practice to do `assert <bool>` to check invariants? I was thinking it would be more informative to fail with a message, e.g.

```ocaml
| Lsend(Cached, _, _, _, _) ->
  invalid_arg "Bytecode does not support Lsend (Cached, ...)"
| Lsend(kind, met, obj, args, _) ->
  ...
```

Comment (garrigue) [reply bytecomp/bytegen.ml:563]: The advantage of an assertion is that the error message gives you the location in the source code, nice for an internal compiler error. We used to have fatal errors named "ctype(1)", "ctype(2)".
But it could be nicer to have also a message.

**Comment by garrigue** [comment]
Does anyone know why we get all these failures for i386-static?
It seems strange to have to do a bootstrap for such a purely internal change of the compiler.
