### PR TITLE
#12189: anonymous polyvariant rows and explicitly polymorphic type annotations

### LINKED ISSUE #12189: Universal quantification fails when mixed with polymorphic variants in OCaml 5.1.0~alpha1
The following test-case:
```
let f :
  type a.
  a ->
  [> `A of a ] =
  fun x -> `A x
```
compiles fine with OCaml 5.0.0 and below but fails with 5.1.0~alpha1 with the following error message:
```
File "test.ml", lines 1-5, characters 4-15:
1 | ....f :
2 |   type a.
3 |   a ->
4 |   [> `A of a ] =
5 |   fun x -> `A x
Error: This expression has type 'a -> [> `A of 'a ]
       but an expression was expected of type 'a -> [> `A of 'a0 ]
       The universal variable 'a0 would escape its scope
```
This only seems to be the case when polymorphic variants are involved as removing them in the code above makes it compile fine again.

### PR DESCRIPTION
**Pull request by Octachron**
Anonymous rows in polyvariant types like ``[> `Foo]`` can be perilous when mixed with explicitly polymorphic type annotation. Indeed, the hidden row variable might capture some of  the universal type variables. This behavior leads to the following error in OCaml 5.1 and later

```ocaml
let f: 'a. [> `Foo of 'a ] -> unit = fun _ -> ()
```
```
Error: This pattern matches values of type [> `Foo of 'a ]
       but a pattern was expected which matches values of type 'b
       The universal variable 'a would escape its scope
```

Unfortunately, this code was allowed by mistake before OCaml 5.1 . And fixing this bug broke some existing code (see #12189) without a painless workaround due to the short form for GADT:

```ocaml
let f: type a. [> `Foo of a ] -> unit = fun _ -> ()
```
In this case, fixing the error above requires to desugar by hand the short form.

To decrease the pain created by this bug fix, this PR proposes to bind anonymous row variables of syntactic polymorphic variant types to the nearest explicitly polymorphic type annotations. In other words,

```ocaml
let f: 'a. [> `Foo of 'a ] -> unit = fun _ -> ()
```
is read as
```ocaml
let f: 'a 'r. ([> `Foo of 'a ] as 'r) -> unit = fun _ -> ()
```

This new reading has the advantage of preserving the ability to use the short form`type a b c. ... ` when mixing GADTs and polymorphic variants in OCaml 5.1. Consider for instance:

```ocaml
type 'a w = Int: int w
let f: type a. a w -> [> `Foo of a ] -> unit = fun Int ->
function `Foo x -> x | _ -> 0
```
this short form is elaborated into
```ocaml
let f: 'a. 'a w -> [> `Foo of 'a ] -> 'a = (fun (type a) -> ... )
```
which is correct with the rule introduced in this PR that the anonymous row variable in `[> Foo ... ]` is bound at the `'a. ... ` level.

However, beware this PR is still a breaking change: users now need to add an alias to an unification variable if they really intended to use a global variable for the row variable:

```ocaml
let f: 'b. [< `Foo | `Bar ] -> 'b -> 'b = fun `Foo x -> x
```
needs to be rewritten after this PR into

```ocaml
let f: 'b. ([< `Foo | `Bar ] as 'r) -> 'b -> 'b = fun `Foo x -> x
```

Fix #12189

### CODE REVIEW

**Comment by garrigue** [comment]
If your goal is to preserve backward compatibility, then you could be more clever: only turn the row variable into a univar if the fields contain univars, and only bind at some `Tpoly` node if one of the explicit variables appears in the fields. This requires collecting the fields along with the row variables.

**Comment by Octachron** [comment]
Being more conservative might be a better option indeed, and the implementation is possibly simpler by registering row variables as associated to an univar whenever the fields use this univar.
At least, the breaking changes are relegated to the much more visibly problematic:
```ocaml
let f: 'a . 'a -> [> `X of 'a ] -> 'a = fun x y ->
  match y with
  | `Y -> x
  | `X x -> x
```
Being more conservative also means that we could emit a warning once we have proper support for `(type a and r = [> X of a])` and/or `type a r. [> X of a] as r`.

**Comment by garrigue** [comment]
This looks good, but I have a hard time understanding the code.
Maybe we can discuss that today.

File: testsuite/tests/typing-poly/poly.ml [hunk 1]
```diff
@@ -1949,3 +1937,54 @@ Line 2, characters 16-24:
 Error: This field value has type 'b option ref which is less general than
          'a. 'a option ref
 |}]
+
+
+(** #12210: turn row variable into univars under Ptyp_poly: *)
```
Comment (gasche) [inline testsuite/tests/typing-poly/poly.ml:1942]: (Maybe we could have example with objects to show that things don't work as nicely for object types.)

File: testsuite/tests/typing-poly/poly.ml [hunk 2]
```diff
@@ -1949,3 +1937,54 @@ Line 2, characters 16-24:
...
+          < n : 'irr.
+                  ('irr -> unit) * (([> `X of 'a | `Y of 'b ] as 'c) -> 'a) > > ->
+  'a = <fun>
+|}]
+
+
+let fail: 'a . 'a -> [> `X of 'a ] -> 'a = fun x y ->
+  match y with
+  | `Y -> x
+  | `X x -> x
```
Comment (gasche) [inline testsuite/tests/typing-poly/poly.ml:1980]: This example is now rejected, but it was accepted in older versions of OCaml. Let me explain what is going on, in case some users see similar code that starts being rejected after the present PR is merged.

In the 5.0 toplevel (without the present PR):

```ocaml
# let fail: 'a . 'a -> [> `X of 'a ] -> 'a = fun x y ->
    match y with
    | `Y -> x
    | `X x -> x;;
val fail : 'a -> [< `X of 'a | `Y > `X ] -> 'a = <fun>
```

What was going on before is that the type annotation ``[> `X of 'a ]`` was too general, more general than what the implementation does, and the implementation was unifying the row variable to something more specific during type-checking of the implementation of the function.

This is similar to what happens on `let f : 'a -> 'a = fun x -> x + 1`, which is (surprisingly?) accepted by OCaml, which happily specializes `'a` into `int`. Before this PR, the implicit row variable in `[> `X of 'a ]` was treated in this not-forced-to-remain-polymorphic way.

On the other hand, `let f : 'a . 'a -> 'a = fun x -> x + 1` is rejected, because `'a . ...` enforces that `'a` remains polymorphic. This is exactly why `fail` is rejected after this PR: now any open polymorphic variant that mentions an explicitly-polymorphic variable (the `'a` in ``[> `X of 'a ]``) is forced to remain polymorphic, so type-checking the function definition fails.

The fix is to write directly the "right" annotation for this program from the start, not a more general version that needs to be un-generalized during type inference:

```ocaml
let fail: 'a . 'a -> [< `X of 'a | `Y ] -> 'a = fun x y ->
    match y with
    | `Y -> x
    | `X x -> x;;
```

( @Octachron maybe you could add this "fixed" version in the testsuite?)

**Review by garrigue — APPROVED** [review]
Code seems correct.

File: typing/typetexp.ml [hunk 3]
```diff
@@ -593,7 +621,11 @@ and transl_type_aux env policy styp =
         in
         { rf_desc; rf_loc; rf_attributes; }
       in
-      let tfields = List.map add_field fields in
+      let more_ref = ref (newvar ()) in
```
Comment (Octachron) [inline typing/typetexp.ml]: Review: we could have `ref None` to make sure that this variable is not used.

File: testsuite/tests/typing-poly/poly.ml [hunk 4]
```diff
@@ -1988,3 +1987,53 @@ Error: This pattern matches values of type [? `Y ]
...
        it may not allow the tag(s) `Y
 |}]
+
+let fail_example_corrected: 'a . 'a -> [< `X of 'a | `Y > `X ] -> 'a = fun x y ->
+  match y with
+  | `Y -> x
+  | `X x -> x
+[%%expect {|
+val fail_example_corrected : 'a -> [< `X of 'a | `Y > `X ] -> 'a = <fun>
+|}]
```
Comment (gasche) [inline testsuite/tests/typing-poly/poly.ml:1997]: Note: on trunk and your branch, I think that you can actually write the more general argument ``[< `X of 'a | `Y ]`` (as I did in my review comment), as it does not introduce a weird intersection as it did on 5.0 and earlier.

Comment (Octachron) [reply testsuite/tests/typing-poly/poly.ml:1997]: Indeed. I was more thinking of doing a minimal correction; but it might be better to track the bug correction too.

**Comment by Octachron** [comment]
Cherry picked on 5.1 (82e609a21f).
