### PR TITLE
fix(windows): Fix racy socketpair on Windows

### LINKED ISSUE #14372: socketpair_win32.c: Possible TOCTOU race in `socketpair()`?
Hi OCaml maintainers,

We've started seeing `socketpair` errors on our Windows CI jobs that look roughly thus:

```
Unix_error: Only one usage of each socket address (protocol/network address/port) is normally permitted.
 socketpair 
Raised at Stdlib__Domain.join in file "domain.ml", line 299, characters 16-24
Called from Eio_windows__Domain_mgr.Impl.run in file "lib_eio_windows/domain_mgr.ml", line 115, characters 21-55
Called from Executor_pool.create.(fun).f in file "OSS/libs/parallelism/Executor_pool.ml", line 106, characters 12-77
Re-raised at Executor_pool.create.(fun).f in file "OSS/libs/parallelism/Executor_pool.ml", line 130, characters 18-54
Called from Eio__core__Fiber.fork_daemon.(fun) in file "lib_eio/core/fiber.ml", line 34, characters 10-14
Re-raised at Eio__core__Switch.maybe_raise_exs in file "lib_eio/core/switch.ml", line 119, characters 21-56
Called from Eio__core__Switch.run_internal in file "lib_eio/core/switch.ml", line 149, characters 4-21
Called from Eio__core__Cancel.with_cc in file "lib_eio/core/cancel.ml", line 118, characters 8-12
Re-raised at Eio__core__Cancel.with_cc in file "lib_eio/core/cancel.ml", line 120, characters 50-58
Called from ...
```

The stack traces are incomplete (but would not be after we run with https://github.com/ocaml/ocaml/pull/14363 merged (thank you again!)).  While I'm not exactly sure where we end up constructing a domain socket (though Lwt sounds like a likely candidate), one thing that _did_ stand out was that `socketpair` is implemented on Windows in terms of a temporary file as opposed to just using a "real" domain socket like you'd expect on a *Nix machine, since `socketpair` never landed in Winsock, I suppose.  Reading between the lines of the error we get back: seems like we are trying to "bind" to the same temporary file on occasion, suggesting that there's a filename collision happening somewhere.

Consider the [following lines](https://github.com/semgrep/ocaml/blob/9135c0c97c6060ef6feabffe024f7ff22fdff953/otherlibs/unix/socketpair_win32.c#L62-L91) in the standard library: 

The standard library creates a temp file mocking the socket (line 61).  We set up our AF_UNIX sockaddr structure using this filename, with a tacet invariant that nobody else should try to use this same filename while we're using it.  However, there is a brief period where the temp file disappears and thus the invariant could be broken: we then then _non-atomically_ delete the file (line 83) before `bind` ing to it, which I believe re-creates the file but as a socket file (line 91).  

Seems like two threads could slip in and choose the same file to "bind" on, if one thread has created and deleted its file, but, prior to calling `bind`, another thread comes in and re-generates the same temporary filename?

I definitely do not know very much about Windows development: I found [this blog post](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/) that mentions alternative ways of implementing sockets (so-called "abstract" and "unnamed" sockets): It sounds like there are perhaps [issues using abstract sockets](https://github.com/microsoft/WSL/issues/4240)?  Seems like if we could at least seed the temp file name with something domain-local, we could sidestep the collision?

### PR DESCRIPTION
**Pull request by jmgrosen**
Previously socketpair on win32 relied on GetTempFileName to generate a unix socket path. This API uses very little entropy and thus relies on the created file essentially serving as a lock to avoid concurrent calls picking the same temp name. However, since socketpair must delete the file before binding to that path, it essentially relinquishes the lock for that window. This sometimes leads to address-in-use errors when concurrent threads or processes are trying to create socketpairs.

This patch replaces that path name generation with one that uses the process ID and an incrementing socketpair-call-specific ID. This rules out the possibility of concurrent calls to socketpair picking the same temp name. This does not rule out other threads or processes deliberately colliding with the name, but the peerid check later errors if another process collides.

Fixes #14372.

One issue with this implementation is that if an OCaml process is killed _while_ `socketpair` is being executed, the socket file could persist and end up conflicting with future processes' `socketpair` calls if they have the same PID and `socketpair_id` counter value. I think this is a remote enough possibility to be worth ignoring, but other approaches include retrying a few times by incrementing `socketpair_id`, generating `socketpair_id` randomly (with more randomness than `GetTempFileName` would use), or both.

I don't have a great way to consistently regression-test this in a way that feels appropriate for a test suite, but I'm including a reproducer below that usually fails on my machine without the patch but always succeeds with it. You might need to tweak some of the knobs to reproduce it, though. We have also seen no socketpair errors in Semgrep since deploying this change. Please let me know if you have suggestions for how to incorporate it as a test!

This is an alternative to #13450 with a narrower fix. As discussed in #14372, #13450 did not seem to fix the bug in Semgrep's usage and it doesn't fix the reproducer.

Reproducer:
```ocaml
let n_domains = ref 8
let n_socket_pairs = ref 10_000
let keep_sockets_open = ref false

let go i =
  for _ = 0 to !n_socket_pairs do
    let r, w = Unix.socketpair Unix.PF_UNIX Unix.SOCK_STREAM 0 in
    if not !keep_sockets_open then
      (Unix.close r; Unix.close w)
  done

let argspecs =
  [
    ("-d", Arg.Set_int n_domains, "Number of domains");
    ("-s", Arg.Set_int n_socket_pairs, "Number of socketpair calls");
    ("-o", Arg.Set keep_sockets_open, "Keep all the socket pairs open");
  ]
let usage = "socketpair_repro [-d N] [-s N] [-o]"

let join_print_exn i d =
  try
    Domain.join d;
    Printf.printf "Domain %u succeeded\n%!" i
  with e ->
    Printf.printf "Domain %u failed: %s\n%!" i (Printexc.to_string e)

let () =
  Arg.parse argspecs (fun _ -> ()) usage;
  Printf.printf "spawning %u domains, each to create %u socketpairs\n%!" !n_domains !n_socket_pairs;
  let domains = List.init !n_domains (fun i -> Domain.spawn (fun _ -> go i)) in
  List.iteri join_print_exn domains
```

### CODE REVIEW

**Review by MisterDA — APPROVED** [review]
LGTM, thanks for tackling this issue.
How about making `socketpair_id` an `atomic_ulong` and using [`atomic_fetch_add(&socketpair_id, 1)`](https://en.cppreference.com/w/c/atomic/atomic_fetch_add.html) instead of [`InterlockedIncrement`](https://learn.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedincrement)?

File: otherlibs/unix/socketpair_win32.c [hunk 1]
```diff
@@ -71,22 +77,14 @@ static int socketpair(int domain, int type, int protocol,
...
     goto fail_wsa;
 
-  /* The documentation requires removing the file before binding the socket. */
-  if (DeleteFile(path) == 0) {
-    drc = GetLastError();
-    if (drc != ERROR_FILE_NOT_FOUND) {
-      caml_win32_maperr(drc);
-      goto fail_sockets;
-    }
-  }
```
Comment (nojb) [inline otherlibs/unix/socketpair_win32.c:88]: Sorry if I'm missing something obvious: Is the comment above ("the documentation requires removing the file") wrong? Can you say a few words about the removal of this piece of code?

Comment (jmgrosen) [reply otherlibs/unix/socketpair_win32.c:88]: The comment above is correct: `bind` requires the requested binding path to not exist. Before this change, `GetTempFileName` created an empty file at the path it returned, so it needed to be removed before binding. However, after this change, a path is generated without an associated file being created, so there is no file that needs to be removed before binding, in the typical case.

There _could_ still be a file at that generated path, either
1. leftover from a previous OCaml process that was killed during a `socketpair` invocation (see the PR description), or
2. some non-OCaml file that happens to be named according to the same pattern.

Restoring this deletion would address (1), but with the risk of messing up another process/user in (2). Both possibilities seem unlikely to happen to me, but I can re-add this deletion, or implement one of the other solutions that I mentioned in the PR description to address (1) without the risk for (2).

Thanks for the close reading!

Comment (nojb) [reply otherlibs/unix/socketpair_win32.c:88]: Thanks for the explanation. I am OK with leaving the code as it is, and only complexifying it, later, if it is needed.

**Comment by nojb** [comment]
> other approaches include retrying a few times by incrementing `socketpair_id`, generating `socketpair_id` randomly (with more randomness than `GetTempFileName` would use), or both.

Yet another possibility would be to use the current timestamp. But I think the current approach is fine.

**Review by nojb — APPROVED** [review]
LGTM

@jmgrosen Can you add the reviewers to the Changes entry? We can then move to merge.

**Comment by jmgrosen** [comment]
@nojb Pushed with the reviewers in Changes and with @MisterDA's suggestion of `InterlockedIncrement` -> `atomic_fetch_add`.

Thanks for the extremely quick reviews, both of you!

**Comment by nojb** [comment]
The CI failure is unrelated (the AppVeyor build is timing our due to the 1h limit).
