### PR TITLE
Replace TypedtreeIter with Tast_iterator

### LINKED ISSUE #7878: Replace TypedtreeIter by Tast_iterator
**Original bug ID:** 7878
**Reporter:** @trefis
**Status:** acknowledged (set by @gasche on 2019-02-20T15:37:21Z)
**Resolution:** open
**Priority:** low
**Severity:** minor
**Category:** misc
**Tags:** junior_job
**Monitored by:** @nojb

## Bug description

And make it consistent with Ast_iterator.

Cf. https://github.com/ocaml/ocaml/pull/2173

### PR DESCRIPTION
**Pull request by xenia-foxtrot**
Hi there! This is intended to be my contribution for Outreachy. I'm going to tag @gasche here since he's the contact I've been given.

This PR fixes #7878. It removes `TypedtreeIter.ml[i]` and adds `tast_iterator.ml[i]`, which is similar in implementation and interface to `tast_mapper`. Additionally, it replaces the single use of `TypertreeIter` in `typing/parmatch`. 

I've compiled and tested this successfully on Ubuntu 18.10.

### CODE REVIEW

File: typing/parmatch.ml [hunk 1]
```diff
@@ -2438,39 +2438,38 @@ let pattern_stable_vars ns p =
   let module M_mod = unpack M .. in true
 *)
 
+open Tast_iterator
```
Comment (gasche) [inline typing/parmatch.ml]: Could we do without a global `open` statement in the file? I'd rather have qualified uses (`Tast_iterator.foo`) in general, with maybe some local opens `(let open Tast_iterator in ...)` in places where systematic qualification hurts readability.

**Review by gasche — COMMENTED** [review]
Thanks for the PR!

The code seems generally nice to me, but I haven't made a point-by-point comparison of the default iterators yet (fairly boilerplate-y unfortunately).

(Looking at the `parmatch` code again, the hackish part is fairly unclear, and I regret not explaining better when we touched it last time... In any case, I checked that the new code is doing the same thing as the previous one -- although `enter_*` and `leave_*` have been merged in a single function.)

**Comment by gasche** [comment]
cc @alainfrisch and @trefis who might be interested in this PR.

File: typing/tast_iterator.ml [hunk 2]
```diff
@@ -0,0 +1,495 @@
...
+let type_extension sub {tyext_constructors; tyext_params; _} =
+  List.iter (fun (c, _) -> sub.typ sub c) tyext_params;
+  List.iter (sub.extension_constructor sub) tyext_constructors
+
+let type_exception sub {tyexn_constructor; _} =
+    sub.extension_constructor sub tyexn_constructor
+
+let extension_constructor sub {ext_kind; _} =
+    match ext_kind with
+      | Text_decl (ctl, cto) ->
```
Comment (nojb) [inline typing/tast_iterator.ml]: Hate to nitpick, but this indentation is fairly non-standard; typically `|` is aligned with `match`.

File: typing/tast_iterator.ml [hunk 3]
```diff
@@ -0,0 +1,495 @@
...
+    | Texp_coerce (cty1, cty2) ->
+        opt (sub.typ sub) cty1;
+        sub.typ sub cty2
+    | Texp_newtype _ -> ()
+    | Texp_poly cto -> opt (sub.typ sub) cto
+  in
+  List.iter (fun (e, _, _) -> extra e) exp_extra;
+  sub.env sub exp_env;
+  match exp_desc with
+    | Texp_ident _  -> ()
```
Comment (nojb) [inline typing/tast_iterator.ml]: Idem.

File: typing/tast_iterator.ml [hunk 4]
```diff
@@ -0,0 +1,495 @@
...
+    type_kind: iterator -> type_kind -> unit;
+    value_binding: iterator -> value_binding -> unit;
+    value_bindings: iterator -> (rec_flag * value_binding list) -> unit;
+    value_description: iterator -> value_description -> unit;
+    with_constraint: iterator -> with_constraint -> unit;
+  }
+
+(** Helper function that applies a function over an option. 
+ * Taken from ast_iterator.ml*)
+let opt f = function None -> () | Some x -> f x
```
Comment (nojb) [inline typing/tast_iterator.ml]: Can use `Option.iter`

File: typing/tast_iterator.ml [hunk 5]
```diff
@@ -0,0 +1,495 @@
...
+        sub.module_expr sub mexpr;
+        sub.expr sub exp
+    | Texp_letexception (cd, exp) ->
+        sub.extension_constructor sub cd;
+        sub.expr sub exp
+    | Texp_assert exp -> sub.expr sub exp
+    | Texp_lazy exp -> sub.expr sub exp
+    | Texp_object (cl, _) -> sub.class_structure sub cl
+    | Texp_pack mexpr -> sub.module_expr sub mexpr
+    | Texp_letop {let_ = l; ands; body; _} ->
```
Comment (nojb) [inline typing/tast_iterator.ml]: Could just use punning for `let_` as well, instead of rebinding.

Comment (xenia-foxtrot) [reply typing/tast_iterator.ml]: I had to rebind let_ because for some reason my editor was convinced that it was a let expression and not a variable name. I can remove if you'd like, but it might cause issues for other people too.

File: typing/parmatch.ml (hunk 1 above)
Comment (xenia-foxtrot) [reply typing/parmatch.ml]: A local open would probably work as well. We have to have an open statement somewhere otherwise the compiler will complain about fields that aren't visible in the current scope.

Comment (gasche) [reply typing/parmatch.ml]: You can use `record.Module.field` to access a field declared in another record. But in that case, opening just within the scope where the iterator is used would also be fine.

Comment (Octachron) [reply typing/parmatch.ml]: Another option would be to use a short alias for `Tast_iterator` something like:
```OCaml
module Iter = Tast_iterator
```

Comment (gasche) [reply typing/parmatch.ml]: Yes, but still, not in the global scope, when only one sub-part of one function uses the iterator.

**Comment by xenia-foxtrot** [comment]
@nojb @gasche Alright I think I've made the changed you both requested. Let me know how it looks!

File: Changes [hunk 6]
```diff
@@ -57,6 +57,9 @@ Working version
 - GPR#2308: More debugging information on [Cmm] terms
   (Mark Shinwell, review by Stephen Dolan)
 
+- GPR#7878: Replaced TypedtreeIter with tast_iterator
```
Comment (nojb) [inline Changes]: Please also quote the relevant issue number #8539.

Comment (xenia-foxtrot) [reply Changes]: Sure thing. How should I do this? I assume I shouldn’t replace 7878.

Comment (ulugbekna) [reply Changes]: Great PR! See [contributing](https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md#changelog) for reference on how to edit `Changes`.

**Comment by xenia-foxtrot** [comment]
@nojb @ulugbekna I've updated `Changes`. Is it alright now?

**Comment by nojb** [comment]
There are some `check-typo` errors: https://travis-ci.org/ocaml/ocaml/jobs/511022496#L488-L490.

**Comment by nojb** [comment]
Also, regarding `Changes`, following #8542, please remove the `GPR` prefixes. Sorry for the back-and-forth on this, it stems from the very recent migration of our bugtracker to GitHub!

**Comment by xenia-foxtrot** [comment]
> There are some `check-typo` errors: https://travis-ci.org/ocaml/ocaml/jobs/511022496#L488-L490.

I can fix the whitespacing issue, but what do I need to do for the copyright line? I don't see any information about this in Contributing.

**Comment by nojb** [comment]
> I can fix the whitespacing issue, but what do I need to do for the copyright line? I don't see any information about this in Contributing.

`tast_iterator.ml` needs a copyright header, as the rest of the files.

Also, you should put your own name in the copyright header and update the year (2019).

@gasche @damiendoligez is there anything special to be done, copyright-wise, for this first-time contribution?

**Comment by xenia-foxtrot** [comment]
Oh I'm not sure what's going on with 22c745e. Is this going to be an issue? I can try to rebase it.

**Comment by xenia-foxtrot** [comment]
Alright never-mind, I got the history fixed.
Anyways, this should conform to the styling guides.

**Comment by nojb** [comment]
`tast_iterator.ml` is still missing a copyright header, and the `.mli` should have your name in it.

**Comment by gasche** [comment]
Re. copyright: I'm afraid that we do, in fact, have something to do: this contribution is not small enough to pass under the "no copyright" policy, so @ILikePizza555 should sign a CLA and send it to @xavierleroy. This is all explained in [CONTRIBUTING.md#Contributor License Agreement](https://github.com/ocaml/ocaml/blob/trunk/CONTRIBUTING.md#contributor-license-agreement).

**Comment by xenia-foxtrot** [comment]
@nojb Ack! Sorry about that. I think the change got lost when I was mucking around with git. Anyways, I've updated it now.

**Comment by xenia-foxtrot** [comment]
@gasche I got the agreement signed and sent.

**Comment by xavierleroy** [comment]
CLA received in good order, we can proceed with the review (if it's not finished) and the merge (if it is).

File: typing/tast_iterator.mli [hunk 7]
```diff
@@ -0,0 +1,69 @@
+(**************************************************************************)
+(*                                                                        *)
+(*                                 OCaml                                  *)
+(*                                                                        *)
+(*            Nicolas Ojeda Bar, LexiFi, Isaac "Izzy" Avram               *)
```
Comment (nojb) [inline typing/tast_iterator.mli]: Only your name here, and year should be 2019.

File: typing/tast_iterator.ml [hunk 8]
```diff
@@ -0,0 +1,505 @@
+(**************************************************************************)
+(*                                                                        *)
+(*                                 OCaml                                  *)
+(*                                                                        *)
+(*                          Isaac "Izzy" Avram                            *)
+(*                                                                        *)
+(*   Copyright 2012 Institut National de Recherche en Informatique et     *)
```
Comment (nojb) [inline typing/tast_iterator.ml]: Year should be 2019.

File: typing/tast_iterator.ml [hunk 9]
```diff
@@ -0,0 +1,505 @@
...
+  List.iter (fun (c, _) -> sub.typ sub c) typ_params
+
+let type_declarations sub (_, list) = List.iter (sub.type_declaration sub) list
+
+let type_extension sub {tyext_constructors; tyext_params; _} =
+  List.iter (fun (c, _) -> sub.typ sub c) tyext_params;
+  List.iter (sub.extension_constructor sub) tyext_constructors
+
+let type_exception sub {tyexn_constructor; _} =
+    sub.extension_constructor sub tyexn_constructor
```
Comment (nojb) [inline typing/tast_iterator.ml]: Sorry to nitpick, but the indentation is very inconsistent in this file. We typically indent with 2 spaces only.

**Review by nojb — APPROVED** [review]
LGTM, once the small corrections in copyright header and indentation are done.

**Comment by xenia-foxtrot** [comment]
@nojb Eh, don't worry about being nitpicky. I understand the importance of good code style. Frankly I should be apologizing for my changes not being more consistent! 😛 

Anyways, I fixed the copyright info and the indentation.

File: typing/tast_iterator.ml (hunk 9 above)
Comment (nojb) [reply typing/tast_iterator.ml]: Indentation above still needs to be adjusted.

File: typing/tast_iterator.ml [hunk 10]
```diff
@@ -0,0 +1,508 @@
...
+  List.iter (fun (e, _, _) -> extra e) exp_extra;
+  sub.env sub exp_env;
+  match exp_desc with
+  | Texp_ident _  -> ()
+  | Texp_constant _ -> ()
+  | Texp_let (rec_flag, list, exp) ->
+      sub.value_bindings sub (rec_flag, list);
+      sub.expr sub exp
+  | Texp_function {cases; _} -> sub.cases sub cases
+  | Texp_apply (exp, list) ->
```
Comment (nojb) [inline typing/tast_iterator.ml:195]: Indentation below needs to be adjusted.

File: typing/tast_iterator.ml [hunk 11]
```diff
@@ -0,0 +1,508 @@
...
+let class_description sub x =
+  class_infos sub (sub.class_type sub) x
+
+let module_type sub {mty_desc; mty_env; _} =
+  sub.env sub mty_env;
+  match mty_desc with
+  | Tmty_ident _      -> ()
+  | Tmty_alias _      -> ()
+  | Tmty_signature sg -> sub.signature sub sg
+  | Tmty_functor (_, _, mtype1, mtype2) ->
```
Comment (nojb) [inline typing/tast_iterator.ml:297]: Indentation below needs to be adjusted.

File: typing/tast_iterator.ml [hunk 12]
```diff
@@ -0,0 +1,508 @@
...
+  | OTtag (_, ct) -> sub.typ sub ct
+  | OTinherit ct -> sub.typ sub ct
+
+let class_field_kind sub = function
+  | Tcfk_virtual ct -> sub.typ sub ct
+  | Tcfk_concrete (_, e) -> sub.expr sub e
+
+let class_field sub {cf_desc; _} = match cf_desc with
+  | Tcf_inherit (_, cl, _, _, _) -> sub.class_expr sub cl
+  | Tcf_constraint (cty1, cty2) ->
```
Comment (nojb) [inline typing/tast_iterator.ml:439]: Indentation below needs to be adjusted.

File: typing/tast_iterator.ml [hunk 13]
```diff
@@ -0,0 +1,508 @@
...
+
+let include_infos f {incl_mod; _} = f incl_mod
+
+let class_type_declaration sub x =
+  class_infos sub (sub.class_type sub) x
+
+let class_declaration sub x =
+  class_infos sub (sub.class_expr sub) x
+
+let iter_str_desc sub str_desc = match str_desc with
```
Comment (nojb) [inline typing/tast_iterator.ml]: I would inline this function inside `structure_item` below, like in all the other functions where there is no separate function to treat the "desc" part.

File: typing/tast_iterator.ml (hunk 9 above)
Comment (nojb) [reply typing/tast_iterator.ml]: `sub.extension_constructor sub tyexn_constructor` should be indented with 2 spaces.

File: Changes [hunk 14]
```diff
@@ -80,6 +80,9 @@ Working version
 - #2308: More debugging information on [Cmm] terms
   (Mark Shinwell, review by Stephen Dolan)
 
+- #7878, #8542: Replaced TypedtreeIter with tast_iterator
+  (Isaac "Izzy" Avram)
```
Comment (nojb) [inline Changes]: Please add reviewers here (@gasche and myself).

Comment (xenia-foxtrot) [reply Changes]: Sure thing!

File: typing/tast_iterator.ml [hunk 15]
```diff
@@ -0,0 +1,506 @@
...
+  List.iter (fun (c, _) -> sub.typ sub c) typ_params
+
+let type_declarations sub (_, list) = List.iter (sub.type_declaration sub) list
+
+let type_extension sub {tyext_constructors; tyext_params; _} =
+  List.iter (fun (c, _) -> sub.typ sub c) tyext_params;
+  List.iter (sub.extension_constructor sub) tyext_constructors
+
+let type_exception sub {tyexn_constructor; _} =
+    sub.extension_constructor sub tyexn_constructor
```
Comment (nojb) [inline typing/tast_iterator.ml]:
```suggestion
  sub.extension_constructor sub tyexn_constructor
```

Comment (xenia-foxtrot) [reply typing/tast_iterator.ml]: How on earth do I keep missing these indentation issues. I swear I combed through this file several times now.

**Comment by nojb** [comment]
Thanks! I think that's all. I'll squash-merge once the CI passes.
