### PR TITLE
Change inlining cost of flambda switches.

### LINKED ISSUE #7449: excessive inlining of jump tables
**Original bug ID:** 7449
**Reporter:** markghayden
**Assigned to:** @chambart
**Status:** assigned (set by @chambart on 2017-01-03T20:59:28Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Platform:** AMD64
**OS:** MacOS
**OS Version:** 10.12.2
**Version:** 4.04.0
**Category:** middle end (typedtree to clambda)
**Tags:** flambda
**Monitored by:** @gasche @ygrek

## Bug description

See the attached code.  The [to_string] function is inlined at all call sites, even with no optimization specified at the command line (!?!).  Note that each call site includes a full copy of the jump table and all the jump branches.  The test case here has 30 items.  I've seen this with larger cases (300 items).  Maybe I'm missing something, but it seems this is really off here since this behavior can result in significant code growth.  A work-around is to annotate with '[@inline never]'.

## Steps to reproduce

Compile with 4.04.0 or 4.05.0.dev trunk.  Note that for 4.05.0.dev, the lookup table is used if all the return values are constants and perhaps that is OK to inline.  Added a [failwith] for one of the cases forces the use of jump tables, at least on AMD64.

  ocamlopt  -c -S du.ml

## Additional information

See attached ML file.  Assembler output will follow.

## File attachments

- [du.ml](https://gist.githubusercontent.com/vicuna/733c0e55d549bc98266f7120833c7ed1/raw/cfb34474ec5add4608232604d68dc9ad17debfa6/du.ml)
- [du.s](https://gist.githubusercontent.com/vicuna/733c0e55d549bc98266f7120833c7ed1/raw/533850dce9799aa42b01200713ca8cbbba009034/du.s)

### PR DESCRIPTION
**Pull request by chambart**
The cost of a switch didn't really depend on its size. This reflects a bit better that large switch are not necessarily worth inlining.
The added branches cost less than the first ones because in a jump table adding more branches only requires adding a new entry to the table.

This fixes #7449

### CODE REVIEW

File: middle_end/flambda/inlining_cost.ml [hunk 1]
```diff
@@ -89,7 +89,12 @@ let lambda_smaller' lam ~than:threshold =
...
       lambda_size body
     | Switch (_, sw) ->
-      let aux = function _::_::_ -> size := !size + 5 | _ -> () in
+      let rec aux =
+        function
+        | [] | [_] -> ()
+        | [_;_] -> size := !size + 5
+        | _ :: t -> size := !size + 1; aux t
+      in
       aux sw.consts; aux sw.blocks;
```
Comment (gasche) [inline middle_end/flambda/inlining_cost.ml]: I think the code would be easier to read as

```ocaml
let cost cases =
 let size = List.length cases in
 if size <= 1 then 0
 else 3 + size
in
size := !size + cost sw.consts + cost sw.blocks;
```

(It's a bit odd that a switch with one const and one block case has cost 0, but if I understand correctly you don't really care?)

**Review by gasche — APPROVED** [review]
Looks reasonable.

File: middle_end/flambda/inlining_cost.ml (hunk 1 above)
Comment (chambart) [reply middle_end/flambda/inlining_cost.ml]: Yes it might be worth taking into account the size for that 'if'. The thing is that the parameters for inlining have been carefully tuned through lots of benchmarking. Changing the computation too much would requires retunning everything.
So it would better reflect the actual inlining cost. But this is too much effort for this.

Comment (chambart) [reply middle_end/flambda/inlining_cost.ml]: I shamelessly took your suggestion. What should I put in the change since there is no code from me ?

Comment (gasche) [reply middle_end/flambda/inlining_cost.ml]: Well sometimes we use "Foo and bar, review by blah", but "bar" and "blah" have to be distinct in this case, so I would recommend keeping me as a reviewer instead ;-)

Comment (gasche) [reply middle_end/flambda/inlining_cost.ml]: > The thing is that the parameters for inlining have been carefully tuned through lots of benchmarking. Changing the computation too much would requires retuning everything.

At first I thought this justification made perfect sense, but: don't you also need (re)tuning if you change the cost of more-than-2 matches? I thought this was a case of "oh we don't need to benchmark this change because it does not matter this strongly", but your comment seems to imply that maybe we would need to.

Comment (gasche) [reply middle_end/flambda/inlining_cost.ml]: (Well one argument would be that the change you propose does not affect pattern-matching on list, or any of the common datastructures, while the change for one-const-and-one-block would.)

**Comment by xavierleroy** [comment]
Why is this PR not merged? What are we waiting for?

**Comment by lthls** [comment]
We're waiting for a Changes entry. If I can't get @chambart to push one I'll do it myself and merge tomorrow.
