### PR TITLE
fix #11508: Bytes.escaped is memory-unsafe in presence of concurrent updates

### LINKED ISSUE #11508: Bytes.escaped unsafe under concurrent modification
There's a safety issue with the current definition of `Bytes.escaped`:
https://github.com/ocaml/ocaml/blob/7412593a42f0e6a8c274c0cb7bf22a4c3646abd0/stdlib/bytes.ml#L170-L208

`Bytes` operations should not crash under concurrent usage as documented in https://github.com/ocaml/ocaml/pull/11237.
However under concurrent modification of the underlying data structure, the above may result in out-of-bounds `unsafe_set` if more escapable `char`s are present since the target length `n` was calculated.

Here's a test case to trigger it:
```ocaml
(*TEST*)

let buf = Bytes.make 128 '0'

let fn_mutate s =
  let c = if Random.bool () then '0' else '\n' in
  Bytes.fill s 0 127 c

let fn_escape s =
  let s' = Bytes.escaped s in
  assert ((Bytes.length s') <= 4*(Bytes.length s))

let _ =
  let iter = Atomic.make 0 in
  let d_mutate = Domain.spawn (fun () ->
        while Atomic.get iter < 100_000; do fn_mutate buf done; ) in
  let d_escape = Domain.spawn (fun () ->
        while Atomic.get iter < 100_000; do
          fn_escape buf; ignore (Atomic.fetch_and_add iter 1) done; ) in

  ignore (Domain.join d_mutate);
  ignore (Domain.join d_escape)
```

```
$ ocamlopt -o /tmp/bytescrash.exe /tmp/bytescrash.ml 
$ /tmp/bytescrash.exe 
Fatal error: allocation failure during minor GC
Aborted (core dumped)
```

I'm creating a issue rather than a PR, to discuss the preferred fix.
- one option is to make an early  `copy` of `s` which will prevent concurrent changes to the copy
- another option is to switch from `unsafe_set` to safe `set`
- a third option is to bound writing to be within the bounds of the output buffer
- ...

This was a team effort: @ctk21 identified the cause and wrote the independent test case illustrating it. @haesbaert suggested an elegant fix. I just made it crash with a random test... :sweat_smile:

### PR DESCRIPTION
**Pull request by gasche**
Fix for #11508

### CODE REVIEW

**Comment by gasche** [comment]
cc @jmid, @ctk21, @haesbaert

**Comment by gasche** [comment]
Note: the implementation fixed is `Bytes.escaped : bytes -> bytes`. The current implementation of String.escaped first checks if any character needs escaping, if no escaping is necessary it returns the input string (without a copy), ortherwise it returns `Bytes.unsafe_to_string (Bytes.escaped (Bytes.unsafe_of_string s))`. This means that:

- in the fast path where no character needs escaping, the performance profile of both Bytes.escaped and String.escaped is unchanged by this PR
- in the slow path of String.escaped, we perform one extra copy that should not be necessary because no one can correctly mutate the input string (I vaguely remember that in previous discussions we decided that it's okay to break memory-safety if people mutate `string` values?)

I think this is good enough for a "first PR to get things safe, we can always improve later if we want". And yes, I was too lazy to write precise benchmarks for this function -- I think it would be required if we changed the implementation significantly, but not for the "minimal sensible fix' in this PR. Anyone should of course feel free to contribute such benchmarks if they want.

**Comment by haesbaert** [comment]
> Note: the implementation fixed is `Bytes.escaped : bytes -> bytes`. The current implementation of String.escaped first checks if any character needs escaping, if no escaping is necessary it returns the input string (without a copy), ortherwise it returns `Bytes.unsafe_to_string (Bytes.escaped (Bytes.unsafe_of_string s))`. This means that:
> 
> * in the fast path where no character needs escaping, the performance profile of both Bytes.escaped and String.escaped is unchanged by this PR
> * in the slow path of String.escaped, we perform one extra copy that should not be necessary because no one can correctly mutate the input string (I vaguely remember that in previous discussions we decided that it's okay to break memory-safety if people mutate `string` values?)
> 
> I think this is good enough for a "first PR to get things safe, we can always improve later if we want". And yes, I was too lazy to write precise benchmarks for this function -- I think it would be required if we changed the implementation significantly, but not for the "minimal sensible fix' in this PR. Anyone should of course feel free to contribute such benchmarks if they want.

Your diff is 1:1 with what I had in my tree, so LGTM.

**Comment by gasche** [comment]
Well do not hesitate to send a PR next time :-)

**Comment by xavierleroy** [comment]
I'm not too happy about the extra copy.  Again, we're degrading the performance of the standard library just for the benefit of racy user code that should not have been written in the first place.  Could we at least avoid the extra copy for `String.escaped`?

**Comment by c-cube** [comment]
I think I agree with @xavierleroy, I'm confused by what this is trying to achieve. I might be missing the bigger picture, but concurrent modification of `bytes` should fall in the "don't do that" category, no?

**Comment by gasche** [comment]
I updated the PR to avoid the extra copy in String.escaped. This is done by defining the escaping logic in an `unsafe_escape` function shared by both Bytes.escaped and String.escaped. This function is only safe on uniquely-owned byte sequences or on immutable byte sequences, so Bytes.escaped performs a copy but String.escaped does not need to. It is also parametric on whether the returned by sequence may be physically equal to its input (perfectly sensible for String.escaped) or not (Bytes.escaped requires a copy there).

**Comment by gasche** [comment]
@c-cube What this PR is trying to achieve is that type-correct OCaml code using innocuous library functions does not segfault. Currently it is possible to segfault by mutating a byte sequence from a domain and calling `Bytes.escaped` on the same byte sequence from another domain. Doing this is morally wrong (it is not okay to have a write-read race across domains without synchronization) but Multicore OCaml is designed to still provide safety guarantees in this case, which standard library functions must not invalidate.

**Comment by gasche** [comment]
Minor note: I had to tweak the PR because of the `tools/sync_stdlib_docs` tool. Everytime I cross its path its fairly unpleasant boilerplate to deal with, and I'm tempted to claim that the cure is worse than the disease (out-of-sync fooLabels docs) and get rid of it. I have given in on the temptation yet.

**Comment by dbuenzli** [comment]
> Everytime I cross its path its fairly unpleasant boilerplate to deal with, and I'm tempted to claim that the cure is worse than the disease

FWIW I share the sentiment, as I noted there it made preparing #11410 rather inconvenient.

Especially somehow it's easy to forget/realize the machinery actually exists which means you will likely have to start over at least once…

**Comment by gasche** [comment]
The CI is now passing, this PR is ready for reviewing again.

File: stdlib/bytes.ml [hunk 1]
```diff
@@ -167,7 +167,20 @@ let trim s =
...
+     #11508, #11509: This logic would be incorrect in presence of
+     concurrent modification to the input, making the use of
+     [unsafe_set] below memory-unsafe.
+
+     Precondition: This function may be safely called only on
+     immutable or uniquely-owned byte sequences.
+
+     If [share] is true, then we may return the input byte sequence
+     itself when it contains no characters to escape. In all other
+     cases we return a fresh, uniquely-owned byte sequence. *)
```
Comment (xavierleroy) [inline stdlib/bytes.ml]: Unless I'm mistaken, you don't need the two `share` modes and can always do as if `share = false`:
- When called from Bytes.escape, `s` is a fresh copy of the input, uniquely owned, so it can be returned as the result.
- When called from String.escape, `s` is immutable and can be shared with the result.

File: stdlib/string.ml [hunk 2]
```diff
@@ -105,14 +105,10 @@ let trim s =
...
-      match unsafe_get s i with
-      | '\"' | '\\' | '\000'..'\031' | '\127'.. '\255' ->
-          bts (B.escaped (bos s))
-      | _ -> escape_if_needed s n (i+1)
-  in
-  escape_if_needed s (length s) 0
+  let b = bos s in
+  (* We satisfy [unsafe_escape]'s precondition by passing an
+     immutable byte sequence. *)
+  bts (B.unsafe_escape ~share:true b)
```
Comment (xavierleroy) [inline stdlib/string.ml]: Why a `let`?
```
  bts (B.unsafe_escape (bos s))
```
or, more modern
```
  s |> bos |> B.unsafe_escape |> bts
```

**Review by xavierleroy — COMMENTED** [review]
I think this is the right approach, but it still makes one copy too many in the "`Bytes.escaped` / no escape needed" case.  "Shared xor mutable", brother!

File: stdlib/string.ml (hunk 2 above)
Comment (gasche) [reply stdlib/string.ml]: It's purely stylistic, but the comment refers to "an immutable byte sequence" which is `b`. I prefer to refer to a named value defined right above than to a subexpression of a non-trivial computation.

File: stdlib/bytes.ml (hunk 1 above)
Comment (gasche) [reply stdlib/bytes.ml]: Good catch! The comment claims that we return a "fresh" sequence, but I can give the function a stronger specification (in the mutable case) where we consume the ownership of the input, and we return a byte sequence (fresh or not) with its ownership.

**Review by gasche — COMMENTED** [review]
Thanks @xavierleroy, I performed the simplification you suggested.

**Review by xavierleroy — APPROVED** [review]
Looks fine, thanks!

**Comment by xavierleroy** [comment]
Cherry-picked to 5.0: bc6cfe8caa

**Comment by shindere** [comment]
Sorry to arrive that late, I just wanted to ask:

Xavier Leroy (2022/08/27 01:16 -0700):
> Unless I'm mistaken, you don't need the two `share` modes and can always do as if `share = false`:
> - When called from Bytes.escape, `s` is a fresh copy of the input, uniquely owned, so it can be returned as the result.
> - When called from String.escape, `s` is immutable and can be shared with the result.
>
>
> > +  let b = bos s in
> +  (* We satisfy [unsafe_escape]'s precondition by passing an
> +     immutable byte sequence. *)
> +  bts (B.unsafe_escape ~share:true b)

Why bts rather than sob?

**Comment by gasche** [comment]
`sob` means a loud cry in English, so not the best name choice for anything at all. Also, these functions are short hands for `Bytes.unsafe_to_string` (bts) and `Bytes.unsafe_of_string` (bos). (They predate this PR.)
