### PR TITLE
Fix #10271 using Env.remove_last_open

### LINKED ISSUE #10271: [trunk] Bound types via GADT are not resolved when referred via a module
The following test-case succeeds with OCaml 4.12 but fails with trunk (https://github.com/ocaml/ocaml/commit/8b8168ee097aa15e0148816984279220526f970f)
```
$ cat test.ml
module M = struct
  type _ rr = Soa : int rr
  type b = B : 'a rr * 'a -> b
end

let test =
  let M.(B (k, v)) = M.(B (Soa, 0)) in
  match k, v with
  | M.Soa, soa -> (soa : int)
$ ocamlc test.ml
File "test.ml", line 9, characters 19-22:
9 |   | M.Soa, soa -> (soa : int)
                       ^^^
Error: This expression has type $B_'a but an expression was expected of type
         int
       $B_'a is abstract because no corresponding cmi file was found in path.
```
However when we remove the module `M` and move the types at toplevel or only remove the references to `M` in `test` and add an `open M` above, it works.
```
$ cat test.ml
module M = struct
  type _ rr = Soa : int rr
  type b = B : 'a rr * 'a -> b
end

open M

let test =
  let B (k, v) = B (Soa, 0) in
  match k, v with
  | Soa, soa -> (soa : int)
$ ocamlc test.ml
```

### PR DESCRIPTION
**Pull request by garrigue**
Define a new function `Env.remove_last_open` to handle local open in pattern matching.

This should subsume both #10273 and #10299
However, the code is interacting with the structure of `Env.t` in a non trivial way, and requires to remove consistence check in `Env.make_copy_of_types`, so I'm not really comfortable with going this route.

### CODE REVIEW

**Comment by alainfrisch** [comment]
I did not follow the original problems, but wondering: cannot the "remove last open" be considered an explicit operation on environments, stored as such in the summary (instead of filtering it)?

**Comment by garrigue** [comment]
This could be done, and would shorten a bit the code.
But actually using `filter_summary` lets us ensure first that we really opened the module, so that we can then have an assertion failure if the actual environment does not match. So the length of `filter_summary` is not really a problem for me.
My misgiving is rather that we are trying to partially backtrack an environment, when it is in practice simpler to rebuild it from a previous state (i.e. we just need to put back some types and local constraints, discarding all the rest).
So to me this looks like defining a non-existing feature to use a very small part of it, with all the risks of code rot that can come with that (have to think about what is a coherent environment, etc...)

File: typing/env.ml [hunk 1]
```diff
@@ -122,6 +122,9 @@ module TycompTbl =
           bindings for each name, as in comp_labels and
           comp_constrs. *)
 
+      root: Path.t;
```
Comment (lpw25) [inline typing/env.ml:197]: I think we can skip adding this field since you are already checking the path when you find it in the summary.

File: typing/typecore.ml [hunk 2]
```diff
@@ -1958,11 +1958,15 @@ and type_pat_aux
       assert construction_not_used_in_counterexamples;
       let path, new_env =
         !type_open Asttypes.Fresh !env sp.ppat_loc lid in
-      let new_env = ref new_env in
-      type_pat category ~env:new_env p expected_ty ( fun p ->
-        env := Env.copy_local !env ~from:!new_env;
```
Comment (lpw25) [inline typing/typecore.ml:2019]: Since this was the only use of `copy_local`, I think we should remove it from `Env`.

**Review by lpw25 — APPROVED** [review]
This looks much better than `copy_local` to me. Happy to merge this once `copy_local` has been deleted too.

File: typing/env.ml (hunk 1 above)
Comment (garrigue) [reply typing/env.ml:197]: I persist to think that this approach is inherently more fragile, so I'm not going to throw away security nets :-)

File: typing/env.ml [hunk 3]
```diff
@@ -1242,7 +1261,7 @@ let make_copy_of_types env0 =
     IdTbl.map f env0.values
   in
   (fun env ->
-     if env.values != env0.values then fatal_error "Env.make_copy_of_types";
+     (*if env.values != env0.values then fatal_error "Env.make_copy_of_types";*)
```
Comment (garrigue) [inline typing/env.ml:1346]: This assertion fails with `remove_last_open`. Can we replace it with something else?

**Comment by garrigue** [comment]
I have updated the code, avoiding duplication.
If this is still fine, I merge.

**Review by lpw25 — APPROVED** [review]
