### PR TITLE
typing: Fix uncaught Cannot_apply exception

### LINKED ISSUE #14603: "Fatal error: exception Ctype.Cannot_apply" on 5.5.0~alpha1
I'm getting a fatal exception on the recent first alpha release of 5.5.0 that does not occur on 5.4.1.

The most minimal reproducing example I've found is this:

```ocaml
type[@unboxed] 'a foo = { foo : 'b } constraint 'a = 'b * 'c

let bar : 'c. (unit * 'c) foo = { foo = () }
```

The observed output is

```
Fatal error: exception Ctype.Cannot_apply
```

The exception only occurs when the type is unboxed and when `'c` is explicitly annotated "forall" on `bar`.

I hope this is small enough to provide some clue as to the origin!

### PR DESCRIPTION
**Pull request by gasche**
fixes #14603

### CODE REVIEW

**Comment by gasche** [comment]
The repro case from @brandonzstride is as follows:

```ocaml
type[@unboxed] 'a foo = { foo : 'b } constraint 'a = 'b * 'c

let bar : 'c. (unit * 'c) foo = { foo = () }
```

The compilation path for `bar` calls `Typeopt.value_kind` on the type `'c. (unit * 'c) foo`, to understand whether it is known to be an immediate-only type (for example).

- Until 5.4, `value_kind` would stop at the `Tpoly` node for `'c . ...` and return "I don't know".
- In 5.5/trunk, the `Tpoly` node is stripped away and `Typedecl_unboxed.get_unboxed_type_representation` gets called with `(unit * 'c) foo`, and in turn calls `Ctype.apply` to expand the type arguments into the definition of `'foo`. This fails because this `'c` is a Tunivar (introduced by the Tpoly node), and `Ctype.apply` uses unification internally which causes a univar-escape error.
- With this PR, when we see the `Tpoly` node we call `Ctype.instantiate_poly`, to replace the polymorphic variables by `Tvar` copies, so when we get to `(unit * 'c) foo` we have a Tvar for `'c`, so the rest works as it should.

**Comment by smuenzel** [comment]
In `Typedecl_unboxed.get_unboxed_type_representation`  https://github.com/ocaml/ocaml/blob/fe32118ad6b2ca7b5f35ecdc10cc7a129fbe03bd/typing/typedecl_unboxed.ml#L34 , we also strip away a Tpoly node, but I wasn't able to immediately come up with an example where we leave an orphaned universal variable

**Comment by smuenzel** [comment]
This one should fail:

```ocaml
type[@unboxed] 'a foo = { foo : 'b } constraint 'a = 'b * 'c

let bar : 'c . (unit * 'c) foo = { foo = () }

type [@unboxed] 'a t1 = { foo' : 'c . ('a * 'c) foo }

type 'a t0 = 'a t1

type 'a t2 = { t0 : 'a t0 }
```

**Comment by smuenzel** [comment]
Could we add a function to `Ctype` to encapsulate this pattern?
```ocaml
let maybe_instance_poly ty =
  match get_desc ty with
  | Tpoly (ty', tl) -> instance_poly ~keep_names:true tl ty'
  | _ -> ty
```

This could also be used at https://github.com/ocaml/ocaml/blob/fe32118ad6b2ca7b5f35ecdc10cc7a129fbe03bd/typing/typecore.ml#L1206-L1211

**Comment by gasche** [comment]
@smuenzel excellent suggestions, thanks. I integrated them. (This means that you are now a co-author and we need to find a reviewer.)

I feel that we are missing something here: calling `Ctype.instance_poly` liberally is a good way to make the bug go away, but I think that we should be able to do this sort of type-directed optimization by manipulating type expressions that contain Tunivar nodes (if only to avoid the linear traversal to remove them on each Tpoly node). So what I rather want is a version of `Ctype.apply` that can be used on types containing free univars.

I think that the PR as proposed is a nice bugfix and even simplifies/improves a bit on the current implementation, and we can think of changing `get_unboxed_type_representation` to support free univars in a second step.

File: typing/typecore.ml [hunk 1]
```diff
@@ -1203,12 +1203,7 @@ let solve_Ppat_constraint tps loc env sty expected_ty =
   tps.tps_pattern_force <- force :: tps.tps_pattern_force;
   let ty, expected_ty' = instance ty, ty in
   unify_pat_types loc env ty (instance expected_ty);
-  let expected_ty' =
-    match get_desc expected_ty' with
-    | Tpoly (expected_ty', tl) ->
-        instance_poly ~keep_names:true tl expected_ty'
-    | _ -> expected_ty'
-  in
+  let expected_ty' = Ctype.maybe_instance_poly expected_ty' in
```
Comment (Octachron) [inline typing/typecore.ml:1206]: Since `maybe_instance_poly` is an ill-typed function, I would rather avoid using it inside the typechecker itself.

File: typing/typeopt.ml [hunk 2]
```diff
@@ -21,20 +21,18 @@ open Typedtree
...
-  let ty =
-    match get_desc ty with
-    | Tpoly(ty, _) -> ty
-    | _ -> ty
-  in
+  let ty = Ctype.maybe_instance_poly ty in
   match get_desc ty with
   | Tconstr _ ->
       let ty = Ctype.expand_head_opt env ty in
+      let ty = Ctype.maybe_instance_poly ty in
```
Comment (Octachron) [inline typing/typeopt.ml]: An abbreviation cannot be  a polymorphic type, this call is confusing.

File: typing/typecore.ml (hunk 1 above)
Comment (gasche) [reply typing/typecore.ml:1206]: I'm not sure what you mean by "ill-typed", can you elaborate?

My understanding is that it takes a type that may be a polymorphic scheme, and takes a fresh instance of any toplevel-bound polymorphic variable.

File: typing/typeopt.ml (hunk 2 above)
Comment (gasche) [reply typing/typeopt.ml]: My approach in typeopt has been to conservatively assume that any type expression may be a Tpoly, and ensure that any match on `Tconstr` is done on a type where the eventual Tpoly node has been instantiated away. This is a simple strategy that can be checked locally, without structural assumptions on where Tpoly nodes are allowed. (I suspect that these assumptions have a tendency to age badly.)

**Comment by gasche** [comment]
Note: I would not mind a type-level / static distinction between places that are known to allow type schemes and could thus be a Tpoly node, and places that are known to hold monomorphic schemes -- this would be a way to reduce the number of places where we need to wonder about Tpoly. But today we don't have this (and it may prove too invasive/work-intensive). I think the approach in this PR is a reasonable first step to fix the bugs reported and make the code more robust.

File: typing/typecore.ml (hunk 1 above)
Comment (Octachron) [reply typing/typecore.ml:1206]: In a well-typed context, we have a separation of the cases where polymorphic scheme are necessary (function parameters, methods), allowed (top-level definition, record fields) and forbidden (all other contexts).

The `maybe_instance_poly` ignores this separation which seems ok-ish once typechecking is done, but when typechecking ignoring the separation is suspicious (and the instantiation in `solve_Ppat_constraint` is part of the problem solved in #14480 ).

But thinking about it, maybe it is fine to have suspicious function call in a suspicious case.

File: typing/typeopt.ml (hunk 2 above)
Comment (Octachron) [reply typing/typeopt.ml]: Only very specific type expressions can be Tpoly. Pretending to handle cases that violate one of the straigthforward typechecker invariant only make the code harder to understand (because future readers will not have the information that you were being defensive).

Comment (smuenzel) [reply typing/typeopt.ml]: @gasche, if your goal is to prevent future issues as type checker invariants change, maybe having an `assert false` here could alert future PR authors to issues (although it may be too heavyweight to put asserts all over the place in general)

Comment (gasche) [reply typing/typeopt.ml]: I prefer the code with the property that every `Tconstr` match occurs after a easy-to-check-locally `maybe_instance_poly`, but obviously this sentiment is not shared. I don't want to get stuck on this so I removed this line to please @Octachron.

**Review by Octachron — APPROVED** [review]
I agree that overall it is a good idea to instantiate type scheme before pattern matching on type expressions in `Typeopt`.

**Comment by gasche** [comment]
Thanks! I will merge (and cherry-pick in 5.5) when the CI confirms that it is happy.

**Comment by gasche** [comment]
Merged, and cherry-picked in 5.5 as f33d001ee5938a944c651243215b7e967e2df243.
