### PR TITLE
Fix #9695: no error when opening an alias to a missing module

### LINKED ISSUE #9695: usability issue: no error when opening an alias to a missing module
Apparently `open X` does not complain if `X` is an alias to an unknown module and `-no-alias-deps` is used -- it behaves as if it was just ignored. This looks like a usability bug in the compiler to me:

```ocaml
module A = MissingModule
let () = let open A in x

(* $ ocamlc -no-alias-deps test.ml
File "test.ml", line 2, characters 23-24:
2 | let () = let open A in x
                           ^
Error: Unbound value x
*)
```

```ocaml
module A = MissingModule
let () = let open A in ()
(* compiles just fine with -no-alias-deps *)
```

(Note: `open A` at the toplevel behaves in the same surprising way.)

I hit this issue while working on the compiler itself: I had an `open Nativeint`, and below it used the function `to_int`; I would get an "Unbound value `to_int`" because the Makefile .depend file was stale and nativeint was not compiled yet.

This appears to be a regression: OCaml 4.03 to 4.05 (but not later version) reports the following error on both examples:

```
File "test.ml", line 2, characters 18-19:
Error: This is an alias for module MissingModule, which is missing
```

OCaml 4.02.1 (`-no-alias-deps` was introduced in 4.02) reports a worse message:

```
File "test2.ml", line 2, characters 5-6:
Error: This module is not a structure; it has type (module MissingModule)
```

### PR DESCRIPTION
**Pull request by garrigue**
Fix #9695, which was caused by using `Env.get_components` without checking for errors.
Fortunately `Env.get_components_res` does returns errors.

### CODE REVIEW

**Comment by garrigue** [comment]
This is a bug, and the fix is very simple. Please review.

**Review by trefis — DISMISSED** [review]
LGTM.

File: typing/env.ml [hunk 1]
```diff
@@ -2002,9 +2002,10 @@ let add_components slot root env0 comps =
   }
 
 let open_signature slot root env0 =
-  match get_components (find_module_components root env0) with
-  | Functor_comps _ -> None
-  | Structure_comps comps ->
+  match get_components_res (find_module_components root env0) with
+  | Error _
+  | Ok (Functor_comps _) -> None
```
Comment (gasche) [inline typing/env.ml]: `open_pers_signature` right below seems to assume that the only `None` case here is a functor. What should we do now that this assumption is not correct anymore? I am also nervous about the `Env_open` case in envaux.ml which also `assert false` on a `None` result.

Could maybe change the return type from an `option` to something more informative, so that the `Error` cases can be distinguished from the `Functor_comps` case?

`env_from_summary` seems to expect that `open_signature` could also raise the exception `Not_found`. Is this still the case today?

Comment (garrigue) [reply typing/env.ml]: Indeed, lots of stuff broken.
Switch everything to Error + polymorphic variant ?

Comment (trefis) [reply typing/env.ml]: > `env_from_summary` seems to expect that open_signature could also raise the exception Not_found. Is this still the case today?

Callers of `open_pers_signature` make the same assumption. And yes, it can happen: the call to `find_module_components` can raise `Not_found`.

Also, it seems that `open_pers_signature` is only called from `Matching`, on a module which we know not to be an alias.

I have no comment about `env_from_summary`, I guess one would need to compile some files, with one aliasing the other, then try running cmt2annot (or the debugger) after having removed the cmi of the first one?

**Comment by gasche** [comment]
>  Switch everything to Error + polymorphic variant ?

If we want to refactor, I wonder if it really makes sense to have the same functions compute both module components and functor components. Intuitively I would expect callers to either know that they want module components, or know that they want functor components. I think this code would be easier to write and reason about if "Functor" was among the failure cases.

File: typing/env.ml (hunk 1 above)
Comment (garrigue) [reply typing/env.ml]: Ok, turning into a nightmare.
I switched everything to Error.
Now `open_signature` returns ` (Env.t, [``Not_found | ``Functor]) result`, and both the exception `Not_found` and errors in `get_components` are mapped to `Error ``Not_found`

**Comment by garrigue** [comment]
This is not a refactoring, this is a bug fix.
I'm not going to touch to `get_components`, just clarify what `open_signature` is doing.
But this may be a good idea eventually.

**Comment by gasche** [comment]
I like the new code much better, thanks.

I think that it is probably mildly incorrect to squash all `module_components_failure` values into a `Not_found` error: this is not semantically wrong but we lose a lot of precision in the cause of the error. This could probably be fixed as a second iteration.

Could you add the following example to the testsuite?

```
module Test (S : sig module type S end) (M : S.S) = struct open M (* should not succeed silently *) end
```

File: testsuite/tests/typing-modules-bugs/pr9695_bad.ml [hunk 2]
```diff
@@ -0,0 +1,10 @@
+(* TEST
+flags = " -w a -no-alias-deps"
+ocamlc_byte_exit_status = "2"
+* setup-ocamlc.byte-build-env
+** ocamlc.byte
+*** check-ocamlc.byte-output
+*)
```
Comment (gasche) [inline testsuite/tests/typing-modules-bugs/pr9695_bad.ml:7]: Is there a reason for not using an `* expect` test with `flags="-no-alias-deps"`?

**Review by gasche — APPROVED** [review]
The new patch looks good to me.

I  made a minor comment about the test: it would be nice to have it as an expect-test if we can, as they are more readable and easier to maintain.

Feel free to merge whenever this is ready.

File: testsuite/tests/typing-modules-bugs/pr9695_bad.ml (hunk 2 above)
Comment (garrigue) [reply testsuite/tests/typing-modules-bugs/pr9695_bad.ml:7]: I'm not sure that it would work (it seems the top-level errored on the alias rather than on the open)

**Comment by gasche** [comment]
Jacques suggests that we should cherry-pick in 4.11. There is a risk of breaking wrong programs that were silently accepted before, despite an incorrect `open`; which sounds like a good thing as those could have a different semantics if the module becomes available later (due to shadowing). cc @Octachron .

**Comment by Octachron** [comment]
I was curious to see if it is possible to trigger this bug with dune and my favorite `implit_transitive_deps false` option: the answer is positive.

Isn't this error detected by the unused open warning usually?

It seems to me that it would be better to fix this erratic behavior as soon as possible, and thus it makes sense to backport it in 4.11 .

**Comment by gasche** [comment]
Cherry-picked in 4.11 as 6672acbcd8bd55d4abaf87d0401768c91b79f514.

**Comment by hhugo** [comment]
I'm seeing an error with the tip of ocaml/4.11 which seem to be related to that PR. I or @lpw25 will try to produce a repro case soon

**Comment by hhugo** [comment]
The following use to work with 4.10 and no longer does. 
```ocaml
module type S = sig
  module Intf : sig
    module type S
  end
  module Impl : Intf.S
end

module Make (Intf : sig module type S end) (Impl : Intf.S) : S = struct
  module Intf = Intf
  module Impl = Impl
end

module Intf = struct
  module type S = sig
    type t
  end
end
module Impl = struct
  type t
end

module M = Make(Intf)(Impl)
open! M.Impl
```

```
Line 1, characters 6-12:
1 | open! M.Impl;;
          ^^^^^^
Error: This module is not a structure; it has type Make(Intf)(Impl).Intf.S
```

**Comment by hhugo** [comment]
This seems to be the expected behavior. Ignore the previous comment.

**Comment by Octachron** [comment]
In your example, the open was previously a not-so-apparent no-op in 4.10 . Was that also the case in the real code?

**Comment by hhugo** [comment]
apparently

**Comment by gasche** [comment]
As @Octachron is suggesting, my understanding is that the change in this PR revealed another bug, either in the type-checker (which cannot resolve the signature ...S precisely enough) or in your code. In either case, it's probably better that we know about it -- the current post-PR behavior is the better one.

**Comment by Octachron** [comment]
@gasche, the current behavior is the expected one as far as I understand: the signature constraint on the functor result
```ocaml
module Make (Intf : sig module type S end) (Impl : Intf.S) : S = ...
```
makes the module type `Make(Intf)(Impl).Intf.S` abstract.

**Comment by hhugo** [comment]
I believe the code in https://github.com/LaurentMazare/ocaml-dataframe/blob/master/src/dataframe/df.mli#L187 is missing some kind of `with module Open_on_rhs_intf := ...`
Cc @LaurentMazare

**Comment by garrigue** [comment]
Indeed, replacing the return type of `Make` by `S with module Intf = Intf` correctly solves the problem.
