### PR TITLE
Fixed #9207: ocamlyacc can now handle 255 entry points

### LINKED ISSUE #9207: Ocamlyacc: overflow with 128 or more parsers
`ocamlyacc` produces ill-formed `.ml` files if a grammar has 128 or more entrypoints.  
This generated `.ml` file was produced by `ocamlyacc` from a BNFC-generated `.mly` file:
```ocaml
...
let pSuper (lexfun : Lexing.lexbuf -> token) (lexbuf : Lexing.lexbuf) =
   (Parsing.yyparse yytables 126 lexfun lexbuf : Abstest.super)
let pSwitch (lexfun : Lexing.lexbuf -> token) (lexbuf : Lexing.lexbuf) =
   (Parsing.yyparse yytables 127 lexfun lexbuf : Abstest.switch)
let pSynchronized (lexfun : Lexing.lexbuf -> token) (lexbuf : Lexing.lexbuf) =
   (Parsing.yyparse yytables -128 lexfun lexbuf : Abstest.synchronized)
let pTemplate (lexfun : Lexing.lexbuf -> token) (lexbuf : Lexing.lexbuf) =
   (Parsing.yyparse yytables -127 lexfun lexbuf : Abstest.template)
...
```
`ocamlc` reports a type error:
```
File "Partest.ml", line 5129, characters 4-28:
5129 |    (Parsing.yyparse yytables -128 lexfun lexbuf : Abstest.synchronized)
           ^^^^^^^^^^^^^^^^^^^^^^^^
Error: This expression has type
         int -> (Lexing.lexbuf -> 'a) -> Lexing.lexbuf -> 'b
       but an expression was expected of type int
```
The buggy `.ml` code is produced by this print statement:
https://github.com/ocaml/ocaml/blob/4e6e9123287405a08b349c3e0e12d53000e8534d/yacc/reader.c#L1701-L1703
Seems like the `entry` component of the `bucket` type was (needlessly?) dimensioned to bytesize, not catering for values >=128:
https://github.com/ocaml/ocaml/blob/4e6e9123287405a08b349c3e0e12d53000e8534d/yacc/defs.h#L137-L150

I attach a `.mly` file created from this MWE BNFC file:
```
EInt. Exp ::= Integer;
coercions Exp 127;
```
[Par128entrypoints.mly.zip](https://github.com/ocaml/ocaml/files/3997930/Par128entrypoints.mly.zip)

### PR DESCRIPTION
**Pull request by andreasabel**
The previous promised limit of ocamlyacc was 256 entry points, the
actual limit was 127 due to representation of bucket->entry as char.
Switching to unsigned char extends the limit to 255.

I introduced a constant MAX_ENTRY_POINT as a synonym of MAXCHAR to
handle checks against the limit consistently over the different modules
of ocamlyacc.

Extensions beyond 255 entry points would require a bit more work (which
looks unrewarding) since there is an assumption in the implementation
that the octal representation of an entry point fits into 3 digits.

- [x] Documentation: the upper limit on entry points was not documented in the man page, so I did not edit the man pages.
- [x] Testing: I did not find a comprehensive testsuite in place for ocamlyacc, thus, I did not add any tests. The existing test (singular) runs fine.

Merry Christmas!

### CODE REVIEW

File: yacc/defs.h [hunk 1]
```diff
@@ -145,10 +145,16 @@ struct bucket
...
     char assoc;
-    char entry;
+    unsigned char entry;  /* 1..MAX_ENTRY_POINT (0 for unassigned) */
     char true_token;
 };
 
+/* MAX_ENTRY_POINT is the maximal number of entry points into the grammar. */
+/* Entry points are identified by a non-zero byte in the input stream,     */
+/* so there are at most 255 entry points.                                  */
+
```
Comment (xavierleroy) [inline yacc/defs.h:155]: I updated the comment to explain the source for this limitation to 255 entry points.

File: yacc/defs.h [hunk 2]
```diff
@@ -145,10 +145,16 @@ struct bucket
     short prec;
     char class;
     char assoc;
-    char entry;
+    unsigned char entry;  /* 1..MAX_ENTRY_POINT (0 for unassigned) */
     char true_token;
```
Comment (xavierleroy) [inline yacc/defs.h:149]: The missing `unsigned` is the root of the issue, indeed.

**Review by xavierleroy — APPROVED** [review]
Looks good to me.  Thanks for the patch.  I updated a comment directly, so that this can be merged promptly.

File: Changes [hunk 3]
```diff
@@ -74,8 +74,8 @@ Working version
   (Gabriel Scherer, review by Armaël Guéneau)
 
 * #9207: fix ocamlyacc to work correctly with up to 255 entry points
```
Comment (dra27) [inline Changes:76]: The fix isn’t breaking, so this wants to be `-` (not near my laptop, or I’d just push it!)

Comment (xavierleroy) [reply Changes:76]: Well spotted, thanks.  Corrected in 584b1429e
