### PR TITLE
Give 'while true do e done' a polymorphic type

### LINKED ISSUE #11805: More general type for "while true do ... done".
I often find myself writing loops that are only exited via an exception, for example when reading a file:
```ocaml
let input_lines : in_channel -> string list = fun ic ->
  let lines = ref [] in
  try while true do
    lines := input_line ic :: !lines
  done; assert false with End_of_file ->
  List.rev !lines
```
However, as you can see in the example above, one needs to write something like `while true do ... done; assert false`, even though the loop can never be exited normally.

Would it make sense to have a special case for `while true do ... done` in type-inference, so that it is given a weakly-polymorphic type?

### PR DESCRIPTION
**Pull request by yallop**
Closes #11805.

While loops usually have type `unit`, but as a special case,
```ocaml
while true do e done
```
is now given a polymorphic type, avoiding the need to follow it with unreachable code to appease the typechecker.  For example, in this example from the manual:

```ocaml
try while true do
    let y = f !x in
    if !x = y then raise Done else x := y
 done; assert false
 done
with Done -> !x;;
```

the `assert false` is no longer necessary.

~~Note: by default, code following a `while true do e done`, such as `assert false` in the example above, will now result in a `[nonreturning-statement]` warning.~~

### CODE REVIEW

File: Changes [hunk 1]
```diff
@@ -3,6 +3,9 @@ Working version
 
 ### Language features:
 
+* #12295: Give `while true' a polymorphic type, similarly to 'assert false'
```
Comment (nojb) [inline Changes]: The initial single quotes are different in both quotations :)

**Review by nojb — APPROVED** [review]
The patch is simple enough that I feel confident approving it. Do I understand correctly that the bootstrap is necessary because of warning 21?

**Comment by gasche** [comment]
I am worried about the compatibility impact of the new `[nonreturning-statement]` warning locations:
- if users fix the warning, they get code that is incompatible with previous OCaml releases
- the warning is quite useful in general in detecting dead code, and we don't want to encourage people to disable it globally

Could we consider silencing the warning in this specific case for the next few releases? We would re-enable it later, at a point where most users will have migrated to OCaml versions supporting the new typing rule. (So: the final state would be simple and intuitive, and we would have small kludge during a transition period.)

**Comment by gasche** [comment]
Another option is for users to disable the warning locally using an attribute, but this makes their code uglier due to a change they are not responsible for. I don't like it.

**Comment by yallop** [comment]
@nojb:
> Do I understand correctly that the bootstrap is necessary because of warning 21?

Yes, that's right.

@gasche:
> Could we consider silencing the warning in this specific case for the next few releases? 

That's a good idea.  I've implemented that behaviour: the `[nonreturning-statement]` is now disabled for `while` loops.

File: Changes (hunk 1 above)
Comment (yallop) [reply Changes]: Thanks! Now fixed.  I've also listed reviewers and reporters.

**Comment by nojb** [comment]
@gasche are you happy with the current state of the PR?

File: typing/typecore.ml [hunk 2]
```diff
@@ -4999,10 +5004,16 @@ and type_construct env loc lid sarg ty_expected_explained attrs =
 (* Typing of statements (expressions whose values are discarded) *)
 
 and type_statement ?explanation env sexp =
+  let allow_polymorphic e = match e.pexp_desc with
+    | Pexp_while _ -> true
```
Comment (gasche) [inline typing/typecore.ml:5021]: I would prefer if we had a code comment that explains why we are special-casing this construct. In particular, the comment should explicitly mention the version where it was added, so that we can decide (when we meet this part of the code again in N years) whether it is time to remove the special case.

**Review by gasche — APPROVED** [review]
Very nice, thanks!

**Comment by Alizter** [comment]
I was staring at this for a while trying to work out what was intended. Could we leave a comment mentioning that this doesn't compile on older versions?

File: toplevel/topcommon.ml [hunk 3]
```diff
@@ -233,8 +233,7 @@ let read_input_default prompt buffer len =
       Buffer.add_char phrase_buffer c;
       incr i;
       if c = '\n' then raise Exit;
-    done;
-    (!i, false)
+    done
```
Comment (Alizter) [inline toplevel/topcommon.ml:236]: Specifically here.

**Comment by polytypic** [comment]
Well, this basically causes new warnings to be emitted in cases that were just fine previously.

Here is an example from Kcas:

```ocaml
        (* ... *)
        try
          if must_be_done_in_this_tx then
            (* If the old buckets have already been accessed, we cannot perform
               rehashing outside of the transaction.  In this case rehashing
               becomes linearithmic, O(n*log(n)), because that is the best that
               the transaction log promises.  However, as we access the bucket
               locations mostly in order, we often actually get linear time,
               O(n), performance. *)
            let initial_state = Array.length old_buckets in
            while true do
              (* If state is modified outside our expensive tx would fail. *)
              if Loc.fenceless_get state != initial_state then Retry.invalid ();
              rehash_a_few_buckets ~xt
            done
          else
            (* When possible, rehashing is performed cooperatively a few buckets
               at a time.  This gives expected linear time, O(n). *)
            while true do
              Xt.commit { tx = rehash_a_few_buckets }
            done;
          r
        with Done -> r
        (* ... *)
```

The above two `while true` loops are terminated by exceptions by design. The above didn't give a warning earlier, but with `5.2.0+trunk` it does:

```
File "src/kcas_data/hashtbl.ml", lines 237-241, characters 12-16:
237 | ............while true do
238 |               (* If state is modified outside our expensive tx would fail. *)
239 |               if Loc.fenceless_get state != initial_state then Retry.invalid ();
240 |               rehash_a_few_buckets ~xt
241 |             done
Error (warning 21 [nonreturning-statement]): this statement never returns (or has an unsound type.)
```

With `5.2.0+trunk` one can fix this by removing the redundant return of `r` (second to last line).  Unfortunately that doesn't work with earlier compilers.  So, to portably avoid the warning one needs to e.g. add a `(if ... : unit)` annotation or e.g. `ignore @@` before the `if ...`, which is kind of annoying.

This change gives me mixed feelings.  This kind of  special case typing is rather weird in OCaml and unfortunately it will likely give quite a few warnings from code that was considered just fine earlier.

Did you consider the alternative of introducing new syntax?

For example, I suspect that `while do ... done` would be parseable, where the condition expression is eliminated.

**Comment by nojb** [comment]
@polytypic: it was decided to disable the `nonreturning-statement` warning when `while true do ... done` is followed by another expression in a sequence to avoid breaking code such as `while true do ... done; assert false` that, indeed, is quite common. However, in your example, `while true do ... done` appears as a branch of a conditional, so this logic does not kick in... Perhaps it should? cc @yallop 

Having said that, my feeling is that such cases (`while do ... done` appearing as a branch of a conditional) are relatively uncommon, so I don't expect a _lot_ of breakage from it (but of course, this is hardly a consolation if you are affected :))

> Did you consider the alternative of introducing new syntax?

If you dig through the history of this issue via the reference at the top of this PR, you will see that indeed such possibilities were discussed, but no consensus was reached.

**Comment by yallop** [comment]
> So, to portably avoid the warning one needs to e.g. add a `(if ... : unit)` annotation or e.g. `ignore @@` before the `if ...`, which is kind of annoying.

Does adding `[@warning "-21"]` to the sequence (i.e. `(if ... ; r)[@warning "-21"]` address the problem, too?  It still involves a code change, of course, but disabling new warnings using warning annotations might be less annoying.

**Comment by gasche** [comment]
I think that this issue is caused by the typed-directed nature of the warning, which makes it difficult to reliably disable for a specific syntactic construct. Here the issue is with `(if ... then while-true else while-true); rest`, but we also have an issue with, for example `(let .. in while-true); rest`. I did not notice this problem when reviewing @yallop's implementation of the warning-disabling heuristic.

**Comment by polytypic** [comment]
After trying a couple of alternatives, I'm now planning to go with moving the (unnecessary) return of `r` inside both branches:

```ocaml
if ... then begin
  while true do
    ...
  done;
  r
end
else begin
  while true do
    ...
  done;
  r
end
```

This is not the most concise way to avoid the warning, but it exploits the (additional) special case to avoid the warning.

Adding the annotation e.g.

```ocaml
        (* ... *)
        try[@warning "-21"]
          if must_be_done_in_this_tx then
            (* If the old buckets have already been accessed, we cannot perform
        (* ... *)
```

does disable the warning, but I'd prefer not to disable warnings.

I kind of like the new typing as it can make code simpler.

Unfortunately one cannot really take advantage of the new typing for a long time (unless targeting >= 5.2 is ok) and one may also have to introduce workarounds for it.

**Comment by yallop** [comment]
> I think that this issue is caused by the typed-directed nature of the warning, which makes it difficult to reliably disable for a specific syntactic construct.

I think it's possible to do a bit better.  I'll send a PR shortly.

**Comment by yallop** [comment]
@polytypic: the change in #12568 should allow your existing code to compile without warnings in 5.2.0
