### PR TITLE
#13263: fix escaping of true and false in printing functions

### LINKED ISSUE #13263: Printing issue of reserved keywords
Currently the mechanism for printing reserved identifiers that are keywords is broken with keywords that are values :

For example in the toplevel :
```ocaml
# let x = Bool.(false)
val x : Bool.t = Bool.\#false
```

This is problematic because `Bool.\#false` is undefined.

### PR DESCRIPTION
**Pull request by Octachron**
Both `true` and `false` should not be escaped using the raw identifier syntax if they appear in a context where a variant constructor is expected.  For instance, in

```ocaml
let x = true 0
```
we don't want to escape `true` in
>```
>Error: The constructor true expects 0 argument(s),
>       but is applied here to 1 argument(s)
>```

Similarly, it is better to print `Path.To.(true)` as `Path.To.(true)` and not `Path.To.true` nor `Path.To.\#true`.

This PRs tweak the constructor printer in `Oprint` to handle this last case and adds a specific printer for `variant constructor longident` for error messages in `Pprintast`.

Along the way, it removes a backpatched printer in `Env` that has not been needed since the implementation of the `longident` printers has moved to `Pprintast` rather than `Printtyp`, and it fixes a missing `inline code` tag in a nearby error message.

Close #13263

### CODE REVIEW

File: parsing/pprintast.ml [hunk 1]
```diff
@@ -146,7 +155,8 @@ module Doc = struct
   *)
   let nominal_exp t =
     let open Format_doc.Doc in
-    let longident l = Format_doc.doc_printer longident l.Location.txt in
+    let longident ?(is_constr=false) l =
+      Format_doc.doc_printer (any_longident ~is_constr) l.Location.txt in
```
Comment (gasche) [inline parsing/pprintast.ml:159]: Nitpick: I would re-declare `longident` and `constr` here.

File: typing/typecore.ml [hunk 2]
```diff
@@ -6783,13 +6783,16 @@ let report_error ~loc env = function
   | Name_type_mismatch (kind, lid, tp, tpl) ->
       let type_name = Datatype_kind.type_name kind in
       let name = Datatype_kind.label_name kind in
+      let pr = match kind with
+        | Datatype_kind.Record -> quoted_longident
+        | Datatype_kind.Variant -> quoted_constr
```
Comment (gasche) [inline typing/typecore.ml:6788]: It smells a bit weird to me to handle record field labels and constructor variant labels differently here. I understand that `true` and `false` are variant constructors and not record fields, but I would vote for handling them in the same way here unless this creates issues.

**Review by gasche — APPROVED** [review]
This looks okay and it does improve the testsuite output. I made a few nitpick comments.

File: typing/typecore.ml (hunk 2 above)
Comment (Octachron) [reply typing/typecore.ml:6788]: The point is that  with raw identifiers `true` is now both a valid record field and a valid constructor, but the record field must be escaped
```ocaml
type r = { \#true: int }
```
whereas the variant constructor must be left unescaped
```ocaml
type s = true
```

In practice, the variant case doesn't happen because this error path is only reachable with qualified name, and
`M.true` is a syntax error.

Comment (gasche) [reply typing/typecore.ml:6788]: I guess that the root of evil here is to pretend that the constructor `true` is an identifier; things would be simpler if reserved keywords also had reserved AST constructs.

Comment (Octachron) [reply typing/typecore.ml:6788]: Another option would be to forbid `\#true` and `\#false` because according to OCaml lexing rule `true` and `false` clearly start with a capital letter.

Comment (gasche) [reply typing/typecore.ml:6788]: I think that this would also be perfectly reasonable. I have no opinion and I think that not showing `\#true` in real-world programs is probably more important than precisely how we deal with oddball programs, so I would follow your preference.

Comment (Octachron) [reply typing/typecore.ml:6788]: I am inclined to fix first the printing bugs with this PR and continue the discussion later in #13246 .
