### PR TITLE
Refactor caml_c_thread_(un)register to fix various bugs

### LINKED ISSUE #12773: TSan-reported race in tests/parallel/test_c_thread_register.ml
When using a TSan-enabled compiler, `tests/parallel/test_c_thread_register.ml` fails, but not on every run, with TSan reporting a use-after-free, which is probably a race.

```
==================
WARNING: ThreadSanitizer: heap-use-after-free (pid=1442508)
  Read of size 8 at 0x7bb400000000 by thread T3 (mutexes: write M78):
    #0 scan_stack_frames runtime/fiber.c:243 (test_c_thread_register.opt+0x10428d)
    #1 caml_scan_stack runtime/fiber.c:284 (test_c_thread_register.opt+0x10428d)
    #2 caml_do_local_roots runtime/roots.c:69 (test_c_thread_register.opt+0x123fcb)
    #3 caml_thread_scan_roots /home/miod/git/ocaml.tsan/otherlibs/systhreads/st_stubs.c:174 (test_c_thread_register.opt+0xddb2a)
    #4 caml_empty_minor_heap_promote runtime/minor_gc.c:611 (test_c_thread_register.opt+0x120b66)
    #5 caml_stw_empty_minor_heap_no_major_slice runtime/minor_gc.c:742 (test_c_thread_register.opt+0x121008)
    #6 caml_stw_empty_minor_heap runtime/minor_gc.c:773 (test_c_thread_register.opt+0x1212e9)
    #7 stw_handler runtime/domain.c:1362 (test_c_thread_register.opt+0xfd411)
    #8 handle_incoming runtime/domain.c:335 (test_c_thread_register.opt+0xfd411)
    #9 caml_handle_incoming_interrupts runtime/domain.c:348 (test_c_thread_register.opt+0xfd64d)
    #10 backup_thread_func runtime/domain.c:998 (test_c_thread_register.opt+0xfd64d)

  Previous write of size 8 at 0x7bb400000000 by thread T4 (mutexes: write M78):
    #0 free ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:711 (libtsan.so.0+0x37ab8)
    #1 caml_stat_free runtime/memory.c:645 (test_c_thread_register.opt+0x11ef17)
    #2 caml_free_stack runtime/fiber.c:582 (test_c_thread_register.opt+0x104be7)
    #3 caml_thread_free_info /home/miod/git/ocaml.tsan/otherlibs/systhreads/st_stubs.c:320 (test_c_thread_register.opt+0xdeac3)
    #4 caml_thread_remove_and_free /home/miod/git/ocaml.tsan/otherlibs/systhreads/st_stubs.c:359 (test_c_thread_register.opt+0xdf04b)
    #5 caml_c_thread_unregister /home/miod/git/ocaml.tsan/otherlibs/systhreads/st_stubs.c:708 (test_c_thread_register.opt+0xdfa3a)
    #6 thread_func <null> (test_c_thread_register.opt+0xececa)

  Mutex M78 (0x5603ee6b2448) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1227 (libtsan.so.0+0x4bee1)
    #1 caml_plat_mutex_init runtime/platform.c:55 (test_c_thread_register.opt+0x1230fa)
    #2 caml_init_domains runtime/domain.c:916 (test_c_thread_register.opt+0xfc50e)
    #3 caml_init_gc runtime/gc_ctrl.c:348 (test_c_thread_register.opt+0x108e53)
    #4 caml_startup_common runtime/startup_nat.c:111 (test_c_thread_register.opt+0x1357c7)
    #5 caml_startup_common runtime/startup_nat.c:88 (test_c_thread_register.opt+0x1357c7)
    #6 caml_startup_exn runtime/startup_nat.c:139 (test_c_thread_register.opt+0x13598b)
    #7 caml_startup runtime/startup_nat.c:144 (test_c_thread_register.opt+0x13598b)
    #8 caml_main runtime/startup_nat.c:151 (test_c_thread_register.opt+0x13598b)
    #9 main runtime/main.c:37 (test_c_thread_register.opt+0x659c9)

  Thread T3 (tid=1442513, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
    #1 install_backup_thread runtime/domain.c:1064 (test_c_thread_register.opt+0xfae6a)
    #2 install_backup_thread runtime/domain.c:1273 (test_c_thread_register.opt+0xfe037)
    #3 caml_domain_spawn runtime/domain.c:1270 (test_c_thread_register.opt+0xfe037)
    #4 caml_c_call <null> (test_c_thread_register.opt+0x135fd3)
    #5 camlStdlib__Domain.spawn_701 <null> (test_c_thread_register.opt+0xacf26)
    #6 camlTest_c_thread_register.entry <null> (test_c_thread_register.opt+0x6845c)
    #7 caml_program <null> (test_c_thread_register.opt+0x65f39)
    #8 caml_start_program <null> (test_c_thread_register.opt+0x1360ef)
    #9 caml_startup_common runtime/startup_nat.c:132 (test_c_thread_register.opt+0x1358e0)
    #10 caml_startup_common runtime/startup_nat.c:88 (test_c_thread_register.opt+0x1358e0)
    #11 caml_startup_exn runtime/startup_nat.c:139 (test_c_thread_register.opt+0x13598b)
    #12 caml_startup runtime/startup_nat.c:144 (test_c_thread_register.opt+0x13598b)
    #13 caml_main runtime/startup_nat.c:151 (test_c_thread_register.opt+0x13598b)
    #14 main runtime/main.c:37 (test_c_thread_register.opt+0x659c9)

  Thread T4 (tid=1442514, finished) created by thread T1 at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
    #1 spawn_thread <null> (test_c_thread_register.opt+0xecf43)
    #2 caml_c_call <null> (test_c_thread_register.opt+0x135fd3)
    #3 camlTest_c_thread_register.fun_358 <null> (test_c_thread_register.opt+0x68388)
    #4 camlStdlib__Domain.body_706 <null> (test_c_thread_register.opt+0xad00f)
    #5 caml_start_program <null> (test_c_thread_register.opt+0x1360ef)
    #6 caml_callback_exn runtime/callback.c:200 (test_c_thread_register.opt+0xf8333)
    #7 domain_thread_func runtime/domain.c:1187 (test_c_thread_register.opt+0xfc7ab)

SUMMARY: ThreadSanitizer: heap-use-after-free runtime/fiber.c:243 in scan_stack_frames
==================
==================
WARNING: ThreadSanitizer: heap-use-after-free (pid=1442508)
  Read of size 8 at 0x7bb400000010 by thread T3 (mutexes: write M78):
    #0 scan_stack_frames runtime/fiber.c:247 (test_c_thread_register.opt+0x1042a1)
    #1 caml_scan_stack runtime/fiber.c:284 (test_c_thread_register.opt+0x1042a1)
    #2 caml_do_local_roots runtime/roots.c:69 (test_c_thread_register.opt+0x123fcb)
    #3 caml_thread_scan_roots /home/miod/git/ocaml.tsan/otherlibs/systhreads/st_stubs.c:174 (test_c_thread_register.opt+0xddb2a)
    #4 caml_empty_minor_heap_promote runtime/minor_gc.c:611 (test_c_thread_register.opt+0x120b66)
    #5 caml_stw_empty_minor_heap_no_major_slice runtime/minor_gc.c:742 (test_c_thread_register.opt+0x121008)
    #6 caml_stw_empty_minor_heap runtime/minor_gc.c:773 (test_c_thread_register.opt+0x1212e9)
    #7 stw_handler runtime/domain.c:1362 (test_c_thread_register.opt+0xfd411)
    #8 handle_incoming runtime/domain.c:335 (test_c_thread_register.opt+0xfd411)
    #9 caml_handle_incoming_interrupts runtime/domain.c:348 (test_c_thread_register.opt+0xfd64d)
    #10 backup_thread_func runtime/domain.c:998 (test_c_thread_register.opt+0xfd64d)

  Previous write of size 8 at 0x7bb400000010 by thread T4 (mutexes: write M78):
    #0 free ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:711 (libtsan.so.0+0x37ab8)
    #1 caml_stat_free runtime/memory.c:645 (test_c_thread_register.opt+0x11ef17)
    #2 caml_free_stack runtime/fiber.c:582 (test_c_thread_register.opt+0x104be7)
    #3 caml_thread_free_info /home/miod/git/ocaml.tsan/otherlibs/systhreads/st_stubs.c:320 (test_c_thread_register.opt+0xdeac3)
    #4 caml_thread_remove_and_free /home/miod/git/ocaml.tsan/otherlibs/systhreads/st_stubs.c:359 (test_c_thread_register.opt+0xdf04b)
    #5 caml_c_thread_unregister /home/miod/git/ocaml.tsan/otherlibs/systhreads/st_stubs.c:708 (test_c_thread_register.opt+0xdfa3a)
    #6 thread_func <null> (test_c_thread_register.opt+0xececa)

  Mutex M78 (0x5603ee6b2448) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1227 (libtsan.so.0+0x4bee1)
    #1 caml_plat_mutex_init runtime/platform.c:55 (test_c_thread_register.opt+0x1230fa)
    #2 caml_init_domains runtime/domain.c:916 (test_c_thread_register.opt+0xfc50e)
    #3 caml_init_gc runtime/gc_ctrl.c:348 (test_c_thread_register.opt+0x108e53)
    #4 caml_startup_common runtime/startup_nat.c:111 (test_c_thread_register.opt+0x1357c7)
    #5 caml_startup_common runtime/startup_nat.c:88 (test_c_thread_register.opt+0x1357c7)
    #6 caml_startup_exn runtime/startup_nat.c:139 (test_c_thread_register.opt+0x13598b)
    #7 caml_startup runtime/startup_nat.c:144 (test_c_thread_register.opt+0x13598b)
    #8 caml_main runtime/startup_nat.c:151 (test_c_thread_register.opt+0x13598b)
    #9 main runtime/main.c:37 (test_c_thread_register.opt+0x659c9)

  Thread T3 (tid=1442513, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
    #1 install_backup_thread runtime/domain.c:1064 (test_c_thread_register.opt+0xfae6a)
    #2 install_backup_thread runtime/domain.c:1273 (test_c_thread_register.opt+0xfe037)
    #3 caml_domain_spawn runtime/domain.c:1270 (test_c_thread_register.opt+0xfe037)
    #4 caml_c_call <null> (test_c_thread_register.opt+0x135fd3)
    #5 camlStdlib__Domain.spawn_701 <null> (test_c_thread_register.opt+0xacf26)
    #6 camlTest_c_thread_register.entry <null> (test_c_thread_register.opt+0x6845c)
    #7 caml_program <null> (test_c_thread_register.opt+0x65f39)
    #8 caml_start_program <null> (test_c_thread_register.opt+0x1360ef)
    #9 caml_startup_common runtime/startup_nat.c:132 (test_c_thread_register.opt+0x1358e0)
    #10 caml_startup_common runtime/startup_nat.c:88 (test_c_thread_register.opt+0x1358e0)
    #11 caml_startup_exn runtime/startup_nat.c:139 (test_c_thread_register.opt+0x13598b)
    #12 caml_startup runtime/startup_nat.c:144 (test_c_thread_register.opt+0x13598b)
    #13 caml_main runtime/startup_nat.c:151 (test_c_thread_register.opt+0x13598b)
    #14 main runtime/main.c:37 (test_c_thread_register.opt+0x659c9)

  Thread T4 (tid=1442514, finished) created by thread T1 at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:969 (libtsan.so.0+0x605b8)
    #1 spawn_thread <null> (test_c_thread_register.opt+0xecf43)
    #2 caml_c_call <null> (test_c_thread_register.opt+0x135fd3)
    #3 camlTest_c_thread_register.fun_358 <null> (test_c_thread_register.opt+0x68388)
    #4 camlStdlib__Domain.body_706 <null> (test_c_thread_register.opt+0xad00f)
    #5 caml_start_program <null> (test_c_thread_register.opt+0x1360ef)
    #6 caml_callback_exn runtime/callback.c:200 (test_c_thread_register.opt+0xf8333)
    #7 domain_thread_func runtime/domain.c:1187 (test_c_thread_register.opt+0xfc7ab)

SUMMARY: ThreadSanitizer: heap-use-after-free runtime/fiber.c:247 in scan_stack_frames
==================
```

Steps to reproduce:
```
git reset --hard <REVISION_TO_TEST>;
./configure --enable-tsan && make && cd testsuite && env KEEP_TEST_DIR_ON_SUCCESS=1 make one TEST=tests/parallel/test_c_thread_register.ml;
timeout 60 sh -c 'while ./_ocamltest/tests/parallel/test_c_thread_register/ocamlopt.byte/test_c_thread_register.opt ; do true; done'; test $? -eq 124
```

With a head of trunk at `9b059b1e7a66e9d2f04d892a4de34c418cd96f69`, I have not been able to trigger the TSan report.
With a head of trunk at `b4308a0c74070116a5fb27b07e1c15f099c2c0e3`, I have been able to trigger it at least once in ten runs.

This hints to a subtle regression introduced by #12318. This does not mean that particular change is faulty, but it might make an existing race occur more easily than prior to that change.

### PR DESCRIPTION
**Pull request by gadmm**
Another systhread rabbit-hole: `caml_c_thread_(un)register`. In order to make it better understandable, I refactored it in order to share code with thread_new, thread_start and thread_stop. Differences between thread_new+thread_start and c_thread_register are subtle and come down to when is the GC available to allocate the thread descriptor. ~We could share even more code if we change a few details, I can share some idea if someone has the time to implement it.~

I think several bugs are fixed by this refactor:

- Fix #12773 : Missing restore (via @Johan511 & #12830)
- Fix calling c_thread_register without having initialized systhreads
- Fix invalid raising of exception and leak if tick thread is not created
- Fix missing `memprof_delete_thread`s
- Fix situation where the main thread tries to stop before the registered C thread (?)
- Fix missing signal stack

### CODE REVIEW

**Comment by gadmm** [comment]
Effort has been made to let this PR be reviewed commit-per-commit.

**Comment by gadmm** [comment]
Another discrepancy: in case of an uncaught exception,  `caml_fatal_uncaught_exception` is called and the program stops. This is in contrast with regular systhreads: in case of an uncaught exception, the thread stops and an error is output on stderr, and `Thread.set_uncaught_exception_handler` is obeyed.

**Review by ghost — APPROVED** [review]
Good work! This looks more readable to me, and should help preventing introducing new bugs or inconsistencies in the future.

I can confirm I can no longer reproduce the sporadic failure encountered in `parallel/test_c_thread_register.ml` on this branch.

**Comment by gasche** [comment]
@dustanddreams I'm thankful for your review (I was worried of ending up being the reviewer by lack of any other volunteer), but I am surprised that you managed to do a full review of this tricky code without asking any question / for any clarification or with no particular improvement to suggest. Is the code really that nice, or are you adverse to nitpicking?

**Comment by ghost** [comment]
> Is the code really that nice, or are you adverse to nitpicking?

The individual commits were simple enough and self-contained to be able to assess the impact of each of them.

**Comment by gadmm** [comment]
Thanks for the review.

It is indeed tricky code if we consider that we cannot rely on the current state of the code, so a global review could be useful in addition of a commit-per-commit review. Some of the bugs look big-if-true (e.g. missing altsigstack) so a helpful method @gasche could be for each bug listed, to confirm that there was a bug, and to convince oneself that it is fixed correctly in this PR. This would make a cross-review that would usefully increase confidence in this code.

File: otherlibs/systhreads/st_stubs.c [hunk 1]
```diff
@@ -703,9 +706,15 @@ CAMLexport int caml_c_thread_register(void)
     Tick_thread_running = 1;
   }
 
-  /* Release the master lock */
-  thread_lock_release(Dom_c_threads);
+  /* Release the domain lock the regular way. Note: we cannot receive
+     an exception here. */
+  caml_enter_blocking_section_no_pending();
```
Comment (gasche) [inline otherlibs/systhreads/st_stubs.c:721]: At this point there are many ways offered to "enter blocking section" or "release the runtime lock", including this one or `thread_lock_release` but also `caml_thread_enter_blocking_section`. I'm a bit lost as to which does what. Can you explain why `caml_enter_blocking_section(_no_pending)` is the right one to use here, and maybe include this explanation in the comment on lines 709-710?

File: otherlibs/systhreads/st_stubs.c [hunk 2]
```diff
@@ -661,42 +683,39 @@ CAMLprim value caml_thread_new(value clos)
...
-  /* Allocate the thread descriptor on the heap */
+  /* Create tick thread if not already done */
+  st_retcode err = create_tick_thread();
+  if (err != 0) goto out_err;
+
+  /* Set a thread info block */
+  caml_thread_t th = thread_alloc_and_add();
+  /* If it fails, we release the lock and return an error. */
+  if (th == NULL) goto out_err;
+  thread_init_current(th);
```
Comment (gasche) [inline otherlibs/systhreads/st_stubs.c:715]: I am missing something here. My reading of the code suggest that `thread_alloc_and_add` returns thread info block with an uninitialized runtime state (all fields are 0/NULL), and then `thread_init_current` calls `restore_runtime_state(th)` which "restores" this unitialized runtime state into `Caml_state`, resulting in a domain in an incorrect state.

I would naively expect a new thread to somehow get a valid `Caml_state` (this could be done by `caml_init_domain_self` for example), and then start by *saving* this valid runtime state in the thread info block.

**Comment by gasche** [comment]
This PR introduces a `detach_from_runtime` abstraction that I like, and in particular it makes the final code of `unregister` very simple. On the other hand, the current `register` implementation is not symmetric, it remains messy. Could we maybe introduce an `attach_to_runtime` function that would serve a symmetric purpose?

File: otherlibs/systhreads/st_stubs.c (hunk 1 above)
Comment (gasche) [reply otherlibs/systhreads/st_stubs.c:721]: One thing that is confusing to me is that "thread lock" and "domain lock" are two notions that are not orthogonal but overlapping. In particular, if I understand correctly, `thread_lock_release` eventually calls `caml_release_domain_lock` (among other things).

Reading this code, I have no clear idea whether one of the following holds:
1. in the success path, the stuff that occurs before `caml_enter_blocking_section` sums up to the equivalent of what `thread_lock_release` would have done, so we end up with something that is equivalent to a well-bracketed acquisition and release of the thread lock, or
2. in the success path, the code is doing *less* than what `thread_lock_release` would have done, because the point is to keep ownership of *something* after the function returns

(My bet would be that (1) holds, that those `caml_c_{register,unregister}` functions are expected to be called from foreign threads that are not "active" in any respect with regard to the OCaml runtime (or equivalently, that can run concurrently with the runtime or OCaml mutators), and preserve this property on exit.)

File: otherlibs/systhreads/st_stubs.c (hunk 2 above)
Comment (gasche) [reply otherlibs/systhreads/st_stubs.c:715]: (Ah: maybe it is fine if the domain is in an invalid state, because we are giving up control so immediately another thread will be activated and restore its own (valid) state?)

**Comment by jmid** [comment]
FYI, I've given this PR a spin on [`multicoretests`](https://github.com/ocaml-multicore/multicoretests) as a stress test. It triggered
- an instance of #12230 under MinGW bytecode
- an instance of the fatal error from #12855 under MinGW native code

~~(none of which are related to this PR)~~ (actually I had a small hope of the PR fixing the former)
 and otherwise held up nicely!

**Comment by gadmm** [comment]
Thanks everyone, I might get back to this in January! Have nice holidays.

File: otherlibs/systhreads/st_stubs.c (hunk 1 above)
Comment (gadmm) [reply otherlibs/systhreads/st_stubs.c:721]: Indeed the two functions must be intimate of the details of the relationship the thread lock and the domain lock. The goal is to construct and destruct an "OCaml" thread from scratch which is why it deals with the details of acquiring/releasing the lock. Out of the four locking operations, though, two should be straightforward. If the C thread is correctly attached to the domain, then one can call caml_enter_blocking_section at the end of having attached it, and caml_leave_blocking_section at the beginning of detaching it. Indeed the point is to have a thread with which caml_enter/leave_blocking_section are functional. I think the current comment meant to explain this is clear enough, but this might be more clear when reading the code directly rather than from the diff.

File: otherlibs/systhreads/st_stubs.c (hunk 2 above)
Comment (gadmm) [reply otherlibs/systhreads/st_stubs.c:715]: This is a bit counter-intuitive, but the thread info _is_ initialized with a valid runtime state indeed. I added a comment to clarify this in a new commit.

In reviewing this fact, I have found that I do not understand the initialization of `th->trap_barrier_off` which is in discrepancy with that in `domain_create`. This needs to be reviewed by someone knowledgeable before merging. (See the temporary `TODO` comment.)

(All this initialization between domain_create and caml_thread_new_info could be further factored, but I won't be doing this here.)

Sorry for piling up the commits, but upon the review you prompted, I fixed another issue with error handling in `caml_thread_new_info`, whereby the NULL return value of allocated memprof state was ignored.

**Comment by gadmm** [comment]
> This PR introduces a `detach_from_runtime` abstraction that I like, and in particular it makes the final code of `unregister` very simple. On the other hand, the current `register` implementation is not symmetric, it remains messy. Could we maybe introduce an `attach_to_runtime` function that would serve a symmetric purpose?

It is factored as much as possible. (Well, I could move `create_tick_thread` into `thread_alloc_and_add`, but this would change the error message in the cases where creating the tick thread fails. It's up for discussion.)

There is an inextricable difference between the two ways to attach a new thread. It is essential in one that the thread descriptor is allocated before creating the thread, while in the other, it must be allocated while attaching the thread. The details of when the GC is available are tricky.

**Comment by gadmm** [comment]
This PR is a bugfix candidate for 5.2. Do you think this could arrive in time, or should I target 5.3 instead?

File: otherlibs/systhreads/st_stubs.c [hunk 3]
```diff
@@ -298,12 +303,11 @@ static caml_thread_t caml_thread_new_info(void)
 
 #ifndef NATIVE_CODE
   th->trap_sp_off = 1;
-  th->trap_barrier_off = 2;
+  th->trap_barrier_off = 2; /* TODO: 0? trap_barrier_block? */
   th->external_raise = NULL;
```
Comment (gasche) [inline otherlibs/systhreads/st_stubs.c:308]: @dustanddreams would you by chance be able to dive into this `trap_barrier_off` business and give an opinion on what would be best here?

For now I think that keeping the current behavior unchanged with the TODO question is okay, so we *could* merge the PR without clarification if useful to make progress, but it would of course be nicer to answer the question.

**Review by gasche — APPROVED** [review]
I read the code, made some suggestions, and haven't found any important issue. I am happy to approve this bugfix PR and move towards merging in 5.2 -- I will wait a bit in case @gadmm or others want to discuss further changes.

File: otherlibs/systhreads/st_stubs.c (hunk 3 above)
Comment (gadmm) [reply otherlibs/systhreads/st_stubs.c:308]: cc also @fabbing who presented an impressive detailed account of how exception handling works, hence they might be familiar with this already.

Comment (gadmm) [reply otherlibs/systhreads/st_stubs.c:308]: (The question is why is there a discrepancy—the only one—with `domain_create` here.)

Comment (ghost) [reply otherlibs/systhreads/st_stubs.c:308]: I don't know why there is such a discrepancy here. I think `caml_thread_new_info` should definitely initialize `trap_barrier_block` to `-1` here, and I also think setting `trap_barrier_off` to `0` rather than `2` in `domain_create` would make sense, unless this was done on purpose to prevent barriers from firing too early in a domain's life (in which case a comment explaining that rationale would have been nice).

Comment (gadmm) [reply otherlibs/systhreads/st_stubs.c:308]: Thanks a lot for your analysis.

I see that these fields were not there in OCaml 4. They are new, including this initialization code.

So it is worth fixing quickly. A fix would need a second person to review (not me). Hence I recommend fixing it separately and leave the TODO in the code (and create a new issue about it/add it to the systhread issue).

Comment (gasche) [reply otherlibs/systhreads/st_stubs.c:308]: I agree with your analysis and am willing to merge the PR, but you need to rebase it first. This is a bugfix PR, so you should include it in the 5.2 section.

Comment (ghost) [reply otherlibs/systhreads/st_stubs.c:308]: > So it is worth fixing quickly. A fix would need a second person to review (not me). Hence I recommend fixing it separately and leave the TODO in the code (and create a new issue about it/add it to the systhread issue).

There should be two TODO then, one in `caml_thread_new_info` regarding the non-initialization of `trap_barrier_block` and one in `domain_create` regarding the initialization of `trap_barrier_off`.

Comment (fabbing) [reply otherlibs/systhreads/st_stubs.c:308]: I also think `trap_barrier_block` should be initialized to `-1`.
But, if my understanding is correct, `trap_barrier_off` should stay initialized to `2`, to avoid triggering a trap when reaching the default exception handler (as guessed from https://github.com/gadmm/ocaml/blob/f00e977cc5779fa73c42a0db5bcb112de7f16237/runtime/debugger.c#L248). Also this constant is expected in this computation: https://github.com/gadmm/ocaml/blob/f00e977cc5779fa73c42a0db5bcb112de7f16237/runtime/interp.c#L157

Comment (gadmm) [reply otherlibs/systhreads/st_stubs.c:308]: @dustanddreams As far I can see, `trap_barrier_off` is already initialized to 0 inside `domain_create`. Did you mean something different?

Comment (gadmm) [reply otherlibs/systhreads/st_stubs.c:308]: Thanks @fabbing and @dustanddreams, I'll simply keep the TODO as is for now.

**Comment by gadmm** [comment]
I just rebased.

File: otherlibs/systhreads/st_stubs.c (hunk 3 above)
Comment (gadmm) [reply otherlibs/systhreads/st_stubs.c:308]: This issue is now recorded as part of #12399 with a link to the present discussion
