### PR TITLE
Fix caml_sys_time on Windows

### LINKED ISSUE #7469: Sys.time returns wall-clock elapsed time on Windows not CPU time
**Original bug ID:** 7469
**Reporter:** @dra27
**Assigned to:** @dra27
**Status:** assigned (set by @dra27 on 2017-01-27T17:48:39Z)
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Version:** 4.05.0 +dev/beta1/beta2/beta3/rc1
**Target version:** later
**Category:** runtime system and C interface

## Bug description

The clock function in the Microsoft CRT returns wall clock and not CPU time.

## Steps to reproduce

See https://msdn.microsoft.com/en-us/library/4e2ess30.aspx

## Additional information

GetProcessTimes should give a value closer to getrusage(RUSAGE_SELF, ...)

### PR DESCRIPTION
**Pull request by dra27**
Now returns processor time instead of wall clock time (MSCRT clock function doesn't conform with ISO C)

Fixes #7469

### CODE REVIEW

**Comment by gasche** [comment]
Do we have a volunteer to review this, @nojb maybe?

File: runtime/caml/osdeps.h [hunk 1]
```diff
@@ -19,6 +19,8 @@
 #define CAML_OSDEPS_H
 
 #ifdef _WIN32
+#include <time.h>
```
Comment (dra27) [inline runtime/caml/osdeps.h:22]: I wasn't keen on this addition (at least it's inside `_WIN32`) but it seemed more palatable than even more `#ifdef _WIN32` in sys.c

File: runtime/win32.c [hunk 2]
```diff
@@ -1019,3 +1019,26 @@ int caml_num_rows_fd(int fd)
...
+
+  tmp.u.LowPart = stime.dwLowDateTime;
+  tmp.u.HighPart = stime.dwHighDateTime;
+  total = tmp.QuadPart;
+  tmp.u.LowPart = utime.dwLowDateTime;
+  tmp.u.HighPart = utime.dwHighDateTime;
+  total += tmp.QuadPart;
+
+  /* total in 100-nanosecond intervals (1e7 / CLOCKS_PER_SEC) */
+  clocks_per_sec = INT64_LITERAL(10000000U) / (ULONGLONG)CLOCKS_PER_SEC;
```
Comment (nojb) [inline runtime/win32.c:1042]: Naive question: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getprocesstimes says
> All times are expressed using FILETIME data structures. Such a structure contains two 32-bit values that combine to form a 64-bit count of 100-nanosecond time units.

which I interpret to mean that the units of `total` is 100-nanoseconds (`1e-7` seconds). I would then expect `clocks_per_sec` to be simply `INT64_LITERAL(10000000U)`.

I don't understand what `CLOCKS_PER_SEC` is doing here. What am I missing?

**Review by nojb — APPROVED** [review]
LGTM, modulo a point in the arithmetic which I don't see right away.

File: runtime/win32.c (hunk 2 above)
Comment (dra27) [reply runtime/win32.c:1042]: I've found that there's no such thing as naïve where time is concerned!

`CLOCKS_PER_SEC` is the number of `clock_t`s in a second, so the return value of `GetProcessTimes` needs to be divided by (1e7 / CLOCKS_PER_SEC) to convert it... assuming I haven't messed up my arithmetic (which is highly possible!)

Comment (nojb) [reply runtime/win32.c:1042]: Ah, I see it now, this function is supposed to return `clock_t`'s, not seconds. Thanks!

**Comment by dra27** [comment]
Thanks, @nojb!
