### PR TITLE
fix -dsource printing of the pattern (A as x | (B as x))

### LINKED ISSUE #9999: dsource prints as-patterns inside or-patterns incorrectly
The output is missing some parentheses. Example:

```
$ ocamlc -version
4.11.1

$ cat foo.ml
let () =
  match `A with
  | (`A as x) | (`B as x) -> ignore x

$ ocamlc foo.ml -dsource
let () = match `A with | `A as x|`B as x -> ignore x

$ ocamlc foo.ml -dsource 2> foo.p.ml
$ ocamlc foo.p.ml
File "foo.p.ml", line 1, characters 25-35:
1 | let () = match `A with | `A as x|`B as x -> ignore x
                             ^^^^^^^^^^
Error: Variable x must occur on both sides of this | pattern
```

This is because the output is interpreted as if parenthesized as

```
let () = match `A with | (`A as x|`B) as x -> ignore x
```

because of the relative precedence of `|` and `as`.

### PR DESCRIPTION
**Pull request by gasche**
fixes #9999

### CODE REVIEW

File: parsing/pprintast.ml [hunk 1]
```diff
@@ -397,22 +397,34 @@ and core_type1 ctxt f x =
...
+  let rec left_associative x acc = match x with
+    | {ppat_desc=Ppat_or (p1,p2); ppat_attributes = []} ->
+        left_associative p1 (p2 :: acc)
+    | x -> x :: acc
+  in
+  match left_associative x [] with
+  | [] -> assert false
+  | [x] -> pattern1 ctxt f x
+  | orpats ->
+      pp f "@[<hov0>%a@]" (list ~sep:"@,|" (pattern1 ctxt)) orpats
```
Comment (Octachron) [inline parsing/pprintast.ml]: I personally prefer "@ | ` to match the spaces used in pattern cases.

File: parsing/pprintast.ml [hunk 2]
```diff
@@ -397,22 +397,34 @@ and core_type1 ctxt f x =
...
   end
   else match x.ppat_desc with
     | Ppat_alias (p, s) ->
-        pp f "@[<2>%a@;as@;%a@]" (pattern ctxt) p protect_ident s.txt (* RA*)
-    | Ppat_or _ -> (* *)
-        pp f "@[<hov0>%a@]" (list ~sep:"@,|" (pattern ctxt))
-          (list_of_pattern [] x)
-    | _ -> pattern1 ctxt f x
+        pp f "@[<2>%a@;as@;%a@]"
+          (* we do not use pattern_or here: it would be correct
```
Comment (Octachron) [inline parsing/pprintast.ml]: Using `pattern` like before would be correct too, since `_ as x as y` is valid.

**Review by Octachron — APPROVED** [review]
The code looks good to me. The problems with nested `as` inside or-patterns is fixed. The new code adds some unnecessary parentheses in corner cases, but they probably increase readability.

File: parsing/pprintast.ml (hunk 1 above)
Comment (gasche) [reply parsing/pprintast.ml]: Hmm okay. Are you sure this will only improve pretty-printing? (I don't know what the input changes will be; I used `@,|` as it was in the previous code.)

File: parsing/pprintast.ml (hunk 2 above)
Comment (gasche) [reply parsing/pprintast.ml]: Yes, `pattern` was incorrect before due to the pretense that `as` and `|` had the same priority. Now that the two levels are split it would be correct again (this was the main point of the change). I am not completely sure which is better. `pattern` has a more standard structure, but I find the printing for `A | B as x` very confusing.

Note: if we wanted to avoid the parentheses in `(A as x) | B`, we would need a different, wicked change, namely handling another layer of Ppat_alias inside the leftmost or-pattern (this would not be `pattern`, but a rule that allows `alias` and is below `pattern_or`.)

Comment (gasche) [reply parsing/pprintast.ml]: On the second thought, I may go with `pattern` again. I like that it lets me remove a comment, and also `A | B as x` has the upper-side that (although it is confusing) the "natural" interpretation is ill-scoped, so people have to understand its meaning to be able to interpret it at all.

File: parsing/pprintast.ml (hunk 1 above)
Comment (Octachron) [reply parsing/pprintast.ml]: It is a strictly personal preference for white spaces and `A x | B x | C x` rather than `A x|B x|C x`

**Comment by jhjourdan** [comment]
BTW, congrats, it's PR#10000 !

**Comment by gasche** [comment]
@Octachron I changed the PR as suggested. Thanks for the nice review.

**Comment by gasche** [comment]
I merged in trunk and cherry-picked in 4.12 ( 2736fde7b672f581af6b36113feae9826ba2afaa ). Thanks @aantron for the bug report.

@Octachron: before writing the present PR I was not aware that the monster-testfile `parsetree/source.ml` was hand-maintained and not an automatically generated file. It contains a lot of copies of tests from the testsuite. This sounds like a Bad Idea (tm). Do we have a plan? (cc @damiendoligez @alainfrisch)
