### PR TITLE
#8917, printtyp: fix printing of nested recursive definitions

### LINKED ISSUE #8917: printtyp: incorrect name disambiguation
```
        OCaml version 4.08.0

# module B = struct type t end;;
module B : sig type t end
# module type S = sig module rec A : sig type t = B.t end and B : sig type t end end;;
module type S =
  sig module rec A : sig type t = B/2.t end and B : sig type t end end
```
When reading this, I expect `B/2` to be the module not part of the recursive group (otherwise why would it disambiguate?).

However, that is not the case:
```
# module F (X : S) = struct let f (x : X.A.t) : X.B.t = x end;;
module F : functor (X : S) -> sig val f : X.A.t -> X.B.t end
```

cc @Octachron

### PR DESCRIPTION
**Pull request by Octachron**
This PR fixes disambiguation issue when printing nested recursive definitions. For instance,
```OCaml
module A= struct end
module type s = sig
  module rec A: sig type t end
  and B: sig type t = A.t end
end
```
is currently printed as

> module A : sig  end
module type s =
  sig module rec A : sig type t end and B : sig type t = A/2.t end end

because the printing code forgets about `A` when it enters the recursive definition of `t`.

This PR solves this issue by making the management of state in `Printtyp` more cautious (and maybe more straightforward).

The first commit is mostly preparatory: it reorganizes the printing code for signature by splitting it in three phases:

* identification of syntactic signature items (class (and private variant) definitions generate ghost signature items)
* identification of recursive groups (to hide some types inside of their recursive definitions)
* printing.

The second commit is the fix itself which backtracks some of the printer state after the printing of signature items rather than erasing them.

The fourth commit simplifies the printer code by using the notion of syntactic item for private variant definitions. 

The last two commits are refactoring commits that align the management of the naming context state with the rest of the printer state inside signature.

Closes #8917

### CODE REVIEW

**Comment by gasche** [comment]
The first commit has a commit message that says "split print_signature in three phases". This is much less informative than what you say in the PR:

>  - identification of syntactic signature items (class (and private variant) definitions generate ghost signature items)
> - identification of recursive groups (to hide some types inside of their recursive definitions)
> printing

I believe it would be nice to add this information to the commit message. (It *is* sort of clear what is happening if one looks at the *end* of the patch first, but this is too much guessing.)

File: typing/printtyp.ml [hunk 1]
```diff
@@ -1578,46 +1569,55 @@ let hide ids env = List.fold_right
...
-      | Some (id, r, k ) when r = recs -> id :: get_ids Trec_next (skip k rem)
-      | _ -> [] in
-  List.iter Naming_context.add_protected (get_ids Trec_first items)
+let group_syntactic_items x =
+  let rec group acc = function
+    | Sig_class _ as src :: ctydecl :: tydecl1 :: tydecl2 :: rem ->
+        group ({src; ghosts = [ctydecl; tydecl1; tydecl2]}::acc) rem
+    | Sig_class_type _ as src :: tydecl1 :: tydecl2 :: rem ->
+        group ({src; ghosts = [tydecl1; tydecl2]}::acc) rem
+    | src :: rem -> group ({src; ghosts=[]}::acc) rem
```
Comment (gasche) [inline typing/printtyp.ml]: could this pattern be made non-fragile by listing the `src` cases?

File: typing/printtyp.ml [hunk 2]
```diff
@@ -1578,46 +1569,55 @@ let hide ids env = List.fold_right
...
-let still_in_type_group env' in_type_group item =
-  match in_type_group, recursive_sigitem item with
-  | true, Some (_,Trec_next,_) -> true
-  | _, Some (_, (Trec_not | Trec_first),_) ->
-      stop_type_group env' ; true
-  | _ -> stop_type_group env'; false
+let recursive_sigitem = function
+  | Sig_class(id,_,rs,_) | Sig_class_type (id,_,rs,_) | Sig_type(id, _, rs, _)
+  | Sig_module(id, _, _, rs, _) -> Some (id,rs)
+  | _ -> None
```
Comment (gasche) [inline typing/printtyp.ml]: Could this pattern be made non-fragile?

File: typing/printtyp.ml [hunk 3]
```diff
@@ -1578,46 +1569,55 @@ let hide ids env = List.fold_right
...
+      | Some (id, (Trec_first | Trec_next) )  -> in_group [id] [elt] acc rest
+  and in_group ids group acc = function
+  | [] ->  List.rev (rec_group ids group :: acc)
+  | elt :: rest ->
+      match recursive_sigitem elt.src with
+      | None | Some (_,Trec_not) ->
+          not_in_group (Not_rec elt::rec_group ids group::acc) rest
+      | Some (id, Trec_first)  ->
+          in_group [id] [elt] (rec_group ids group :: acc) rest
+      | Some (id, Trec_next) -> in_group (id::ids) (elt::group) acc rest in
```
Comment (gasche) [inline typing/printtyp.ml]: I believe you could write this as follows if you like:

```ocaml
| elt::rest ->
  begin (*!*) match recursive_sigitem elt.src with
  | Some (id, Trec_next) -> 
    in_group (id::ids) (elt::group) acc rest
  | None | Some (_, (Trec_not | Trec_first)) ->
    not_in_group (rec_group ids group :: acc) (elt :: rest)
  end
```

File: typing/printtyp.ml [hunk 4]
```diff
@@ -1638,19 +1638,37 @@ let rec tree_of_modtype ?(ellipsis=false) = function
...
-      protect_rec_items items;
-      reset_naming_context ();
-      let trees = trees_of_sigitem item in
-      let env' = Env.add_signature (item :: sg) env' in
-      trees @ tree_of_signature_rec env' in_type_group rem
+  wrap_env (fun env -> env)
+    (tree_of_signature_rec (fun _ (_,x) -> x) !printing_env) sg
+
+and tree_of_signature_rec : 'r. (_->_->'r) -> _ -> _ -> 'r list
+  = fun decorate env' sg ->
```
Comment (gasche) [inline typing/printtyp.ml]: I spent a bit of time stuck trying to understand what `decorate` means besides "the thing that lets me factorize the other piece of code at the end". I believe that a better way to do this would be to change the type of `tree_of_signature_rec` (and `..._sigitem_group`) to return, instead of an `out_sig_item list`, an `(env * sig_item * out_sig_item) list`, and let the two callers map on this result for post-processing.

File: typing/printtyp.ml [hunk 5]
```diff
@@ -1638,19 +1638,37 @@ let rec tree_of_modtype ?(ellipsis=false) = function
...
+  let structured = group_recursive_items (group_syntactic_items sg) in
+  let collect_trees_of_rec_group (env,trees) group =
+    let env', more_trees = trees_of_recursive_sigitem_group env group in
+    let more_trees = List.map (decorate env) more_trees in
+    set_printing_env env';
+    env', more_trees :: trees in
```
Comment (gasche) [inline typing/printtyp.ml]: This is not due to your refactoring (it was already there), but I find it confusing that this code passes `env` around as a pure state-passing program *and* mutates the printing state at the same time. If I read the (new) code correctly, it is always the case that whenever `trees_of_recursive_sigitem_group` is called with an `env` parameter, then this `env` input is equal to `!printing_env`. If that is indeed true, could we drop the env-passing here, and have `trees_of_recursive_sigitem_group` just take the group as input, read `input_env` and call `set_printing_env` before returning?

(Maybe this belong to a separate commit or PR.)

**Review by gasche — COMMENTED** [review]
I am two-thirds-of-the-way trough the review of the first commit, and I have the impression that I should yield now and look at the rest later. (Maybe there are a bit too many things going on in the first commit. :-)

File: typing/printtyp.ml [hunk 6]
```diff
@@ -1638,19 +1638,37 @@ let rec tree_of_modtype ?(ellipsis=false) = function
...
-      let env' = Env.add_signature (item :: sg) env' in
-      trees @ tree_of_signature_rec env' in_type_group rem
+  wrap_env (fun env -> env)
+    (tree_of_signature_rec (fun _ (_,x) -> x) !printing_env) sg
+
+and tree_of_signature_rec : 'r. (_->_->'r) -> _ -> _ -> 'r list
+  = fun decorate env' sg ->
+  let structured = group_recursive_items (group_syntactic_items sg) in
+  let collect_trees_of_rec_group (env,trees) group =
+    let env', more_trees = trees_of_recursive_sigitem_group env group in
```
Comment (gasche) [inline typing/printtyp.ml]: I find the name `more_trees` confusing. Initially I thought that this was a recursive function that would return an output for some part of the input it consumed, and then rest of the input. I think that `group_trees` would be a better name. 

Note:  with the no-env-passing suggestion you could also get rid of the fold style, use `List.concat_map`, and thus just call it `trees` if you wished.

File: typing/printtyp.ml [hunk 7]
```diff
@@ -1638,19 +1638,37 @@ let rec tree_of_modtype ?(ellipsis=false) = function
...
+and trees_of_recursive_sigitem_group env group =
+  let display x =
+    reset_naming_context ();
+    List.map (fun y -> x.src,y) (trees_of_sigitem x.src) in
+  match group with
+  | Not_rec x -> add_sigitem env x, display x
+  | Rec_group (ids,items) ->
+      let is_type = match items with
+        | {src=Sig_type _; _ } :: _ -> true
+        | _ -> false  in
```
Comment (gasche) [inline typing/printtyp.ml]: This code makes the assumption (compared to the previous code) that if one item of a recursive group is a `Sig_type` declaration, then all items are types. Are we sure this is true? (I *think* it currently is true.) One could also *not* make this assumption by collecting the `ids` to hide with a `filter_map`.

File: typing/printtyp.ml (hunk 5 above)
Comment (gasche) [reply typing/printtyp.ml]: Now that I reviewed `trees_of_recursive_sigitem_group` as well, I am not convinced anymore than pushing the state-setting logic there is the right idea, because in that function state-passing is natural. (We don't want to call `set_printing_env` more than once for efficiency reasons.) It could stay here, but still doesn't need to be a fold.

**Review by gasche — COMMENTED** [review]
I am now done reviewing the first commit, and I believe that it is correct. It gets rid of code that is really arcane...

File: typing/printtyp.ml [hunk 8]
```diff
@@ -1581,6 +1578,10 @@ type rec_item_group =
   | Not_rec of syntactic_sig_item
   | Rec_group of (Ident.t list * syntactic_sig_item list)
 
+let with_hidden_items ~is_type ids f =
+  if is_type && not !Clflags.real_paths then
+    wrap_env (hide ids) (Naming_context.with_hidden ids f)
+  else Naming_context.with_hidden ids f
```
Comment (gasche) [inline typing/printtyp.ml]: The code of this function is short, but it is a tricky piece of code. I wish you would give a name to the first wrapper, for example `with_hidden_in_printing_env`, and avoid the duplication, so that the structure is clear.

File: typing/printtyp.ml [hunk 9]
```diff
@@ -1581,6 +1578,10 @@ type rec_item_group =
   | Not_rec of syntactic_sig_item
   | Rec_group of (Ident.t list * syntactic_sig_item list)
 
+let with_hidden_items ~is_type ids f =
+  if is_type && not !Clflags.real_paths then
+    wrap_env (hide ids) (Naming_context.with_hidden ids f)
```
Comment (gasche) [inline typing/printtyp.ml]: I am worried about the potential performance impact of `wrap_env`, which is calling `set_printing_env` twice instead of once. I understand that this is key to fixing your bug, but it is also known to be a performance-sensitive aspect of the type-checker. I would like to either:
- convince myself that `wrap_env` is not in fact used much more than before (but I am skeptical here), or
- get a performance test in a short-path-sensitive scenario (I don't know how to do this, but Leo, Fred or Thomas would know), or
- ensure that `wrap_env` does not cost, by caching the short-path-related state across `wrap_env` instead of recomputing it (this should probably be a separate, preliminary PR)

**Review by gasche — COMMENTED** [review]
I reviewed the second commit and I understand what it changes to the code: currently, calls to `hide_rec_items` permanently affect the printing state, while the new code ensure that they are reverted after the printing of each recursive group.

One thing I don't fully understand is why it fixes the bug on the example in the PR. What is the call to `hide_rec_items` that was the source of the problem? The explanation I can think of is that we have a problem at the end of the `type t` single-element group within `A`, but that should result in `t` remaining hidden, while you mention that the code "forgets about `A`". Why would `t` remaining hidden result in the `A/2.t` printing?

(Note: the previous commit also changed the way `hide_rec_items` is called, by calling it once per group instead of once for each item. I asked myself whether the bug could also have been caused, before, by not-resetting after printing the `A` item. But I don't think that is how it works, because printing B would have started by hiding the exact same items.)
After thinking about it more, I believe that the bug on this specific example may have been actually fixed by the previous commit, by ensuring that `hide_rec_items` is called once for the whole group A/B, and not once for A and once for B (and then it was the call on A which was problematic). Is that correct?

File: typing/printtyp.ml (hunk 9 above)
Comment (Octachron) [reply typing/printtyp.ml]: I think grouping together the printing environment and short-path states could work well. Then, it would be simpler to cache both at the same time.

File: typing/printtyp.ml (hunk 2 above)
Comment (Octachron) [reply typing/printtyp.ml]: Fixed.

File: typing/printtyp.ml (hunk 3 above)
Comment (Octachron) [reply typing/printtyp.ml]: This is a little bit simpler indeed.

File: typing/printtyp.ml (hunk 4 above)
Comment (Octachron) [reply typing/printtyp.ml]: I used a slightly more structured output: an  ` (env * (sig_item * out_sig_item) list) list)`.

File: typing/printtyp.ml (hunk 5 above)
Comment (Octachron) [reply typing/printtyp.ml]: I removed the duplicated handling of env here.

File: typing/printtyp.ml (hunk 7 above)
Comment (Octachron) [reply typing/printtyp.ml]: Class recursive group can contains types. At the end, it was simpler to be less clever here and let the hidding functions handle this part.

File: typing/printtyp.ml (hunk 8 above)
Comment (Octachron) [reply typing/printtyp.ml]: I am not completely convinced, but why not?

File: typing/printtyp.ml (hunk 9 above)
Comment (Octachron) [reply typing/printtyp.ml]: I added the caching, in a separate commit, I am not completely sure if it necessary to split it from this PR.

File: typing/printtyp.ml (hunk 6 above)
Comment (Octachron) [reply typing/printtyp.ml]: Renamed to group_trees.

File: typing/printtyp.ml (hunk 9 above)
Comment (gasche) [reply typing/printtyp.ml]: I would prefer to review this caching as a first separate PR that the printing changes builds on. This is a sensitive change that needs to be reviewed carefully, and it will be yet another occasion to gently ping @lpw25 on the short-paths reimplementation.

Comment (gasche) [reply typing/printtyp.ml]: @Octachron I could be convinced to try to do the separating-the-PRs work next week if you are indeed in holidays during that time. Let me know if that would help.

Comment (Octachron) [reply typing/printtyp.ml]: I should have some time  to split the commit by by the end of the week.

Comment (gasche) [reply typing/printtyp.ml]: (gentle ping: you might have a time window open to split the PRs between 4.11.1 and 4.11.2.)

Comment (gasche) [reply typing/printtyp.ml]: This has now be done, the caching logic was reviewed and merged (#9889).

File: typing/printtyp.ml [hunk 10]
```diff
@@ -1745,16 +1745,16 @@ and tree_of_signature sg =
 
 and tree_of_signature_rec env' sg =
   let structured = group_recursive_items (group_syntactic_items sg) in
-  let collect_trees_of_rec_group (env,trees) group =
+  let collect_trees_of_rec_group group =
+    let env = !printing_env in
     let env', group_trees =
       Naming_context.with_ctx (fun () ->
-          trees_of_recursive_sigitem_group env group
+          trees_of_recursive_sigitem_group !printing_env group
```
Comment (gasche) [inline typing/printtyp.ml]: why not use `env` here?

File: typing/printtyp.ml [hunk 11]
```diff
@@ -1659,14 +1659,19 @@ let with_hidden_items ~is_type ids f =
...
-    | [] -> List.rev acc in
-  group [] x
+        remove_row ({src; ghosts = ghosts @ [tydecl1; tydecl2]}::acc) rem
+    | src :: rem -> remove_row ({src; ghosts} :: acc) rem
+    | [] -> List.rev acc
+  and remove_row acc = function
+    | Sig_type(id,_,_,_) as row :: rest when is_row_name (Ident.name id) ->
+        group ~ghosts:[row] ~acc rest
+    | rest -> group ~ghosts:[] ~acc rest in
+  remove_row [] x
```
Comment (gasche) [inline typing/printtyp.ml]: I'm not sure about the change in this function.

1. It's a minor point, but `ghosts @ [...]` is a code smell that sticks out in the code. In this case it is fine as `ghosts` is a zero- or one-element list, but having a way to write this code without it would still be nice. (I hope that there is a very different way to write this function.)
2. The previous `group` function had the property that the `syntactic_sig_item` records generated would respect the source order, in the sense that the `src` phrase would always come before the `ghosts` phrases, which would themselves be in source order. If I understand the code here correctly, this property is broken, as row-name Sig_type will be attached as ghost items to the *following* syntactic item in source order. This is weird.

Do I correctly guess that row-type declarations are emitted *before* the type they were generated from? That would justify some of (2), but I would still prefer to have a distinction in the "syntactic sig item" between ghost-before and ghost-after items. I would find it clearer and more reassuring, even though it may not make a difference for printing proper.

I hope there is a better way to write this grouping function where the control flow and output ordering are clearer and easier to reason about.

File: typing/printtyp.ml [hunk 12]
```diff
@@ -1738,7 +1738,10 @@ and tree_of_signature_rec : 'r. (_->_->'r) -> _ -> _ -> 'r list
   = fun decorate env' sg ->
   let structured = group_recursive_items (group_syntactic_items sg) in
   let collect_trees_of_rec_group (env,trees) group =
-    let env', more_trees = trees_of_recursive_sigitem_group env group in
+    let env', more_trees =
+      Naming_context.with_ctx (fun () ->
+          trees_of_recursive_sigitem_group env group
+        ) in
```
Comment (gasche) [inline typing/printtyp.ml]: Commit message nitpick: "less backtrack*ing*", and I would write "once *per* group" rather than "once by group".

File: typing/printtyp.ml [hunk 13]
```diff
@@ -1747,16 +1750,15 @@ and tree_of_signature_rec : 'r. (_->_->'r) -> _ -> _ -> 'r list
...
-  match group with
-  | Not_rec x -> add_sigitem env x, [display x]
-  | Rec_group (ids,items) ->
-      let is_type = match items with
-        | {src=Sig_type _; _ } :: _ -> true
-        | _ -> false  in
-      List.fold_left add_sigitem env items,
-      with_hidden_items ~is_type ids (List.map display) items
+  let display x =  x.src, tree_of_sigitem x.src in
+      match group with
```
Comment (gasche) [inline typing/printtyp.ml]: I don't particularly care but the indentation is weird here, probably a mistake.

File: typing/printtyp.ml [hunk 14]
```diff
@@ -1656,11 +1656,13 @@ type syntactic_sig_item =
   { src: Types.signature_item; ghosts: Types.signature_item list }
 type rec_item_group =
   | Not_rec of syntactic_sig_item
-  | Rec_group of (Ident.t list * syntactic_sig_item list)
+  | Rec_group of ( (bool * Ident.t) list * syntactic_sig_item list)
```
Comment (gasche) [inline typing/printtyp.ml]: On the value-construction side, booleans are not very informative. It would make sense to use a proper record here.

File: typing/printtyp.ml [hunk 15]
```diff
@@ -1670,7 +1670,11 @@ let group_syntactic_items x =
         remove_row (s_elt :: acc) rem
     | Sig_class_type _ as src :: tydecl1 :: tydecl2 :: rem ->
         remove_row ({src; ghosts = ghosts @ [tydecl1; tydecl2]}::acc) rem
-    | src :: rem -> remove_row ({src; ghosts} :: acc) rem
+    | [Sig_class _] | [Sig_class _; _ ] | [Sig_class _; _;_ ] -> assert false
+    | [Sig_class_type _] | [Sig_class_type _; _ ] -> assert false
```
Comment (gasche) [inline typing/printtyp.ml]: Have you tried the version where there is a single `Sig_class` case, with a nested match on the rest of the list, which contains the error cases? It might be nicer (it makes it easier to understand what are the asserted-false situations).

**Review by gasche — COMMENTED** [review]
I reviewed the following commits and they look fine -- see review comments.

- printtyp: generated row types are ghost sigitems
- preserve naming context after printing a sigitem 
- printtyp: less backtrack for the naming context 
- review: patterns refactoring
- Simpler tree_of_signature_rec
- I did *not* review "Hide all type ids"
- more_trees -> group_trees
- more names for with_hidden
- No more state-passing and mutating 

I don't have a global vision on the PR yet. I think that maybe it would help if you squashed some of the commits that it makes sense to squash (I could look at the first two commits again without duplicating review thoughts).

I had high-level questions (why/how does it fix the bug?) in https://github.com/ocaml/ocaml/pull/8929#pullrequestreview-416284219 that I still don't know how to answer.

File: typing/printtyp.ml (hunk 11 above)
Comment (Octachron) [reply typing/printtyp.ml]: I have added on layer of structure to handle the fact that private row type declarations are prefixed to the recursive group that define them:
```ocaml
type a and b = private < .. > and c = private < .. >
```
generate
```ocaml
type b#row
type c#row
type a and b = private < .. >
```

File: typing/printtyp.ml (hunk 14 above)
Comment (Octachron) [reply typing/printtyp.ml]: Fixed with an explicit record for identifiers that should be hidden.

File: typing/printtyp.ml (hunk 15 above)
Comment (Octachron) [reply typing/printtyp.ml]: I don't find the change that convincing but why not.

**Comment by Octachron** [comment]
Should I split the signature restructuring part of this PR to make it easier to review?

Concerning the bug fix part, the high-level explanation is that the printing code keeps a list of identifiers being currently defined to avoid wrongly detecting a name collision in
```ocaml
type a
type a = T of b and b = T of a 
```
In the absence of recursive modules, such recursive definitions cannot be nested, and it is fine to reset the list of protected identifiers at the end of every definitions. This is what the current code is doing. However, in presence of recursive module definitions, recursive definitions can be nested, and one need to properly track the stack of current recursive definitions. This is what this PR is doing by using `with_hidden` for each recursive group rather than directly calling `reset_protected`.

**Comment by gasche** [comment]
I'm swamped and the details of this PR have long been flushed from my memory, so any split to make review easier would be warmly welcome.

**Comment by gasche** [comment]
The smaller PR #10219 was just merged. If I understand correctly, a few fixes remain only in the present patchset, so it would be worth rebasing it on top of the current trunk.

**Comment by Octachron** [comment]
Rather than a few fix, I would rather say that this is the actual fix for the printing of nested recursive definition. However, this fix was hidden before in the midst of the traversal clean up. The rebased version of this PR is much shorter in consequence.

File: typing/printtyp.ml [hunk 16]
```diff
@@ -262,10 +262,10 @@ let with_arg id f =
...
 let fuzzy_id namespace id = namespace = Module && S.mem (Ident.name id) !fuzzy
 
-let add_protected id = protected := S.add (Ident.name id) !protected
-let reset_protected () = protected := S.empty
-let with_hidden id f =
-  protect_refs [ R(protected,S.add (Ident.name id) !protected)] f
+let with_hidden ids f x =
+  let update m id = S.add (Ident.name id.ident) m in
+  protect_refs [ R(protected, List.fold_left update !protected ids)]
+    (fun () -> f x)
```
Comment (gasche) [inline typing/printtyp.ml]: Nitpick: I find it irritating that `with_arg` and `with_hidden` don't have the same signature, with one using `(unit -> 'a) -> 'a` and the other `('a -> 'b) -> 'a -> 'b`. Then the file also has `with_ctx` which is unit-style, and various derivatives of `with_hidden` which use its protocol. It would be better if a single style was used for all `with_` functions.

(If you don't know how to choose: I have a personal preference for the one that would, in a better world than ours, let me write `let@ () = with_hidden ids in ...`.)

**Review by gasche — APPROVED** [review]
Very nice, thanks! Doesn't one of the PRs in the stack (#9889, #10219, #8929) deserve a Changes entry? I think it was a notable change.

File: typing/printtyp.ml (hunk 16 above)
Comment (Octachron) [reply typing/printtyp.ml]: Good point. I have updated the code to use the `(unit -> 'a) -> 'a` protocol uniformly to keep the `resource-acquiring` interpretation of `with_*` functions.

**Comment by Octachron** [comment]
I agree that adding a change entry for the bug report and the three related PRs is warranted.
