### PR TITLE
revert c1a7ace (originally c545e04)

### LINKED ISSUE #7696: record expression deleted when all fields specified
**Original bug ID:** 7696
**Reporter:** @yallop
**Status:** new
**Resolution:** open
**Priority:** normal
**Severity:** minor
**Category:** typing
**Related to:** #6608
**Monitored by:** @nojb @gasche

## Bug description

In 4.03.0 the record expression in an field update was always evaluated:

   # { (assert false) with contents = 1 } ;;
   Characters 0-36:
     { (assert false) with contents = 1 } ;;
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   Warning 23: all the fields are explicitly listed in this record:
   the 'with' clause is useless.
   Exception: Assert_failure ("//toplevel//", 1, 2).

In more recent versions (4.04.2, 4.05.0, 4.06.0) the record expression is removed if all the fields are specified:

   # { (assert false) with contents = 1 } ;;
   Characters 0-36:
     { (assert false) with contents = 1 } ;;
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   Warning 23: all the fields are explicitly listed in this record:
   the 'with' clause is useless.
   - : int ref = {contents = 1}

There's previous discussion on Mantis and GitHub:

   ocaml/ocaml#6608#c16416
   https://github.com/ocaml/ocaml/pull/901#issuecomment-259717609

### PR DESCRIPTION
**Pull request by garrigue**
Fix #7696 by reverting c1a7ace.
(A wrong ordering happened with #6608, so that this commit was first introduced and reverted, and then reintroduced later)

### CODE REVIEW

File: testsuite/tests/letrec-check/basic.ml [hunk 1]
```diff
@@ -115,7 +115,10 @@ val y : 'a list -> unit = <fun>
 (* this is accepted as all fields are overridden *)
 let rec x = { x with contents = 3 }  [@ocaml.warning "-23"];;
 [%%expect{|
-val x : int ref = {contents = 3}
+Line 1, characters 12-35:
+1 | let rec x = { x with contents = 3 }  [@ocaml.warning "-23"];;
+                ^^^^^^^^^^^^^^^^^^^^^^^
+Error: This kind of expression is not allowed as right-hand side of `let rec'
```
Comment (alainfrisch) [inline testsuite/tests/letrec-check/basic.ml:121]: The comment `(* this is accepted as all fields are overridden *)` above that test doesn't hold anymore.

**Comment by garrigue** [comment]
Done. I prefer to keep examples.

**Comment by xavierleroy** [comment]
Merged.  Thank you all.
