### PR TITLE
Fix #14766

### LINKED ISSUE #14766: Module with a module-dependent function doesn't match its inferred signature
The following program is unexpectedly rejected by the type checker in current `trunk` (3436fd64):

```ocaml
include Unit
type t = float
module type S = sig type t end
let f : (module X:S) -> X.t -> int
  = fun (module X:S)     _  -> 3
```

Here's the error message:

```
File "/tmp/bug.ml", line 1:
Error: The implementation /tmp/bug.ml
       does not match the interface (inferred signature): 
       Values do not match:
         val f : (module X : S) -> X.t -> int
       is not included in
         val f : (module X : S) -> X.t -> int
       The type (module X : S) -> X.t -> int is not compatible with the type
         (module X : S) -> X.t -> int
       Type X.t is not compatible with type X.t
       File "/tmp/bug.ml", line 4, characters 4-5: Expected declaration
       File "/tmp/bug.ml", line 4, characters 4-5: Actual declaration
```

If either of the first two lines ("`include Unit`"  or "`type t = float`") is removed, type-checking passes.

### PR DESCRIPTION
**Pull request by smuenzel**
In #11648 , a recursive call to `nondep_type_rec_aux` did not include the `id_map`, resulting in the module path of a `Tfunctor` not being properly substituted, resulting in #14766

### CODE REVIEW

File: typing/ctype.ml [hunk 1]
```diff
@@ -6480,7 +6480,7 @@ let rec nondep_type_rec_aux ?(expand_private=false) env id_map ids ty =
                 Tvariant (set_row_name row (Some (Path.subst id_map p, tl)))
             | _ -> Tvariant row
           end
-      | desc -> copy_type_desc (nondep_type_rec env ids) desc
+      | desc -> copy_type_desc (nondep_type_rec_aux env id_map ids) desc
```
Comment (samsa1) [inline typing/ctype.ml]: `nondep_trec` also work here

File: typing/ctype.ml
Comment (samsa1) [inline typing/ctype.ml]: Removing the `nondep_type_rec` from the recursive group will prevent the same error happening the future.

File: typing/ctype.ml (hunk 1 above)
Comment (smuenzel) [reply typing/ctype.ml]: Changed, thanks!

File: typing/ctype.ml
Comment (smuenzel) [reply typing/ctype.ml]: Done!

File: typing/ident.ml [hunk 2]
```diff
@@ -287,7 +287,7 @@ let print ~with_scope ppf =
         pp_stamped (name, stamp)
   | Unscoped us ->
       let Unscoped.{ name; stamp } = Unscoped.get_desc us in
-      fprintf ppf "U%a"
+      fprintf ppf "U:%a"
```
Comment (smuenzel) [inline typing/ident.ml:290]: I made this change since just prefixing U is confusing, since UX could be a valid module  name

**Comment by samsa1** [comment]
Another example that might be a bit more straightforward than the one by @yallop :
```ocaml
module type T = sig
  type t
end

module F (X : T) = struct
  type t = (module Y : T) -> Y.t -> X.t
end

module M = F(struct type t = float end)
```

**Review by samsa1 — APPROVED** [review]
This change clearly fixes a regression from #11648  that most likely originated from a typo during rebasing.

File: Changes [hunk 3]
```diff
@@ -254,6 +250,10 @@ Working version
   counter-example search space.
   (Florian Angeletti, review by Gabriel Scherer)
 
+- #14766, #14768: Fix missing substitution in #11648 that could case a module
+  containing a module-dependent function not to match its inferred interface.
```
Comment (Octachron) [inline Changes]: Another option would be add the issue and PR numbers to the #11648 entry with the idea that is a bug fix on the development version of the compiler, and not really an user visible change by itself.

Comment (smuenzel) [reply Changes]: done

File: testsuite/tests/typing-modular-explicits/pr14766.ml [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+(* example from @yallop, would cause an error due to not substituting a fresh
+   X in X.t in nondep_type_rec_aux *)
+include Unit
+type t = float
+module type S = sig type t end
+let f : (module X:S) -> X.t -> int
+  = fun (module X:S)     _  -> 3
+
+let () =
+  print_int (f (module Unit) ())
```
Comment (Octachron) [inline testsuite/tests/typing-modular-explicits/pr14766.ml]: Since the issue was with nondep, I would propose to add those tests in the main expect (testsuite/tests/typing-modular-explicits/general.ml) test for modular explicit. Typically, shadowing an included `t` is enough to trigger the bug
```ocaml
module U = struct
  type t = unit = ()
end
module M = struct
  include U
  type t = float
  module type S = sig type t end
  let f : (module X:S) -> X.t -> int = fun (module X:S)     _  -> 3
end
```

File: typing/ident.ml (hunk 2 above)
Comment (Octachron) [reply typing/ident.ml:290]: I have a similar changes that also a `Unscoped.print` function and use it in `Rawprinttyp`. I think those debugging changes are better in a separate commit.

Comment (Octachron) [reply typing/ident.ml:290]: See ff184187f9, but I will submit those debugging changes as a separate PR, this will be simpler.

**Comment by Octachron** [comment]
Beware that you have accidentally merged the debug commit with the main one during your `rebase -i`.

**Comment by smuenzel** [comment]
> Beware that you have accidentally merged the debug commit with the main one during your `rebase -i`.

Good spot! I attempted to fix this now

**Review by Octachron — APPROVED** [review]
This looks very ready to merge now. Thanks for the quick fix!

File: typing/ctype.ml [hunk 5]
```diff
@@ -6480,7 +6480,7 @@ let rec nondep_type_rec_aux ?(expand_private=false) env id_map ids ty =
                 Tvariant (set_row_name row (Some (Path.subst id_map p, tl)))
             | _ -> Tvariant row
           end
-      | desc -> copy_type_desc (nondep_type_rec env ids) desc
+      | desc -> copy_type_desc nondep_trec desc
```
Comment (garrigue) [inline typing/ctype.ml:6483]: Just a remark that this looks typical of some change missed during a rebase.
Since we have been rebasing this PR for several years, there might be other hidden problems :(
