### PR TITLE
Better location when reporting unbound label prefix in record expressions

### LINKED ISSUE #11629: ocamlopt reports incorrect error locations for unfound identifiers
Consider the following example, minimized from Coq's extraction:
```ocaml
module Coq__1 = struct end

type t = { f1 : int ; f2 : int }

let f () = { f1 = 0
        ; Coq__10.f2 = 0 }
```
I get
```
$ ocamlopt foo.ml
File "foo.ml", line 5, characters 13-15:
5 | let f () = { f1 = 0
                 ^^
Error: Unbound module Coq__10
Hint: Did you mean Coq__1?
$ ocamlopt -v
The OCaml native-code compiler, version 4.11.2
Standard library directory: /home/jgross/.opam/4.11.2+fp/lib/ocaml
```
I understand what's going on here (OCaml will assume that all constructors come from the same module and hence will qualify all of them similarly), but it's still confusing to have it highlight a bit of code that does not reference the unbound module, especially when I did not write the OCaml code myself because it was generated by Coq.

### PR DESCRIPTION
**Pull request by nojb**
In #11629 a wrong error location is reported in an expression of the form
```ocaml
{ f = ...; M.g = ... }
```
when the module `M` is unbound. The current error message points to the `f` label, instead of the `M.g` label.

This is because in order to disambiguate the record labels, the compiler first detects if at least one of the labels is qualified (here, `M.g`) and prefixes all other unqualified labels (here, `f`) with the same prefix, giving:
```ocaml
{ M.f = ...; M.g = ... }
```
The error is then reported for the first label even though it is actually coming from the second label. This PR tries to improve this situation by making the logic that prefixes unqualified labels simultaneously reorder them, leaving the qualified label from which the prefix was extracted (here, `M.g`) *first* in the list of labels. This means it will be resolved _first_ and so in the case of unbound module error, we have the guarantee that it will point to an actual error in the program text.

Fixes #11629

### CODE REVIEW

**Comment by JasonGross** [comment]
Thank you!

Is it worth also adding a test to the test-suite for when fields have incompatible module qualifications (as in https://github.com/coq/coq/issues/16677)?

**Comment by nojb** [comment]
> Is it worth also adding a test to the test-suite for when fields have incompatible module qualifications (as in [coq/coq#16677](https://github.com/coq/coq/issues/16677))?

Good idea, done.

**Comment by gasche** [comment]
Wait, doesn't reordering the fields alter the evaluation order? In that case, this is a no-go, unless you first let-bind everything to fix the order.

Other potential approaches to fix this bug that come to mind:
1. We could have more locations inside Longident values, so that `M.g` can have `M` come from one part of the source and `g` from another. But this would break all ppx code, we probably don't want to do this.
2. What about *not* manually prefixing the fields with the module name? Surely we can find another way to implement the type-directed disambiguation logic that does not involve manually transforming the source code.

I would try (2).

**Comment by nojb** [comment]
> Wait, doesn't reordering the fields alter the evaluation order?

I wondered the same but, if I understand correctly, we already enforce evaluation to happen in the order specified by the type definition:

https://github.com/ocaml/ocaml/blob/3a009da2ad56d25046ecbd0d6c148858ebca69f6/typing/typecore.ml#L1245-L1251

**Comment by nojb** [comment]
> > Wait, doesn't reordering the fields alter the evaluation order?
> 
> I wondered the same but, if I understand correctly, we already enforce evaluation to happen in the order specified by the type definition:

@gasche: do you agree with this explanation? does it suffice to make the approach in this PR more palatable?

> 2\. What about _not_ manually prefixing the fields with the module name? Surely we can find another way to implement the type-directed disambiguation logic that does not involve manually transforming the source code.

Coming back to this, I think the manual prefixing of fields is not really related to _type-directed disambiguation_ but to the much more basic syntactic shorthand of writing `{M.f; g}` in place of `{M.f; M.g}`.

**Comment by gasche** [comment]
I agree with your explanation and I find it a bit shocking, it means that the evaluation order of labels depends on the field order in the type declaration rather than the field order in the record expression. In this context, your change fixes an issue in a simple way. I don't know about "palatable" -- I timed out of this because it looked ugly, apologies for the not-so-helpful reaction.



> I think the manual prefixing of fields is not really related to _type-directed disambiguation_ but to the much more basic syntactic shorthand of writing `{M.f; g}` in place of `{M.f; M.g}`.

Yes, but notice that the type-directed disambiguation logic is called right after this prefixing happens. We could instead integrate the prefixing inside `disambiguate_lid_a_list`, for example at

https://github.com/ocaml/ocaml/blob/9d5c55c00dc01a472a442db1c892c736b2cf877d/typing/typecore.ml#L1189-L1195

I believe that what we could do is to first call`process_label lid` on all `Ldot` fields (this would get module-lookup errors out first thing), and then call them on the `Lid` fields with a patched `lid` prefixed by one of the `Ldot` prefixes, if any. Then we would get the same behavior as your patch, without needing to patch the source and/or reorder fields.

This being said, your approach is simpler and it is currently obvious that it does not change the semantics because the sorting-of-fields happens locally, right below.

File: typing/typecore.ml [hunk 1]
```diff
@@ -1218,28 +1218,29 @@ let disambiguate_lid_a_list loc closed env usage expected_type lid_a_list =
...
+  let rec loop accu = function
+    | [] -> lid_a_list
+    | ({txt = Longident.Ldot (modname, _); _}, _ as lid_a) :: rest ->
+        lid_a ::
+        List.map (fun (lid, a as lid_a) ->
+            match lid.txt with
+            | Longident.Lident s ->
+                {lid with txt = Longident.Ldot (modname, s)}, a
+            | _ -> lid_a
+          ) (List.rev_append accu rest)
```
Comment (gasche) [inline typing/typecore.ml]: It would be nice to have a comment that explains why we are doing this:
- if at least one field is explicitly qualified, we qualify all fields to reduce field-name ambiguity
- we reorder the explicitly-qualified field before the other, to ensure that potential error messages related to the qualification will be raised on this field first rather than the "ghost" longidents we produced
- the reordering does not change the program semantics because our caller `type_label_a_list` sorts the field by type-declaration order anyway

**Review by gasche — APPROVED** [review]

**Comment by nojb** [comment]
> I believe that what we could do is to first call`process_label lid` on all `Ldot` fields (this would get module-lookup errors out first thing), and then call them on the `Lid` fields with a patched `lid` prefixed by one of the `Ldot` prefixes, if any. Then we would get the same behavior as your patch, without needing to patch the source and/or reorder fields.

Thanks for the suggestion!

I pushed a commit with this approach. Testsuite passes.

Review welcome!

File: typing/typecore.ml [hunk 2]
```diff
@@ -1192,7 +1192,37 @@ let disambiguate_lid_a_list loc closed env usage expected_type lid_a_list =
       disambiguate_label_by_ids closed ids in
     Label.disambiguate ~warn ~filter usage lid env expected_type scope in
   let lbl_a_list =
-    List.map (fun (lid,a) -> lid, process_label lid, a) lid_a_list in
+    (* Resolve qualified labels first to catch any unbound ones. *)
```
Comment (gasche) [inline typing/typecore.ml]: "to catch any unbound ones" is not clear to me (I don't think I would be able to guess what it means without our current shared knowledge context). Comment suggestion:

```
    (* If one label is qualified [{ foo = ...; M.bar = ... }],
       we will disambiguate all labels using one of the qualifying modules,
       as if the user had written [{ M.foo = ...; M.bar = ... }].

       #11630: It is important to process first the
       user-qualified labels, instead of processing all labels in
       order, so that error messages coming from the lookup of
       M (maybe no such module/path exists) are shown to the user
       in context of a qualified field [M.bar] they wrote
       themselves, instead of the "ghost" qualification [M.foo]
       that does not come from the source program. *)
```

File: typing/typecore.ml [hunk 3]
```diff
@@ -1192,7 +1192,37 @@ let disambiguate_lid_a_list loc closed env usage expected_type lid_a_list =
...
+        match lbl, lid_a with
+        | Some lbl, (lid, a) -> lid, lbl, a
+        | None, (lid, a) ->
+            let lid =
+              match qual, lid.txt with
+              | Some modname, Longident.Lident s ->
+                  {lid with txt = Longident.Ldot (modname, s)}
+              | _ -> lid
+            in
+            lid, process_label lid, a
```
Comment (gasche) [inline typing/typecore.ml]: My intuition is that here I would expect the original `lid` as written by the user, not the qualified version, in the first component of the tuple. (I think that by changing `lid` here you are still "modifying the source", so to speak.)

File: typing/typecore.ml [hunk 4]
```diff
@@ -1192,7 +1192,37 @@ let disambiguate_lid_a_list loc closed env usage expected_type lid_a_list =
...
+        ) lid_a_list
+    in
+    (* Find a module prefix (if any) to qualify unqualified labels *)
+    let qual =
+      List.find_map (function
+          | {txt = Longident.Ldot (modname, _); _}, _ -> Some modname
+          | _ -> None
+        ) lid_a_list
+    in
+    (* Prefix unqualified labels with [qual] and resolve them *)
```
Comment (gasche) [inline typing/typecore.ml]: Comment suggestion:

```
    (* Prefix unqualified labels with [qual] and resolve them.

       Prefixing unqualified labels does not change the final
       disambiguation result, it restricts the set of candidates
       without removing any valid choice.
       It matters if users activated warnings for ambigious or
       out-of-scope resolutions -- they get less warnings by
       qualifying at least one of the fields. *)
```

**Review by gasche — APPROVED** [review]
Wow, I did not expect you to choose the harder route instead of your first iteration. A+ for the effort :-) It's nice to know that this also works and I do find it more principled -- but it would also be fine if you preferred to use your first patch. See inline comments -- I think we should change which of the `lid` is returned in the first component, but I would wait confirmation that this actually passes the testsuite before claiming that it will pass.

File: typing/typecore.ml (hunk 2 above)
Comment (nojb) [reply typing/typecore.ml]: Thanks, I amended as suggested.

File: typing/typecore.ml (hunk 3 above)
Comment (nojb) [reply typing/typecore.ml]: Good point, amended as suggested (and the testsuite still passes).

File: typing/typecore.ml (hunk 4 above)
Comment (nojb) [reply typing/typecore.ml]: Amended as suggested, thanks.

**Comment by gasche** [comment]
This looks good to me.

**Comment by nojb** [comment]
> This looks good to me.

Thanks! Merged (the AppVeyor failure looks completely unrelated).
