### PR TITLE
Fix CSE across atomic loads again

### LINKED ISSUE #12825: CSE of non-atomic load around atomic load breaks SC
Here is an example (see also in [godbolt](https://ocaml.godbolt.org/z/56sbxhYnE)):

```ocaml
let cse_breaks_sc non_atomic atomic =
  let before = !non_atomic in
  (* happens before *)
  let fence = Atomic.get atomic in
  (* happens before *)
  let after = !non_atomic in
  (* The above non_atomic read is optimized away, which breaks sequential consistency. *)
  before - after + fence
```

What can happen is that another domain executes something like:

```ocaml
non_atomic := also_new_value;
(* happens before *)
Atomic.set atomic new_value;
```

and due to the CSE on the second load of `non_atomic` the program can give results that are not consistent with the memory model.

Specifically, the `Atomic.get atomic` gives the `new_value` (which means the `Atomic.set` happens before the `Atomic.get`), but then the second read of the `non_atomic` does not return the `also_new_value`, because it has been optimized away.

The arithmetic at the end is just so that the compiler doesn't just optimize out all the reads.  Also, the example is minimized.  (In practical use cases there is typically more work between the reads of the `non_atomic`.  The first read is done to see if it makes sense to try to do that work (which also includes the atomic read, which is typically more expensive (i.e. it is reading a contested memory location)) and the second read (after the atomic read) is to ensure that in fact no other domain running in parallel has completed the work before we did.)

I checked that this also happens with `5.2.0+trunk` switch freshly created with opam.

### PR DESCRIPTION
**Pull request by gasche**
Fixes #12825 by handling atomic loads as stores.

(Intuition: atomic loads update the view/frontier of the current thread, so some previous loads of non-atomic locations are not valid anymore.)

### CODE REVIEW

**Review by kayceesrk — APPROVED** [review]
The change looks good to me.

File: asmcomp/CSEgen.ml [hunk 1]
```diff
@@ -227,8 +227,14 @@ method class_of_operation op =
...
-      (* #12173: disable CSE for atomic loads. *)
-      if is_atomic then Op_other
+      (* #12173: disable CSE for atomic loads.
+         #12825: atomic loads cannot be treated as Op_other
+           because they update our view / the frontier of the
+           non-atomic locations, so past non-atomic (mutable) loads
+           may be not be valid anymore.
+         We conservatively tread them as non-initializing stores.
+      *)
+      if is_atomic then Op_store true
```
Comment (kayceesrk) [inline asmcomp/CSEgen.ml:237]: Cosmetic change suggestion.

Is it worth changing the definition of `Op_load` to include atomicity information (similar to`Iload {is_atomic: bool; mutability: Asttypes.mutable_flag`)? `Op_load {is_atomic = true}` will be treated the same as `Op_store true`.

https://github.com/ocaml/ocaml/blob/ba71f2e47d3c260196bbdb9c89b24517e6c2fab8/asmcomp/CSEgen.ml#L25-L30

Comment (gasche) [reply asmcomp/CSEgen.ml:237]: We could do this as a refactor that also changes `Op_store of bool` into something like `Op_store of [ Init | Assign ]`. I would suggest to defer this to a different PR to give more time to the questions of taste than to the bugfix.

Comment (kayceesrk) [reply asmcomp/CSEgen.ml:237]: Sounds good.

**Review by xavierleroy — COMMENTED** [review]
The test will break on every non-x86-64 platform.  Please remove it and don't ever match on compiler dumps from the back-end.

**Comment by gasche** [comment]
Ah, right.... Could we maybe restrict the test to only run on amd64 architectures? It sounds useful to be able to unit-test the compiler (besides the memory-model tests). On the other hand, I see the point that such tests are many too unitary, this very particular regression is unlikely to introduce itself exactly on this example.

**Comment by gasche** [comment]
(I guess we also have the problem of different register allocation under different ABIs, etc.)

**Comment by lthls** [comment]
> Ah, right.... Could we maybe restrict the test to only run on amd64 architectures? It sounds useful to be able to unit-test the compiler (besides the memory-model tests).

If you want to check that, please write a tool linking with compilerlibs to check the output. There's already a Cmm parser in `testsuite/tools`, you can probably just expand it a bit to support atomic operations and write a small executable that compiles to linear and prints a summary of the instruction sequence (that will be stable enough to use as reference).

**Comment by maranget** [comment]
FYI  I have suggested a  test that should fail in case of non-atomic load moving from after an atomic load to before it. See PR #12854.

**Comment by gasche** [comment]
I'm not motivated enough to try to figure out how to write the test that @lthls suggests, so I just removed the test from this PR. Same fix, no test, no problem.

**Comment by gasche** [comment]
@maranget was eager to see progress on this to unblock #12854, so I went ahead and merged. Thanks everyone!
