### PR TITLE
Release bytecode only after backtrace has been recorded

### LINKED ISSUE #9701: "unknown location" in backtraces in ocaml script
I'm trying to get backtraces in simple test code:
```
let f () = failwith "test"
let proc () = f ()
let () = proc ()
```
Running `env OCAMLRUNPARAM=b ocaml test.ml`:
```
ocaml --version
The OCaml toplevel, version 4.10.0
```
```
Exception: Failure "test".
Raised at file "stdlib.ml", line 29, characters 22-33
Called from unknown location
Called from file "toplevel/toploop.ml", line 212, characters 17-27
```
Notice the "unknown location"

But for older version location in source file was provided
```
ocaml --version
The OCaml toplevel, version 4.05.0
```
```
Exception: Failure "test".
Raised at file "pervasives.ml", line 32, characters 22-33
Called from file "./test.ml", line 3, characters 9-16
Called from file "toplevel/toploop.ml", line 180, characters 17-56
```

discuss thread for reference: https://discuss.ocaml.org/t/backtraces-in-script-run-by-ocaml/5970

### PR DESCRIPTION
**Pull request by renatoalencar**
When an exception happens bytecode has been released before the
backtrace is recorded and so all the debugging information related,
because of that the backtrace information for the script that has
just been compiled was not being found, which resulted on showing
'unknown location' instead of the actual location.

Enable debug flag for running a file on toplevel.

Resolves #9701

### CODE REVIEW

File: toplevel/byte/topeval.ml [hunk 1]
```diff
@@ -87,13 +87,16 @@ let load_lambda ppf lam =
   match
     may_trace := true;
     Fun.protect
-      ~finally:(fun () -> may_trace := false;
-                          if can_free then Meta.release_bytecode bytecode)
+      ~finally:(fun () -> may_trace := false)
```
Comment (gasche) [inline toplevel/byte/topeval.ml]: I would be in favor of completely removing the `Fun.protect` call here, if only because it shows up in the user-visible backtrace.

**Review by gasche — APPROVED** [review]
I believe that this is a correct bugfix to a regression we introduced in 4.12 -- see the discussion in https://github.com/ocaml/ocaml/issues/9701#issuecomment-983631220 .

File: toplevel/byte/topeval.ml (hunk 1 above)
Comment (renatoalencar) [reply toplevel/byte/topeval.ml]: Sure, removed.

**Comment by renatoalencar** [comment]
@gasche I would like to have a regression test for that. But couldn't figure that out from what is present on testsuite/tests/tool-toplevel/.

**Comment by gasche** [comment]
Re. testing: there is a flag `ocaml_script_as_argument` to test `ocaml foo.ml`, see `testsuite/tests/tool-ocaml/directive_failure.ml` (`./ocamltest/ocamltest -e ..../mytest.ml` shows how the test runs, `-e` logs on stderr instead of a file).

**Comment by renatoalencar** [comment]
I was able to add the test, but not to make sure that's right. I couldn't make it fail when the reference file is different from the actual output of the script.

File: testsuite/tests/tool-toplevel/pr9701.ml [hunk 2]
```diff
@@ -0,0 +1,12 @@
+(* TEST
+ocaml_script_as_argument = "true"
+ocaml_exit_status = "2"
+* setup-ocaml-build-env
+** ocaml
+*)
```
Comment (gasche) [inline testsuite/tests/tool-toplevel/pr9701.ml:7]: You need to add a `check-ocaml-output` step (see for example `tests/typing-shadowing-of-pervasives-submodules/redefine_largefile_top.ml`).

Comment (renatoalencar) [reply testsuite/tests/tool-toplevel/pr9701.ml:7]: Thank you very much

Comment (renatoalencar) [reply testsuite/tests/tool-toplevel/pr9701.ml:7]: Done

**Comment by renatoalencar** [comment]
Looks like that  test is failing because of the backslash Windows uses for paths, `toplevel/byte/topeval.ml` still the same though. I'm gonna try to understand why.

```
> Running pr9701.ml in bytecode toplevel (expected exit status: 2)
> Commandline: C:\projects\🐫реализация-mingw32\runtime\ocamlrun.exe C:\projects\🐫реализация-mingw32\ocaml.exe -noinit -no-version -noprompt -nostdlib -I C:\projects\🐫реализация-mingw32\stdlib -I C:\projects\🐫реализация-mingw32\toplevel pr9701.ml
>   Redirecting stdout to C:\projects\🐫реализация-mingw32\testsuite\_ocamltest\tests/tool-toplevel\pr9701\ocaml\ocaml.output 
>   Redirecting stderr to C:\projects\🐫реализация-mingw32\testsuite\_ocamltest\tests/tool-toplevel\pr9701\ocaml\ocaml.output 
> ### begin stdout ###
> Exception: Failure "test".
> Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
> Called from <unknown> in file ".\pr9701.ml", line 13, characters 9-16
> Called from Topeval.load_lambda in file "toplevel/byte/topeval.ml", line 89, characters 4-14
> ### end stdout ###
> Action 1/1 (ocaml) passed
> Running test check-ocaml-output with 1 actions
> 
> Running action 1/1 (check-ocaml-output)
> Comparing toplevel output C:\projects\🐫реализация-mingw32\testsuite\_ocamltest\tests/tool-toplevel\pr9701\ocaml\ocaml.output to reference C:\projects\🐫реализация-mingw32\testsuite\tests\tool-toplevel\pr9701.compilers.reference
> Action 1/1 (check-ocaml-output) failed (toplevel output C:\projects\🐫реализация-mingw32\testsuite\_ocamltest\tests/tool-toplevel\pr9701\ocaml\ocaml.output differs from reference C:\projects\🐫реализация-mingw32\testsuite\tests\tool-toplevel\pr9701.compilers.reference: 
> --- "C:\\projects\\\360\237\220\253\321\200\320\265\320\260\320\273\320\270\320\267\320\260\321\206\320\270\321\217-mingw32\\testsuite\\tests\\tool-toplevel\\pr9701.compilers.reference"	2021-12-01 20:22:49.778687600 +0000
> +++ "C:\\projects\\\360\237\220\253\321\200\320\265\320\260\320\273\320\270\320\267\320\260\321\206\320\270\321\217-mingw32\\testsuite\\_ocamltest\\tests/tool-toplevel\\pr9701\\ocaml\\ocaml.output"	2021-12-01 20:50:30.477731600 +0000
> @@ -1,4 +1,4 @@
>  Exception: Failure "test".
>  Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
> -Called from <unknown> in file "./pr9701.ml", line 13, characters 9-16
> +Called from <unknown> in file ".\pr9701.ml", line 13, characters 9-16
>  Called from Topeval.load_lambda in file "toplevel/byte/topeval.ml", line 89, characters 4-14
> 
> )
```

**Comment by Octachron** [comment]
A simpler workaround might be to fix the filename by adding a line directive at the start of the script:
```ocaml
#1 "pr9701.ml"
Printexc.record_backtrace true;;
```

**Comment by gasche** [comment]
It's odd that Windows is using `.\foo.ml`, but `toplevel/byte/topeval.ml`. (cc @dra27)

But yes I would go for @Octachron's workaround, or just disable the test under Windows for now.

**Comment by renatoalencar** [comment]
Gonna try @Octachron's workaround first, it seems to work locally.

**Comment by xavierleroy** [comment]
What's the status on this PR?  It looks like a bug fix, so it should be given some attention for 4.14.

File: toplevel/toploop.ml [hunk 3]
```diff
@@ -109,6 +109,7 @@ let load_file = load_file false
 (* Execute a script.  If [name] is "", read the script from stdin. *)
 
 let run_script ppf name args =
+  Clflags.debug := true;
```
Comment (xavierleroy) [inline toplevel/toploop.ml:112]: Is this related to the bug fix or an independent change?

**Comment by gasche** [comment]
Thanks for the ping! I guess we got distracted by other stuff. I fixed the Changes conflict and will merge in 4.14 if the CI comes back green.

**Comment by renatoalencar** [comment]
> What's the status on this PR? It looks like a bug fix, so it should be given some attention for 4.14.

It should be really to go. Although I think location for scripts could be really improved, this specific bug should be fixed.

File: toplevel/toploop.ml (hunk 3 above)
Comment (renatoalencar) [reply toplevel/toploop.ml:112]: Without this, the toplevel wouldn't collect debug information and show no line numbers after an exception.

Comment (xavierleroy) [reply toplevel/toploop.ml:112]: I still don't understand.  Is this change visible to users?  If so it should have been discussed as part of this PR and it should be described as such in the Changes file.

Comment (gasche) [reply toplevel/toploop.ml:112]: I understand this as a minor fix to an inconsistency in the toplevel code: `Toploop.loop`, called by interactive usage of the toplevel, sets `Clflags.debug := true` on entry, but (until this change) `ocaml foo.ml` would behave differently. With this change, both Toploop entry points from Topmain do the same thing.

Comment (dra27) [reply toplevel/toploop.ml:112]: That will affect the output of shebang ocaml scripts, which is a known area for surprising bug reports (cf. the still-smouldering, if closed, stuff around #2155). That sounds worth an explicit entry in Changes, therefore?
