### PR TITLE
Remove old polymorphic variant type syntax

### LINKED ISSUE #11261: Private polymorphic variant and old variant syntax leads to assert false in typing/typetexp.ml
```
type 'a t = private [`F]

type 'a first = F : ('b#t as 'a) first
```
```
./ocamlopt.opt -I stdlib /tmp/b.ml
File "/tmp/b.ml", line 3, characters 21-25:
3 | type 'a first = F : ('b#t as 'a) first
                         ^^^^
Alert deprecated: old syntax for polymorphic variant type
Fatal error: exception File "typing/typetexp.ml", line 342, characters 10-16: Assertion failed
```

This seems like it happens because the old syntax for polymorphic variants is taking a different codepath (in Ptyp_class) than the new syntax. I'm not familiar with this code, but maybe if we discover that we're dealing with a polymorphic variant in Ptyp_class, we want to translate to the new-style syntax, and then call the function again to ensure consistent behaviour?

### PR DESCRIPTION
**Pull request by smuenzel**
Instead of having two code paths for polymorphic variant types in `Typetexp`, map the old syntax to its equivalent new syntax.

Fixes #11261

### CODE REVIEW

**Comment by gasche** [comment]
The description of the PR is enticing but the end-result does not seem simpler than the current code, it's still a lot of special cases for deprecated syntax that has a direct replacement.

Here is an alternative proposal: let's remove the deprecated syntax for polymorphic variants completely. It's been deprecated for ages, the alternative has been available for ages as well, let's remove some cruft from the type-checker.

Note: according to [the manual](https://v2.ocaml.org/manual/types.html#sss:typexpr-sharp-types), the deprecated syntaxes are `#t` for `[< t]` and ``#t[> `A | B | `C ]`` for ``[t > `A | `B | `C]``, but in practice I don't know if the second form is accepted at all, even ``t[> `A ]`` is a syntax error in my tests.

**Comment by smuenzel** [comment]
Deleting code sounds even better, I agree.
I'll update this pr.

**Comment by gasche** [comment]
If it's not too much work, it would be useful if you could store the first version in a branch in your github fork, so that we can point people to it when discussing alternatives.

**Comment by smuenzel** [comment]
I pushed my try at this

See https://github.com/ocaml/ocaml/compare/trunk...smuenzel:ocaml:fix-poly-variants-old for the previous version

**Review by gasche — APPROVED** [review]
I like the new implementation much better, thanks! I'm approving as I believe that the change is correct, but this cannot merged yet, we need maintainer consensus to remove the feature.

**Comment by gasche** [comment]
It looks like this syntax was deprecated in 42d1811a9354b00f15f77753c520decc0ef4b4bd in 2001, in preparation of OCaml 3.03.

**Comment by dra27** [comment]
For anyone who's having a slow day like me, this is about deprecating the polymorphic variant _type_ syntax (`val f : #t -> ...`) not the pattern matching syntax `match v with #t -> ...` 🤦‍♂️

This has also displayed a deprecation warning for 21 years, so I agree it can go!

**Comment by xavierleroy** [comment]
Let's wait for @garrigue 's approval.  But, yes, this removal of a long-deprecated syntax looks fine to me.

**Review by garrigue — APPROVED** [review]
Long overdue

File: typing/typetexp.ml [hunk 1]
```diff
@@ -298,7 +282,7 @@ and transl_type_aux env policy styp =
           in
           let path, decl = Env.find_type_by_name lid2 env in
           ignore(Env.lookup_cltype ~loc:lid.loc lid.txt env);
-          (path, decl, false)
+          (path, decl)
         with Not_found ->
           ignore (Env.lookup_cltype ~loc:lid.loc lid.txt env); assert false
       in
```
Comment (garrigue) [inline typing/typetexp.ml:288]: I am kind of of wondering whether it would make sense to replace all this by a simple call to `lookup_type ~loc:lid.loc lid2 env`

But this may go in a separate PR.

Comment (smuenzel) [reply typing/typetexp.ml:288]: I think separate PR might be better, to keep this PR deletion-only.

**Comment by smuenzel** [comment]
I updated the changes file

**Comment by gasche** [comment]
Merged, thanks!
