### PR TITLE
Name mangling: use `.` instead of `__` as module separator

### LINKED ISSUE #8998: in ocamlopt, the mapping from ocaml name to C symbols is not injective
A function `b__c` in a.ml become a C symbol like "caml__A__b__c_NUMBER". A function `c` in a__b.ml can create the same C symbol. Example:

```
$ cd /tmp
$ echo "let b__c () = ()" > a.ml
$ echo "let c () = ()" > a__b.ml
$ ocamlopt a.ml a__b.ml
/usr/bin/ld: a.o: in function `camlA__b__c_1002':
:(.text+0x0): multiple definition of `camlA__b__c_1002'; a__b.o::(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
```

There are a few consequences:
- unexpected link time errors as shown above
- parsing ocaml C symbol is ambiguous (the reason why I looked at this)
- possible segfault with shared objects, as clashing symbols at runtime is not an error

Example of segfault:

```bash
rm -rf /tmp/test
mkdir -p /tmp/test
cd /tmp/test
cat > common.ml <<EOF
type exn += E : 'a * ('a -> unit) -> exn
EOF
cat > a.ml <<EOF
let b__c str = Printf.printf "A.b__c\n%!input: %s\n%!" str
let () = raise (Common.E ("asd", b__c))
EOF
cat > a__b.ml <<EOF
let c x = Printf.printf "A__b.c\n%!input: %d\n%!" x
let () = raise (Common.E (12, c))
EOF
cat > main.ml <<EOF
let load name =
  print_endline ("loading " ^ name);
  try Dynlink.loadfile name
  with Dynlink.Error (Library's_module_initializers_failed (Common.E (x, f))) ->
    f x
let () = load "a.cmxs"
let () = load "a__b.cmxs"
EOF

ocamlopt -c common.ml
for name in common a a__b; do
    ocamlopt -linkall -shared $name.ml -o $name.cmxs
done
ocamlopt -I . common.cmx dynlink.cmxa main.ml
./a.out
```

outputs:

```
$ ./script
loading a.cmxs
A.b__c
input: asd
loading a__b.cmxs
A.b__c
./script : ligne 33 : 28382 Erreur de segmentation  (core dumped) ./a.out
```

### LINKED ISSUE #11321: Symbol name collision on ARM64 causing link errors
I have a very large file called `values.ml`. To speed up compilation, I split it up into files named `values__0.ml` ... `values__7.ml`, then I changed my `values.ml` file to:

```ocaml
include Values__0
include Values__1
include Values__2
include Values__3
include Values__4
include Values__5
include Values__6
include Values__7
```

This works great. Compiles much faster with much less memory usage. On x86-64.

On ARM64 (both on an Apple M1 and Ubuntu on AWS Graviton2) it causes a link error like so:
```
duplicate symbol '_camlFoo_bar__Values__4' in:
    foo/bar/foo_bar.a(foo_bar__Values__4.o)
    foo/bar/foo_bar.a(foo_bar__Values.o)
duplicate symbol '_camlFoo_bar__Values__3' in:
    foo/bar/foo_bar.a(foo_bar__Values__3.o)
    foo/bar/foo_bar.a(foo_bar__Values.o)
duplicate symbol '_camlFoo_bar__Values__2' in:
    foo/bar/foo_bar.a(foo_bar__Values__2.o)
    foo/bar/foo_bar.a(foo_bar__Values.o)
duplicate symbol '_camlFoo_bar__Values__1' in:
    foo/bar/foo_bar.a(foo_bar__Values__1.o)
    foo/bar/foo_bar.a(foo_bar__Values.o)
ld: 4 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I noticed however that the symbols in the `objdump -D foo__bar.a` appear to be random blobs of code.

```
000000000000a8e8 <_camlFoo_bar__Values__4>:
    a8e8: 00 00 00 00   udf     #0
    a8ec: 00 00 00 07   <unknown>
    a8f0: fc 17 00 00   udf     #6140
    a8f4: 00 00 00 00   udf     #0

000000000000a8f8 <_camlFoo_bar__Values__3>:
    a8f8: 2e 2f 5f 62   <unknown>
    a8fc: 75 69 6c 64   <unknown>
    a900: 2f 64 65 66   <unknown>
    a904: 61 75 6c 74   <unknown>
    a908: 2f 61 77 73   <unknown>
    a90c: 2f 65 63 32   <unknown>
    a910: 2f 76 61 6c   ldnp    d15, d29, [x17, #-496]
    a914: 75 65 73 2e   umax.4h v21, v11, v19
    a918: 6d 6c 00 00   udf     #27757
    a91c: 00 00 00 05   <unknown>
    a920: fc 0b 00 00   udf     #3068
    a924: 00 00 00 00   udf     #0

000000000000a928 <_camlFoo_bar__Values__2>:
    a928: 61 77 73 6d   ldp     d1, d29, [x27, #-208]
    a92c: 5f 65 63 32   <unknown>
    a930: 00 00 00 00   udf     #0
    a934: 00 00 00 07   <unknown>
    a938: fc 0f 00 00   udf     #4092
    a93c: 00 00 00 00   udf     #0

000000000000a940 <_camlFoo_bar__Values__1>:
    a940: 41 77 73 6d   ldp     d1, d29, [x26, #-208]
    a944: 5f 65 63 32   <unknown>
    a948: 5f 5f 56 61   <unknown>
    a94c: 6c 75 65 73   <unknown>
    a950: 00 00 00 00   udf     #0
    a954: 00 00 00 07   <unknown>
```

Also there's only 4 of those even thought there are eight submodules.

That made me wonder if naming my modules `Values__0` ... `Values__7`  when I also have a `Values` begged for some kind of generated symbol name collision. Sure enough, changing them to `values_sub0.ml` ... `values_sub7.ml` fixed the issue.

So, a workaround is possible though I'm sorry to say I don't know what exactly is causing this collision.

Every minimal test case I've tried to construct does not exhibit this bug. Hopefully the cause of the bug is more apparent to in-the-know people. Thanks very much.

### PR DESCRIPTION
**Pull request by xavierleroy**
Currently, ocamlopt mangles names using the following format: `camlModule__Submodule__identifier_stamp`.

However, the `__` separator is ambiguous with double underscores that can occur in module or identifier names, see linked issues below.

This PR simply uses `.` (single dot) instead of `__` as separator, resulting in non-ambiguous, good-looking mangled names
`camlModule.Submodule.identifier_stamp`.

Dots in identifiers are supported by all known assemblers except MASM.  OCaml 5 does not currently use MASM, and there are MASM-compatible alternatives, such as using `$` instead of `.`.

Fixes: #8998
Fixes: #11321

### CODE REVIEW

**Comment by xavierleroy** [comment]
Note to reviewers: `caml_system__code_begin` and `caml_system__code_end` still use double underscores because they are referenced from C.  This is ugly but no ambiguity with user-defined names can occur.

File: asmcomp/asmpackager.ml [hunk 1]
```diff
@@ -49,8 +49,9 @@ let read_member_info pack_path file = (
       let (info, crc) = Compilenv.read_unit_info file in
       if info.ui_name <> name
       then raise(Error(Illegal_renaming(name, file, info.ui_name)));
+      (* FIXME should use functions from Compilenv *)
       if info.ui_symbol <>
-         (Compilenv.current_unit_infos()).ui_symbol ^ "__" ^ info.ui_name
+         (Compilenv.current_unit_infos()).ui_symbol ^ "." ^ info.ui_name
```
Comment (gasche) [inline asmcomp/asmpackager.ml:53]: Unless I missed something, this is `Compilenv.make_symbol (Some info.ui_name)`.

File: asmcomp/power/emit.mlp [hunk 2]
```diff
@@ -75,10 +75,6 @@ let (trap_size, trap_handler_offset, trap_previous_offset) =
   | ELF64v1 -> (32, 56, 64)
   | ELF64v2 -> (32, 40, 48)
 
-(* Output a symbol *)
-
-let emit_symbol s = Emitaux.emit_symbol '.' s
```
Comment (gasche) [inline asmcomp/power/emit.mlp:80]: If I understand correctly, this change (same for s390x below) changes the 'escaping character' from `.` to` $` on these architectures. Will that work, why was `.` not used before?

**Comment by dbuenzli** [comment]
I suppose this will affect `perf`'s  OCaml demangling support that has been upstreamed [here](https://lore.kernel.org/linux-perf-users/20210203211537.b25ytjb6dq5jfbwx@nyu/T/#u) by @copy ([background discussion](https://discuss.ocaml.org/t/ann-perf-demangling-of-ocaml-symbols-a-short-introduction-to-perf/7143)).

**Comment by gasche** [comment]
> Note to reviewers: caml_system__code_begin and caml_system__code_end still use double underscores because they are referenced from C. This is ugly but no ambiguity with user-defined names can occur.

Maybe this could be documented by a comment in the code?

We could also use one of the two following less ad-hoc conventions:
- `caml_system` names uses `__` rather than `.`
- runtime names (`caml_[a-z].*`, includes `caml_hot` in addition to `caml_system`) use `__`

(This has the benefit of making the patch smaller and requiring no change if we later want to refer to other runtime code sections from C.)

**Comment by mshinwell** [comment]
This seems like a good change, but one clarification: I didn't think that submodule information was currently encoded in the mangled names (although it would be nice to do so in the future).

**Comment by fabbing** [comment]
The frame-pointers tests in the testsuite use a rough name demangling to compare the fp backtrace to the reference one.
Here is a patch to have those tests to pass again:
```diff
diff --git a/testsuite/tests/frame-pointers/c_call.reference b/testsuite/tests/frame-pointers/c_call.reference
index 68128b3270..6d5fa7dfbb 100644
--- a/testsuite/tests/frame-pointers/c_call.reference
+++ b/testsuite/tests/frame-pointers/c_call.reference
@@ -1,18 +1,18 @@
 fp_backtrace_many_args
 caml_c_call_stack_args
-camlC_call__f
-camlC_call__entry
+camlC_call.f
+camlC_call.entry
 caml_program
 caml_start_program
 main
 caml_c_call
-camlC_call__f
-camlC_call__entry
+camlC_call.f
+camlC_call.entry
 caml_program
 caml_start_program
 main
-camlC_call__f
-camlC_call__entry
+camlC_call.f
+camlC_call.entry
 caml_program
 caml_start_program
 main
diff --git a/testsuite/tests/frame-pointers/effects.reference b/testsuite/tests/frame-pointers/effects.reference
index 400faa045a..10ba6b0ddb 100644
--- a/testsuite/tests/frame-pointers/effects.reference
+++ b/testsuite/tests/frame-pointers/effects.reference
@@ -1,35 +1,35 @@
 # computation f
-camlEffects__f
+camlEffects.f
 caml_runstack
-camlEffects__entry
+camlEffects.entry
 caml_program
 caml_start_program
 main
 # perform effect (E 0)
 # caught effect (E 0). continuing...
-camlEffects__h_effect_e
-camlEffects__entry
+camlEffects.h_effect_e
+camlEffects.entry
 caml_program
 caml_start_program
 main
 # perform returns 1
-camlEffects__f
+camlEffects.f
 caml_runstack
-camlEffects__h_effect_e
-camlEffects__entry
+camlEffects.h_effect_e
+camlEffects.entry
 caml_program
 caml_start_program
 main
 # done 2
-camlEffects__v_retc
-camlEffects__h_effect_e
-camlEffects__entry
+camlEffects.v_retc
+camlEffects.h_effect_e
+camlEffects.entry
 caml_program
 caml_start_program
 main
 # continue returns 3
-camlEffects__h_effect_e
-camlEffects__entry
+camlEffects.h_effect_e
+camlEffects.entry
 caml_program
 caml_start_program
 main
diff --git a/testsuite/tests/frame-pointers/exception_handler.reference b/testsuite/tests/frame-pointers/exception_handler.reference
index 83f55aa862..0f1bbeebcb 100644
--- a/testsuite/tests/frame-pointers/exception_handler.reference
+++ b/testsuite/tests/frame-pointers/exception_handler.reference
@@ -1,24 +1,24 @@
-camlException_handler__handler
-camlException_handler__bare
-camlException_handler__entry
+camlException_handler.handler
+camlException_handler.bare
+camlException_handler.entry
 caml_program
 caml_start_program
 main
-camlException_handler__handler
-camlException_handler__bare
-camlException_handler__entry
+camlException_handler.handler
+camlException_handler.bare
+camlException_handler.entry
 caml_program
 caml_start_program
 main
-camlException_handler__handler
-camlException_handler__nested
-camlException_handler__entry
+camlException_handler.handler
+camlException_handler.nested
+camlException_handler.entry
 caml_program
 caml_start_program
 main
-camlException_handler__handler
-camlException_handler__nested
-camlException_handler__entry
+camlException_handler.handler
+camlException_handler.nested
+camlException_handler.entry
 caml_program
 caml_start_program
 main
diff --git a/testsuite/tests/frame-pointers/filter-locations.sh b/testsuite/tests/frame-pointers/filter-locations.sh
index e54bd2b505..ac1827d9cb 100755
--- a/testsuite/tests/frame-pointers/filter-locations.sh
+++ b/testsuite/tests/frame-pointers/filter-locations.sh
@@ -4,7 +4,7 @@ set -eu
 
 program="${1}"
 # https://stackoverflow.com/questions/29613304/is-it-possible-to-escape-regex-metacharacters-reliably-with-sed/29626460#29626460
-program_escaped=$(echo ${program} | sed 's/[^^\\]/[&]/g; s/\^/\\^/g; s/\\/\\\\/g')
+program_escaped=$(echo "${program}" | sed 's/[^^\\]/[&]/g; s/\^/\\^/g; s/\\/\\\\/g')
 regex_backtrace='^.*(\(.*\)+0x[[:xdigit:]]*)[0x[[:xdigit:]]*]$'
 regex_trim_fun='^\(caml.*\)_[[:digit:]]*$'
 
diff --git a/testsuite/tests/frame-pointers/reperform.reference b/testsuite/tests/frame-pointers/reperform.reference
index 49d193f2de..f0580e158a 100644
--- a/testsuite/tests/frame-pointers/reperform.reference
+++ b/testsuite/tests/frame-pointers/reperform.reference
@@ -1,19 +1,19 @@
 # resumed...
-camlReperform__foo
-camlReperform__foo
-camlReperform__foo
-camlReperform__foo
-camlReperform__foo
-camlReperform__foo
+camlReperform.foo
+camlReperform.foo
+camlReperform.foo
+camlReperform.foo
+camlReperform.foo
+camlReperform.foo
 caml_runstack
-camlReperform__bar
-camlReperform__bar
-camlReperform__bar
-camlReperform__bar
-camlReperform__bar
-camlReperform__bar
+camlReperform.bar
+camlReperform.bar
+camlReperform.bar
+camlReperform.bar
+camlReperform.bar
+camlReperform.bar
 caml_runstack
-camlReperform__entry
+camlReperform.entry
 caml_program
 caml_start_program
 main
diff --git a/testsuite/tests/frame-pointers/stack_realloc.reference b/testsuite/tests/frame-pointers/stack_realloc.reference
index df007d7c1d..699a14f2c0 100644
--- a/testsuite/tests/frame-pointers/stack_realloc.reference
+++ b/testsuite/tests/frame-pointers/stack_realloc.reference
@@ -1,11 +1,11 @@
-camlStack_realloc__callback
+camlStack_realloc.callback
 caml_start_program
 caml_callback
 c_fun
 caml_c_call
-camlStack_realloc__f_comp
+camlStack_realloc.f_comp
 caml_runstack
-camlStack_realloc__entry
+camlStack_realloc.entry
 caml_program
 caml_start_program
 main
diff --git a/testsuite/tests/frame-pointers/stack_realloc2.reference b/testsuite/tests/frame-pointers/stack_realloc2.reference
index 4014640948..a14bb479e3 100644
--- a/testsuite/tests/frame-pointers/stack_realloc2.reference
+++ b/testsuite/tests/frame-pointers/stack_realloc2.reference
@@ -1,11 +1,11 @@
-camlStack_realloc2__callback
+camlStack_realloc2.callback
 caml_start_program
 caml_callback
 c_fun
 caml_c_call
-camlStack_realloc2__f_comp
+camlStack_realloc2.f_comp
 caml_runstack
-camlStack_realloc2__entry
+camlStack_realloc2.entry
 caml_program
 caml_start_program
 main
```

**Comment by xavierleroy** [comment]
> one clarification: I didn't think that submodule information was currently encoded in the mangled names

I was referring to packed modules.  They do use names of the `camlModule__Submodule__ident_stamp` kind.

**Comment by xavierleroy** [comment]
Re: demangling in the test suite, there's also ad-hoc demangling in tests/unwind/stack_walker.c.  However it's done completely differently... making it unlikely to be able to share code.

**Comment by xavierleroy** [comment]
> `caml_system` names uses `__` rather than `.`

I think the frame table `caml_system.frametable` must use the same convention as the ocamlopt-generated modules.

>   runtime names (`caml_[a-z].*`, includes `caml_hot` in addition to `caml_system`) use __

Actually, I don't know how `caml_hot` is used.  But if the ocamlopt name-forming machinery is used, you don't get to choose the convention.

File: asmcomp/power/emit.mlp (hunk 2 above)
Comment (xavierleroy) [reply asmcomp/power/emit.mlp:80]: Will that work?  Precheck testing says yes.  Both platforms run Linux and use GNU binutils, which support `$` in identifiers just fine.  We no longer support native-code generation for Power running under AIX.

Why was `$` not used before?  The s390x port was derived from the Power port (IBM oblige), and so it inherited this quirk of the Power port.  The latter was originally developed for AIX, and probably the AIX assembler didn't like `$` in identifiers.  This was in 1996, so pardon me if my memory is hazy.

Comment (gasche) [reply asmcomp/power/emit.mlp:80]: Good, so this means that the whole escaping design is simpler than before, more consistent between backends.

**Review by gasche — APPROVED** [review]
I have reviewed the change and I believe that the code is nice. (I have no clue whether it actually works, but luckily we have the CI telling us t hat it does.)

Two points would be worth addressing before merging, I think:
- you commented on a subtle point (https://github.com/ocaml/ocaml/pull/11430#issuecomment-1181547999), I think it should be stored in the code as a comment
- the patch introduces a FIXME, and from a distance it looks easy to fix the FIXME right away so I would suggest doing that

File: asmcomp/asmpackager.ml (hunk 1 above)
Comment (xavierleroy) [reply asmcomp/asmpackager.ml:53]: > Unless I missed something, this is Compilenv.make_symbol (Some info.ui_name).

I'm afraid not, because `Compilenv.make_symbol` adds a `caml` prefix.  I'll keep looking in Compilenv...

Comment (xavierleroy) [reply asmcomp/asmpackager.ml:53]: I give up and removed the FIXME.  If it ain't broke...

**Comment by xavierleroy** [comment]
> you commented on a subtle point (https://github.com/ocaml/ocaml/pull/11430#issuecomment-1181547999), I think it should be stored in the code as a comment

A natural place would be in the .S files, but I dislike the idea of putting the same comment in 7 different files.

**Comment by gasche** [comment]
check-typo was not appropriately revered:

> ./asmcomp/x86_proc.ml:99.81: [long-line] line is over 80 columns

you also probably need a Changes entry, as this is a user-facing change

**Comment by xavierleroy** [comment]
Working on it.

**Comment by gasche** [comment]
> > you commented on a subtle point ([#11430 (comment)](https://github.com/ocaml/ocaml/pull/11430#issuecomment-1181547999)), I think it should be stored in the code as a comment
> 
> A natural place would be in the .S files, but I dislike the idea of putting the same comment in 7 different files.

You could comment in the C code that refers to these names, and/or assume that everyone reads amd64 as the reference backend.

**Comment by xavierleroy** [comment]
Added comment to runtime/startup_nat.c

File: Changes [hunk 3]
```diff
@@ -14,6 +14,12 @@ Working version
 
 ### Code generation and optimizations:
 
+- #8998, #11321, #11430: change mangling of OCaml long identifiers
+  from `camlModule__name_NNN` to `camlModule.name_NNN`.  The previous
+  mangling schema, using `__`, was ambiguous.
+  (Xavier Leroy, report by sliquister and Michael Bacarella,
+   review by Gabriel Scherer)
```
Comment (gasche) [inline Changes:21]: .mailmap suggests to normalize "sliquister" into "Valentin Gatien-Baron", which is more common in our Changes file.

Comment (xavierleroy) [reply Changes:21]: There are other occurrences of sliquister.  Also, if someone doesn't put their real name in their Github account, I don't feel like going the extra distance to find their real name.

**Comment by xavierleroy** [comment]
One more round of CI precheck to be on the safe side...

File: Changes (hunk 3 above)
Comment (gasche) [reply Changes:21]:
```
$ grep -o "Valentin Gatien-Baron" Changes  | wc -l
43
$ grep -o "sliquister" Changes  | wc -l
2
```

> Also, if someone doesn't put their real name in their Github account, I don't feel like going the extra distance to find their real name.

Fortunately someone maintains a `.mailmap` file that records the contributors expressed naming preference, so in the vast majority of cases you don't need to go much distance and can be sure that you are using the recommended name. (When in doubt, for people not yet in .mailmap, I send an email to ask.)

Comment (gasche) [reply Changes:21]: This being said: feel free to merge as-is anyway, I can normalize the Changes later if I feel like it.

**Comment by xavierleroy** [comment]
CI is happy, and the fight over Changes can wait :-)  Merging!

**Comment by nojb** [comment]
I think `riscv/emit.mlp` was forgotten in this PR, but no worries, I'll do it as part of #11418.
