### PR TITLE
Fix #9866 by allowing to lose some abbreviations during unification

### LINKED ISSUE #9866: Stack overflow when checking recursive constraint
The following program

```ocaml
type 'a t = 'b  constraint 'a = 'b t
```

is correctly rejected with an error message in 4.11.0

```
Line 1, characters 0-36:
1 | type 'a t = 'b  constraint 'a = 'b t;;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: In this definition, a type variable cannot be deduced
       from the type parameters.
```

but causes a stack overflow in the compiler in `trunk`.

@garrigue: I think this was introduced by #9500.

### PR DESCRIPTION
**Pull request by garrigue**
(This PR went through a number of design changes; in particular it now rejects #9866 and #9873. Look at the end of the discussion for the current status, which reverts almost all the first commit.)

This is a tentative fix for #9866.
Rather than failing on
```
type 'a t = 'b  constraint 'a = 'b t;;
```
it accepts it, because the new logic for injectivity is able to determine that `t` is injective (all the variables in its argument constraint appear at an injective position in the body), so that it is actually a valid type definition.

The stack overflow in #9866 came from unifiying with an abbreviation that created an empty recursion. This is avoided now by forgetting abbreviations that would create such spurious recursion.
Note that a few error messages are changed in the testsuite as a result. Also, we need to be more precise in the argument constraints in recursive types (potential incompatibility, but such code is rare, and the fix is easy).

### CODE REVIEW

**Comment by gasche** [comment]
I tried to look at the code and I think that more explanations would be useful.

First the type definition: my understanding is that the only valid instance of such a type declaration is a recursive knot `type foo = foo t` -- the constraint `'a = 'b t` becomes `foo = foo t`, which is valid. For any constraint-satisfying `'a t` we must have `'a = foo` (indeed we must have `'a = 'b t` with `'a t = b`, so in particular `'a = 'a t t` which implies `'a = foo`), so in particular `t` is injective.

Regarding the code: the code of unification tries to head-expand in some cases, but only when deemed "useful". The proposed change adds a new situation where head-expansion happens, when unifying `t1` with `t2`: we perform head-expansion on `t2` if the head-expansion of `t1` occurs recursively inside `t2`, but not inside its expansion -- and conversely.

The only change is that more head-expansion happens, so from a distance this looks clearly sound, but I can't tell why this change would be desirable (on the testsuite it looks more like a small usability regression as the extra expansions give larger types in various error messages) and how it prevents the non-termination situations. There is also some `create_recursion` logic in `unify3` that looks related, but I don't understand what it does either. (Maybe the new code applies this logic in some cases that would not previously reach the `create_recursion` part in `unify3`?) Ideally it would be nice to have a single part of the code that deals with these `deep_occur` checks, instead of now having the logic spread in two different places.

**Comment by garrigue** [comment]
Thank you for reading the code.
The reason there are no explanations is that I'm not sure I understand how it works really (for the unification part).

First, to clarify why `type 'a t = 'b constraint 'a = 'b t` is now accepted:
* its meaning actually is not a recursive knot: it corresponds to the definition `type 'b t t = 'b`, as you can see in examples. This is because occurrences of `t` in parameters do not need to be regular. So for instance `int t t` expands to `int`.
* Since all the variables (i.e. `'b`) in  the parameter appear in the body, `t` can be deemed injective before checking that `'b` is properly bound in the parameter, so it is a valid type definition.
* Actually, rejecting it on injectivity grounds would require changes in the variance inference algorithm that would probably reject types we want to accept
* The stack overflow doesn't come from the injectivity check, but from unification, and it seems that this is only by chance that this was never triggered before

Now, about the unification code.

For the `create_recursion` part, there is an explanation at line 2119 of ctype.ml. I think that Jérôme wrote it but I might be wrong. While I understand how this  code can help solve problems, it is much harder to convince oneself that it protects against all situations, and actually the problem with `type 'a t = 'b constraint 'a = 'b t` seems to show that this is not enough. (If this deifnition breaks an invariant, it is not clear what it was supposed to be...)

The code I added in `unify2` applies the same kind of reasoning, but rather than removing the abbreviation a posteriori, it just keeps it out of the loop when linking nodes. Interestingly, it seems that with the code I added, `create_recursion` is no longer necessary. This is not a logical implication, so I'm leaving the code there, but at least removing `create_recursion` does not change the behavior on the test suite, while it changed it before.

I'm still trying to see if there would be a less intrusive change, and such that we can really prove invariants. However, since we already know that there are situations where it is just impossible to detect locally the creation of a cycle, it seems a difficult task, and formalizing a new approach where abbreviations are annotations rather than nodes is going to be more productive.

Your explanation, it is slightly incorrect in that I'm not expanding more than before. There is just a criterion for ignoring the pre-expansion version, which results in some loss of abbreviations.

Last, there is a small impact on constrained parameters, but actually the new behavior seems more in line with the specification (in mutually recursive type definitions, constraints are not to be inferred from other definitions in the recursion, but to be added by hand, before being checked; however in practice it seems that some constraints are inherited when expansion is triggered).

**Comment by gasche** [comment]
> its meaning actually is not a recursive knot: it corresponds to the definition `type 'b t t = 'b`, as you can see in examples. This is because occurrences of `t` in parameters do not need to be regular. So for instance `int t t` expands to `int`.

This was my initial guess about the meaning of the type (and it is also injective), but I now believe that it is wrong. (So there may be an issue if this what the type-checker implements). Indeed, in `int t t`, the outermost occurrence of `t` respects the constraint, but the inner occurrence does not: `int t` is not a valid type if `'a t` carries the constraint `'a = 'b t`. (My mental model of constraints is that they define types that are not well-formed for any choice of parameters, but only for constraint-satisfying choices of parameter.) I'm not sure what the relation is with "regularity" as you mention; sure, `'a = 'b t` is not a regular recursion, but I would disagree if you meant that (non-regular) recursive occurrences of `t` do not have to respect the constraint.

Thanks for the clarifications for the rest -- I do not have much to add. I hope you do find a better approach, or find a way to see better why this approach makes sense, and possibly how it obsoletes the `create_recursion` logic. Maybe it could be worth asking Jérôme if he has an opinion?

**Comment by lpw25** [comment]
> int t is not a valid type if 'a t carries the constraint 'a = 'b t

Surely this holds recursively: if `int t t` expands to `int` then `int = int t t` and so `int` is a valid argument to `t`.

**Comment by gasche** [comment]
That sounds convincing, but then it suggests that `type 'a t = 'a` is also a valid choice (that this type declaration is less general than the constrained one), and it is more general than the interpretation you and Jacques propose.

**Comment by garrigue** [comment]
> That sounds convincing, but then it suggests that `type 'a t = 'a` is also a valid choice (that this type declaration is less general than the constrained one), and it is more general than the interpretation you and Jacques propose.

Actually, it only looks less general.
```
# type 'a t = 'b constraint 'a = 'b t;;
# module F(X:sig type a end) = struct let f (x : X.a) = (x : X.a t) end;;
module F : functor (X : sig type a end) -> sig val f : X.a -> X.a t end
```
The only difference with `type 'a t = 'a` is that it attempts to unify `'a` with `'b t`, which can change the way the inferred types look, and has bad interactions with univars (which is not new):
```
# let f (type a) (x : a) = (x : a t);;
val f : 'a t -> 'a t t = <fun>
# let f : 'a. 'a -> 'a t = fun x -> x;;
Error: The universal type variable 'a cannot be generalized: it is bound to  'a t.
```

Yet, this type is only accepted because constraints on type parameters are delayed until the type is actually used.
The following definition fails.
```
# type 'a t = 'a constraint 'a = 'b t;;
Error: The type abbreviation t is cyclic
```

**Comment by garrigue** [comment]
I have not found another solution yet, and will probably settle with this approach.
Thanks to @yallop, the code is gradually strengthened, but again the lack of clear invariant in corner cases is biting us...
(The last fix is a wrong call to `Ctype.apply` in the toplevel printer.)

**Comment by garrigue** [comment]
Actually, there are more wrong calls to `Ctype.apply` around, I wonder why they were never noticed: `Ctype.apply` simply doesn't support constrained type parameters.

**Comment by garrigue** [comment]
Oops no, `Ctype.apply` is supposed to handle constrained parameters too. So something else is happening.

**Comment by garrigue** [comment]
I have pushed new commits that
* make the regularity check in `Typedecl.check_recursion` stricter by disallowing expansion of newly defined types; as a results both #9866 and #9873 are rejected as non-regular types (rather than the previous variance-related message)
* revert the changes in `Ctype.unify2`, so that we keep abbreviations

The first change has a potential impact on existing code, but it appears to be strictly less than the previous changes, and it makes much more sense that everything I tried before. Now we can have a correct understanding of the regularity check, and I would even say that the code which allowed expanding newly defined types was buggy to start with, as it assumed regularity while checking for it.

This PR also contains small changes I made while experimenting and that seem to make sense on their own.
I think it is now ready for review.

**Comment by xavierleroy** [comment]
We need this PR to be re-reviewed and approved quickly, otherwise it will not make it into 4.12.

File: typing/ctype.ml [hunk 1]
```diff
@@ -2092,7 +2092,7 @@ let expand_trace env trace =
 let deep_occur t0 ty =
   let rec occur_rec ty =
     let ty = repr ty in
-    if ty.level >= lowest_level then begin
+    if ty.level >= t0.level then begin
```
Comment (lpw25) [inline typing/ctype.ml:2108]: Just to check: this is an unrelated optimisation right?

File: toplevel/genprintval.ml [hunk 2]
```diff
@@ -613,6 +613,9 @@ module Make(O : OBJ)(EVP : EVALPATH with type valu = O.t) = struct
             Oval_printer printer)
 
 
-    in nest tree_of_val max_depth obj ty
-
+    in
+    let snap = Btype.snapshot () in
+    Misc.try_finally
+      (fun () -> nest tree_of_val max_depth obj (Ctype.correct_levels ty))
+      ~always:(fun () -> Btype.backtrack snap)
```
Comment (lpw25) [inline toplevel/genprintval.ml]: This is presumably an unrelated fix that you needed for some expect tests to work correctly?

File: typing/typedecl.ml [hunk 3]
```diff
@@ -668,7 +671,7 @@ let check_well_founded_decl env loc path decl to_check =
 
 (* Check for ill-defined abbrevs *)
 
-let check_recursion env loc path decl to_check =
+let check_recursion ~orig env loc path decl to_check =
```
Comment (lpw25) [inline typing/typedecl.ml]: Could you make it `orig_env`? We nearly always make environments explicit with their name, and I find the code easier to follow if it is explicit here too.

File: typing/typedecl_variance.ml [hunk 4]
```diff
@@ -166,9 +166,11 @@ let compute_variance_type env ~check (required, loc) decl tyl =
             match ty.desc with
             | Tvar _ -> raise Exit
             | Tconstr _ ->
```
Comment (lpw25) [inline typing/typedecl_variance.ml:168]: Is this also an unrelated bug fix?

File: typing/typedecl.ml [hunk 5]
```diff
@@ -1571,7 +1577,7 @@ let check_recmod_typedecl env loc recmod_ids path decl =
      (path, decl) is the type declaration to be checked. *)
   let to_check path = Path.exists_free recmod_ids path in
   check_well_founded_decl env loc path decl to_check;
-  check_recursion env loc path decl to_check;
+  check_recursion ~orig:env env loc path decl to_check;
```
Comment (lpw25) [inline typing/typedecl.ml]: Is it possible to still create types that break the new restrictions by going via a recursive module? Or will `env` not contain the expansions for the paths being checked, so that the restriction is actually stricter for types in recursive modules?

**Review by lpw25 — APPROVED** [review]
I confirm that the changes make things stricter, so are safe, and that the new restrictions seem much easier to think about than the old ones. Possibly they will break existing code, but any such code must be pretty weird.

File: typing/typedecl.ml (hunk 5 above)
Comment (yallop) [reply typing/typedecl.ml]: There's this, which causes a stack overflow:

```ocaml
module type S =
sig
  type !'a s
  type !'a t = 'b  constraint 'a = 'b s
end

module rec M : S =
struct
  type !'a s = 'a M.t
  type !'a t = 'b constraint 'a = 'b s
end
```

File: testsuite/tests/typing-misc/constraints.ml [hunk 6]
```diff
@@ -85,17 +85,31 @@ Error: The definition of abs contains a cycle:
...
+Line 3, characters 7-9:
+3 |   and ('k,'l) abs = 'l constraint 'k = 'l is_an_object
+           ^^
+Error: Constraints are not satisfied in this type.
+       Type 'l is_an_object should be an instance of < .. > is_an_object
+|}]
+
+module PR6505a = struct
+  type 'o is_an_object = < .. > as 'o
+  and ('k,'l) abs = 'l constraint 'k = 'l is_an_object constraint 'l = < .. >
```
Comment (gasche) [inline testsuite/tests/typing-misc/constraints.ml]: I'm a bit confused about what is the status of this testsuite example. My understanding is that the original code

```
type ('k, 'l) abs = 'l constraint 'k = 'l is_an_object
```

was written with the understanding that `constraint 'k = 'l is_an_object` would enforce that `'k` be an object type, and also make it equal to `'l`. Now the checker is more strict and this constraint is rejected unless we also force `'l` to be an object type in a separate constraint -- so the constraint `is_an_object` does not seem to be of any use anymore, unless I am missing something. Assuming we are trying to write a short example of interesting constraint (and not just to record the fix to an existing example), should this not be written

```ocaml
type ('k, 'l) abs = 'l constraint 'k = 'l constraint 'l = < .. >
```

? If I understand correctly, this is exactly equivalent, as we cannot use `'o is_an_object` to imply an additional constraint anymore.

**Review by gasche — COMMENTED** [review]
In a comment (https://github.com/ocaml/ocaml/issues/9866#issuecomment-685087413) I mentioned projection types such as

```ocaml
type 'a gamma = 'b constraint 'a = < gamma : 'b >
```

are those types still accepted and can they be used as expected? (I suppose they are, but I'm not sure this is checked by the testsuite.)

For example I would expect the following to be possible 

```ocaml
type 'a x = 'b constraint 'a = < x : 'b; .. >
type 'a y = 'b constraint 'a = < y : 'b; .. >

type 'a x_to_y = 'a x -> 'a y
```

File: toplevel/genprintval.ml (hunk 2 above)
Comment (garrigue) [reply toplevel/genprintval.ml]: Doing nothing changes the output in `typing-gadts/principality-and-gadts.ml`, suggesting that the printing function alters the type in an observable way.
However, if we use `Ctype.correct_levels`, there doesn't seem to be a need to backtrack (the above examples does not change), so I simplified a bit the code.

File: typing/ctype.ml (hunk 1 above)
Comment (garrigue) [reply typing/ctype.ml:2108]: Indeed. Since `deep_occur` looks deeply, it seems better to stop as early as we can.

File: typing/typedecl.ml (hunk 3 above)
Comment (garrigue) [reply typing/typedecl.ml]: Done.

File: typing/typedecl.ml (hunk 5 above)
Comment (garrigue) [reply typing/typedecl.ml]: Thanks for the example. This was to be expected: since this fix relies on using the original environment, and we don't use it for recursive modules, the check on recursive modules is insufficient.
This said, I tried to use the original environment for recursive modules too (see branch garrigue/ocaml/fix9866_recmodule), and the stack overflow is still there. So the problem seems deeper. Maybe the timing of the check is not the right one...

**Comment by garrigue** [comment]
> For example I would expect the following to be possible
> 
> ```ocaml
> type 'a x = 'b constraint 'a = < x : 'b; .. >
> type 'a y = 'b constraint 'a = < y : 'b; .. >
> 
> type 'a x_to_y = 'a x -> 'a y
> ```

It is still possible. Constrained parameters in types already defined are handled as before, the change is only for constrained parameters of types involved in the recursion.

File: testsuite/tests/typing-misc/constraints.ml (hunk 6 above)
Comment (garrigue) [reply testsuite/tests/typing-misc/constraints.ml]: Good point.
Since the problem is not so much the module, but rather that `y` should not have an ill-founded type, I have changed the example to
```ocaml
  type 'o is_an_object = < .. > as 'o
  type ('k,'l) abs = 'l constraint 'k = 'l is_an_object
```
which also answers your other question.

**Comment by garrigue** [comment]
I have made a few changes, and would happy if somebody can look at the final state.
I plan to merge this tomorrow.

As written in code comments, @yallop has found an example with recursive modules where this fix doesn't work.
I have no easy solution. I still think that the current fix is worthwhile, as it avoids stack overflows on very simple definitions.

**Review by lpw25 — APPROVED** [review]
LGTM

**Comment by garrigue** [comment]
Cherry-picked on 4.12 at 08f053982
