### PR TITLE
bytecode -custom supply missing externs

### LINKED ISSUE #12790: [ocaml-5.1.0]: Bytecode -custom exes fail to link with cc a C++ compiler
Since ocaml-5.1.0, bytecode `-custom` executables fail to link if given `-cc` a C++ compiler (e.g `-cc "clang++"` will fail but `-cc "clang"` works).
```
$ cat > hello_world.ml
let () = print_string "Hello world!\n"
^D
$ ocamlc.opt -o hello-world ./hello_world.ml -custom -cc "clang++"
clang-16: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
ld: Undefined symbols:
  _caml_builtin_cprim, referenced from:
      _caml_build_primitive_table in libcamlrun.a[14](dynlink.b.o)
      _caml_build_primitive_table_builtin in libcamlrun.a[14](dynlink.b.o)
  _caml_names_of_builtin_cprim, referenced from:
      _caml_build_primitive_table in libcamlrun.a[14](dynlink.b.o)
      _caml_main in libcamlrun.a[56](startup_byt.b.o)
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
File "./hello_world.ml", line 1:
Error: Error while building custom runtime system
```

This regression was introduce in [this commit](https://github.com/ocaml/ocaml/commit/99a05d2cd41f912243fd31b0534a9d18aef8155b) and the reason is as follows: `-custom` bytecode executables link with compiler generated C like
```c
#if defined __cplusplus
extern "C" {
#endif
typedef long value;

typedef value (*caml_primitive)();

...
extern value caml_abs_float(void);
...

const caml_primitive caml_builtin_cprim[] = {caml_abs_float, ...};
const char* const caml_names_of_builtin_cprim = {"caml_abs_float", ...};

...

#if defined __cplusplus
}
#endif
```
Since `caml_builtin_cprim` and `caml_names_of_builtin_cprim` are `const` qualified, when compiled with a C++ compiler (>= C++11), they are given internal linkage [^1] (unlike C).

The fix is to arrange for the generated code to mark `caml_builtin_cprim` and `caml_names_of_builtin_cprim` as `extern`:
```c
extern const caml_primitive caml_builtin_cprim[] = {caml_abs_float, ...};
extern const char* const caml_names_of_builtin_cprim = {"caml_abs_float", ...};
```

[^1]:  C++11: C.1.2 https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3337.pdf

### PR DESCRIPTION
**Pull request by shayne-fletcher**
Since ocaml-5.1.0, bytecode `-custom` executables fail to link if given `-cc` a C++ compiler. 
```
$ cat > hello_world.ml
let () = print_string "Hello world!\n"
^D
$ ocamlc.opt -o hello-world ./hello_world.ml -custom -cc "clang++"
ld: Undefined symbols:
  _caml_builtin_cprim, referenced from:...
  _caml_names_of_builtin_cprim, referenced form:...
...
```
This is a consequence of certain symbols in generated code being assigned internal linkage by default. This PR addresses the issue by arranging to qualify these constants as `extern`.  Fixes https://github.com/ocaml/ocaml/issues/12790

### CODE REVIEW

**Comment by xavierleroy** [comment]
I have a problem with this fix: it produces dubious C code.  At least according to gcc and to clang, an `extern` declaration with an initializer is a likely error in C:
```
● cat foo.c
extern const char * x[2] = { "a", "b" };
● clang -std=c11 -Wall -c foo.c
foo.c:1:21: warning: 'extern' variable has an initializer [-Wextern-initializer]
    1 | extern const char * x[2] = { "a", "b" };
      |                     ^
1 warning generated.
● gcc -std=c11 -Wall -c foo.c
foo.c:1:21: warning: ‘x’ initialized and declared ‘extern’
    1 | extern const char * x[2] = { "a", "b" };
      |                     ^
```

**Comment by shayne-fletcher** [comment]
i'll refine the fix. let's make `extern` conditional on `#ifdef __cplusplus`.

**Comment by shayne-fletcher** [comment]
> i'll refine the fix. let's make `extern` conditional on `#ifdef __cplusplus`.

i've pushed and verified that change. the generated code now reads like,
```
#if defined __cplusplus
extern const c_primitive caml_builtin_cprim[] = {
#else
const c_primitive caml_builtin_cprim[] = {
#endif
```
it's taking a long time for the changes to get reflected here. i suspect github is having an incident ([downdetector](https://downdetector.com/status/github/) seems to indicate so).

**Comment by MisterDA** [comment]
Two suggestions: you could also put just the `extern` under the `#ifdef __cplusplus`:
```c
#if defined __cplusplus
extern
#endif
const c_primitive caml_builtin_cprim[] = {
```
or separate declaration and definition:
```c
extern const c_primitive caml_builtin_cprim[];
const c_primitive caml_builtin_cprim[] = {
```
both of these work with C and C++.

**Comment by shayne-fletcher** [comment]
> ... you could also put just the extern under the #ifdef __cplusplus

i agree. i think (1) is ever so slightly less verbose and the best phrasing so far.
```c
#if defined __cplusplus
extern
#endif
const char * const caml_names_of_builtin_cprim[] = {
```
have pushed that. thanks for having a look @MisterDA !

**Comment by MisterDA** [comment]
I wonder if the symbol should be protected against C++ name mangling with `extern "C"`. Not sure if variable names are mangled.

**Comment by shayne-fletcher** [comment]
> I wonder if the symbol should be protected against C++ name mangling with `extern "C"`. Not sure if variable names are mangled.

the symbols get C  mangling correctly as things are (`_caml_builtin_cprim`, `_caml_names_of_builtin_cprim`). this is because in the case of C++, all the definitions of a 'foo.camlprim.c' are made to reside in an `extern "C"` block.

**Review by MisterDA — APPROVED** [review]

**Comment by Octachron** [comment]
@MisterDA having a look at the change this seems mostly a safe change that could be backported to 5.1, what is your opinion ?

**Comment by xavierleroy** [comment]
I still think it is wrong to compile C code contained in a `.c` file as if it were C++ code.  Actually, `clang++` warns about that:
```
$ clang++ -c foo.c
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
```
`ocamlc -custom` generates a temporary C file that must be compiled by a C compiler.

**Comment by MisterDA** [comment]
I guess the correct invocation would be `c++ -x c`, so `ocamlc.opt -o hello-world ./hello_world.ml -custom -cc "clang++ -x c"`.

**Comment by shayne-fletcher** [comment]
It is indeed wrong to compile a C file with a C++ compiler. But... you need to compile a C file, then link C++ objects. That requires two distinct command lines. The fact that currently OCaml uses the linker to compile a C file is the root cause, as it mixes the compilation of one language (C) with the linking of another (C++). One option would be to have two distinct command lines, and compile the .c file in a separate operation. That seems a more invasive change than this diff.

We did try `-x c` but that causes any object files on the command line to be treated as C files, which causes all kinds of problems.

**Comment by shayne-fletcher** [comment]
>We did try `-x c` but that causes any object files on the command line to be treated as C files, which causes all kinds of problems.

```
$ cat > hello_world.ml
let () = print_string "Hello world!\n"
^D
$ cat > foo.cpp
void f() {}
^D
$ clang++ -c -o foo.o foo.cpp
$ ocamlc.opt -c -o hello.cmo hello_world.ml
$ ocamlc.opt -o hello hello.cmo foo.o -custom -cc "clang++ -x c"
foo.o:1:1: error: source file is not valid UTF-8
<CF><FA><ED><FE><U+000C><U+0000><U+0000><U+0001><U+0000><U+0000><U+0000><U+0
...
```

**Comment by xavierleroy** [comment]
> you need to compile a C file, then link C++ objects.

Thanks for pointing this out.  For the linking phase we need g++ or clang++, but then they interpret .c source files as C++ files. I agree we're kind of cornered here...

**Comment by Octachron** [comment]
@xavierleroy , does your comment count as a reluctant approval for this PR ?

File: Changes [hunk 1]
```diff
@@ -514,6 +514,9 @@ Working version
 
 ### Bug fixes:
 
+- # 12791: bytecode -custom supply missing externs
```
Comment (xavierleroy) [inline Changes]: A more descriptive line is needed.  Please mention that it's for linking with a C++ linker.

File: runtime/gen_primsc.sh [hunk 2]
```diff
@@ -52,12 +52,18 @@ sed \
...
+echo '#endif'
 echo 'const c_primitive caml_builtin_cprim[] = {'
 sed -e 's/.*/  (c_primitive) &,/' "$primitives"
 echo '  0 };'
 
 # Generate the table of primitive names
 echo
+echo '#if defined __cplusplus'
+echo 'extern'
+echo '#endif'
```
Comment (xavierleroy) [inline runtime/gen_primsc.sh]: These changes appear unnecessary to me.  The output of `runtime/gen_primsc.sh` will always be compiled by a C compiler, like everything else in the runtime/ directory.  Can you please revert these changes?

**Review by xavierleroy — COMMENTED** [review]
I agree with the proposed changes to `bytecomp/symtable.ml`.  Some suggestions below.

**Review by xavierleroy — APPROVED** [review]
Thanks @shayne-fletcher for the updates.  I'm fine with the current state of this PR.  Now merging!

**Comment by Octachron** [comment]
@xavierleroy , I am considering cherry-picking to 5.1 to avoid a feature hole between OCaml 5.0 and OCaml 5.2. Any objections?

**Comment by xavierleroy** [comment]
No objections, thanks for asking.
