### PR TITLE
manual: simplified rendering for toplevel code examples

### LINKED ISSUE #10142: Multiline OCaml code samples in manual all slightly malformed
(This is a bug report rather than a PR because I've spent too long trying to fix it, and failed. It's probably easy for someone who knows the code). The correct formatting should be, to pick the first multiline code from the first chapter of the tutorial:

```
# let rec fib n =
    if n < 2 then n else fib (n-1) + fib (n-2);;
```
(Hash on first line, space after hash, indenting otherwise correct)

But currently we see:

TEXT manual
```
#let rec fib n =
#  if n < 2 then n else fib (n-1) + fib (n-2);;
```
(Hash on every line, no space after hash on first line)

HTML manual
```
# let rec fib n =
   if n < 2 then n else fib (n-1) + fib (n-2);;
val fib : int -> int = <fun>
```
(Adds the hash with css `::before` mechanism, so indenting now wrong)

PDF manual
```
# let rec fib n =
#   if n < 2 then n else fib (n-1) + fib (n-2);;
```
(Correct indenting, but hash on every line, which top level doesn't do)

### PR DESCRIPTION
**Pull request by Octachron**
Toplevel code examples in the manual are now directly generated as

```latex
$\?$ let f x =
   x * x
- : val f: int -> int = <fun>
```

with the prompt macro `\?` uniformly defined as a black colored `#`.

rather than

```latex
$\?$let f x =
$\?$  x * x
$\:$- : val f: int -> int = <fun>
```

with each backend defining its own interpretation of `\:` and `\?`.

Similarly, non-toplevel examples are now emitted as

```
let f x =
  x * x
- : val f: int -> int = <fun>
```
with neither `\:` nor `\?` present.

This simplification is enough to achieve the uniform rendering of toplevel examples requested in #10142 .

Closes #10142

### CODE REVIEW

**Comment by xavierleroy** [comment]
I'm OK with not prefixing every line of input with `#`.

However, in the PDF output, the `\:` macro was used to typeset replies in a different font (slanted typewriter), and I'm afraid your simplification is destroying this presentation trick.

**Comment by Octachron** [comment]
Sorry, I have over-simplified the presentation, the current full rendering is:
```ocaml
\begin{camlinput}
$\?$ let f x =
   x * x
\end{camlinput}
\begin{camloutput}
- : val f: int -> int = <fun>
\end{camloutput}
```
and the styling of the replies has been moved to the camloutput environment (and friends) with the syntax highlighting PR:
https://github.com/ocaml/ocaml/blob/trunk/manual/manual/manual.tex#L25

File: tools/caml_tex.ml [hunk 1]
```diff
@@ -690,11 +697,10 @@ let process_file file =
...
         (* Special characters may also appear in output strings -Didier *)
         let output = Text_transform.escape_specials output in
-        let phrase = global_replace ~!{|^\(.\)|} camlin phrase
-        and output = global_replace ~!{|^\(.\)|} camlout output in
+        let phrase = format_input mode phrase in
         let final_output =
           if omit_answer && String.length error_msgs > 0 then
-            global_replace ~!{|^\(.\)|} camlout error_msgs
+            error_msgs
           else if omit_answer then ""
```
Comment (gasche) [inline tools/caml_tex.ml]: The `String.length error_msgs > 0` test appears useless now.

**Review by gasche — COMMENTED** [review]
Naive question: with your change the weird prompt-magic of `\:` is completely gone from `{camloutput}` environment, and for `{camlinput}` environments it is kept only on the first line. But why have that macro on the first line, and not inserted automatically by the environment? Is there ever a place where we used `camlinput` but we don't want a prompt macro? (Could this be done with two different environments instead of this weird preprocessing?)

**Comment by Octachron** [comment]
We are still using the camlinput environment in the verbatim and signature modes, where we explicitly don't want to show a toplevel prompt. We could also split these two kinds of environments and lift the logic of "add an hash on the first line, indent on the other line" to latex.

**Comment by gasche** [comment]
I think it would be clearer and simpler. Does this require wide changes to the manual, or are those environments internal to the user-accessible macros?

**Comment by gasche** [comment]
I had missed something, not only is a `$\?$` added on the first line, but two spaces are added on followup lines to change the identation. Thanks @Octachron for the clarification, I'm dropping the suggestion to do it in pure LaTeX.

**Comment by xavierleroy** [comment]
> We could also split these two kinds of environments and lift the logic of "add an hash on the first line, indent on the other line" to latex.

But hevea's macros are not powerful enough to implement this logic.  So for the HTML version, prompt and indentation would be done by CSS magic?

**Comment by Octachron** [comment]
Purely in term of simplicity, I don't think that Latex∩Hevea can beat a few lines of OCaml.

**Review by gasche — APPROVED** [review]
I believe that this change is an improvement. Approved.

Now that I gave some brain cycles to this problem, I should mention that I would prefer to use distinct environments for toplevel examples and structures/signatures, but I actually don't care that much, and my idea that it would simplify the implementation was wrong.

**Comment by gasche** [comment]
Note: we should wait to merge this PR until the Appveyor status is sorted out.
