### PR TITLE
ocamlyacc: source locations for %type declarations

### LINKED ISSUE #10001: ocamlyacc: wrong file and line information for types in %type declarations
If a type in a %type declaration causes a compiler error, the error message will point to the generated code, rather than the `.mly` source.  This is because ocamlyacc fails to generate line directives for it.

### PR DESCRIPTION
**Pull request by DemiMarie**
This can be incredibly useful if there is a type error.

Also avoid locale-dependent isalpha().

Fixes #10001.

### CODE REVIEW

**Comment by gasche** [comment]
Why are you putting resources into improving ocamlyacc? I have the impression that Menhir is generally better in all ways, and that `ocamlyacc` should be, for all intent and purposes, deprecated.

**Comment by DemiMarie** [comment]
> Why are you putting resources into improving ocamlyacc? I have the impression that Menhir is generally better in all ways, and that `ocamlyacc` should be, for all intent and purposes, deprecated.

In some cases, not having a dependency on Menhir (which is typically a separate package) can be useful.  Also, this PR didn’t take very long to make, and it fixes an issue that has tripped me up in the past.  If this were a major change like #33 I would agree with you, but it isn’t.  These changes might also make lives easier for those working on Menhir, as Menhir uses ocamlyacc to bootstrap.

**Comment by xavierleroy** [comment]
> In some cases, not having a dependency on Menhir (which is typically a separate package) can be useful.

Inevitably, ocamlyacc will become a separate package too.  So, you should still consider switching to Menhir now.

**Comment by DemiMarie** [comment]
> > In some cases, not having a dependency on Menhir (which is typically a separate package) can be useful.
> 
> Inevitably, ocamlyacc will become a separate package too. So, you should still consider switching to Menhir now.

I will eventually, but this change does fix a bug.  I also pushed a commit that fixes a wrong exit code in an error case.

**Comment by DemiMarie** [comment]
Also, I am not sure how to contribute to Menhir.

**Comment by gasche** [comment]
Menhir is hosted at <https://gitlab.inria.fr/fpottier/menhir>, which is user-hostile as far as git forges go because you have to ask the maintainer (@fpottier) first to create an account for you, and only then you can make a MR/PR. (This sucks, and would be solved by proper federation of git forges.)

If you want to contribute something, you may want to create an issue to describe the change or write to the menhir mailing-list first.

**Comment by DemiMarie** [comment]
@gasche fair.  In any case I would still like to see this PR merged, as it is a strict improvement and doesn’t add maintenance burden.  If you are worried about the positive diffstat, I have some patches that rip out hundreds of lines of unused code.

**Comment by DemiMarie** [comment]
(Fun fact: ocamlyacc is actually better than Menhir when it comes to correctly lexing OCaml code.  ocamlyacc correctly handles `{a|...|a}` strings, whereas Menhir does not.  @fpottier you might want to fix that.)

**Comment by fpottier** [comment]
Thanks @DemiMarie for pointing this out. I have opened [an issue in Menhir's repository](https://gitlab.inria.fr/fpottier/menhir/-/issues/67).

**Comment by DemiMarie** [comment]
You’re welcome @fpottier.  It honestly makes no sense for this code to be duplicated between Menhir, ocamllex, and the compiler itself, so I filed #11738 to see if this could be made part of compiler-libs or similar.

File: yacc/reader.c [hunk 1]
```diff
@@ -1459,7 +1476,7 @@ void read_grammar(void)
         }
         at_first = 0;
         if (c == EOF) break;
-        if (isalpha(c) || c == '_' || c == '.' || c == '$' || c == '\'' ||
+        if (In_bitmap(caml_ident_start, c) || c == '_' || c == '.' || c == '$' || c == '\'' ||
                 c == '"')
```
Comment (damiendoligez) [inline yacc/reader.c]: The line is too long.

```suggestion
        if (In_bitmap(caml_ident_start, c) || c == '_' || c == '.' || c == '$' ||
                c == '\'' || c == '"')
```

File: yacc/reader.c [hunk 2]
```diff
@@ -904,14 +904,15 @@ void declare_tokens(int assoc)
...
+        column = cptr - line;
         tag = get_tag();
         c = nextc();
         if (c == EOF) unexpected_EOF();
     }
 
     for (;;)
     {
-        if (isalpha(c) || c == '_' || c == '.' || c == '$')
+        if (In_bitmap(caml_ident_start, c) || c == '.' || c == '$')
```
Comment (damiendoligez) [inline yacc/reader.c]: You will have to fix `IS_IDENT` (used in `get_name`) too. As it is, you're moving from locale-dependent behavior to a locale-dependent inconsistency that (if I read the code correctly) leads to an infinite loop.

**Review by damiendoligez — COMMENTED** [review]
I think you should leave `isalpha` alone or leave it for another PR.

The location stuff looks good.

File: yacc/reader.c (hunk 2 above)
Comment (DemiMarie) [reply yacc/reader.c]: An, good point.

Comment (damiendoligez) [reply yacc/reader.c]: Another point: we are trying to move OCaml toward Unicode, so it's probably not a good idea to push ocamlyacc toward better handling of Latin-1...

File: Changes [hunk 3]
```diff
@@ -319,6 +319,9 @@ Working version
   `ocamlmklib.opt` are no longer installed to `$BINDIR`.
   (Xavier Leroy, review by Gabriel Scherer)
 
+- #11728: ocamlyacc: generate line directives for %type declarations
+  (Demi Marie Obenour)
```
Comment (damiendoligez) [inline Changes]:
```suggestion
  (Demi Marie Obenour, review by Damien Doligez)
```

**Review by damiendoligez — APPROVED** [review]
Update Changes and we're good to merge.

**Comment by damiendoligez** [comment]
Thanks !

**Comment by DemiMarie** [comment]
You’re welcome @damiendoligez!  Thanks for the help!
