### PR TITLE
Fix idle domain gc

### LINKED ISSUE #11589: Idle domain slows down major GC cycles
Consider the program below, which was reported to me by @Octachron. If you run it without options, it runs on a single domain without explicitly calling the GC and its heap size goes up to 31 MB. If you run it with `-spawn`, it launches a domain that only sleeps in parallel with its main computation, and its heap size goes up to 694 MB.

What happens is that the major GC slice budget is computed from the number of words allocated by the domain since the last slice. But the domain doesn't allocate and the slice budget is zero, so the slice doesn't do anything, even though the domain does have some work to do for the GC cycle (sweeping, for example). This ends up starving the GC cycle.

The GC still makes progress because of opportunistic slices, but these slices are very small and the GC runs a lot slower (6 cycles vs 116 cycles without the extra thread).

This is probably the same problem as #11548.

```ocaml
(* compile with:
  ocamlfind opt -package unix,domainslib -linkpkg sorttest.ml
*)
module Timings = struct

  type t = {
    cpu_time : float;
    wall_time : float
  };;

let time_computation (f : unit -> 'a) : t * 'a =
  let times_start = Sys.time ()
  and wall_start = Unix.gettimeofday () in
  let ret = f () in
  let times_end = Sys.time ()
  and wall_end = Unix.gettimeofday () in
  { cpu_time = times_end -. times_start ;
    wall_time = wall_end -. wall_start
  },
  ret
end
module Quicksort = struct
  let pivot (cmp : 'a -> 'a -> int) (a : 'a array) (left : int) (right : int) =
    assert(0 <= left);
    assert(left <= right);
    assert(right <= Array.length a);
    let mid_start = ref left
    and mid_end = ref (left + 1)
    and current_pos = ref (right - 1)
    and pivot = a.(left) in
    while !mid_end <= !current_pos do
      assert (left <= !mid_start);
      assert (!mid_start < !mid_end);
      assert (!current_pos < right);
      let current = a.(!current_pos) in
      match cmp current pivot with
      | 0 ->
        a.(!current_pos) <- a.(!mid_end);
        mid_end := !mid_end + 1
      | n when n < 0 ->
        a.(!mid_start) <- current;
        a.(!current_pos) <- a.(!mid_end);
        mid_start := !mid_start+1;
        mid_end := !mid_end+1
      | _ ->
        current_pos :=  !current_pos - 1
    done;
    for i= !mid_start to !mid_end-1 do
      a.(i) <- pivot
    done;
    (!mid_start, !mid_end);;

  let rec quicksort (cmp : 'a -> 'a -> int) (a : 'a array) (left : int) (right : int) =
    assert(0 <= left);
    assert(left <= right);
    assert(right <= Array.length a);
    if right - left > 1
    then
      let (mid_start, mid_end) = pivot cmp a left right in
      let len_left = mid_start - left
      and len_right = right - mid_end in
      if len_left < len_right then
        (quicksort cmp a left mid_start;
         quicksort cmp a mid_end right)
      else
        (quicksort cmp a mid_end right;
         quicksort cmp a left mid_start);;
end


[@@@warning "-unused-value-declaration"]


let assert_sorted cmp a left right =
  for i=left to right-2 do
    assert (cmp a.(i) a.(i+1) <= 0)
  done

let checksum a left right =
  let sum = ref 0 in
  for i=left to right-1 do
    sum := !sum lxor a.(i)
  done;
  !sum

let random_array seed max n =
  let prng = Random.State.make seed in
  Array.init n (fun _ -> Random.State.int prng max);; 

let print_array oc prt a left right =
  for i=left to right-1 do
    Printf.fprintf oc "[%d] = %a\n" i prt a.(i)
  done

let output_int oc n =
  output_string oc (string_of_int n);;

let pp_size ppf x =
  let x = x *. 8. in
  let rec human s suffixes x =
    match x<1024., suffixes with
    | true, _ | false, [] ->
      Printf.fprintf ppf "%.2f%sB" x s
    | false, s :: suffixes ->
      human s suffixes (x/.1024.)
  in
  human "" ["k";"M";"G";"T"] x
module Tsk = Domainslib.Task
(*  ;;
let cores = 4 in
let pool = Tsk.setup_pool ~num_additional_domains:(cores-1) () in
let run f = Tsk.run pool f in
*)
;;

type mode = Spawn_domains | Explicit_gc | Implicit_gc
let mode = ref Implicit_gc
let stride = ref 1000
let args = [
    "-spawn", Arg.Unit (fun () -> mode := Spawn_domains ), "spawn more than one domain";
    "-gc", Arg.Unit (fun () -> mode := Explicit_gc ), "add explicit call to the GC";
    "-default", Arg.Unit (fun () -> mode := Implicit_gc ), "no explicit call to the GC, single domain";
    "-stride", Arg.Set_int stride, "size increase at each step (default=1000)"
  ]

let () = Arg.parse args ignore ""
let mode = !mode
let stride = !stride
;;
let run f = f () in
let rec loop () =
  Unix.sleepf 100.0;
  loop ()
in
begin match mode with
| Spawn_domains ->
  let _d = Domain.spawn loop in
  Printf.eprintf "loop domain = %d\n%!" (Obj.magic (Domain.get_id _d))
| _ -> ()
end;
let n1 = ref 1 in
while !n1 <= 500_001 do
  let n = !n1 in
  n1 := n + stride;

  let max = 10000
  and seed = [|n; 2; 3|] in
  let a = random_array seed max n in
  let sum = checksum a 0 n in
  let times,() = Timings.time_computation (fun () ->
                     run
                     (fun () -> Quicksort.quicksort ( - ) a 0 n)) in
  assert_sorted ( - ) a 0 n ;
  let stat = Gc.quick_stat () in
  let sum2 = checksum a 0 n in
  let () = match mode with
    | Explicit_gc -> Gc.full_major ()
    | _ -> ()
  in
  assert (sum = sum2);
  Printf.printf "%d\t%f\t%f" n times.cpu_time times.wall_time;
  Printf.printf "\tmax=%a\theap=%a\tmajor allocated=%a minor=%d major=%d"
    pp_size (float stat.top_heap_words)
    pp_size (float stat.heap_words)
    pp_size stat.major_words
    stat.minor_collections
    stat.major_collections
  ;
  Printf.printf "\n";
  flush stdout
done;;
```

### LINKED ISSUE #12042: Out-of-memory crash when using a second domain
This program crashes after a few seconds with an out-of-memory error:
```ocaml
let main () =
  while true do
    ignore (Bytes.create (64 * 1024))
  done

let () =
  Domain.spawn main |> Domain.join
```

```
$ ocamlopt --version
5.0.0

$ ocamlopt -o test.exe test.ml && ./test.exe
fish: “./test.exe” terminated by signal SIGKILL (Forced quit)
[336325.516584] Out of memory: Killed process 221782 (test.exe) total-vm:103708848kB, anon-rss:6535600kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:202340kB oom_score_adj:0
```
If I remove the `Domain.spawn` bit and just run `main ()` directly, then there is no problem.

I also tested with https://github.com/ocaml/ocaml/pull/11903 at @sadiqj's suggestion and it still fails, though @kit-ty-kate noted that:
> I just tested with this branch, and while it ultimately still fails the same way, it does is significantly slower.
> - With 5.0.0 and trunk it takes just 3 seconds to OOM-kill with 32GB of RAM
> - With this branch it takes a whole good minute and some change

/cc @kayceesrk

### PR DESCRIPTION
**Pull request by damiendoligez**
Trying to fix #11589 (and maybe #11548). Two changes here:

1. GC work accounting and distribution becomes global.
2. extra major slices are done globally instead of locally.

The benchmark code is here: https://gist.github.com/damiendoligez/86a3afa6c6a594e0274d6194d91457b7

### GC work accounting
Major allocations are counted globally and the counts are evenly distributed among active domains. These counts tell the major GC slices how much work they have to do. The main difficulty is that some domains may run out of major GC work for the current cycle before others. Then they cannot do any more GC work before the global synchronization at the end of the GC cycle (i.e. the STW event that starts the next cycle). In this case we have to redistribute their counts back to the domains that still have something to do.
This accounting tries to guarante that the global speed of major collection keeps up with the speed of allocation.

### extra major slices
When we allocate directly in the major heap, we sometimes have to trigger major GC slices in addition to the ones that are automatically run between minor collections. In trunk, this is done only in the allocating domain, but that's not enough: in the benchmark program, the allocating domain has already run out of GC work and these slices do nothing and allocation gets ahead of collection. In order to do these global slices, we have to send a signal to all other domains, but we don't need synchronization, do I modified the STW code to add an asynchronous mode.

### benchmark results
| test | max heap size (MB) | minor collections | major collections |
|-----|--------------:|------------------:|-----------------:|
|trunk sequential | 30.5 | 125 | 116 |
|trunk with idle domain | 694.0 | 121 | 6 |
|this PR sequential | 52.6 | 112 | 112 |
|this PR with idle domain | 99.9 | 194 | 47 |

We can clearly see some improvement, but I still have to investigate:
- ~~why the number of minor collections changes so much~~
- ~~why the sequential test of this PR uses much more memory than trunk~~
- ~~what is still holding up the major GC~~

Fixes #11589
Fixes #12042

### CODE REVIEW

File: runtime/major_gc.c [hunk 1]
```diff
@@ -1150,14 +1159,13 @@ static void cycle_all_domains_callback(caml_domain_state* domain, void* unused,
...
 
-      /* Reset GC work accounting counters. */
-      for (i = 0; i < Max_domains; i++){
-        domain_accounts[i].alloc = 0;
-        domain_accounts[i].dependent = 0;
-        domain_accounts[i].extra = 0.0;
-      }
+      /* reset work counters */
+      caml_plat_lock (&accounting_lock);
+      caml_enumerate_participating_domains (&reset_domain_account);
```
Comment (gasche) [inline runtime/major_gc.c]: I'm confused, aren't the arguments `int participating_count, caml_domain_state **participating` precisely supposed to let us do this (iterate on all participating domains)? If it is enough to access the `stw_domains` globals, why do we have them in the STW API?

**Review by gasche — COMMENTED** [review]
(I was randomly passing by and have a question.)

**Comment by gasche** [comment]
What is the status of this PR? It looks like it does fix or at least greatly alleviate memory-consumption issues. Do we want to eventually get it merged? What do we need to do?

**Comment by damiendoligez** [comment]
I'm still working on this. I'm not satisfied with the increase of memory consumption in the sequential case.

**Comment by kayceesrk** [comment]
@damiendoligez I wondered if you had an idealised model for major slice scheduling in the multi-domain case. One thing we can do is to use [olly](https://github.com/tarides/runtime_events_tools#olly) to generate the traces and analyse run post-facto to see how close this PR gets to this ideal. [Perfetto](https://perfetto.dev/#analysis) has a SQL-based trace analysis framework where we can explore the trace by asking queries.  

IINM, runtime events currently does not report counter events for major heap sizes and estimated live data, which would be a pre-requisite for feeding into this idealised model. CC @sadiqj.

**Comment by damiendoligez** [comment]
I don't have a detailed model, I only know that, going back to https://gist.github.com/stedolan/52c13d6b1a30276db31ca98683c8db16, with the default overhead parameter we need to do about 5.2 units of work (the average of m and s) for each word allocated. When the GC does much less than that, the heap will get unacceptably large. The tricky part is distributing this work among the domains that do have some GC work available.

**Comment by damiendoligez** [comment]
I have much simplified the accounting logic: there is now a global counter of how much needs to be done, and each major slice tries to do that much work and decreases the global counter by how much work was actually done.

We still need to trigger major slices on other domains when the current domain runs out of things to do. This means we sometimes have all domains doing a major slice at the same time. There is a work-sharing mechanism to handle this case without doing N times the total amount of work.

The results are now better than trunk, even without any idle thread, but they still get worse when there are idle threads:

This PR:

| spawn | heap max (MB) | minor GC | major GC | work-to-alloc | backlog |
|-------|---------------|----------|----------|---------------|---------|
| 0     | 15.62         | 434      | 434      | 4.00          | 0.00    |
| 1     | 26.53         | 231      | 231      | 3.08          | 0.23    |
| 2     | 30.99         | 180      | 180      | 2.88          | 0.28    |
| 3     | 31.12         | 165      | 165      | 2.82          | 0.29    |
| 5     | 31.15         | 159      | 159      | 2.80          | 0.30    |
| 10    | 31.71         | 160      | 159      | 2.86          | 0.28    |


Trunk:

| spawn | heap max (MB) | minor GC | major GC | work-to-alloc |
|-------|---------------|----------|----------|---------------|
| 0     | 30.47         | 130      | 126      | 3.31          |

The work-to-alloc column gives the ratio of GC work done to number of words allocated in the major heap. When the GC's control loop works perfectly, this is 4 (assuming default GC settings). The backlog colum gives the amount of work that is left in the counter at the end of the program over the total amount of work.


I tried to increase the running time of the test with 0 or 1 idle thread:

no idle thread:

| steps | heap max (MB) | minor GC | major GC | work-to-alloc | backlog |
|-------|---------------|----------|----------|---------------|---------|
| 500   | 15.62         | 434      | 434      | 4.00          | 0.00    |
| 1000  | 30.27         | 918      | 918      | 4.00          | 0.00    |
| 1500  | 46.14         | 1409     | 1409     | 4.00          | 0.00    |
| 2000  | 61.40         | 1902     | 1902     | 4.00          | 0.00    |


one idle thread:

| steps | heap max (MB) | minor GC | major GC | work-to-alloc | backlog |
|-------|---------------|----------|----------|---------------|---------|
| 500   | 26.53         | 231      | 231      | 3.08          | 0.23    |
| 1000  | 54.92         | 473      | 473      | 3.03          | 0.24    |
| 1500  | 89.34         | 716      | 716      | 3.00          | 0.25    |
| 2000  | 103.00        | 960      | 960      | 3.01          | 0.25    |


The work-to-alloc ratio and residual backlog seem to be stable when the benchmark runs longer.


I still need to do a smoke check with sandmark and check whether this will fix #11548.

**Comment by gasche** [comment]
If I read your numbers right, in the sequential case (spawn=0) the benchmark runs many more GC slices in your PR than in trunk: 434 with your PR, 126 with trunk. You say that this is better behavior because the work-to-alloc hits the intended target of 4.0. But is that good? I suppose that there is no issue with throughput because each slice doesless work?

(If I understand correctly, the impact on throughput is approximated by the work-to-alloc ratio, so 4 instead of 3.3 means slightly more time spent in the major GC but not much more, and we get to halve the memory usage in return.)

**Comment by damiendoligez** [comment]
>If I read your numbers right, in the sequential case (spawn=0) the benchmark runs many more GC slices in your PR than in trunk: 434 with your PR, 126 with trunk. You say that this is better behavior because the work-to-alloc hits the intended target of 4.0. But is that good? I suppose that there is no issue with throughput because each slice doesless work?

It's actually a number of major GC cycles, not slices. Note that this program is quite atypical: it allocates more in the major heap than in the minor heap (which explains why the number of minor GCs is equal to the number of major cycles: each major cycle forces a minor GC). To answer your question, I think it's good because it lets the GC reach the target work-to-alloc ratio, which trunk doesn't.

**Comment by kit-ty-kate** [comment]
I can confirm that this PR in its current state also fixes https://github.com/ocaml/ocaml/issues/12042

**Comment by damiendoligez** [comment]
@stedolan @kayceesrk : I think this is ready for review and should be integrated in 5.1, although it's likely that some further improvements are possible. They will be left for a later PR.

File: runtime/domain.c [hunk 2]
```diff
@@ -602,6 +602,8 @@ static void domain_create(uintnat initial_minor_heap_wsize) {
   domain_state->dependent_size = 0;
   domain_state->dependent_allocated = 0;
 
+  domain_state->major_work_done_between_slices = 0;
+
```
Comment (kayceesrk) [inline runtime/domain.c:606]: The other newly introduced domain-local variables also need to be initialised.

**Comment by kayceesrk** [comment]
The changes are surprisingly simple and look good to me. I should say that I haven't fully checked whether the new slice computation does the right thing. This is something that @stedolan may want to do. 

One component that I've been wondering about is

> We still need to trigger major slices on other domains when the current domain runs out of things to do. 

We have to do something similar for triggering major slices when the first domain in a minor cycle uses half of its minor heap: https://github.com/ocaml/ocaml/pull/11750. But the mechanisms are different. https://github.com/ocaml/ocaml/pull/11750 interrupts all of the domains by obtaining the `all_domains_lock` and sets the interrupt word to `-1`. See `advance_global_major_slice_epoch` this PR uses an asynchronous version of `caml_try_run_on_all_domains_async` in order to trigger major slice globally. 

I wondered whether both of these can be expressed using a similar mechanism. Have you thought about this @damiendoligez?

**Comment by gasche** [comment]
@kayceesrk we discussed this PR at the triaging meeting today. We would like to merge some version of it in 5.1 if possible. If you think that you wouldn't have the time to go to the finish line in the next few weeks/months, let us know and we will look for another potential reviewer.

**Review by kayceesrk — APPROVED** [review]
I've gone through the computation for updating gc work, and they look correct to me. 

I would be curious to see Sandmark results on this. Has this already been done @damiendoligez?

**Comment by kayceesrk** [comment]
The sandmark results are available now. Only the results from the `turing` machine (28 cores) is available. The 128 core `navajo` seems to be down. 

## Sequential

Sequential results are [here](https://sandmark.ocamllabs.io/?app=Sequential+Benchmarks&sequential_12=turing_5.2.0%2Btrunk%2Bfix-idle-gc%2Bsequential_20230423_7440f24&sequential_B0=turing&sequential_00=5.2.0%2Btrunk%2Bsequential&sequential_02=turing_5.2.0%2Btrunk%2Bsequential_20230423_063894d&sequential_10=5.2.0%2Btrunk%2Bfix-idle-gc%2Bsequential&sequential_num_variants=2&sequential_11=20230423&sequential_01=20230423&sequential_B1=20230423&sequential_find_by=variant&sequential_B2=turing_5.2.0%2Btrunk%2Bsequential_20230423_063894d
).

There are a few "differences" from the trunk version. In terms of running time, there are a few regressions:

image

_**It may be worthwhile investigating `pi_digits5` benchmark which shows 50% slowdown.**_ 

There's a drop in maxRSS for the benchmarks with the biggest slowdown

image

See that the two benchmarks `pi_digits5` and `zarith_pi` which showed the biggest slowdowns also seem to use much less memory.

This PR also make the program do a lot more major and minor GCs. 

### Normalised minor collection count 

image

### Normalised major collection count 

image

Do we expect this PR to increase the major and minor GC counts? (Not that this number alone matters, as the running time + maxRSS is perhaps a better representation of the user-observable behaviour).  

## Parallel

The parallel speedup results are [here](https://sandmark.ocamllabs.io/?app=Parallel+Benchmarks&parallel_00=5.2.0%2Btrunk%2Bparallel&parallel_10=5.2.0%2Btrunk%2Bfix-idle-gc%2Bparallel&parallel_02=turing_5.2.0%2Btrunk%2Bparallel_20230423_063894d&parallel_find_by=variant&parallel_num_variants=2&parallel_01=20230423&parallel_11=20230423&parallel_12=turing_5.2.0%2Btrunk%2Bfix-idle-gc%2Bparallel_20230423_7440f24).

On most benchmarks, this PR performs exactly the same. On `test_decompress`, there is a significant 2x speedup over trunk. I suspect that this benchmark exhibits the idle-domain behaviour that this benchmark fixes. This is excellent.

**Comment by damiendoligez** [comment]
@kayceesrk 

> The sandmark results are available now. Only the results from the `turing` machine (28 cores) is available. The 128 core `navajo` seems to be down.

Thanks for running the benchmarks.

> _**It may be worthwhile investigating `pi_digits5` benchmark which shows 50% slowdown.**_
> There's a drop in maxRSS for the benchmarks with the biggest slowdown
> See that the two benchmarks `pi_digits5` and `zarith_pi` which showed the biggest slowdowns also seem to use much less memory.

This paints a picture of the bugfix working correctly: when the GC is too lazy (as in trunk) the program runs fast but uses too much memory. With the fix, the GC works harder to maintain the user-chosen time/space trade-off. A slowdown of 50% means the GC is now using (more than) 33% of the running time, which is a bit high but not off the scale.

Note that pi_digits5 and zarith_pi are almost exactly the same program. Maybe one of them should be eliminated from sandmark.

> Do we expect this PR to increase the major and minor GC counts? (Not that this number alone matters, as the running time + maxRSS is perhaps a better representation of the user-observable behaviour).

Major GC counts: definitely yes. Minor GC counts: since the major GC forces a minor at the start of its cycle, yes. It would be interesting to compare the absolute numbers here.

> ## Parallel

> On most benchmarks, this PR performs exactly the same. On `test_decompress`, there is a significant 2x speedup over trunk. I suspect that this benchmark exhibits the idle-domain behaviour that this benchmark fixes. This is excellent.

If I read the graphics correctly, `test_decompress` exhibits a **slowdown** rather than a speedup. I've looked at the raw numbers, and it seem to use much more memory as well. I'll need to investigate this.

**Comment by kayceesrk** [comment]
> If I read the graphics correctly, test_decompress exhibits a slowdown rather than a speedup. I've looked at the raw numbers, and it seem to use much more memory as well. I'll need to investigate this

You are right. I was reading the result that I wanted to see. Good catch. 

Other observations make sense to me.

File: runtime/domain.c [hunk 3]
```diff
@@ -1363,8 +1365,16 @@ int caml_domain_is_in_stw(void) {
...
+  The explanation above applies if [sync] = 1. When [sync] = 0, no
+  synchronization happens, and we simply run the handler asynchronously on
+  all domains. We still hold the stw_leader field until we know that
+  every domain has run the handler, so another STW section cannot
+  interfere with this one.
+
 */
 int caml_try_run_on_all_domains_with_spin_work(
+  int sync,
```
Comment (sadiqj) [inline runtime/domain.c:1377]: I'm not entirely sure we want to change this interface for this one use case. This function looks deceptively simple to use but actually ended up being a source of many bugs.

I think there is one in the use here: https://github.com/ocaml/ocaml/pull/11903/files#diff-67115925103982a8ebeb085cfab5ef31a182c9a442bc51e053934364d3750dafR1637 . `caml_try_run_on_all_domains_with_spin_work` can just fail to actually run the function if it can't be the stw_leader or take the all_domains_lock. This means that we might have a `requested_global_major_slice` whose actions actually get ignored.

As an alternative we could support the use-case here with something simpler:

```
while(1) {
  handle_interrupts();
  if( caml_plat_try_lock(&all_domains_lock) ) {
   /* iterate through stw_domains.participating_domains and set requested_major_slice to 1 */
   caml_plat_unlock(&all_domains_lock);
  }
}
```

The only race is when you're about to enter a major slice anyway, so doesn't make a difference.

**Review by sadiqj — APPROVED** [review]
The changes look good other than the note I already made about synchronisation.

I don't think it should block this PR (which blocks 5.1) but I would be really good to increase the documentation in the code for the actual computations that form the GC pacing. The little explainer in major_gc.c helps but we could probably go further. It took me a while to piece together the different parts.

I'm also not sure I understand why we take the max of alloc_work/extra_work/dependent_work - shouldn't extra and dependent be considered part of the heap and be included in a combination calculation of work to be done?

**Comment by kayceesrk** [comment]
> If I read the graphics correctly, test_decompress exhibits a slowdown rather than a speedup. I've looked at the raw numbers, and it seem to use much more memory as well. I'll need to investigate this.

Do you have any new insights into what's going wrong here?

File: runtime/domain.c (hunk 3 above)
Comment (damiendoligez) [reply runtime/domain.c:1377]: I was aware of this when I wrote the code. Maybe I should leave `requested_global_major_slice` alone in this case. The idea was that it's not a correctness bug: if it happens infrequently enough, we're still good.

For this:
```
while(1) {
  handle_interrupts();
  if( caml_plat_try_lock(&all_domains_lock) ) {
   /* iterate through stw_domains.participating_domains and set requested_major_slice to 1 */
   caml_plat_unlock(&all_domains_lock);
  }
}
```
This is not enough: we also have to interrupt all other domains. And signal the backup threads of the idle domains. I started writing that code, then I realized I was rewriting a large part of `caml_try_run_on_all_domains_with_spin_work`. At that point I decided to reuse it instead of rolling my own buggy version.

**Comment by damiendoligez** [comment]
>I'm also not sure I understand why we take the max of alloc_work/extra_work/dependent_work - shouldn't extra and dependent be considered part of the heap and be included in a combination calculation of work to be done?

For `dependent_work`, it's probably doable but there is some design work to do, see https://github.com/ocaml/ocaml/pull/10418#discussion_r727187752

For `extra_work` it's even less obvious since this is completely outside memory, and in different units.

At any rate, this max operation is inherited from 4.14 and I don't think we should change it in this PR. There will be a successor to #10418 for this.

**Comment by damiendoligez** [comment]
@kayceesrk, I found a bug while trying to figure it out. This bug may or may not be the cause but the fix is a medium-scale refactoring of this code, which we're working on, @stedolan and I.

**Comment by kayceesrk** [comment]
Thanks for the update @damiendoligez.

**Comment by damiendoligez** [comment]
The problem with `test_decompress` turns out to be interference with a pre-existing bug, see #12249 for details.

**Comment by xavierleroy** [comment]
Now that #12249 is merged, is this PR ready to be merged?  We're all eager to have better GC behavior in 5.1.

**Comment by kayceesrk** [comment]
Having reviewed the PR previously, if the `test_decomress` issue is fixed, I would be happy to merge the PR.

**Comment by damiendoligez** [comment]
Rebased. I have checked by hand that the `test_decompress` speedup is OK. @kayceesrk do you want to relaunch the parallel tests? IMO it's not worth it unless it is a negligible amount of work.

**Comment by kayceesrk** [comment]
I've also manually tested the PR on `test_decompress` and I confirm the speedup is fine. I'm ok to merge this PR.

I have also relaunched the parallel tests: https://github.com/ocaml-bench/sandmark-nightly-config/commit/d5e19dbbaa920c3f02f758f546ad57ed19663259. The results should be available in a day.

**Comment by kayceesrk** [comment]
Sandmark results confirm that the speedup is fine. [Here](https://sandmark.ocamllabs.io/?app=Parallel+Benchmarks&parallel_01=20230501&parallel_num_variants=2&parallel_02=turing_5.2.0%2Btrunk%2Bfix-idle-gc%2Bparallel_20230501_7440f24&parallel_11=20230524&parallel_10=5.2.0%2Btrunk%2Bfix-idle-gc%2Bparallel&parallel_12=turing_5.2.0%2Btrunk%2Bfix-idle-gc%2Bparallel_20230524_03ce04a&parallel_find_by=variant&parallel_00=5.2.0%2Btrunk%2Bfix-idle-gc%2Bparallel) is the sandmark run on parallel benchmarks that compares the runs before and after the fix.

**Comment by Octachron** [comment]
Cherry-picked on 5.1 (613f96d7bf)
