### PR TITLE
caml_update_dummy: do not try to update size-0 atoms

### LINKED ISSUE #12153: Bytecode miscompilation of recursive definition of empty first class module
This produces segfaulting bytecode with `trunk`'s ocamlc, but not 4.14.1. I haven't bisected the cause yet.

```ocaml
module type S = sig end;;

let rec k =
  (module struct end : S)
```

Notably, these variations do not segfault:

```ocaml
module type S = sig end;;

let k =
  (module struct end : S)
```

```ocaml
module type S = sig val x : int end;;

let rec k =
  (module struct let x = 3 end : S)
```

ocamlopt does not produce segfaulting code.

### PR DESCRIPTION
**Pull request by gasche**
fixes #12153

### CODE REVIEW

File: runtime/alloc.c [hunk 1]
```diff
@@ -316,7 +316,14 @@ CAMLprim value caml_update_dummy(value dummy, value newval)
 
   tag = Tag_val (newval);
 
-  if (tag == Double_array_tag){
+  if (Wosize_val(dummy) == 0) {
+      /* Size-0 blocks are statically-allocated atoms; we cannot
+         mutate them, but there is no need as the runtime only uses
+         dummies of tag 0 for valid OCaml values -- even, say, for
+         0-sized flat float arrays. So doing nothing suffices. */
```
Comment (xavierleroy) [inline runtime/alloc.c]: It's hard to write unambiguous sentences that use "only".  Suggested rewrite:
```suggestion
      /* Size-0 blocks are statically-allocated atoms. We cannot
         mutate them, but there is no need since the dummy was
         created with tag 0 and since all atoms used
         to represent OCaml values have tag 0, including empty
         arrays and empty flat float arrays. So, doing nothing suffices. */
```

**Review by xavierleroy — APPROVED** [review]
Looks good to me.  A suggestion for a comment below.

File: runtime/alloc.c (hunk 1 above)
Comment (gasche) [reply runtime/alloc.c]: Thanks! I updated. the comment.
