### PR TITLE
Restrict local function optimisation

### LINKED ISSUE #8563: [@inline] annotation behaves incorrectly on 4.08 (flambda only)
The following program, when compiled with flambda on 4.08 (and trunk), does not respect the `[@inline never]` annotation. Cmm is below.
When `raise_stuff` is exported by the signature, the `[@inline never]` annotation works.

This only happens when the `raise_stuff` functions is used exactly once.

```
module X : sig
  val run_function : int -> int 
end = struct
  let [@inline never] raise_stuff () =
    raise Exit

  let run_function x =
    if x <> 0
    then raise_stuff ()
    else x
end
```
with 4.07:
```
(function{/tmp/inline_stuff.ml:6,34-53} camlInline_stuff__raise_stuff_6
     (param/1448: val)
 (raise_notrace{/tmp/inline_stuff.ml:7,4-14} "camlStdlib__Pmakeblock_2739"))

(function{/tmp/inline_stuff.ml:9,19-71} camlInline_stuff__run_function_17
     (x/1451: val)
 (if (!= x/1451 1)
   (app{/tmp/inline_stuff.ml:11,9-23} "camlInline_stuff__raise_stuff_6" 1a
     val)
   x/1451))
```
with 4.08:
```
(function{/tmp/inline_stuff.ml:9,19-71} camlInline_stuff__run_function_6
     (x/91: val)
 (if (!= x/91 1)
   (raise_notrace{/tmp/inline_stuff.ml:7,4-14} "camlStdlib__Pmakeblock_1820")
   x/91))

```

### PR DESCRIPTION
**Pull request by lthls**
This PR disables the local function optimisation when it would move code inside a different function. This seems coherent with the purpose of the transformation, which is to generate static catches (which cannot cross function boundaries).

The testsuite changes (apart from the new test) are either benign cases where the optimisation used to apply but doesn't anymore (the `functors` test) or backtrace changes due to different inlining decisions.

Fixes #8563, #10993.

### CODE REVIEW

**Comment by gasche** [comment]
I wonder whether @alainfrisch has an opinion on this proposal.

It's interesting that the proposed solution to a UI problem ("an optimisation changes I didn't know about changes the code in ways I find surprising") is to restrict an optimization to apply less often. I don't know if this is the right approach.

**Comment by lthls** [comment]
My point of view is that the extensive discussion on #2143 pointed out a number of potential issues with applying this optimisation too broadly, and #8563 and #10993 showed actual issues reported by our users. So this PR applies one of the suggestions from #2143, which is to restrict the scope (I didn't restrict it to the exact scope of the calls, as was also suggested, because there was a good argument that it would make code less readable).

I'm open to adding another variant of the `[@local]` attribute, say `[@local force]`, that removes the restriction, but has to be passed explicitly. I could also repurpose the existing `[@local]` and `[@local always]` attributes to mean that, but then I'd lack a good way to check that the optimisation doesn't apply by default across function boundaries in the testsuite.

**Comment by gasche** [comment]
@alainfrisch without feedback from you on this question, I think the default approach (for me at least) would be to trust @lthls's intuition and move towards merging this.

(cc maybe @nojb as the confidante)

**Comment by nojb** [comment]
> @alainfrisch without feedback from you on this question, I think the default approach (for me at least) would be to trust @lthls's intuition and move towards merging this.
> 
> (cc maybe @nojb as the confidante)

I haven't discussed this PR with @alainfrisch (and in fact I had missed this PR when it was submitted last year), but having gone over the whole discussion (and the example https://github.com/ocaml/ocaml/pull/12092#issuecomment-1463977121), my feeling is that this PR is reasonable, as it makes the optimization more predictable while preserving its applicability to the most common use-cases.

File: testsuite/tests/backtrace/lazy.ml [hunk 1]
```diff
@@ -1,6 +1,12 @@
...
-   flags = "-g"
-   * native
+
+flags = "-g"
+* no-flambda
+** native
+* flambda
+reference = "${test_source_directory}/lazy.flambda.reference"
+** native
+
```
Comment (gasche) [inline testsuite/tests/backtrace/lazy.ml]: Could you use TEST_BELOW to avoid line number updates in the future? See tests/backtrace/backtrace.ml.

File: lambda/simplif.ml [hunk 2]
```diff
@@ -790,6 +791,7 @@ let simplify_local_functions lam =
      by the outermost lambda for which the the current lambda
      is in tail position. *)
   let current_scope = ref lam in
+  let current_function_scope = ref lam in
```
Comment (gasche) [inline lambda/simplif.ml:796]: Could there be a comment here with a reference to the PR/issue?

**Review by gasche — APPROVED** [review]
Given the somewhat positive feedback, I reviewed the PR for correctness and nitpickings. Approved.

Personally I remain somewhat unconvinced by the change proposed, but I'm willing to trust of people who know more about optimization than I do.

My non-expert understanding is that our inlining (1) relies on code size and (2) needs to inline the whole definition, instead of being able to carve out contexts of interest (worth duplicating) and leave the rest in place -- we never do a worker-wrapper transform and then inline the wrapper only. These two (sensible, simple) properties of inliners give fragile behavior when moving code in function F may prevent F from being inlined, and thus hurt performance even though the change in F itself could be beneficial. The "local function optimization" was guilty of moving code around in this way, so it is being blamed for a general problem with inlining-based optimization. Maybe because no one else is moving much code around in Simplif, and maybe also because it is harder from within flambda to interact with before-flambda transformations.

**Comment by lthls** [comment]
Thanks for your review, I'll update the PR with your suggestions. I'd still like to convince you that moving code across function boundaries is a bad idea, so I've left some more arguments below.

The inlining algorithms (both of them) can cope relatively well with the code moved around by this pass, as long as functions do not have attributes. But in the presence of either user-provided attributes (`[@inline]`) or compiler-derived attributes (the `stub` flag), this optimisation doesn't propagate attributes at all meaning that we end up with code with the wrong attributes, and the inliners have no choice but to respect the attributes, producing potentially very bad code.
Here is an example:
```ocaml
let almost_always () = Sys.opaque_identity true
let not_toplevel () =
  let[@inline never] cold () = (* Put a lot of code here *) in
  let[@inline always] hot () = if almost_always () then () else cold () in
  hot (); hot (); hot (); hot (); hot ()
```
You will see that all the code of `cold` ends up duplicated (with closure too, not only with flambda). Given that inlining attributes are described extensively in the manual, and the local function optimisation is not, this looks like a clear bug to users (see the two issues I linked in the description of the PR). The stub case is less common and less visible to users, but it's still quite problematic, and #12092 would make it very, very common.

There are also a few issues involving closure sizes, which are less extreme but can still cause code to allocate much more than it should when this optimisation is on. Example:
```ocaml
let not_toplevel a b c d e f g h i j k l array =
  let aux x = a + b + c + d + e + f + g + h + i + j + k + l + x in
  Array.map (fun funct -> fun x -> funct (aux x)) array
```
Without the optimisation, the inner-most closure (`fun x -> funct (aux x)`) will have two free variables `funct` and `aux`, while after local function optimisation it will have thirteen. Although the code above looks unnatural, we've seen actual cases that look similar in real code. And although inlining is not involved at all here, if `aux` was inlined instead we wouldn't have the same issue because both inliners work on closure-converted terms, so the parameters would still be accessed from the closure of `aux`, allocated outside the loop, even after inlining.

**Comment by gasche** [comment]
For me the first example you show is an example of an UI problem caused by our current attribute handling, which I would naively think of fixing by changing our attribute UI. (For example @lpw25 suggested a `[@cold]` attribute; we could also revisit the question of having `[@inline never]` disable the local-function optimization if we observe that we made the wrong UI choice.)
(I don't know about functor stubs so I'm not sure what alternative fixes would work for these.)

The second example is an argument for why moving code around across function boundaries can have more undesirable side-effects than moving code around inside functions. Point taken, but I suppose there are also examples where the move is beneficial. (Could there be cases, for example, where inlining the free-variables in the outer closure environment allows for a more fine-grained lifetime analysis inside the function body, and lets the GC collect user values earlier?)

One point in your favor I suppose is that the local function optimization does not make a big difference performance-wise -- it turns a direct call into a jump, no big deal on modern CPUs. We didn't think very much about adding it, and we don't need to think a lot either about disabling it partially, because we expect that in most cases it will not make such a performance difference. Even if in theory my hunch that the change is somewhat misplaced was right, the cost of the change is small and the benefits appear to be non-trivial for people working on other optimisers, so yeah.

**Comment by lthls** [comment]
> For me the first example you show is an example of an UI problem caused by our current attribute handling, which I would naively think of fixing by changing our attribute UI. (For example @lpw25 suggested a `[@cold]` attribute; we could also revisit the question of having `[@inline never]` disable the local-function optimization if we observe that we made the wrong UI choice.)

I agree that we could and should spend some time improving the attribute UI. But I think we need to bring users into the discussion too, as I fear discussions among the compiler maintainers only are going to be biased significantly.

> (I don't know about functor stubs so I'm not sure what alternative fixes would work for these.)

For stubs (including partial application stubs, like in `let f ~x ~y = () in f ~y`), the situation is complex. Only flambda relies on this attribute, and we expected when we added it that nothing would significantly transform functions before reaching flambda. With the addition of local functions, this assumption was broken. There are a lot of possible solutions: we could do nothing and live with some poor inlining decisions, which is what we did for a while. We could restrict the local functions transformation so that it does not create this issue, which is what we did on the Flambda 2 tree and here, but leaves us with no guarantee that the problem will not come up again. We could remove the attribute completely in the front-end, which would lead to slightly higher compilation times and/or slightly poorer inlining decisions with flambda. Or we could try to update the stub status after transformations (or even re-evaluate it upon entry to the middle-end), but that sounds like a lot of work. This PR was the best compromise for the flambda team (good enough result with relatively low effort).

> The second example is an argument for why moving code around across function boundaries can have more undesirable side-effects than moving code around inside functions. Point taken, but I suppose there are also examples where the move is beneficial.

Yes, there are examples where the move is beneficial. Here is a simple example:
```ocaml
let f l = List.length l in
let g y l1 l2 = if y then f l1 else f l2
```
Here we want to take advantage of the key property of the local function optimisation: its ability to share code without introducing a real function. After this PR you would have to move the definition of `f` inside `g` to get the same result.
Also, if `g` is itself turned into a local function, then with this PR `f` will stay as a regular function whereas without the PR both functions would have been turned into catch handlers in their original scope. We might be able to tweak the code of this PR to support this case.

> (Could there be cases, for example, where inlining the free-variables in the outer closure environment allows for a more fine-grained lifetime analysis inside the function body, and lets the GC collect user values earlier?)

When chaining local functions (as in my previous paragraph), before this PR we could have removed all closures and got precise lifetimes. But as long as a function remains then all those variables will be read from a closure, and kept alive as long as the closure(s) is/are, so I don't think there are any significant lifetime gains elsewhere.

> One point in your favor I suppose is that the local function optimization does not make a big difference performance-wise -- it turns a direct call into a jump, no big deal on modern CPUs. We didn't think very much about adding it, and we don't need to think a lot either about disabling it partially, because we expect that in most cases it will not make such a performance difference. Even if in theory my hunch that the change is somewhat misplaced was right, the cost of the change is small and the benefits appear to be non-trivial for people working on other optimisers, so yeah.

It's actually more interesting than just transforming calls into jumps. One of the main things to think about when optimising is how this interacts with other optimisations. So one obvious benefit of this optimisation is that other function-local optimisations, like reference elimination, can trigger in more cases:
```ocaml
let r = ref 0. in
let[@local] return () = if !r > 0. then Some !r else None in
match ... with
| ... -> ...; return ()
| ... -> ...; return ()
```
Without the local function optimisation, `r` escapes and cannot be turned into a mutable variable in `Simplif`, so without Flambda you have to pay the extra allocation and memory operations (Flambda can eliminate references after inlining, so is less likely to be impacted). And without the reference elimination there's no way to unbox the float values stored in and read from `r`, so that's another performance loss.

Fortunately, users that rely on this optimisation can always rewrite their code so that the optimisation triggers even with this new restriction. It can be a bit uncomfortable (particularly for users of `let*` operators), but hopefully not too much.
