### PR TITLE
 #11450: struct end might be really a structure

### LINKED ISSUE #11450: Confusing error message when applying a functor to an empty structure
This simple toplevel session results in an error message that is not very helpful:
```
# module X (P : sig type t end) = struct end;;
# module Y = X(struct end);;
Error: The functor was expected to be applicative at this position
```

Passing anything else than an empty structure lead to a better message. For instance a useless attribute:
```
# module Y = X(struct [@@@foo] end);;
Error: Modules do not match: sig end is not included in sig type t end
     The type `t' is required but not provided
```

This happens because `X()`, the syntax for applying generative functors, translates to `X(struct end)`:
- in the parser: [parser.mly#L1329](https://github.com/ocaml/ocaml/blob/38a9884/parsing/parser.mly#L1329)
- in the typechecker, by directly checking syntactic equality: [typing/typemod.ml#L2271](https://github.com/ocaml/ocaml/blob/38a9884/typing/typemod.ml#L2271)

This makes the implementation simpler at the cost of this slightly worse error message.
Should we try to address this?

### PR DESCRIPTION
**Pull request by Octachron**
This PR propagates the parsetree changes from #11984 to the error machinery in order to fix the confusing functor application error message reported in #11450.

In brief, in a functor argument constructor
```ocaml
F(struct end)
```
we need to consider that `struct end` might be both a structure or an unit module in order to have the error message consistent with the typechecker.

Before #11984, it was impossible to make any difference between `F()` and `F(struct end)`, and the error machinery picked the unit interpretation to catch more "user-visible" errors. This approximation lead to the confusing error message reported in #11450 : 
```ocaml
module F(X:sig type t end) = struct end
module R = F(struct end)
```
> Error: The functor was expected to be applicative at this position

because `F(struct end)` was interpreted as `F()`.

With #11984 and this PR, we can distinguish the two constructs and handle properly the special `struct end` case to get back the right error message without any compromise:

```ocaml
module F(X:sig type t end) = struct end
module R = F(struct end)
```
> Error: Modules do not match: sig end is not included in sig type t end
     The type `t' is required but not provided

 

close #11450

### CODE REVIEW

File: typing/typemod.ml [hunk 1]
```diff
@@ -2118,7 +2118,7 @@ let simplify_app_summary app_view = match app_view.arg with
   | Some arg ->
     let mty = arg.arg.mod_type in
     match arg.is_syntactic_unit , arg.path with
-    | true , _      -> Includemod.Error.Unit, mty
+    | true , _      -> Includemod.Error.Empty_struct, mty
```
Comment (gasche) [inline typing/typemod.ml:2121]: Naive question: what does `arg.is_syntactic_unit` mean now and why do we keep it? (Backwards-compatibility?) Is there a comment somewhere in the codebase that explains this?

File: typing/includemod_errorprinter.ml [hunk 2]
```diff
@@ -518,7 +520,10 @@ module Functor_suberror = struct
       | Named _ | Anonymous ->
           Format.dprintf
             "The functor was expected to be generative at this position"
-
+      | Empty_struct ->
+          (* an empty structure can be used in both applicative and generative
+             context *)
+          assert false
```
Comment (gasche) [inline typing/includemod_errorprinter.ml:526]: I'm always nervous about new `assert false` in the code, but it looks widely used in this file for understandable reason, so this one is arguably okay.

File: typing/typemod.ml (hunk 1 above)
Comment (gasche) [reply typing/typemod.ml:2121]: (Maybe it could/should be renamed `is_empty_struct`)

**Review by gasche — APPROVED** [review]
This is a simple change and I believe that it is correct.

File: typing/typemod.ml (hunk 1 above)
Comment (Octachron) [reply typing/typemod.ml:2121]: This `is_syntactic_unit` field is the typechecker version of `Empty_struct`.

We kept it for backward compatibility reason to be able to coerce a `struct end` to an unit module in a context where an unit module was expected. This implicit conversion currently raises a warning to slowly nudge people away from relying on the generative interpretation of `F()`.

File: Changes [hunk 3]
```diff
@@ -508,6 +508,11 @@ Working version
   by leaf functions.
   (Tom Kelly and Xavier Leroy, review by Mark Shinwell)
 
+- #11450, ????: Fix erroneous functor error messages that were too eager to cast
+  `struct end` functor argument as an unit module in `F(struct end)`,
+  generating erroneous error messages.
+  (Florian Angetti, review by ????)
```
Comment (gasche) [inline Changes]: the two ???? need replacing.
